### ISSUE TITLE
[Slider] onChange ran when initialized

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#1000]
# Bug Report

## Steps to reproduce
1. Create a slider with `onChange` method
2. View the page

## Expected result
Nothing should happen in the `onChange` method and the slider should be initialized as normal

## Actual result
Slider is initialized but `onChange` is ran

## Testcase
https://jsfiddle.net/jgwkd75c/

## Screenshot
![asbYBqd5Eu](https://user-images.githubusercontent.com/11588822/64341103-91115680-cfdf-11e9-8ed4-83147a58e8c0.gif)

## Version
2.7.8

**Comment by hammy2899** [comment]
This is because `set.value()` is ran in the `read.settings()` method here https://github.com/fomantic/Fomantic-UI/blob/develop/src/definitions/modules/slider.js#L1002

and `read.settings()` is ran in the `initialize` method here https://github.com/fomantic/Fomantic-UI/blob/develop/src/definitions/modules/slider.js#L112

**Comment by GammaGames** [comment]
I always assumed this was a feature, dropdown does it too. I do see that a few other modules have a `fireOnInit` setting, but I'm not sure if it's working on the Rating module. https://jsfiddle.net/x8ue7dmq/

I think not calling `onChange` by default and offering a `fireOnInit` for every input would be the most consistent.
