### ISSUE TITLE
[Globals] Defining breakpoints in site.variables in a custom packaged theme not building

### ISSUE THREAD

**Issue by trandromeda** [fomantic/Fomantic-UI#1003]
# Bug Report
## Steps to reproduce
1. Create a custom packaged theme by making a new folder under themes e.g. `semantic/src/themes/mycustomtheme`
2. Create `mycustomtheme/globals/site.variables` 
3. Add your own breakpoints e.g. 
```
@mobileBreakpoint            : 320px;
@tabletBreakpoint            : 958px;
@computerBreakpoint          : 1182px;
@largeMonitorBreakpoint      : 1360px;
@widescreenMonitorBreakpoint : 1920px;
```
4. In `theme.config`, specify Globals: @site to use the custom theme e.g. `@site       : 'mycustomtheme';`
5. Run `gulp build`

## Expected result
Site should use new breakpoint values

## Actual result
Site ignores breakpoint values in custom theme's site.variables, instead uses the values of the *last* theme that was specified in Globals: @site.

## Testcase
(unable to demonstrate this in a jsfiddle)
You can replicate using this simple UI to view different breakpoint behaviours (cards span full width under tablet size):
```
<div class="ui four column grid stackable cards">
  <div class="ui fluid card">
  A card
  </div>
    <div class="ui fluid card">
  A card
  </div>
    <div class="ui fluid card">
  A card
  </div>
    <div class="ui fluid card">
  A card
  </div>
    <div class="ui fluid card">
  A card
  </div>
    <div class="ui fluid card">
  A card
  </div>
</div>
```

* setting another one of the pre-packaged themes in Globals: @site, such as Github or Amazon, will correctly set the breakpoints
* custom breakpoints work when setting them in the Site Theme
* if making changes to `site.variables` of the custom theme, `gulp watch` will not be triggered

## Version
2.7.8

**Comment by trandromeda** [comment]
I just found this in `tasks/build/css.js':

```
      if(path.indexOf('site.variables') !== -1)  {
        return;
      } 
```

So any changes to a `site.variables` file is ignored and not built... I'm assuming that is why my custom theme globals for site.variables were not being used either, and from there it seems the intent of the author was to enforce usage of globals only to the Site Theme ...? It confused me that the Github and Amazon themes had a Globals/site.variables file, so I was thinking I could do the same for a custom theme. Would appreciate some clarification on this matter, thanks!

**Comment by exoego** [comment]
@ColinFrick 
Could you see this when you have time ?
I think you have expertise in build tools.

**Comment by ColinFrick** [comment]
I'll look into it.
