### ISSUE TITLE
Modal not centered correctly when using detachable: false

### ISSUE THREAD

**Issue by rmarchiori** [fomantic/Fomantic-UI#1009]
# Bug Report

Hello, it seems that the modal is not centering correctly when using option detachable: false and we have a long scrollable content.

My guess is that it is not calculating the top property correctly, it seems to be using the body height instead of viewport height.

Note 1: If you remove detachable : false option it works.
Note 2: If you remove like a paragraph of text you will then see the modal, but it won't be centered though.

## Steps to reproduce
1. Open the fiddle and click on show modal button

## Expected result
Modal should be centered.

## Actual result
Modal is not centered. 

## Testcase
[jsFiddle link](http://jsfiddle.net/7j38xdbw/1/)

My original Semantic-ui repository issue [link](https://github.com/Semantic-Org/Semantic-UI/issues/6866)

## Version
2.7.8

**Comment by GammaGames** [comment]
It's not centered vertically, though it does stay centered if you make the window tall enough for the content and resize it down.

![Screen record from 2019-09-09 13 43 25](https://user-images.githubusercontent.com/7832163/64561438-fdee5e80-d307-11e9-9e60-a7dcbbfe94b5.gif)

**Comment by prudho** [comment]
It's centered to the dimmer. If your viewport is too small and have to scroll, the dimmer stay upper so the modal is not centered anymore. It's a bug, but I don't know how to fix this 😕
