### ISSUE TITLE
[Tab] Auto-activate doesn't check siblings, breaks individual tab definitions

### ISSUE THREAD

**Issue by Kingo64** [fomantic/Fomantic-UI#1014]
# Bug Report

## Steps to reproduce
1. Initialise a menu with tabs
2. Initialise/modify a single tab in the menu
3. Menu now selects the last modified tab as the 'active' tab incorrectly as it fails to check for siblings

## Expected result
Individual tab should update without affecting the other tab members in the menu.

## Actual result
Last modified tab gets set as the 'active' tab in the menu regardless of actual state.

## Testcase
Demonstration:
[https://jsfiddle.net/spj408zw/](https://jsfiddle.net/spj408zw/)

## Proposed solution
Modify line 697 on tab.js from:
`$anchor = $allModules.filter('[data-' + metadata.tab + '="' + module.escape.string(tabPath) + '"]')`

 To:
`$anchor = $allModules.siblings().filter('[data-' + metadata.tab + '="' + module.escape.string(tabPath) + '"]')`

Worst case scenario, roll back #977 as it introduces issues that were not present before.

## Caused by
#977 

## Version
2.7.8

**Comment by prudho** [comment]
Oh, sorry about that... I did not a anticipated this case 😞

Actually the best fix to provide is to don't check the active tab when a tab was previously initialized. I'll submit a PR soon !

**Comment by lubber-de** [comment]
Fixed by #1025 
See your adjusted jsfiddle here https://jsfiddle.net/bw89drqL/

**Comment by Kingo64** [comment]
Thank you!
