### ISSUE TITLE
YYYY-MM-DD when using 'set date'

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#1019]
# Help Wanted

Just want to ask, is YYYY-MM-DD the corect way format the date when using 'set date'
I have tried with diffrent dates and seem to parse correct every time. 

## Problem

https://jsfiddle.net/p4kbnsae/

**Comment by prudho** [comment]
Yup, this date is parsed correctly every time using this format.

**Comment by lubber-de** [comment]
As @prudho said, this format is parsed (as well as other as you found out), but it's not THE format. 
To be on the very save side, you can always provide a Javascript date object instead of a string.
Closing because your question was answered
