### ISSUE TITLE
[Table] Coloured Border Left

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#1030]
# Feature Request
Essentially a bit like https://fomantic-ui.com/collections/table.html#colored but with the ability to apply it to the left (or right) table row border. A transparent option may also be required.

## Example
https://jsfiddle.net/5for3buz/

## Screenshot
![]()
![image](https://user-images.githubusercontent.com/1376843/65310430-3272dd80-db86-11e9-8cc7-d0243df5ebfc.png)

**Comment by ivandevp** [comment]
Can I work on this?

**Comment by lubber-de** [comment]
@ivandevp I already assigned this to me and a PR is provided this evening

**Comment by ivandevp** [comment]
Oh.. ok. Great!

**Comment by lubber-de** [comment]
Provided PR is here as promised #1049
