### ISSUE TITLE
Label instead of corner icon, is it possible?

### ISSUE THREAD

**Issue by ildede** [fomantic/Fomantic-UI#1035]
# Help Wanted

I'm trying to create an icon with a little label, like this for example:
![Schermata del 2019-09-24 20-49-42](https://user-images.githubusercontent.com/3754465/65541121-fe444780-df0c-11e9-8d9e-79e4622f62cc.png)

I see that this is possible with "_icon & icon_" https://fomantic-ui.com/elements/icon.html#corner-icon
But I can't find a way, directly within Fomantic, of doing this with "_icon & text_". Anyone has some clue about?

Thanks a lot.

**Comment by donaggio** [comment]
Have you looked at this: [https://fomantic-ui.com/elements/label.html#floating](https://fomantic-ui.com/elements/label.html#floating)?
It seems more suited to your needs.

**Comment by ildede** [comment]
The floating label is not so powerful as a group of two icons. For example classes like large/small, or colors, does not work properly on the label.

For now I have created some custom font icon with fontello.

**Comment by hammy2899** [comment]
Currently this is not possible, I can't really think of any reason this would be a common thing you would need so I don't think this would be something we would add unless you can provide some common examples which users would use this for.

**Comment by ildede** [comment]
I don't think this is a common thing, and if this is not something already in Fomantic there is no problem.

My question was just to be sure that I did not miss something.

Thanks ;)
