### ISSUE TITLE
[Grouped Icons][List] Incorrect behaviour of grouped icons in list of item

### ISSUE THREAD

**Issue by Ikaer** [fomantic/Fomantic-UI#1038]
# Bug Report

## Steps to reproduce
use the jsfiddle

## Expected result
grouped icons color should be like normal icon
grouped icons hover color should be like normal icon
grouped icons right margin should be like normal icon

## Actual result
normal color is incorrect.
hover color is incorrect.
right margin is incorrect.

## Testcase
https://jsfiddle.net/7ptejr2f/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/7936075/65600562-a35c3000-dfa0-11e9-9b57-4924948a2594.png)

## Version
2.7.8

Workaround:
https://jsfiddle.net/cav3wsqf/2/

**Comment by mpark86** [comment]
Hi, can I take a look at this?

**Comment by hammy2899** [comment]
@mpark86 Ofcourse 😉
