### ISSUE TITLE
[Dropdown] Prevent focus on Search Selection Dropdown when calling dropdown('show')

### ISSUE THREAD

**Issue by WK6-work** [fomantic/Fomantic-UI#1040]
# Feature Request
## Description
When I call `$.dropdown('show')` to Search Selection Dropdown, the dropdown focuses and scrolls automatically.
​
I would like to control focus and scroll events to the dropdown.
​
## Example
https://jsfiddle.net/ad1h8u03/
​
## Version
2.7.8

**Comment by hammy2899** [comment]
Could you please elaborate more on what you mean exactly as I am a bit confused what your trying to achieve.

**Comment by WK6-work** [comment]
I would like to prevent auto-scrollilng in the right-side example in jsfiddle.
For example by setting a focus option on `$.dropdown('show')`.

e.g.

```
$('#search-selection-dropdown').dropdown('show' { focus: false });
```

![dropdown-auto-scroll](https://user-images.githubusercontent.com/6407737/65682126-4bebbc00-e095-11e9-8cce-0161ba96e70a.gif)

**Comment by lubber-de** [comment]
Made it possible by #1052 
See your adjusted jsfiddle here https://jsfiddle.net/ragfLzky/
