### ISSUE TITLE
Hacktoberfest 2019 🎃

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#1044]
![Hacktoberfest_19_Events_620x76](https://user-images.githubusercontent.com/11588822/65876225-b09e6380-e380-11e9-9914-161b181154c3.png)

Hi all 👋 

Fomantic is participating in Hacktoberfest this year 🎉 we would love for you to spread the word and get as many people as you can involved in open source not just on Fomantic but on as many project as you can. If you've been using open source software for the first time today or the more then 10 years and have never contributed this is a great time to get involved and you can earn yourself a free limited edition T-shirt!

If you want to read more about Hacktoberfest or want to sign up to get your T-shirt head over to the hacktoberfest website! https://hacktoberfest.digitalocean.com

We have added the [`Hacktoberfest`](https://github.com/fomantic/Fomantic-UI/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AHacktoberfest) label to a few issues and we will continue to add it to more as the month goes on. If you decide to work on an issue please leave a comment to let others know so we don't get any duplicate PR's. Also if your struggling to understand anything feel free to leave a comment and ask for help!

> The event starts on 1st October and ends 31st October and you must open 4 valid pull requests to qualify for your free T-shirt.

Good luck to everyone participating 😃

**Comment by lubber-de** [comment]
You might also have a look at the Fomantic-UI-Docs Repository 😉 
https://github.com/fomantic/Fomantic-UI-Docs/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest

**Comment by hammy2899** [comment]
Today is sadly the last day of Hacktoberfest 🎃

I wanted to say a massive thank you to all the amazing people who have contributed this month! Like I have said multiple times this is a community focused project so the more the community becomes involved the better the project will become and this month the community has helped us ship bug fixes and features for our next release so get existed!

For anyone who has not yet contributed please don't let this stop you, contributions from the community is what love it helps improve fomantic for the better.

Again thank you to everyone who has contributed this month!
