### ISSUE TITLE
Form validation disable functionnality on composant does not require Javascript to function

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1053]
# Bug Report

## Expected result
When there is a form validation on form with composant does not required javascript, this composant must function.

## Actual result
When there is a form validation on form with composant does not required javascript, this composant doesn't function.

## Testcase
https://jsfiddle.net/dutrieux/6z17r3q4/1/

## Screenshot
![form_validation](https://user-images.githubusercontent.com/1622751/66061797-711e7580-e540-11e9-84e7-93d96c3ae60f.gif)

## Version
2.7.8

**Comment by lubber-de** [comment]
🤔 Your jsfiddle works fine: The Checkbox is checkable even if JS for form validation is used or not.
However your animated screenshots shows a differen jsfiddle which also uses Angular 1 which might does something with your checkbox which is "corrected" when FUI Form validation is used.
Please provide the jsfiddle from your screenshot for easier investigation

**Comment by dutrieux** [comment]
Ok I find it :
I doesn't work on Firefox but work on Chrome

**Comment by lubber-de** [comment]
Ok, got it. Its not related to firefox, but the way checkboxes are used/supported in form validations. There, it is expected that every checkbox is available as an module object to be able to get its values.
We have to investigate more into this then.
Just for comparison: If i initialize the checkbox before it's working
https://jsfiddle.net/2nkjbhtq/

**Comment by dutrieux** [comment]
I don't understand why it's not due to Firefox because on firefox it's not work and the same jsfiddle work on Chrome, but any way ...

**Comment by lubber-de** [comment]
In chrome direct clicking on the checkbox itself (not the label) was als not working for me

**Comment by dutrieux** [comment]
> 
> 
> In chrome direct clicking on the checkbox itself (not the label) was also not working for me

Ok sorry I ditn't see that :s

**Comment by lubber-de** [comment]
That was quite a headache to find out, but finally fixed by #1068
See your adjusted jsfiddle here (also works on firefox now) https://jsfiddle.net/ysq9j3fn/
