### ISSUE TITLE
[Dropdown] Description position & enhancements

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#1059]
# Feature Request
https://fomantic-ui.com/modules/dropdown.html#description

Have an alternative position for description - such as directly underneath the option (it would also be nice if the description overlap "issue" was fixed so minimum width doesn't need to be set)

Was thinking also to have an alternative/different style so the option name was bold, like a header, and the description was normal colour (the name/header would still be searchable), ie:

![image](https://user-images.githubusercontent.com/1376843/66193423-67a12480-e68a-11e9-96eb-f68aa30c8fa4.png)

Would be good if this could be populated via select options as well using data attributes, such as data-description

**Comment by NestorSegura** [comment]
Hello,

I would like to fix this issue, but I quite don't get what really the problem is. Could you please add an Screenshot?

**Comment by jamessampford** [comment]
Overall, it’s an enhancement of the dropdown description (as per example in the link and mini screenshot) rather than a problem but with the alternative position/style mentioned previously as well as other desired enhancement (data-attribute tags on select options) to populate the description

Though there is a problem with description as it is now (see info box on link), because when the description is too long it overlaps the name/title/label unless a width is provided (but may not always be practical to be provided)

**Comment by lubber-de** [comment]
Implemented by the new optional `vertical item` class in #1116
