### ISSUE TITLE
[Form] transparent input errors

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#107]
Redesign how the transparent inputs display errors as discussed here https://github.com/fomantic/Fomantic-UI/pull/91

**Comment by hammy2899** [comment]
I also ran into this when I did this, I like the animation you did but I'm not 100% maybe the other guys will have an opinion @fomantic/admins 

I personally don't think adding padding to transparent inputs makes them look that bad but again I will wait for the others opinion.

**Comment by prudho** [comment]
Well, `a` is the worst IMHO, since the padding seems really weird on error. But I can't choose between `b` and `c`. Maybe the better is to stay close that non transparent input behaviors, so do not animate them.

**Comment by lubber-de** [comment]
So @ColinFrick , whats your opinion?

**Comment by lubber-de** [comment]
@prudho btw, keep in mind, in case of b) the current behaviour of SUI transparent input could be considered a breaking change, because there is actually no padding

**Comment by ColinFrick** [comment]
IMHO option B fits nicely
I would add new input variables for transparent inputs:
```
@transparentPadding: @padding;
@transparentErrorBackground: @errorBackground;
@transparentErrorColor: @errorColor;
```
So if someone wants to revert to the previous transparent input he can just use these variables.

**Comment by hammy2899** [comment]
Added in 2.6.3
