### ISSUE TITLE
[Dropdown] action button has incorrect border radius

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#1072]
# Bug Report

## Expected result
Dropdown should not have border radius between the action.

## Actual result
Dropdown has border radius as it normally would.

## Testcase
https://jsfiddle.net/pxstuqo9/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/11588822/66294294-8ac51180-e8e0-11e9-88a8-3ba6fc05b6a4.png)

## Version
2.7.8

## Related issues
https://github.com/Semantic-Org/Semantic-UI/issues/5314

**Comment by hammy2899** [comment]
A good fix to this would be to create a new variation for the dropdown of `ui action dropdown` which is the same as `ui action input` but its for the dropdown https://fomantic-ui.com/elements/input.html#action

**Comment by Flo4l** [comment]
I would like to work on this issue :)

**Comment by itsaakashpatel** [comment]
@hammy2899 border-radius: unset property won't do the task?

Thanks!

**Comment by hammy2899** [comment]
@itsaakashpatel Most likely yes but it would be better to add actions support to dropdown.

**Comment by lubber-de** [comment]
Fixed by #1073 
See https://jsfiddle.net/7gf135dc/
@hammy2899 Do you want to open another issue with your `dropdown action` suggestion (although i think it's not needed now)

**Comment by hammy2899** [comment]
@lubber-de I'll just leave it for now since this is technically fixed and the only issue is the class naming isn't semantically correct.
