### ISSUE TITLE
Automate merging dependabot's PR

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#1077]
# Developer productivity for maintainers

## Description

Updating dependencies is important especially for security.

From 2019 July, Dependabot is keep opening many PRs almost daily.
Though it is very helpful, I think it also became a flood of GitHub notification for maintainers/watchers.

So I propose merge automation for minor dependency update using https://mergify.io/ or similar.
For major update like `v7 -> v8`, I think we need manual review and merge process.

**Comment by hammy2899** [comment]
We've had a chat about this before (possibly in Discord). Previously we decided not to auto merge since it could break the build process however now we have CI which checks the build I have enabled auto merging in dependabot.

**Comment by exoego** [comment]
> now we have CI which checks the build I have enabled auto merging in dependabot.

@hammy2899 @lubber-de 
Could you re-consider to enable auto merging

**Comment by hammy2899** [comment]
@exoego It actually is enabled however the bot can't auto merge due to PRs needing reviews before merging and there currently is no way around this.
