### ISSUE TITLE
[Modal] Large modals with less background and detachable: false get cut with wrong top positioning

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#1079]
# Bug Report

The #1013 unfortunately introduced another positioning issue when `detachable:false` is used and the modal is a bit larger 

## Steps to reproduce
1. Look at http://jsfiddle.net/bkh17Lgy/ 
2. Click on "Show modal" at the bottom
3. See the modal is cut at the top

## Expected result
Modal is displayed centered

## Actual result
Modal gets cut because top position has wrong calculated value

#### 2.7.8 with applied #1013
http://jsfiddle.net/bkh17Lgy/ 

#### 2.7.8
http://jsfiddle.net/bkh17Lgy/1

#### 2.7.8 with applied #1013
![image](https://user-images.githubusercontent.com/18379884/66487629-f360e980-eaac-11e9-8e84-48408d8eafc2.png)

#### 2.7.8
![image](https://user-images.githubusercontent.com/18379884/66487655-02e03280-eaad-11e9-9fde-12cd6fa7cd70.png)

## Version
2.8.0 - develop branch

**Comment by lubber-de** [comment]
@prudho Do you have time to investigate into this again?

**Comment by prudho** [comment]
@lubber-de Actually no, work is swallowing my whole time... Feel free to take a look at it if you want !
