### ISSUE TITLE
Not text is being rendered but a handful of letters and question marks (?)

### ISSUE THREAD

**Issue by jprateragg** [fomantic/Fomantic-UI#1085]
# Help Wanted

## Problem
We're currently using 2.7.7 of Fomantic-UI. We're using a vanilla version--no themes/templates/building. Literally downloaded the repository and used the `dist` folder. The only other Javascript/CSS libraries we're using are jQuery, SignaturePad, and TinyMCE. Our application is an internal-only used by employees.

We have two types of users: those who use traditional Windows workstations (desktops/laptops) and those who use virtual desktops (VMware View). All users are using Windows 10 build 1607 and use IE as their main browser. Our virtual desktop users are getting strange issues with the Fomantic-UI interface, and it only seems to be affecting them. I think only one person on a desktop has experienced this issue--but everyone on virtual desktops experiences it. Essentially, all letters on the page will be rendered with a question mark (?) with the exception of a handful of random letters. Clearing the browser cache nor killing all instances of the browser doesn't fix the issue. The only way to fix it is to have the user log off their virtual desktop, then log back on. I've worked with our virtual desktop admin and he can't figure out why the system itself would cause this. Users don't experience this issue on any other internal or external site--just this web application that uses Fomantic-UI.

I have attached a screenshot. I appreciate any help anyone can offer because I'm currently at a loss. Thanks!
![fomantic-ui-issue](https://user-images.githubusercontent.com/3075374/66571160-de339b80-eb3c-11e9-8fa3-6261dd5f676b.png)

**Comment by lubber-de** [comment]
I don't think this is releated to the FUI core.
- Please check the environment of your Virtual Desktops, especially global language
- check, if the VMs do have correct access to the internet (if you use the dist-files the google lato font will still be loaded via internet connection)
- if possible try to at least test once with another browser than IE in the VM Environment
- Please provide a  jsfiddle, which replicates your issue, as we don't know your VM environment and cannot get access to it

**Comment by lubber-de** [comment]
It's probably related how your VMs are being accessed (Citrix, RDP,...) and i guess the font just cannot be rendered correctly to the display engine.
For this you might try to override all fonts globally (To a more common one like "Arial") if you just the dist files. For example like i mentioned here https://github.com/fomantic/Fomantic-UI/issues/367#issuecomment-452618383

**Comment by jprateragg** [comment]
@lubber-de This issue only happens randomly. The user will be working away and interacting with the application without any issues, then after their next click, the entire application renders this way. No amount of clearing cache, Ctrl + F5, or killing all instances of IE will fix it unless the user logs off/on again. But it will work fine for users for 3 days then out of the blue at 2:12pm in the afternoon, it will randomly stop working for someone.

**Comment by jprateragg** [comment]
We don't have Chrome installed on the VM currently, but I'm working with our virtual desktop admin to get it on there so the next time this happens I'll try it in Chrome to see if the same thing happens there.

**Comment by lubber-de** [comment]
This definately sounds like a bug in the display engine how the desktops are being accessed or the IE Version within the VM is not patched (if it is probably not happening when using another browser within the VM)

**Comment by jprateragg** [comment]
My question though is--why just this one site? This is literally the only site our users have issue with. I don't know of any other sites our users use that have this kind of problem. Virtual desktop users have semi-fullish access to the internet so I know they have full access to Google fonts and what not.

**Comment by lubber-de** [comment]
@jprateragg As i guessed before: Maybe it's the only site which uses the Lato Font? 
Please try to override it to make sure it's not related to it.

FUI also makes heavy use of GPU acceleration (`translate3D`, etc...)
A VM usually does not have a real dedicated GPU, which might also be a reason.
Check with your VM admins if, at least for testing purposes, you can assign a vGPU to the VMs (or check if it is already)

**Comment by jprateragg** [comment]
@lubber-de Per your suggestion, I've removed the Google font and re-built Fomantic-UI. I'm going to get this in a test environment and see if the problem persists. Our VMware admin is still looking into the issue.

**Comment by jprateragg** [comment]
@hammy2899 Hey--our VMware admin found this: https://kb.vmware.com/s/article/2151202 He's going to try this fix to see if it makes a difference. It seems like it describes the problem we're having. I will keep you updated.

**Comment by jprateragg** [comment]
@hammy2899 Just another update. We downgraded the UEM agent and the problem re-arose. We now believe the issue may be related to our ForcePoint infrastructure and are now investigating that.

**Comment by lubber-de** [comment]
I am closing this for now and housekeeping, because it is related to your VM infrastructure rather than Fomantic itself.
Out of curiosity, please keep us updated and we'll be happy to reopen this when you can provide a reproducable testcase. 🙂 Thanks
