### ISSUE TITLE
[Form Validation] Automatically add empty rule validation for required fields

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#1094]
Not sure if it exists, don’t believe it does, but how about automatically adding form fields (input/textarea/select) that have the `required=“required”` attribute on them as a validation rule for the empty check? Some other `input` could also have automatic rules, such as `type=“number”` with the min/max attributes, etc etc. Could potentially have it apply with the required+field/fields classes too

I should think Listeners may be required so that if a field were to become no longer required/now required it would be removed/added to the rules. Same may need to be done if a field were added to/removed from the DOM, and something similar if a hidden field becomes visible (?)

If a field were in a segment tab, then when validating the tab should be switched to the tab with the first incomplete field (I don’t think this exists at the moment)

I should also think that a submit button would have to also trigger the validation of whatever form it is inside of the fields that belong to that form

I think if this were done on the fly, then could save some effort in building validation for every form, and only additional validation needs to be manually added, or overrides added in.

**Comment by prudho** [comment]
Well, there's multiple request into this issue, so i'll just anwser to the main for now. Adding an empty check on required fields doesn't seem to be a big deal actually. We can also add a parameter called `autoCheckRequired: true` to disable this feature. What do you think about this @fomantic/maintainers ?
