### ISSUE TITLE
[Form] Refactor input's [type]s

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#1099]
# Feature Request

## Description

* Problem 1. `[type]`s are bloaded and duplicated
    * https://github.com/fomantic/Fomantic-UI/pull/1098#discussion_r335449826
* Problem 2. Some `[type]`s are missing (`month`, `week` and `range`)
    * According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by lubber-de** [comment]
month, week and color added by #2052 
I agree to not refactor the selectors as i initially suggested/thought. The remaining selectors which would have to be excluded are too much

I'll prepare a separate PR for "range"
