### ISSUE TITLE
[Dropdown] Setup select does not convert data-text to Menu items

### ISSUE THREAD

**Issue by ronnievdc** [fomantic/Fomantic-UI#1103]
# Feature Request

## Description
When converting select dropdowns to dropdown menus with `$('select').dropdown()` the data-text metadata is not copied over to the menu dropdown.

Having this feature makes it possible to create select with optgroups, where the visible chosen value as label also contains the optgroup label.

## Testcase
https://jsfiddle.net/6hdtzybr/

**Comment by prudho** [comment]
It should be delivered in 2.8.3 release. Related PR: #1219

**Comment by dutrieux** [comment]
Nice feature !

**Comment by ronnievdc** [comment]
Thanks for adding this feature!
