### ISSUE TITLE
UI menu not at the top of the windows

### ISSUE THREAD

**Issue by Bradley-H** [fomantic/Fomantic-UI#1106]
When I'm making a menu it's not like up aginst the very top of the window. I have to manually edit my styles to have the menu up against the top portion of the window

![Screenshot at 2019-10-18 22-56-48](https://user-images.githubusercontent.com/37282160/67105143-ccb45880-f1fa-11e9-9e31-3b9b7f780d8f.png)

**Comment by lubber-de** [comment]
This should not happen could you please provide a jsfiddle to replicate?

**Comment by GammaGames** [comment]
It kinda looks like some browser default margin shenanigans

**Comment by Bradley-H** [comment]
I found out the problem, I'm using Svelte.js and some of their pre-set css definitions gave the header a 8px padding which gave it that look.
