### ISSUE TITLE
Add node requirement to README.md

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#1107]
# Feature Request

## Description

After many years of Semantic-UI fandom, I grew disheartened by its lack of maintenance. Dozens of small problems like lack of gulp 4 support added too many steps to my deployment process. Today, I discovered Fomantic-UI, and I'm super excited to try it out! But my initial install experience was problematic because `node@10` is required, and the latest (`node@12`) spits out errors at the very end of the process.

```
[16:31:34] Finished 'install' after 1 min
npm WARN notsup Unsupported engine for fomantic-ui@2.7.8: wanted: {"node":">=10.15.3","npm":"6.4.1"} (current: {"node":"12.12.0","npm":"6.12.0"})
npm WARN notsup Not compatible with your version of node/npm: fomantic-ui@2.7.8
npm WARN lsm@1.0.0 No repository field.
```

If the installer is unable to validate and inform of version problems at the beginning of the install process, I very much recommend adding a "Requirements" section to the readme, letting people know to downgrade to `node@10`.

A big thank you to this community for breathing life into this awesome framework!

**Comment by hammy2899** [comment]
@neokio Could you please run these commands and post your output.

```bash
$ node -v
$ npm -v
$ npx gulp -v
```

We run our CI on node 8, 10, 11 and 12 and they all past in their last run so I would like to investigate in to why it is not working for you.

**Comment by neokio** [comment]
I restarted, and reinstalled node 12.12.0 to recreate the error, and now the install (and build) works perfectly. Works like a charm on the latest ...

```
node 12.12.0
npm 6.11.3
gulp CLI 2.2.0
gulp local 4.0.2
```

Chalk this up to unknown user error. It was a fresh install of all tools and services, perhaps restarting was the key. I appreciate you taking the time!
