### ISSUE TITLE
[Modal] Close button inside header

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#1118]
# Feature Request
That would be nice if the modal supports the close button to display inside the header instead of displaying outside of the modal window.

## Description
I prefer the close button of modal to place inside the header. Now, I have to overwrite Fomantic UI CSS to adjust the location of the close button.

## Example
The [full screen modal](https://fomantic-ui.com/modules/modal.html#full-screen) supports the close button within the header. The modal with other sizes should also support too.

## Screenshot (when possible)
![modal](https://user-images.githubusercontent.com/930315/67488524-f86d8d80-f695-11e9-8d0e-afad4d478bdc.png)

**Comment by jgilbertcastro** [comment]
can i test this with raw html or vuejs?

**Comment by lubber-de** [comment]
@jgilbertcastro As it should be adjustable via CSS only, you can test this however you want, as long as the markup is compatible. I would use the docs website @ko2in  mentioned above and resize the screen to test/see the effect and play with changes in developer console

**Comment by lubber-de** [comment]
Fixed by #1215 and released in 2.8.3
