### ISSUE TITLE
[Form] Show/hide message depending on field state

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#1124]
# Feature Request

## Description

`.ui.message.{STATE}` should be shown when the parent `.field` has `.{STATE}` class, otherwise should be hidden,  as similar to [`.ui.form.{STATE}` do so](https://fomantic-ui.com/collections/form.html#field-error).

I think this is useful to control visibility of field-level message depending on field state.

## Testcase
Current:
https://jsfiddle.net/tsL6me0x/

Expected:
https://jsfiddle.net/u0psevtw/

## Screenshot
![image](https://user-images.githubusercontent.com/127635/67546554-a8470780-f737-11e9-8f6a-11e79079b569.png)

## Related Issue
#1097

**Comment by exoego** [comment]
I will address this in PR #1098 or subsequent PR if this suggestion is fine.

**Comment by lubber-de** [comment]
As nobody reviewed your PR so far (i try to do it today), i think this addition could be implemented directly in #1098

**Comment by exoego** [comment]
Thanks, added in PR #1098
