### ISSUE TITLE
[Checkbox] A checked radio input is being hidden by label::before (Angular)

### ISSUE THREAD

**Issue by trandromeda** [fomantic/Fomantic-UI#1126]
# Bug Report

In Angular 7, I've tried various iterations of the radio checkbox straight from the Semantic documentation and initially found that when checking a radio checkbox *on*, it would display the checked state on very briefly before appearing to be checked off again.

This was puzzling because I have used radio checkboxes successfully elsewhere in our application. There was nothing special about this particular checkbox:

```
        <div
            class="ui radio checkbox ourCustomClass"
        >
            <input type="radio" name="radioCheckbox" [checked]="checkIsChecked === someVal" />
            <label>Our label</label>
        </div>
```

and tried both initializing it with $('.ui.checkbox').checkbox() and without. Also tried with and without a `[checked]` attribute.

This was something other members of our team was encountering and we addressed with various patches/hacks to get around.

Finally I saw that the `label` element in a radio checkbox had a styled ::before, and tried overriding it like so:

```
.ui.radio.checkbox input:checked~.box:before, .ui.radio.checkbox input:checked~label:before {
    background: transparent;
}
```

The default value of the background was #fff. Since then the radio checkboxes have been looking and responding just as expected. Still not clear why sometimes this happens to my checkboxes and other times it works out of the box.

## Steps to reproduce
1. Create a group of radio checkboxes using the example from the documentation, sharing the same name
2. Click between the radio buttons
3. Refresh the page and click through the radio buttons again

## Expected result
* Radio checkboxes to be toggled on and off as expected

## Actual result
* Radio checkbox responds briefly to user interaction and then immediately looks 'unchecked.' This is also not consistent - sometimes it will work, other times it won't, between page refreshes

## Screenshot
![Screen Shot 2019-10-25 at 3 13 22 PM](https://user-images.githubusercontent.com/8782432/67597837-168cc980-f73a-11e9-9331-19157b330a07.png)

(note the blue outline of the checkbox indicates it was just clicked)

## Version
2.7.8

**Comment by lubber-de** [comment]
I am unfortunately not able to reproduce this using raw FUI 2.7.8
There is probably something Angular is doing to your checkboxes while managing states. (?)

Here is a jsfiddle: https://jsfiddle.net/o8vzutak/
Please try to adjust it accordingly, so we are able to reproduce the issue 
Thank you

**Comment by lubber-de** [comment]
Closing because of no response. Will reopen if a reproducable jsfiddle is provided
