### ISSUE TITLE
Onchange Calendar not working properly

### ISSUE THREAD

**Issue by lilouch** [fomantic/Fomantic-UI#1127]
I try to implement a calendar only with the date. I would like to get the value of the current selected date on change.
```
<h3>Calendar</h3>
<div class="ui calendar" id="example1">
    <div class="ui input left icon">
      <i class="calendar icon"></i>
      <input type="text" placeholder="Date">
    </div>
  </div>

```
```

$('.ui.calendar').calendar({
 onChange: function (date, text) {
     var newValue = text;
     alert(newValue);
    },
});
```
So far, it's working. I got my alert and the date selected.
However, I'm not interested in time. So, when I initialize a date type calendar, the change is not working anymore. I'm not able to get the current selected value.

```
$('#ui.calendar').calendar({
 onChange: function (date,text) {
     alert("hi");
    },
});
$('#example1')
  .calendar({
    type: 'date'
  })
;
```

Finally, when I implement the range calendar, when I'm calling :
`var dateStart = $('.ui.calendar').calendar('get startDate');`
or 
`var dateStop = $('.ui.calendar').calendar('get endDate');`

I get anything.

Is it a normal behaviour ? Maybe did I miss something ?

**Comment by lubber-de** [comment]
Please try the following working fiddle, because the date is returned just fine also when using `type:'date'`.

**Comment by lubber-de** [comment]
Closing because of no response. Will reopen if it's an reproducable issue. Please adjust my given jsfiddle accordingly
