### ISSUE TITLE
Size setting for dropdown

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1136]
# Feature Request

## Description
I use <select> on my html with $('#select').dropdown() to converted to selection dropdown. To set the size, only posibility is to change the property className.dropdown : like $('#select').dropdown({className:{dropdown:'ui **mini** dropdown'}});

I would be nice, if we can have a property to set the size through settings

**Comment by hammy2899** [comment]
Dropdown size is a visual change so should be applied using CSS via a class which is the current implementation.

**Comment by dutrieux** [comment]
Ok thx for this tip :

https://jsfiddle.net/fhtyzqso/
