### ISSUE TITLE
When detachable false modal is not centered when dynamic content is added

### ISSUE THREAD

**Issue by rmarchiori** [fomantic/Fomantic-UI#1138]
# Bug Report
Modal is not centered when dynamic content is added to it

## Steps to reproduce
1. Click button modal is centered after 5s nre content is added and it is not centered anymore

## Actual result
Modal should be centered

## Testcase
[fiddle](http://jsfiddle.net/e0L176sw/7/)

**Comment by lubber-de** [comment]
This is fixed by https://github.com/fomantic/Fomantic-UI/pull/1096
See your adjusted jsfiddle here http://jsfiddle.net/td396ap8/
