### ISSUE TITLE
Fomantic-UI change Slider label

### ISSUE THREAD

**Issue by CmdrMahesh** [fomantic/Fomantic-UI#1139]
#Fomantic-ui slider change labels texts

## I wonder if there is any way to change the texts that are displayed in the range slider.
I found `labelType:'letter'` which shows A, B, C type label but if it could be possible to show custom texts such as Max, Medium,Low.

**Comment by CmdrMahesh** [comment]
I found 
`<ul class="ui labels">
      	<li class="label"><</li>
        <li class="label">=</li>
        <li class="label">></li>							
 </ul>`

it works and changes the label but it doesn't cover labels at the edge like the default slider shows.

**Comment by ColinFrick** [comment]
You could use the (undocumented) `interpretLabel` setting. it should be a `function(value)` which returns the label.
Example using the greek alphabet: https://jsfiddle.net/t9Lms5ra/

**Comment by CmdrMahesh** [comment]
thank you it worked fine.
maybe this should be added to docs :)
:+1:

**Comment by hammy2899** [comment]
docs issue https://github.com/fomantic/Fomantic-UI-Docs/issues/170
