### ISSUE TITLE
First cell on table definition not properly hidden on Firefox

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1141]
# Bug Report
When table have 'definition' class, the first cell is not properly hidden on **Firefox**, there is a grey border on the left.

## Testcase
https://fomantic-ui.com/collections/table.html#definition

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/1622751/68024493-8bb44d80-fcaa-11e9-9470-9bd947c2b594.png)

## Version
2.7.8

**Comment by lubber-de** [comment]
I unfortunately cannot reproduce this (using the mentioned docs page as testcase ). 😢 
I tried Firefox 68, 69, 70, 71beta on Win10 and MacOS Mojave (all via Browserstack) and even zoomed in up to 200%.
Which Firefox Version, OS, OS DPI Scaling and Browser Zoom factor are you using which reproduces the effect?

**Comment by lubber-de** [comment]
@fomantic/admins Anybody of you able to reproduce this ?
@dutrieux Could you please give some infos i asked for for better investigation?

**Comment by lubber-de** [comment]
Closing for now because of no response.

**Comment by dutrieux** [comment]
I try to find why I have this problem and not you on Firefox, I have this problem on my home and work computer, very strange ...
