### ISSUE TITLE
[Slider] Reversed Vertical Slider's thumb is offset

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#1142]
# Bug Report

## Expected result
Reversed vertical slider thumb should line up with slider

## Actual result
It doesn't

## Testcase
https://jsfiddle.net/82gy40a5/

## Screenshot (when possible)

![image](https://user-images.githubusercontent.com/7832163/68054919-139f5500-fcb5-11e9-85cd-ff2bd42a47af.png)

## Version
2.7.8

## Note
This is fixed by removing the following rule:

```css
.ui.reversed.slider .inner .thumb {
    left: auto;
}
```

A solution could be to make the reversed slider thumb style not apply to vertical ones with the selector `.ui.reversed.slider:not(.vertical) .inner .thumb`

**Comment by RailRunner166** [comment]
I'm liking that solution :eyes:
