### ISSUE TITLE
Wrong Permissions on Generated Files

### ISSUE THREAD

**Issue by tjclifton** [fomantic/Fomantic-UI#1153]
# Bug Report

I'm not sure if it was something specific to my local environment, but when running the installer and then building the CSS, incorrect file permissions are applied to the files in the `dist/` folder.

## Steps to reproduce
1. Install `fomantic-ui` via NPM
2. Run `gulp install -f node_modules/fomantic-ui/gulpfile.js` if necessary 
3. Have the installer set default permission on files (`744` by default)
4. Run `gulp build -f <path-to-fomantic-ui>/gulpfule.js` 
5. Crashes for me with error: `Error: EACCES: permission denied, open '<snip>/semantic/dist/components/reset.css'`

## Expected result

Set file permissions `744` on files

## Actual result

The installer sets the permission in the `semantic.json` as a decimal number:

https://github.com/fomantic/Fomantic-UI/blob/fb9ec3372674509e668110a670de59c6471145d4/tasks/config/project/install.js#L187

Which comes from here by default:

https://github.com/fomantic/Fomantic-UI/blob/fb9ec3372674509e668110a670de59c6471145d4/tasks/config/defaults.js#L14

But the problem arises with the following line:

https://github.com/fomantic/Fomantic-UI/blob/fb9ec3372674509e668110a670de59c6471145d4/tasks/config/project/config.js#L106

This checks the type of the `permission` field, which will be a decimal number by default, and not a string. Then, because a decimal value (in this case `744`) was assigned to `permission`, it reads that value as-is as an octal value, which is used in the `gulp-chmod` plugin. `744` represented in octal is actually `0o1350`, and this is what is essentially passed to the `chmod` handler on the outputted files, and thus very strange permissions are set.

I fix this personally by changing `"permission": 744` to `"permission": "744"`, which causes the above line to parse it correctly as an octal number: `parseInt('744', 8) // => 484, or 0o744`.

## Version
2.7.8

**Comment by lubber-de** [comment]
@ColinFrick Didn't you fix it by #504 somehow? Do we need to change `744` in the default.js to `0o744`
Is this probably related to an older/newer gulp chmod version?

**Comment by ColinFrick** [comment]
Either use octal `0o744` or string `"744"`.
The PR fixed the saved file permission, which is set as a string by the installer.

**Comment by lubber-de** [comment]
@tjclifton Implemented your solution by #1156
