### ISSUE TITLE
[List] Horizontal divided list has an extra left padding for its first child

### ISSUE THREAD

**Issue by sergei-krylov** [fomantic/Fomantic-UI#1158]
# Bug Report
When using a list that is `horizontal` and `divided` the first child has `0.5em` on left padding, and the whole list moves to the right that looks a bit weird.

## Steps to reproduce
Simply make this list
```
<div class="ui container">
  <div class="ui divided horizontal list" style="border: 1px solid red">
    <div class="item">
      <div class="content">
        Item1
      </div>
    </div>
    <div class="item">
      <div class="content">
        Item2
      </div>
    </div>
    <div class="item">
      <div class="content">
        Item3
      </div>
    </div>
  </div>
</div>
```
There are related css classes that apply to the items:
```
.ui.divided.horizontal.list > .item:not(:last-child) {
  padding-right: 0.5em;
}
```
and
```
.ui.divided.horizontal.list > .item {
  padding-left: 0.5em;
}
```

## Expected result
Same as just `horizontal` list the `horizontal divided` list should have no extra padding on the left.

## Actual result
When list has `divided` class it's first child has extra `padding-left: 0.5em` style.
The list looks shifted to the right.

## Testcase
https://jsfiddle.net/sergei_krylov/zu39pxo5/2/

## Version
2.7.8

**Comment by lubber-de** [comment]
As mentioned in the PR, this behavior was wanted to make sure wrapped items align correctly on mobile devices. See #353 
If you remove the padding for the first child, it looks like this:
![image](https://user-images.githubusercontent.com/18379884/68716908-a093b980-05a5-11ea-8855-e7fdc7900b3e.png)

If you keep it as it is, it looks like this:
![image](https://user-images.githubusercontent.com/18379884/68716888-92459d80-05a5-11ea-8536-3b6f09503914.png)

**Comment by hammy2899** [comment]
Closing as per https://github.com/fomantic/Fomantic-UI/pull/1159#issuecomment-553275782
