### ISSUE TITLE
[Label] add inverted variation

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#116]
Add an inverted variation of Label

Same as colored variation but use light colors instead https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/globals/site.variables#L239 like inverted buttons https://fomantic-ui.com/elements/button.html#inverted

**Comment by prudho** [comment]
https://fomantic-ui.com/elements/list.html#inverted ?

**Comment by hammy2899** [comment]
@prudho Still half asleep 😜
