### ISSUE TITLE
Retiring Flag module in favor of Emoji-Flags

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#1172]
# v3 Proposal

## Description
v2.8 added emoji module, which has flags.
https://fomantic-ui.com/elements/emoji.html#flags

It is scalbale (SVG) so looks good at any size.
It also offers up-to-date flags which is missing in current Flag module.
[E.g. Isle of Man](https://github.com/fomantic/Fomantic-UI/issues/660)
![image](https://user-images.githubusercontent.com/127635/68844597-67765900-070d-11ea-9352-3e9df4b95413.png)

So I propose retiring (drop) Flag module from v3.

**Comment by hammy2899** [comment]
I agree with this, just did some quick research and the emoji module offers more flags then the flag module and as @exoego said its more up to date.

**Comment by lubber-de** [comment]
Me too...when doing the emoji docs for 2.8.0 i already thought about at least put a hint into the flags docs to use flag emojis instead.
However, we could still keep the existing flag element and just replace the sprite position by appropriate emoji flags, so existing code will still work (and flags will get a sizing option too!)
This might be only for 2.x and completely remove the separate flag element in 3.x

**Comment by lubber-de** [comment]
I'll prepare a PR as i also have to improve the auto sizing of emojis.

**Comment by exoego** [comment]
Auto-sizing was addressed in PR #1175
