### ISSUE TITLE
probleme

### ISSUE THREAD

**Issue by chanez-web** [fomantic/Fomantic-UI#1177]
# Bug Report

## Steps to reproduce
1. i have bugs whene it come to installe fomantic -ui
2.
### 
# Expected result

192 error Unexpected end of JSON input while parsing near '...4f58","tarball":"http'

## Screenshot (when possible)
![]()

## Version
npm version 6 node 10

**Comment by hammy2899** [comment]
@chanez-web could you please post the full error you are getting and also run the commands below and post the output.

```bash
$ node -v
$ npm -v
$ gulp -v
$ npx gulp -v
```

This helps us debug your issue 🙂

**Comment by chanez-web** [comment]
node  v 10.16.3

npm v6.11.3

gulp (n'est pas reconnu ) he is not recognized

this is all  what is poste whene i execute this commande (npx gulp -v )-->

npm ERR! Unexpected end of JSON input while parsing near '...4f58","tarball":"http'
npm ERR! a complet log of this run can be found in: ERR C:\Users\ACER\AppData\Roaming\npm-cache\_logs\2019-11-15T19_42_27_239Z-debug.log

**Comment by hammy2899** [comment]
@chanez-web could you please upload this file so I can view your log
`C:\Users\ACER\AppData\Roaming\npm-cache_logs\2019-11-15T19_42_27_239Z-debug.log`

**Comment by chanez-web** [comment]
[](C:\Users\ACER\AppData\Roaming\npm-cache\_logs)

















**this is the file **

[2019-11-15T19_42_27_239Z-debug.log](https://github.com/fomantic/Fomantic-UI/files/3852999/2019-11-15T19_42_27_239Z-debug.log)

**Comment by hammy2899** [comment]
@chanez-web could you try running `npm cache clean` and then trying to install again.

**Comment by chanez-web** [comment]
if i run this commande it while delete all my first work whith npm  because i work  whith angula cli

**Comment by hammy2899** [comment]
It won't delete your work `npm cache clean` just cleans the cache npm uses to fetch and download packages from the registry. You can read more about it here https://docs.npmjs.com/cli/cache.html

**Comment by chanez-web** [comment]
it work  thank you so much for your help
