### ISSUE TITLE
[Input] Action input in STATE field has darker border 

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#1181]
# Bug Report

## Expected result

All borders around action button in input should have same color.
![image](https://user-images.githubusercontent.com/127635/69033642-c34d2480-0a22-11ea-9e1f-403590d6d26d.png)

## Actual result

Border-top, right and bottom has darker color.
![image](https://user-images.githubusercontent.com/127635/69033476-6f424000-0a22-11ea-889c-87eabf437db6.png)

## Testcase
https://jsfiddle.net/nfx5k60p/

## Version

2.8,1

**Comment by dutrieux** [comment]
Do you notice that when input take focus, the right border is rounded :

![image](https://user-images.githubusercontent.com/1622751/69052636-d1417c00-0a07-11ea-937a-02e2ff5e82ef.png)

**Comment by exoego** [comment]
@dutrieux 
Nice catch 👍 

I think that STATEs are not direct cause of the unnecessary rounds, since unnecessary rounds also appear in default inputs.
Could you file a new issue ?

**Comment by dutrieux** [comment]
@exoego 
I already do a issue : https://github.com/fomantic/Fomantic-UI/issues/1185
