### ISSUE TITLE
problem angular 

### ISSUE THREAD

**Issue by chanez-web** [fomantic/Fomantic-UI#1183]
# Bug Report

i have a bugs whene it come to install angularCLI (whene i executed this  commende npm install -g @angular/cli )

## Steps to reproduce
1.
2.
3.

## Screenshot (when possible)
![]()

## Version
x.x.x

**Comment by hammy2899** [comment]
@chanez-web Please use the issue templates provided and elaborate on your issue.

**Comment by hammy2899** [comment]
@chanez-web bump

**Comment by hammy2899** [comment]
Closing due to no response.
