### ISSUE TITLE
[Input left action] in form

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1185]
# Bug Report

## Expected result
Left corners **aren't** rounded when the input is in form
![image](https://user-images.githubusercontent.com/1622751/69054519-064fcd80-0a0c-11ea-8782-8c8f51d032c0.png)

## Actual result
Left corners are rounded when the input is in form
![image](https://user-images.githubusercontent.com/1622751/69054356-ae18cb80-0a0b-11ea-9a96-6421b33064b1.png)

## Testcase
https://jsfiddle.net/9tzLg5vq/1/

## Version
2.8.1

**Comment by KarlaChen** [comment]
Hi, @dutrieux , can I fix it?

**Comment by dutrieux** [comment]
@KarlaChen of course, I have not time at moment

**Comment by lubber-de** [comment]
Their already is a pr from @exoego which is supposed to also handle the left actions. See my review comment there https://github.com/fomantic/Fomantic-UI/pull/1197

**Comment by exoego** [comment]
@KarlaChen 
Thanks for taking a atime to resolve this issue 👍 
I have already updated a PR to resolve this issue in #1197.

It would be very helpful if you deal with other issues.
Issues labeled with `good first issue` are good as entry point.
https://github.com/fomantic/Fomantic-UI/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen++label%3A%22%3A1st_place_medal%3A+good+first+issue%22+
