### ISSUE TITLE
Can't install on node v12.13 and npm v6.13

### ISSUE THREAD

**Issue by loweoj** [fomantic/Fomantic-UI#1186]
I'm getting the following error when running npm install: `Unsupported engine for fomantic-ui@2.8.1: wanted: {"node":">=10.15.3","npm":"6.4.1"} (current: {"node":"12.13.0","npm":"6.13.0"})`

My installed versions are:
node: 12.13
npm: 6.13
npx gulp -v:
CLI version: 2.2.0
Local version: 4.0.2

I realise that fomantic requires npm 6.4.1 but I'm curious why? Is there anything I can do other than locking my npm version to 6.4.1?

**Comment by hammy2899** [comment]
@loweoj This is actually a bug, the version shouldn't be absolute.

I will publish a fix in about 30mins.

**Comment by hammy2899** [comment]
@loweoj Give `npm install fomantic-ui` a go, should work now :tada:

**Comment by loweoj** [comment]
Thanks for such a speedy turn-around with this!
