### ISSUE TITLE
[Dropdown] 'set text' does not work with multiselect dropdowns

### ISSUE THREAD

**Issue by chrisdant** [fomantic/Fomantic-UI#1187]
# Bug Report

## Steps to reproduce
1. Create a multiselect dropdown
2. Use 'set text' behavior to set text to 'Foo'

## Expected result
Input field of dropdown should show text 'Foo'

## Actual result
Input field of dropdown shows placeholder text or 'X selected'

## Testcase
https://jsfiddle.net/6x12fbow/10/

## Version
2.8.2

If this is just me missing something, please let me know!

**Comment by prudho** [comment]
This is connected to the `forceSelection` parameter which trigger an internal change... and I don't know how to efficiently fix this 😕

**Comment by lubber-de** [comment]
It does work, however, multiple dropdown uses `set text` internally when labels are not used.
i adjusted your jsfiddle accordingly to make it work inside the onchange function.
https://jsfiddle.net/lubber/rme17v4L/8/
