### ISSUE TITLE
[Tab] Set Active Tab on Instantiation

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#1188]
# Feature Request

## Description
Relevant to this pr: https://github.com/fomantic/Fomantic-UI/pull/977
I have a set of tabs that I initialize and then set the correct tab just after. Because of the above pr, the `onVisible` callback is fired on initialization and when changed to the correct tab. I think it would be nice to be able to pass in `activeTab` in the settings object with the string value that would be passed to the `change tab` behavior. This would help simplify tab initialization through js and remove unintended callbacks.

## Testcase (when possible)
https://jsfiddle.net/ykrae8jp/

## Screenshot (when possible)

![image](https://user-images.githubusercontent.com/7832163/69194250-e4c31480-0ae5-11ea-8ec9-1e4e959002aa.png)

**Comment by maidzen** [comment]
You could just use the "active" class on the menu and content
https://jsfiddle.net/ktfz1se6/

**Comment by GammaGames** [comment]
Yes, that is the way it acts by default. I am not setting the active tab in the html, I'm loading the html and then selecting the active tab in js

**Comment by lubber-de** [comment]
With #1488 the auto activation can be skipped, so the event handler will only be called once in your fiddle again
See your adjusted jsfiddle here https://jsfiddle.net/o5w6t9rx/

**Comment by lubber-de** [comment]
Fixed by #1488 now as you need:
The new option `autoTabActivation` can also be used to define a tab-path to set the active path on initialization (if now active tab exists), so you don't need an additional "change tab" behavior anymore 
See your adjusted jsfiddle here https://jsfiddle.net/ntz2eyf5/
