### ISSUE TITLE
[Dropdown] option text is filled with value if empty

### ISSUE THREAD

**Issue by LolHens** [fomantic/Fomantic-UI#1191]
# Bug Report

When I create a dropdown from a select, all options that had an empty text get the value as their text.
This was introduced in #1112:
```diff
- html +=   escape(option[fields.name],preserveHTML);
+ html +=   escape(option[fields.name] || option[fields.value],preserveHTML);
```
Is this behavour intentional? It doesn't happen on normal selects.

## Steps to reproduce
1. Create a select:
```html
<select class="ui search dropdown filter-dropdown">
  <option value="-1"></option>
  <option value="0">Item A</option>
  <option value="1">Item B</option>
  <option value="2">Item C</option>
</select>
```
2. Initialize dropdown:
```js
$(".dropdown").dropdown();
```

## Expected result
The first option is empty.

### Screenshot
![grafik](https://user-images.githubusercontent.com/1524059/69326193-afd0d200-0c4b-11ea-9c64-9527323c2095.png)

## Actual result
The first option has "-1" as its text.

### Screenshot
![grafik](https://user-images.githubusercontent.com/1524059/69325458-7c417800-0c4a-11ea-86ff-1c5a25a1dd5b.png)

## Testcase
https://jsfiddle.net/mons57e2/

## Version
Since #1112

**Comment by lubber-de** [comment]
Fixed by #1209
