### ISSUE TITLE
i want to créate form with angular and a have same problem in it

### ISSUE THREAD

**Issue by chanez-web** [fomantic/Fomantic-UI#1192]
whene i use the directive ngForm 
in the console appears bugs

in the console i have this 
compiler.js:2175 Uncaught Error: Template parse errors:
There is no directive with "exportAs" set to "ngForm" ("              
                         
                          <form (ngSubmit)="onSubmit(f)" [ERROR ->]#f="ngForm">
  <div class="three fields">
      
"): ng:///AppModule/EdtClientComponent.html@8:57
    at syntaxError (compiler.js:2175)
    at TemplateParser.parse (compiler.js:11388)
    at JitCompiler._parseTemplate (compiler.js:25963)
    at JitCompiler._compileTemplate (compiler.js:25951)
    at compiler.js:25895
    at Set.forEach (<anonymous>)
    at JitCompiler._compileComponents (compiler.js:25895)
    at compiler.js:25808
    at Object.then (compiler.js:2166)
    at JitCompiler._compileModuleAndComponents (compiler.js:25807)
syntaxError @ compiler.js:2175
parse @ compiler.js:11388
_parseTemplate @ compiler.js:25963
_compileTemplate @ compiler.js:25951
(anonymous) @ compiler.js:25895
_compileComponents @ compiler.js:25895
(anonymous) @ compiler.js:25808
then @ compiler.js:2166
_compileModuleAndComponents @ compiler.js:25807
compileModuleAsync @ compiler.js:25769
compileModuleAsync @ platform-browser-dynamic.js:223
compileNgModuleFactory__PRE_R3__ @ core.js:40264
bootstrapModule @ core.js:40599
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1

**Comment by hammy2899** [comment]
@chanez-web Could you please use the issue templates provided, it helps us triage your issue so we can provide the best support.

**Comment by hammy2899** [comment]
Closing due to no response.
