### ISSUE TITLE
Hat Wizard Icon

### ISSUE THREAD

**Issue by cahitberkaykazangirler** [fomantic/Fomantic-UI#1193]
# Bug Report

hot wizard icon does not appear on the system

**Comment by hammy2899** [comment]
@cahitberkaykazangirler `hot wizard` isn't an icon, do you mean `hat wizard`? If you do `hat wizard` works.

**Comment by cahitberkaykazangirler** [comment]
@hammy2899 This icon comes when you type hat wizard.
![image](https://user-images.githubusercontent.com/24186944/69482303-612d5e80-0e2a-11ea-82ba-59a5b5b521da.png)

**Comment by hammy2899** [comment]
@cahitberkaykazangirler Works for me
![image](https://user-images.githubusercontent.com/11588822/69482828-0db21500-0e18-11ea-914d-a486a9ea88cb.png)

What version of FUI are you using and how are you using it (CDN, npm etc.)?

**Comment by cahitberkaykazangirler** [comment]
FUI 2.8.1 and CDN..

https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.1/dist/semantic.min.css
https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.1/dist/semantic.min.js

@hammy2899

**Comment by cahitberkaykazangirler** [comment]
Sorry, I think I need to upgrade my FUI version to 2.8.2. @hammy2899
