### ISSUE TITLE
[Table] Wrong background colour for sorted headers of "very basic" table's variation

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#1194]
# Bug Report

## Expected result
Headers of "very basic" tables (sorted or not) shouldn't have a background color

## Actual result
Sorted header gains a grey background color. This doesn't happen for mobile breakponts (stacked version of the table)

## Testcase
[https://jsfiddle.net/qofhe9vu/show/](https://jsfiddle.net/qofhe9vu/show/)

## Version
2.8.2

**Comment by lubber-de** [comment]
Fixed by #1198
