### ISSUE TITLE
[2.8.1 Breaking Change] Messages inside forms suddenly hidden

### ISSUE THREAD

**Issue by willstott101** [fomantic/Fomantic-UI#1196]
This pull request (#1098 ) seems to be about adding more states to form fields but has an (un-intended? @exoego ) side effect of now hiding `info` `message`s by default when inside forms.

https://github.com/fomantic/Fomantic-UI/pull/1098/files#diff-b650ec5f85caa780eb3a89521725f844R298-R304

So hidden in a minor release we've got parts of my pages suddenly disappearing! Perhaps the messages should only be hidden if the form has a conflicting state class? That feels over-complicated still though.

**rant**
It looks like this behaviour of hiding (warning/error) messages by default has been in semantic-ui for over 5 years... so it's no-one's fault in this project.

Honestly I think it's pretty pointless and not at all user-friendly having anything in the dom hidden by default. Especially based on context (I now have to add `visible` to all my `message`s just-in-case). I wouldn't have had my templates render the message unless I wanted it there. If I want to render it and it not be seen I use an explicit `hidden` class.

I'd personally very much like to see it gone for Fomantic 3.0, preferring richer and better javascript to manage these effects, rather than over-complicated css.
**/rant**

Thanks for all your work here,
**P.S. The coloured form fields look great ;)**

**Comment by lubber-de** [comment]
🤔 We could think about reducing this css and only leave the selector having `:empty` attached.  That probabyl needs adjustments in the validator js code as well

**Comment by lubber-de** [comment]
### Interim Status
🤔 I tried my approach (just leave `:empty`) but turns out setting even an empty message to `display:none` is necessary for Safari, because otherwise it does not show the message at all. We fixed that back then by https://github.com/fomantic/Fomantic-UI/pull/558

I'll play with some more options

**Comment by lubber-de** [comment]
I added a hint to use the `visible` class in case you have static messages inside a form by https://github.com/fomantic/Fomantic-UI-Docs/pull/305

It is already stated in the docs how to force a visiblilty of messages
https://fomantic-ui.com/collections/message.html#visible

It is also stated in the docs that any message component inside a form is basically hidden by default.
https://fomantic-ui.com/collections/form.html#message
![image](https://user-images.githubusercontent.com/18379884/129477560-b1f12ffe-a8ca-4d7f-8dfb-ed754769455a.png)

Before i did this, i tried to make (non empty) messages visible all the time by the `:not(:empty)` selector without any dependency to a form state.
While this basically worked, the possible usecase to display predefined messages inside fields or field groups depending on the form state would have been broken then.
