### ISSUE TITLE
[Form] fields class in fields class add extra margin-bottom

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1202]
# Bug Report

Where there is a fields class in a fields class, a extra margin-bottom is add.

## Testcase
https://jsfiddle.net/dutrieux/sbyt46a9/

## Screenshot
![image](https://user-images.githubusercontent.com/1622751/69914985-5423f700-144a-11ea-9485-dfb148fa830b.png)
![image](https://user-images.githubusercontent.com/1622751/69914903-913bb980-1449-11ea-90da-02504ff589b1.png)

## Version
2.8.2

**Comment by lubber-de** [comment]
@dutrieux Thanks. I just adopted your fix by #1208  😃
