### ISSUE TITLE
Fomantic-UI type definitions for Angular project

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1205]
Hello,
I'm looking for Fomanti-UI type definitions for an Angular project. I can't see Fomantic-UI from [here](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types).

Is still valid to install typings for Semantic-UI? I mean `npm install --save @types/semantic-ui`

**Comment by hammy2899** [comment]
@smartm0use Yeah just use the semantic types you mentioned for now, I will see what I can do for the modules we have added like calendar etc.

**Comment by hammy2899** [comment]
Related to https://github.com/fomantic/Fomantic-UI/issues/396

**Comment by smartm0use** [comment]
Do you know what is the right way to import Fomantic-UI (and related Semantic-UI typings) into an Angular project?

**Comment by hammy2899** [comment]
I haven't used angular for years so no however you shouldn't need to import them like other packages if your `tsconfig` is setup correctly.

**Comment by smartm0use** [comment]
In my `angular.json' file I have set the following:

```
"scripts": [
    "node_modules/jquery/dist/jquery.min.js",
    "node_modules/fomantic-ui/dist/semantic.min.js"
]
```

and in my `tsconfig.ts` file I have set this:

```
"types":[
    "jquery",
    "semantic-ui"
]
```

But the app fails to compile and I have this error in my IDE:

**TS2339: Property 'dropdown' does not exist on type 'JQuery<HTMLElement>'.**

**Comment by hammy2899** [comment]
Try and remove the `types` property from your `tsconfig` because typescript will automatically pickup any types installed from the `@types` org.

**Comment by smartm0use** [comment]
Nothins has changed. Maybe the problem is that Fomantic-Ui isn't matching with Semantic-UI types?

**Comment by hammy2899** [comment]
Can you post a snippet of code where you use fui?

**Comment by smartm0use** [comment]
```
import {Component, OnInit, ViewEncapsulation} from '@angular/core';
import {ActivatedRoute, Router} from '@angular/router';

@Component({
    selector: 'search-users',
    templateUrl: './search-users.component.html',
    styleUrls: ['./search-users.component.scss'],
    encapsulation: ViewEncapsulation.None
})
export class SearchUsersComponent implements OnInit {
    users: Array<any>;

    constructor(private router: Router, private activatedRoute: ActivatedRoute) {
        // Some code...
    }

    ngOnInit() {
        $('.ui.dropdown').dropdown();
    }

    // Other methods...
}
```

**Comment by hammy2899** [comment]
Maybe try and import jquery then typescript will load the types.

**Comment by smartm0use** [comment]
For jQuery I have a "global" import in `main.ts` file:

`import * as $ from 'jquery';`

**Comment by hammy2899** [comment]
Yeah but you will need to import it in every file you use `$` just like every other package.

**Comment by smartm0use** [comment]
I have tried, but nothing changed :(

**Comment by hammy2899** [comment]
Try adding this to your `tsconfig` 
```
"typeRoots": ["./node_modules/@types"]
```

**Comment by smartm0use** [comment]
Yes, I have already it by default.

**Comment by hammy2899** [comment]
Hmm the only thing I can think of is like you said its not loading the types because ts will not load the `@types/semantic-ui` package because theres no import for `semantic-ui`. You could try and bind the semantic-ui types to the fomantic-ui package by creating your own definition with a local `index.d.ts` file if you want to give that ago.

**Comment by smartm0use** [comment]
> @smartm0use Yeah just use the semantic types you mentioned for now, I will see what I can do for the modules we have added like calendar etc.

Could be an issue related to different naming?

**Comment by smartm0use** [comment]
It is 2020, and there is no way to import Fomantic-UI in an Angular project.
I don't know what I changed in my app, I'm getting this kind of error when I try to use methods of Fomantic-UI:

**error TS2339: Property 'dropdown' does not exist on type 'JQuery<HTMLElement>'**

Could it be related to a different version of jQuery that now says `type 'JQuery<HTMLElement>'` instead of `type 'JQuery'`?

**Comment by smartm0use** [comment]
Anyone here is able to use Fomantic-UI into an Angular project?

**Comment by qJake** [comment]
FYI - If you are getting TS errors in the `index.d.ts` file for Semantic's type definitions, you need to include `@types/jquery` version 3.x or higher. The 1.x/2.x versions of jQuery types are not compatible with the Semantic typedefs.

**Comment by prudho** [comment]
Hi, #2822 should make it work.
