### ISSUE TITLE
[Flyout] add flyout as an alternative to modals

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#121]
Create a `flyout` component which is an alternative to modals. They are off canvas menus which can contain anything but overflow over the page content and you can have multiple over one another.

**Comment by romaninsh** [comment]
Google Analytics Admin uses Flyouts in some of their new additions. Screenshots below:

<img width="822" alt="44655268-7085e800-a9ec-11e8-8ba3-e262e54f28e3" src="https://user-images.githubusercontent.com/453929/45745090-e9e1b680-bbf7-11e8-97a5-13e58ef6e0dc.png">

Another Flyout can be opened, shifting the content of original fly-out to the left, so you always see what's behind it:

<img width="825" alt="44655273-724fab80-a9ec-11e8-852f-002f4b34c36a" src="https://user-images.githubusercontent.com/453929/45745120-fd8d1d00-bbf7-11e8-98a8-5aa081b17580.png">

Alternative implementation using SemanticUI and custom CSS:
<img width="1186" alt="41942865-350a230c-796f-11e8-994b-4fe3c604f55b" src="https://user-images.githubusercontent.com/453929/45745153-11d11a00-bbf8-11e8-9a48-28c7cfbacaa1.png">

**Comment by romaninsh** [comment]
Possibly useful - our current code: https://gist.github.com/romaninsh/b74e0570ab5db94d8f52c6147949be73 implementing the fly-out (tks @ibelar!)

**Comment by hammy2899** [comment]
Thanks for the images, will be a big help.

**Comment by prudho** [comment]
Please take a look at #2004.
