### ISSUE TITLE
Wrong data after compiling

### ISSUE THREAD

**Issue by Gokujo** [fomantic/Fomantic-UI#1225]
# Bug Report

I use theme.config to compile own config of fomantic. My old files were made with version 2.7.2. It worked fine. And with version 2.8.2 in css files contains the wrong paths for images and icon fonts. I used material for site but in material folder you can't find either flags.png nor icon fonts.

## Steps to reproduce
1. https://fomantic-ui.com/introduction/getting-started.html

## Testcase
https://pastebin.com/e2Rx9XBQ

## Version
2.8.2

## Screenshot
![Screenshot_3](https://user-images.githubusercontent.com/19776684/70913819-0ba63500-2017-11ea-8f63-8c8ddcc163a9.png)

**Comment by lubber-de** [comment]
If this still happens with 2.9.2,  it should be fixed by #2715

**Comment by lubber-de** [comment]
Potential dupicate of #2261 and fixed by ##2262
I close this for now. If you still encounter the same issue using the latest version, will reopen again
