### ISSUE TITLE
How to remove the installation wizard on npm install?

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1226]
Hello,
I have installed Fomantic-UI in my Angular project using `npm i fomantic-ui`, as described [here](https://fomantic-ui.com/introduction/getting-started.html).

Can you tell me how to prevent the Fomantic configuration wizard from prompting after installation?

Since I use dist folder coming from "node_modules/fomantic-ui" I do not need semantic folder and semantic.json file. So how can I prevent it from being created?

**Comment by hammy2899** [comment]
@smartm0use Since your not using theming you could just use [`fomantic-ui-css`](https://github.com/fomantic/Fomantic-UI-CSS) which doesn't have an installer and would only install to your `node_modules` directory.

**Comment by lubber-de** [comment]
Closing because of no more response and supposing you are using the advice from @hammy2899
