### ISSUE TITLE
Button groups collapse on mobile?

### ISSUE THREAD

**Issue by vidoardes** [fomantic/Fomantic-UI#1230]
I have created a group of buttons like below, but they don't collapse when I view on mobile. Am I doing something wrong, or is this expected behaviour?

https://jsfiddle.net/vidoardes/mgq697xb/4/

**Comment by lubber-de** [comment]
This feature is indeed missing...but possible with a few CSS additions.
I will prepare a PR to implement `stackable buttons`.
In the meantime, i adjusted your jsfiddle here https://jsfiddle.net/a4vj9ucs/

**Comment by vidoardes** [comment]
Thanks, that looks to work pretty well!

**Comment by lubber-de** [comment]
Implemented by #1709
