### ISSUE TITLE
[Slider] [commit 4b1d548] broke smooth: true with preventCrossover: true

### ISSUE THREAD

**Issue by mfeherpataky** [fomantic/Fomantic-UI#1231]
At the moment the DOCS of Fomantic show examples of smoothly repositioned slider.
It however it does not move smoothly, and the slider thumb moves in discreet steps to where the click was registered (even in cases of `step: 0`).

The root cause is the [commit 4b1d548](https://github.com/fomantic/Fomantic-UI/commit/4b1d54894c640896e6554358140e4578159a9bf4#diff-52cb3744b99612b0af91190a82e69b59)
Commit message says
> BREAKING CHANGE: `preventCrossover ` is set to true by default, making this a breaking change.

Current state of affairs: `smooth` works only when `preventCrossover` is set to false

Ideas for possible solutions:
(a) handle both `smooth: true` and `preventCrossover: true`,
(b) immediately - do not set `preventCrossover: true` and/or add information to Docs that prevent `preventCrossover: true` renders `smooth: true` invalid.

**Comment by lubber-de** [comment]
We'll look into this, both settings being true should work together of course

**Comment by lubber-de** [comment]
fixed by #1232
