### ISSUE TITLE
Cursor not visible on search dropdown (Field Error)

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1235]
# Bug Report

With field is Search Dropdown and field have error class, the cursor is not properly visible when the field have focus

## Testcase
https://jsfiddle.net/dutrieux/gLu4zt3m/

## Screenshot (when possible)
![cursor](https://user-images.githubusercontent.com/1622751/71376912-716c6100-25c3-11ea-9a00-0bb32e77d123.gif)

## Version
v2.8.2 (Chrome or Firefox)

**Comment by lubber-de** [comment]
Fixed by #1307 
Thanks for the z-index hint. I changed it to `auto` instead to make sure a fixed 1 won't interfere with the other dropdowns z-indexx values
