### ISSUE TITLE
[Form] action or labeled input doesn't have error style in grouped fields

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1238]
# Bug Report

Action or labeled input doesn't have error style in grouped fields

## Testcase
https://jsfiddle.net/dutrieux/a2po6z54/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/1622751/71280612-f81f0500-235b-11ea-94ae-8a9494139ad3.png)

## Version
v2.8.2

**Comment by lubber-de** [comment]
Fixed by #1614 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/nudwt41r/3/
