### ISSUE TITLE
Compact grid has incorrect margin

### ISSUE THREAD

**Issue by luki1412** [fomantic/Fomantic-UI#1260]
Hello everyone, awesome project just noticed one bug:
When you create a div with grid, the grid gets -1REM margin and rows get +1REM padding, however when you use Compact grid, the padding goes to +0.5REM but margin stays on -1REM therefore content is cut off.

**Comment by luki1412** [comment]
Here's the fiddle: https://jsfiddle.net/o7zfh3wn/

Look at margin and padding for grid,row and column and then remove compact class on grid.
Without compact it works correctly as the sum of padding on row and column adds up to negative margin on grid. With compact it does not and the menu bar is cut off. Column is missing 7px padding top and bottom.

**Comment by ko2in** [comment]
I don't think it's a bug. You can use `internally celled grid` for your use case. [Here](https://jsfiddle.net/pg51owf8/) is the modified version of your fiddle.

**Comment by exoego** [comment]
@ko2in Thanks for suggesting useage of `internally celled grid`

**Comment by exoego** [comment]
@luki1412 
PR #1492 is going to fix margins/paddings of `compact` grid.
I made https://jsfiddle.net/6tun4bor/ based on your fiddle and PR #1492.
Could you confirme that the result is what you are expecting ?

**Comment by luki1412** [comment]
> @luki1412
> PR #1494 is going to fix margins/paddings of `compact` grid.
> I made https://jsfiddle.net/6tun4bor/ based on your fiddle and PR #1494.
> Could you confirm that the result is what you are expecting ?

If you look at my fiddle there is a commented CSS code. If you uncomment it you should see what I have in mind. Not really the same.

**Comment by luki1412** [comment]
> I don't think it's a bug. You can use `internally celled grid` for your use case. [Here](https://jsfiddle.net/pg51owf8/) is the modified version of your fiddle.

Well it is a bug if it doesnt behave the way it's supposed to. Per documentation you can make the grid compact. However it breaks due to compact class.

Here are the details you can observe:
**.grid**  margin all -14px
 **.row** padding top and bottom 14px
  **.column** padding left and right 14px

**.compact** grid margin all -14px
 **.row** padding all 7px
  **.column** padding left and right 7px

Looking at the compact grid sum doesn't add up does it.

**Comment by mareeo** [comment]
I've noticed this same issue, here's an example that's maybe easier to see with a suggested fix for compact and very compact grids commented out. It fixes the original issue of this post and also fixes an issue of compact and very compact grids not having overflowing horizontally when used without rows. The layout was working differently for a normal grid vs compact/very compact grids and these changes makes all the grids work consistently.
[https://jsfiddle.net/wovbrhp1/4/](https://jsfiddle.net/wovbrhp1/4/).

**Comment by lubber-de** [comment]
@mareeo Your proposed fix looks good. Would you like to create a PR accordingly? 😉

**Comment by mareeo** [comment]
https://github.com/fomantic/Fomantic-UI/pull/1794
