### ISSUE TITLE
Inverted sub header color bug

### ISSUE THREAD

**Issue by luki1412** [fomantic/Fomantic-UI#1261]
When you put a header inside an Inverted UI Segment and then add a Sub Header inside that header, only the header gets inverted. Header and icon will be white, subheader will stay black.

EDIT: Seems like its only an issue when putting subheader inside content div like examples on the 
https://fomantic-ui.com/elements/header.html#icon-headers

**Comment by lubber-de** [comment]
I caanot reproduce this unfortunately. I prepared a jsfiddle here https://jsfiddle.net/ub3m5vsL/
Could you please adjust this to make it reproducable? Thanks
![image](https://user-images.githubusercontent.com/18379884/72325366-400c2000-36ad-11ea-826c-315c413ab627.png)

**Comment by lubber-de** [comment]
Nevermind, forgot to try to put it into a content div as you said 🙄 
Reproducable here https://jsfiddle.net/ub3m5vsL/1/
![image](https://user-images.githubusercontent.com/18379884/72325687-f2dc7e00-36ad-11ea-965b-6aeb3b622258.png)

**Comment by lubber-de** [comment]
Fixed by #1262
See https://jsfiddle.net/ub3m5vsL/2/

**Comment by luki1412** [comment]
> Fixed by #1262
> See https://jsfiddle.net/ub3m5vsL/2/

Thanks for the quick response and fix.
