### ISSUE TITLE
CSS bug multiple modals border-radius missing on second+ overlay. 

### ISSUE THREAD

**Issue by VanquishedWombat** [fomantic/Fomantic-UI#1274]
Description: Where multiple modals are displayed (allowMultiple = true) when the second modal opens over the first, then the faint dimmer div that is placed over the first modal is missing the css border-radius setting. Because modals have a border-radius, this has the effect of putting square corners on modal 1. 

Repro of issue: https://jsfiddle.net/fsge8zo9/3/ Look at bottom left corner of first modal when second modal has been opened.

**Comment by lubber-de** [comment]
Fixed by #1275 
See your adjusted jsfiddle here https://jsfiddle.net/10dbpftg/
