### ISSUE TITLE
Validation does not police leading and trailing spaces.

### ISSUE THREAD

**Issue by VanquishedWombat** [fomantic/Fomantic-UI#1278]
Originally identified by @Gwi in discord. 

Issue: Validation does not account for leading and trailing spaces. For example: 

is[dog]. '          dog', ' dog           ' are both valid but should not be.
isExactly[dog] '            dog', 'dog         ' are both valid but should not be.

Repro: Using the [docs demo](https://fomantic-ui.com/behaviors/form.html#specified-content) you can test this out.

The documentation infers otherwise. 'isExactly Dog' would imply, in standard English, that there would be no other characters than D-o-g.  However, in other use cases I could see the need to allow leading or trailing spaces.

Proposed solution:  Firstly I propose that validation should not change the input value unless the following classes are in place. I recommend a class be added to inputs, for example something like 'trimming-both', 'trimming-left', trimming-right' & 'trimming-none'. Fomantic validation would be modified so that the use of one of these classes would operate as inferred by the semantic name of the class. The trimming operation inferred by the class would happen __before__ the validation process was carried out.   This would retain the semantic intention of Fomantic without needing to have the developer revert to script to handle this chore.

**Comment by lubber-de** [comment]
Try the setting: `shouldTrim:false`
![image](https://user-images.githubusercontent.com/18379884/72887091-50567780-3d0b-11ea-882a-5ec6eded9231.png)

**Comment by VanquishedWombat** [comment]
shouldTrim is a good solution but its focus is entirely within the validation process. 

From the perspective of validation this is good. However, there is a disconnect from the perspective of the developer. If the use case requires trimming of spaces from left and/or right,  it is probable that some developers will make the assumption that because validation was passed with shouldTrim = True then they can safely store the data value, unaware that there are spaces in the data etc. 

shouldTrim is also applied as a form-setting, so affecting all inputs in the form.

I do not believe in being a [nanny-state](https://en.wikipedia.org/wiki/Nanny_state), however in this case I believe that adding a directive class as per my initial suggestion would be a positive addition.

**Comment by lubber-de** [comment]
As this is pure JS logic, i would make a similiar trim setting  setting an individual option to each field rule, rather than applying css-classes to the field.

**Comment by VanquishedWombat** [comment]
Happy to go with whatever you think best.

**Comment by lubber-de** [comment]
I added support for individual `shouldTrim` per field fule by #1814 
However, the backend should always validate the submitted values on its own (in this case trim the submitted values) anyway and never trust the frondend validation, so this setting should stay at validation level.

For more special uses cases like "trim-right" "trim-left" i suggest to use a custom validator and set the global `shouldTrim` to false then
