### ISSUE TITLE
Hello! Bug in google chrome Version 79.0.3945.130 (Official Build) (64-bit) for semantic/formantic shapes.

### ISSUE THREAD

**Issue by adminoid** [fomantic/Fomantic-UI#1283]
Bug only in Google Chrome _(latest release for now)_. On mac os Mojave 10.14.6 (18G95)

Look: [https://youtu.be/yZ50_EibkTc](https://youtu.be/yZ50_EibkTc)

I'm reproduce it on [https://fomantic-ui.com/modules/shape.html](https://fomantic-ui.com/modules/shape.html) page. Also bug is on semantic-ui site.

The next side of the cube is not periodically drawn. More often than drawn.

How I may fix it? Thank you!

**Comment by lubber-de** [comment]
Fixed by #1284

**Comment by adminoid** [comment]
Thank you!
