### ISSUE TITLE
Slider not appearing

### ISSUE THREAD

**Issue by hickorysb** [fomantic/Fomantic-UI#1288]
```html
<script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
<script src="semantic/dist/semantic.min.js"></script>
<link rel="stylesheet" type="text/css" href="semantic/dist/semantic.min.css">
```
```html
<body>
    <div class="ui slider"></div>
</body>
```
```js
$('.ui.slider').slider();
```

The slider isn't appearing. I don't know why. Any help is appreciated.
Fomantic-UI v2.8.3

**Comment by lubber-de** [comment]
Your code is fine. It seems you have put semantic.min.css and semantic.min.js to a different location, so the browser cannot find them by the relative path in your code
See here https://jsfiddle.net/bhs0wz3f/

Try to use jsdelivr cdn
```
<script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.3/dist/semantic.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.3/dist/semantic.min.css">
```

**Comment by hickorysb** [comment]
The CDN did not help. I am using Electron if that helps. I have a table and button working fine with Fomantic-UI right now.

**Comment by exoego** [comment]
Could you ensure that js/index is loaded?
You can confirm it network tab of browsers' devyools.

Also, sharing debug console log of
`$('.ui.slider').slider({ debug: true });`
might help.

**Comment by hickorysb** [comment]
No output is logged, index.js is definitely loaded.
![image](https://user-images.githubusercontent.com/44131234/73143672-6e90e000-4049-11ea-9d3a-0774f8dae679.png)

**Comment by hickorysb** [comment]
I fixed it. It was being run before the page was initialized. I wasn't calling it in an onload function.

**Comment by exoego** [comment]
Ah, that is a common mistake.

Closing as resolved.
