### ISSUE TITLE
[Divider] Display problem in chromium 69.0.3497.92 (and maybe other browsers with same engine)

### ISSUE THREAD

**Issue by j5k** [fomantic/Fomantic-UI#129]
### Steps
See fiddle in difference browser. On my system, firefox displays correctly, but chromium incorrectly.

### Expected Result
Horizontal divider since before/expected.

### Actual Result
Display problem in chromium 69.0.3497.92 (and maybe other browsers with same engine).

### Version
2.6.0

### Testcase
https://jsfiddle.net/z04yw8r5/

**Comment by ColinFrick** [comment]
Your html seems to be alittle off. I'm not sure what you are trying to achieve, but there is no `three row grid`.
Maybe you mean `three column grid`?

If you change the html to something like here https://jsfiddle.net/a3wy0vrj/ it works.

**Comment by j5k** [comment]
Thank you very much for the fast response. It was your figured out mistake! (Code from my beginnings with Semantic UI ;-b )

Apologize for your wasted time...
