### ISSUE TITLE
[Calendar] inline form fields

### ISSUE THREAD

**Issue by fsteccanella** [fomantic/Fomantic-UI#1296]
# Bug Report
Calendar bad rendering on inline form fields

## Testcase
https://jsfiddle.net/1h2yntv3/

## Screenshot
![image](https://user-images.githubusercontent.com/5019896/73527305-212ebd00-4413-11ea-9fa2-e0d2b841cfd0.png)

## Version
2.8.3

**Comment by lubber-de** [comment]
Should be fixed by #1298  now
