### ISSUE TITLE
[Modal] Fullscreen modal stuck to left edge of page

### ISSUE THREAD

**Issue by ColinFrick** [fomantic/Fomantic-UI#130]
Original issue: Semantic-Org/Semantic-UI#6587
> ### Steps
> 
>     1. Create a fullscreen modal in html
> 
>     2. Call the modal function on it and show
> 
> 
> ### Expected Result
> 
> Modal should be centered
> ### Actual Result
> 
> Modal is stuck to left edge of page
> ### Version
> 
> 2.4.0
> ### Testcase
> 
> https://jsfiddle.net/Ljcyd5ek/
> 
> It can be fixed by adding the following css into the page to override it:
> 
> ```css
> .ui.fullscreen.modal {
>   left: 2.5% !important;
> }
> ```

**Comment by lubber-de** [comment]
Even, if i personally do not care about IE11: This does not seem to fix IE11 .
See (in IE11): https://jsbin.com/semilikaqu/1/edit?html,css,js,output

It indeed fixes it for every other modern browser ;)

**Comment by ColinFrick** [comment]
See #134

**Comment by lubber-de** [comment]
Sorry, missed that. i can confirm, the other fixes solves it in IE11 also now :sunglasses:
