### ISSUE TITLE
[Calendar] Bug in Yearcalendar

### ISSUE THREAD

**Issue by Amerlander** [fomantic/Fomantic-UI#1311]
When a 2 digit year is inputed some years are translated wrong:

`01` > `2001`
…
`12` > `2001`

`13` > `2020`
...
`31` > `2020`

Inputs after `31` are working correctly, also the century break on `50`.

Can be reproduced in the year calendar in the documentation:
https://fomantic-ui.com/modules/calendar.html#year-calendar

**Comment by lubber-de** [comment]
This seems to be fixed by #1569 in v2.8.7
I cannot reproduce with the current code / doc example anymore
