### ISSUE TITLE
[Icon] Missing icons

### ISSUE THREAD

**Issue by delfuego** [fomantic/Fomantic-UI#1312]
I noticed tonight that there are at least two icons that show up on the documentation page (https://fomantic-ui.com/elements/icon.html#/icon) but don't seem to exist in the icon font file:

```
<i class="hammer icon"></i>
<i class="user shield icon"></i>
```

All the other icons I've tried (e.g., gavel, shield alternate, check, etc.) show up — so this isn't me not having the icon fonts in the right place.

Thoughts? Is there any other debugging I could do?

**Comment by lubber-de** [comment]
The icons exists just fine.
See https://jsfiddle.net/x6sv93o7/
Which fomantic version are you using? Those icons may not exist in older versions than 2.8.3

**Comment by delfuego** [comment]
I'm using the version straight off of Github, the most recent commit:
https://github.com/fomantic/Fomantic-UI/tree/037a0402362fa2ffa44e434fe7e362c8cb753bb8

But now, I'm baffled — because after quitting and restarting Chrome, those icons load for me on my local install. So... I have no clue what happened.

Thanks for indulging this idiocy!
