### ISSUE TITLE
Invalid tasks/config/npm/gulpfile.js

### ISSUE THREAD

**Issue by jeffrson** [fomantic/Fomantic-UI#1320]
The file looks very much like the main gulpfile.js. It references (eg) ./tasks/config/user (and others) which do not exist (files are normally expected relative to gulpfile.js).

Eventually this problem is leading to an error message "Gulp Tasks: Command failed" when I edit my project by VSCode.

So, what's this file for actually?

You probably should either delete it, or insert some dummy code and document the usage.

### Version
2.8.3

### Testcase
gulp --tasks-simple --cwd "c:\test" --gulpfile "c:\test\semantic\tasks\config\npm\gulpfile.js"

**Comment by ColinFrick** [comment]
The `./tasks/config/npm/gulpfile.js` is actually used when installing fomantic-ui.
https://github.com/fomantic/Fomantic-UI/blob/6ff5a07529e4667203b4602d44e7424cf400b623/tasks/install.js#L320-L324

**Comment by jeffrson** [comment]
@ColinFrick 

"Used" - yes, it's copied. However, what is it good for? Where is it really "used"?

And what's about the content of the file? It refers to non existing files.

**Comment by ColinFrick** [comment]
@jeffrson It is copied to the installation directory, then the relative references are correct.

**Comment by jeffrson** [comment]
Well, nevertheless - since semantic/ is copied into to the project directory, VSCode's gulp task scanner nags about missing files everytime a project is opened. :-(
Why not move the file?
