### ISSUE TITLE
[Menu] Colored active item in colored inverted menu

### ISSUE THREAD

**Issue by jlannoy** [fomantic/Fomantic-UI#1321]
In the actual version of fomantic, the "active" class of an item in an inverted menu sets a darker transparent background. On an inverted menu, it is also possible to set a color for an active item. But it's not possible to set a colored active item with a colored inverted menu. 

Check this fiddle : https://jsfiddle.net/4ors5zqy/1/

Here's the CSS styles applied to the colored active item... I don't know how we could give priority to the second one, but I think it could be interesting.

```
.ui.ui.inverted.blue.menu .active.item {
  background-color: rgba(0,0,0,.1);
}
semantic.min.css:37337.ui.ui.inverted.menu .orange.active.item, .ui.ui.inverted.orange.menu {
  background-color: #f2711c;
}
```

**Comment by lubber-de** [comment]
Fixed by #1322
