### ISSUE TITLE
Calendar day is one day early with "monthFirst" true when current value is provided

### ISSUE THREAD

**Issue by beamsky** [fomantic/Fomantic-UI#1324]
### Bug Report

The calendar "date" is one day early when being initiated on a input with a current value.

EX: 2020-02-12 will show as "February 11, 2020" when "monthFirst" is set to "true" (which is the default).

If "monthFirst" is false, it will display as "12 February, 2020" and reads the day correctly.

### Steps to reproduce

Fresh install of 2.8.3
Make an input with an existing value
Initialize the calendar on it as "date"

`  $('#date_calendar').calendar({
    monthFirst: true,
    type: 'date'
  });`

### Expected result

I would expect this to show the correct date. 2020-2-12 should show "February 12, 2020"

### Screenshot (when possible)

You can see this on the Fomantic UI documentation example
https://fomantic-ui.com/modules/calendar.html#/examples under "You can also set the type or date using HTML markup" but this also happens when the input has the value set and not just through data-date.

https://jsfiddle.net/xzsyv1ec/2/

### Version

2.8.3

**Comment by lubber-de** [comment]
I am unfortunately not able to reproduce this using your fiddle at the moment. Both shows the correct date to me
![image](https://user-images.githubusercontent.com/18379884/74415120-090f6280-4e43-11ea-90ad-47c0f70334f2.png)

**Comment by beamsky** [comment]
Interesting. So after a little more digging I was able to get the correct day to show when I use 2020/02/12 instead of 2020-02-12.

![Screenshot_2020-02-13 Fomantic-UI Sandbox - JSFiddle](https://user-images.githubusercontent.com/48980413/74420583-8960a400-4e00-11ea-8997-46fc31478e41.png)

I have tested in both firefox and chrome. I am at a loss on why you can't reproduce it but perhaps it could be something specific to my system. At least in my case I have a work around and there is a good answer on it here and where I got the info to try this change:

https://stackoverflow.com/a/41125840

Updated jsfiddle
https://jsfiddle.net/x9g1Lryk/1/

**Comment by redalpha01** [comment]
This also happens to me and the fix of Monthfirst surprised me because it's not even a documented setting.
I also have Y-M-D with dash separation since it's a form for dates sent to mySQL, so I used a similar formatter to the one mentioned in #568 . A console.log() in the formatter show that the initial date is decremented before being sent to the formatter (with Monthfirst being true - which I believe might be the default).

**Comment by lubber-de** [comment]
> This also happens to me and the fix of Monthfirst surprised me because it's not even a documented setting.

🤔 It actually is documented:
https://fomantic-ui.com/modules/calendar.html#/settings
![image](https://user-images.githubusercontent.com/18379884/80393895-68610880-88b1-11ea-815f-5f06b0472eca.png)

**Comment by redalpha01** [comment]
I... must've typoed in my ctrl+f

**Comment by lubber-de** [comment]
@beamsky We fixed a general timezone issue with #1492 
Could you please try your own jsfiddle again https://jsfiddle.net/x9g1Lryk/1/ which now makes use of the mentioned timezone fix.

I believe you are living in an area where the timezone is many hours different to me (+1) which might explain why i was (and still am) not able to reproduce the difference you encountered

**Comment by beamsky** [comment]
@lubber-de I just tested this and it looks good! Thank you.
![Screenshot_2020-07-24 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/48980413/88439181-55ca7280-cdbf-11ea-9785-75a85658be48.png)
