### ISSUE TITLE
Radio checkboxes return `false` instead of value when value = 0

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#1327]
This perfectly illustrates the problem:
https://jsfiddle.net/designosis/hrj97xao/

Given these two radio buttons ...
```
<input type="radio" name="radio_input" value="0">
<input type="radio" name="radio_input" value="1">
```
...  `form()` will convert `value="0"` to `false`, but any other value is returned correctly.

Maybe someone used an `==` somewhere when they should have used `===`?

**Comment by lubber-de** [comment]
Fixed by #1328
