### ISSUE TITLE
[Input] type="month" does not get styled

### ISSUE THREAD

**Issue by heathwinning** [fomantic/Fomantic-UI#1337]
An input with type="date" in a form field gets the nice padding and rounded border, but with type="month" it gets none of that, see [demo](https://jsfiddle.net/k6xaeLy7/). The month input ought to get the same style.

**Comment by lubber-de** [comment]
Fixed by #2052 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/m71v2y54/
