### ISSUE TITLE
[Calendar] Chrome chose the wrong hour in 24-hour format on some cases

### ISSUE THREAD

**Issue by kawaji** [fomantic/Fomantic-UI#1354]
Chrome: 80.0.3987.132

https://fomantic-ui.com/modules/calendar.html#24-hour-format

If you enter a time for this sample, the time selected in the popup is incorrect.

1 -> 0:00
1: -> 1:00
13 -> 13:00

Entering 2 digits works correctly.

This problem does not occur with FireFox.

![fomantic](https://user-images.githubusercontent.com/1585812/76064110-5c04b180-5fcc-11ea-9bd7-c74310cf8f01.gif)

**Comment by exoego** [comment]
This is reproducible


![chrome-hours](https://user-images.githubusercontent.com/127635/76065473-1bf2fe00-5fcf-11ea-87a4-5d5c943509e7.gif)

**Comment by exoego** [comment]
I will look into this issue and open a PR.

**Comment by lubber-de** [comment]
Fixed by #1569
