### ISSUE TITLE
CSS Build randomly omits 34kB of output

### ISSUE THREAD

**Issue by silverwind** [fomantic/Fomantic-UI#1356]
Running the `gulp build` task seems to randomly omit around 34kB of CSS output in `semantic.min.css` related to the `Transition` module which in turn leads to `Transition: Element is no longer attached to DOM` JS errors when using that build.

To reproduce, clone the master branch, `npm install`, answer all choices with default and run:

````
while true; do rm -rf dist && npm run build &>/dev/null && stat --printf="%s" dist/semantic.min.css | xargs; done
````

It will randomly produce less CSS output, around 30% of times in my sample runs:
````
1354924
1354924
1321417
1354924
1354924
1321417
1321417
1354924
1354924
1354924
1354924
1354924
1354924
1354924
1321417
1321417
1321417
1321417
1354924
````

I see this on Node.js 12.16.1 and 13.10.1 on Linux. Adding `--series` to the `gulp` arguments does not seem to have any affect.

**Comment by lubber-de** [comment]
@ColinFrick Do you have an idea or have time to look into this?

**Comment by das7pad** [comment]
I found the race condition. PR is https://github.com/fomantic/Fomantic-UI/pull/1358
