### ISSUE TITLE
[icon] normal size of icon has not the same vertical-align and line-height of each other size

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1371]
# Bug Report
Normal size of icon has not the same vertical-align and line-height of each other size

## Screenshot
![icon](https://user-images.githubusercontent.com/1622751/76950203-01435200-690a-11ea-84c9-accf04698c43.gif)

## Version
2.8.4

**Comment by lubber-de** [comment]
Fixed by #1372

**Comment by lubber-de** [comment]
We have to (partly) revert this. See #1503 for details
