### ISSUE TITLE
HTML entity encoding behavior in multiselect dropdown

### ISSUE THREAD

**Issue by phuongvumai** [fomantic/Fomantic-UI#1373]
I’m experiencing an issue in Fomantic UI multiselect dropdowns version 2.8.4.

When I choose an item from the multiselect dropdown that contains characters such as & (ampersand) or ‘ (single quote), the hidden input value is encoded into a HTML character entity. However, if I select two items which both contain the special characters, in the hidden input value, the first item is encoded as HTML character entity (eg: &amp;) and the second is unencoded. If I continue to select the third item without the special characters, both items are encoded into HTML entities.

Here is my codepen: https://codepen.io/moistyburger/pen/zYGjQBK

However, if I use semantic-ui version 2.4.1, it does not have such behavior.

**Comment by lubber-de** [comment]
Fixed by #1770

**Comment by Atomicbeast101** [comment]
Is anyone having this issue with v2.9.3? I noticed that it still pastes the encoded version in the input field as seen below:
![image](https://github.com/fomantic/Fomantic-UI/assets/4297664/9b1ad71c-cfd1-4aeb-b438-0f0ce157aeaf)

I tried pulling the value using the following Javascript code:
`$("input[name=services_Search_Vendor").parent().dropdown('get value')`

It still returns `at&amp;t`. Trying to decode it using `decodeURI()` doesn't solve it...
