### ISSUE TITLE
right action left icon input facility

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#1377]
https://jsfiddle.net/allwe/5a3f06ps/1/

rounded not show input action left icon
<img width="352" alt="Jepretan Layar 2020-03-22 pukul 2 19 17 PM" src="https://user-images.githubusercontent.com/33564576/77245911-65914900-6c5d-11ea-9ec6-3a939d1b7a75.png">

**Comment by lubber-de** [comment]
Fixed by #1378

**Comment by apple-idn** [comment]
thanks fixit 🙏🏻
