### ISSUE TITLE
No link to 2.6.0 zip

### ISSUE THREAD

**Issue by princeandrew01** [fomantic/Fomantic-UI#138]
Good Day,

I normally check the releases page on github to check if a new version is out but I realized the 2.6.0 version was not published as a zip. 

I also noticed the fomantic site does not have a link to the zip file like semantic usually does.

Regards,
Andrew

**Comment by hammy2899** [comment]
I just published the release, I must have forgotten to publish.

**Comment by princeandrew01** [comment]
Okay no problem didn't realize you just published.

Its normally in the [Getting Started Section](https://semantic-ui.com/introduction/getting-started.html) right on top under Simpler Setup. See screenshot below:

![image](https://user-images.githubusercontent.com/13138963/45969185-f3f12400-c000-11e8-995d-ff0a3a4bd554.png)

**Comment by hammy2899** [comment]
I removed that section because it isn't the recommended way to install but if you do need the zip you could still get it from GitHub. Hope this clears up any confusion.

**Comment by princeandrew01** [comment]
Yep not a problem thats why I use github generally. Thanks :)
