### ISSUE TITLE
Range slider get triggered even user doesn't move it

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1382]
I'm using Fomantic 2.8.3 and I noticed that the `onChange` callback is triggered even if the slider is not moved.
Both `onChange` and `onMove` are triggered just clicking on the slider, without any values change.

Here is a Plunker: http://jsfiddle.net/5nmhgvdp
As you can see if you just click on the slider, without change value, it get always triggered.

I would like to have it triggered only when users move the slider and only when values are different from previous move.

**Comment by MrL1605** [comment]
I would like to pick this up as part of Hacktoberfest. 

As this is first time exploring Fomantic Source code, if you have any suggestions on how to proceed let me know.

**Comment by ko2in** [comment]
@MrL1605 You can fork this repo and pick whatever issue you would like to contribute and submit PR. Thanks.
