### ISSUE TITLE
Forms - fields CSS too cramped on mobile for 'n wide field' class cases

### ISSUE THREAD

**Issue by VanquishedWombat** [fomantic/Fomantic-UI#1388]
# Bug Report
![image](https://user-images.githubusercontent.com/55594003/78107074-b555da00-73ec-11ea-9fdd-c8941246f973.png)

Taking as a sample the Fomantic UI documentation example of the second and more complex form at https://fomantic-ui.com/collections/form.html#form - the one with billing info. This form is very well laid out with appropriate white-space around the elements giving indication of relationship between components and achieving aesthetic and functional success.  When resizing the browser to trigger the mobile media query range to fire, the  inputs for Card Number, CVC and Expiration become cramped.  Objectively, when the field class used is of the _n wide field_ variety, bottom-margin is required to keep pleasing separation.

## Steps to reproduce
See codepen https://codepen.io/JEE42/pen/vYOPjOx.  To DIY, take the complex payment form sample from the documentation at  https://fomantic-ui.com/collections/form.html#form and switch to a mobile-sized view. Easier done with a fiddle or codepen as per link in test case section below. In mobile view note how Card number, CVC and Expiration are cramped.

## Expected result
There should be more vertical while space between same-row fields. 

## Actual result
Already described above.

## Suggested fix
Suggested fix is to include

`margin-top: 1em; `

in mobile media query rule for multiple-fields. See the before & after screenshots below and before & after codepen links in test case for example with this in place for comparison.

## Testcase
See codepen https://codepen.io/JEE42/pen/vYOPjOx for issue.

Suggested fix is to include "margin-top: 1em;" in media query rule for _n wide fields_ classes. See the example with this in place for comparison.
 
See https://codepen.io/JEE42/pen/WNvmJjY for version with suggested fix applied in codepen css panel.

## Screenshot (if possible)
Before:
![image](https://user-images.githubusercontent.com/55594003/78106729-e5e94400-73eb-11ea-888b-377bbf4ba177.png)
![image](https://user-images.githubusercontent.com/55594003/78107066-b1c25300-73ec-11ea-8a0f-f9b6f9393cd0.png)

After:
![image](https://user-images.githubusercontent.com/55594003/78106890-4c6e6200-73ec-11ea-9acf-e8dd4d6943a5.png)
![image](https://user-images.githubusercontent.com/55594003/78107092-c1da3280-73ec-11ea-89be-1cd2ffb628e9.png)

## Version
2.8.4

**Comment by lubber-de** [comment]
Thanks, i adopted your fix with a similiar selector in #1550
