### ISSUE TITLE
[Install] Postinstall script fails

### ISSUE THREAD

**Issue by baterflyrity** [fomantic/Fomantic-UI#1389]
# Bug Report

Hi! I'd like to submit some surprising bug. When Fomantic UI is installed via symlink it detects self as dependency and fails `gulp install`. 

**How can I force post install script running per project?**

## Steps to reproduce

_I'm using [pnpm](https://pnpm.js.org/) like `pnpm add fomantic-ui`._
But ones can simple use `npx pnpm install` in project's root directory.

## Expected result

It should run post install script to copy package files to project and configure paths.

## Actual result

> Packages: +637
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resolving: total 642, reused 642, downloaded 0, done
node_modules/.pnpm/registry.npmjs.org/fomantic-ui/2.8.4/node_modules/fomantic-ui: Running install script, failed in 6s
.../2.8.4/node_modules/fomantic-ui install$ gulp install
│ [13:39:40] Using gulpfile ...\node_modules\.pnpm\registry.npmjs.org\fomantic-ui\2.8.4\node_modules\fomantic-ui\gulp
│ [13:39:40] Starting 'install'...
│ SUI is a sub-module, skipping end-user install
│ [13:39:40] The following tasks did not complete: install
│ [13:39:40] Did you forget to signal async completion?
└─ Failed in 6s
 ERROR  Command failed with exit code 1.

## Version

2.8.4

**Comment by lubber-de** [comment]
Fixed by #2280
