### ISSUE TITLE
[dropdown with search] showOnFocus=false & minCharacters: 1

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1396]
# Bug Report

I use dropdown (with search) with `showOnFocus=false` & `minCharacters: 1`, after click on :arrow_down_small: to show list (work properly) if I click (focus) on the dropdown, the list is show.

## Steps to reproduce
https://jsfiddle.net/dutrieux/wqfnb7rj/

![focusout](https://user-images.githubusercontent.com/1622751/78502766-fdfdf200-7762-11ea-8029-6467e42c9e55.gif)

The problem come from `iconClicked `variable who are not properly set to `false `in this case

## Version
2.8.4

**Comment by lubber-de** [comment]
Fixed by #1398 See your adjusted jsfiddle here https://jsfiddle.net/L21jhap3/
