### ISSUE TITLE
[Dropdown] apiSettings.cache=false, the whole list is not refresh by clicking on the down arrow icon

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1399]
# Bug Report
when `apiSettings.cache` is set false, the whole list is not refresh by clicking on the down arrow icon.

## Testcase
https://jsfiddle.net/dutrieux/gecLh9d4/

## Screenshot (if possible)
![not_refresh](https://user-images.githubusercontent.com/1622751/78535191-0d754d80-77ec-11ea-8daf-5381bc410ec9.gif)
## Version
2.8.4

**Comment by dutrieux** [comment]
@lubber-de I proposed a patch for this issue, if you can check, It's definitely not the right solution, but if it'll make any progress in solving the problem...

**Comment by lubber-de** [comment]
fixed by #1414
