### ISSUE TITLE
[Modal] default close button action not applied

### ISSUE THREAD

**Issue by n00b42** [fomantic/Fomantic-UI#1404]
# Bug Report
According to the documentation ([Link](https://fomantic-ui.com/modules/modal.html#actions)):
> [...] Close actions are applied by default to all button actions [...]

All buttons in a modal should by default close the modal (as long as they do not "return false".
But a button that is neither approve nor deny will not close the modal.

## Steps to reproduce
1. Build modal with a button without approve/deny classes
2. Open modal
3. Click button

## Expected result
Modal is closed.

## Actual result
Modal is not closed.

## Testcase
https://jsfiddle.net/at0orzm8/

## Screenshot
![](https://i.imgur.com/tjFfgnI.gif)

## Version
2.8.4

**Comment by lubber-de** [comment]
I think this is a misunderstanding from the docs. Ever since in SUI, there always only exists selectors for approve and deny actions. All those buttons will close the modal by default, that's what the part of the docs you are referring to means.

However, there already also exists a selector for the close icon:
```
selector    : {
    close    : '> .close',
```

You could change this to also cover your desired action buttons
```
selector    : {
    close    : '> .close, .actions .button',
```

**Comment by ko2in** [comment]
@lubber-de Do we need anything to update in documentation? Please let me know if there's anything and I'll submit a PR.

**Comment by lubber-de** [comment]
@ko2in Well, i just found out, the docs already say `> .close, .actions .button`.... so we rather need a PR to implement this as default (as the docs say so) instead of adjusting the docs 👀

**Comment by lubber-de** [comment]
oh, well the docs indee also need a slight change from

`.close, .actions .button`
to
`> .close, .actions .button`

**Comment by lubber-de** [comment]
The modal settings docs have been adjusted by https://github.com/fomantic/Fomantic-UI-Docs/pull/287 to match the code which only had the close selector (without additional action buttons)
We will additionally adjust the docs regarding the initially mentioned statement (which stated that _all_ actions buttons will trigger the close) to be more clear.

**Comment by lubber-de** [comment]
>  We will additionally adjust the docs regarding the initially mentioned statement

Done by https://github.com/fomantic/Fomantic-UI-Docs/pull/406
