### ISSUE TITLE
[Modal] Modal fluid action button incorrect margin

### ISSUE THREAD

**Issue by n00b42** [fomantic/Fomantic-UI#1405]
# Bug Report
In a modal a fluid (full width) action button is shown with incorrect margins.

## Steps to reproduce
1. Build Modal with `fluid` button
2. Open Modal

## Expected result
Margins should be equal on all sides

## Actual result
Left margin to big

## Testcase
https://jsfiddle.net/6xp2rdvh/

## Screenshot
![](https://i.imgur.com/rb6Rnjc.png)

## Version
2.8.4

**Comment by lubber-de** [comment]
Fixed by #1406  See your adjusted jsfiddle here https://jsfiddle.net/kt85yapn/
