### ISSUE TITLE
[Modal] Scrolling fullscreen modals are not centered correctly in IE11

### ISSUE THREAD

**Issue by ColinFrick** [fomantic/Fomantic-UI#141]
# Bug Report

This bug affects all .scrolling legacy modals, for which the width is defined in percent:
* fullscreen modals
* mobile (screen width < 768px)
* tablet (screen width < 992px)

While retrieving the modals width the scrollbar is not rendered, therefore it returns a larger width than it should - in this cases the modal is half the scrollbars width further to the left.

## Steps to reproduce
1. Open modal in IE11
2. Resize browser

## Expected result
Modal rendered in the center

## Actual result
Modal rendered off center

## Testcase
https://s.codepen.io/ColinFrick/debug/RePVvo/ZoABaKpKOWxr

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/5517677/46276479-82652880-c560-11e8-8be5-d26426008cd7.png)

## Version
2.6.0

**Comment by lubber-de** [comment]
Time has passed.
IE has died.
This won't get fixed anymore, sorry.
