### ISSUE TITLE
[Step] Support vertical step invert direction

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#1418]
# Feature Request
The current vertical step (https://fomantic-ui.com/elements/step.html#vertical) always need to be placed at the left column in the grid container, because the arrow of the active step always points to the right direction.

The vertical step might also be placed in the right column, and the arrow of active step should point to the left direction.

## Example
This fiddle (https://jsfiddle.net/oz1js6yn/2/) shows how the vertical step should be in the right column in grid container.

**Comment by lubber-de** [comment]
Implemented by #1426 
Thanks for the solution. I adopted your code and made a new `.ui.right.vertical.steps` variant out of it
