### ISSUE TITLE
Blank space on right page side

### ISSUE THREAD

**Issue by zdarin** [fomantic/Fomantic-UI#1432]
Hi i have a question i something do wrong or its maybe a bug? i have a blank space on right corner when slightly scroll to right. I figured out that when grid not inside any container or segment it has blank right corner. Then i put all outside grids to segments and its all seems to be ok but when i write top menu then it has a smaller blank space on right. Please see attached img what i mean.

![Screenshot 2020-04-22 at 10 29 15](https://user-images.githubusercontent.com/42121280/79963336-ed06ed80-8491-11ea-8f91-f29dbb1ce78a.png)

**Comment by lubber-de** [comment]
Please provide a jsfiddle to reproduce and easier investigation. Thanks

**Comment by zdarin** [comment]
https://jsfiddle.net/romz8p2L/

you can see that little space in right on segment even when fluid
when change segment with grid space bigger

**Comment by lubber-de** [comment]
Sorry, i cannot reproduce (even your screenshot) by the given jsfiddle 😢 
This is produced by your jsfiddle
![image](https://user-images.githubusercontent.com/18379884/79979761-4d9e2680-84a2-11ea-848e-c3fb51801cfc.png)

**Comment by zdarin** [comment]
try now on bottom make scroll bar

**Comment by ColinFrick** [comment]
@zdarin Which browser are you using? OS?

**Comment by zdarin** [comment]
Safari 13.1

**Comment by ColinFrick** [comment]
@zdarin Thanks. Seems only Safari has this problem. Firefox / Chrome works just fine.

**Comment by zdarin** [comment]
Ou not tested forget about it

**Comment by zdarin** [comment]
Maybe some fix have ? Maybe can me explain how to write?

**Comment by lubber-de** [comment]
Not happening on Safari 14.1+ anymore
