### ISSUE TITLE
Calendar is not in front in the next row of a grid

### ISSUE THREAD

**Issue by tom-lp-at** [fomantic/Fomantic-UI#1447]
# Help Wanted
I have a grid with 3 column in a row.
in the last column, there is a Field with a Calendar.
If i click on the calendar it pop´s up.
But the controls/fields from the next row are overlapping the calendar (or the calendar is in the background). 
For the same row - where the calendar is placed - all controls are overlapped from the Popup of the Calender. But not the controls from the next row....
i played around with z-index, but it seams i found not the right place to control the z-Index of the Calender. (it have 1900 per default and i try with higher and lower values. also on the overlapping controls).

## Testcase
i make a Fiddle to show the behavior of the calendar : https://jsfiddle.net/fxpk596j/

**Comment by tomlp** [comment]
i found out, that this behaviour comes by setting "popupOptions" to "bottom left"...
If i set it to "top left" it seams all right...
May be a Bug ?
kR Tom

**Comment by lubber-de** [comment]
Yes, it's a bug. The z-index is basically the correct fix, we just have to test this with other z-index values of other components like modal/popup, etc. i'd rather think we should better adjust the z.-index for the popup (which the calendar uses) when its inside a sidebar

**Comment by lubber-de** [comment]
Closing as the calendars `context` setting can fix this situation since #2542 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/8tjL3ksv/1/
