### ISSUE TITLE
[Build Process] gulp install not running

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#145]
# Bug Report

Started after the new release with the new gulp 4 PR.

## Steps to reproduce
1. npm install fomantic-ui
2. select all components when prompt

## Expected result
Should install correctly

## Actual result
Install process crashes with following error
>Did you forget to signal async completion?

## Version
2.6.1

**Comment by hammy2899** [comment]
@acconrad You may want to look into this for your PR.

**Comment by hammy2899** [comment]
Reverted the changes for now.

**Comment by acconrad** [comment]
Sorry I'm confused, what needs to be addressed here? This looks like an offshoot of Semantic-UI. If you run `gulp` on this project does that error pop up here but not on Semantic? I'm guessing there are slight nuances and differences that weren't accounted for here that work there.

**Comment by ColinFrick** [comment]
@acconrad try to install your branch in an empty npm project:
$ npm init
$ npm i --save-dev gulp@4
$ npm i acconrad/Semantic-UI#acc-upgrade-gulp4

**Comment by acconrad** [comment]
Fixed @hammy2899 @ColinFrick . It wasn't _actually_ broken, it was a false flag. The older version of Semantic UI used a `process.exit` which is fine in Gulp 3, but in Gulp 4 the proper way is to pass in a `done()` callback into a `gulp.task` and close that way. That was the last stone I forgot to turn, but it is now completed! My branch is now updated and if you run through it again you should get exactly what you need without errors this time :)

**Comment by ColinFrick** [comment]
Thanks for the update @acconrad I will test it further later today.
