### ISSUE TITLE
[Dropdown search multi] The whole list not properly display

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1457]
# Bug Report

When `.search .multi .dropdown` has option `showOnFocus: false`, the whole list is not properly display (when click on dropdown) in somes situtations.

## Testcase
https://jsfiddle.net/dutrieux/4tysf05h/

## Screenshot
![bug](https://user-images.githubusercontent.com/1622751/81504041-7bc79700-92e7-11ea-94cc-cfc778a31c1a.gif)

I check it to solve this problem, but to hard for me : there is a problem with `<input class="search" autocomplete="off" tabindex="0">` layout (`position:static`) (not the same as single dropdown).

At the beginner : when there is not selected item in the dropdown, the  `<input class="search" autocomplete="off" tabindex="0">` (`position:static`) can't not take the event `click` because `<div class="default text"></div>` is above (`position:relative`).

And for the other case : when there is multi-line in the dropdown, the `<input class="search" autocomplete="off" tabindex="0">` don't take all width :

![image](https://user-images.githubusercontent.com/1622751/81504546-45d7e200-92ea-11ea-817e-d092ab38e120.png)

## Version
2.8.4

**Comment by lubber-de** [comment]
Seems, it only relies on the `showOnFocus: false` setting. The other settings `forceSelection` and `minCharacter` are irrelevant

**Comment by dutrieux** [comment]
> Seems, it only relies on the `showOnFocus: false` setting. The other settings `forceSelection` and `minCharacter` are irrelevant

@lubber-de, `minCharacter=0` is necessary too, otherwise there is no reason to display the whole list when you click on the dropdown.

**Comment by lubber-de** [comment]
fixed by #1414
