### ISSUE TITLE
[Dropdown] preselected + .search + api

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1459]
# Bug Report
If dropdown onload have a preselected value, when the whole list is display (via api), the item of preselected value is filtered.

## Testcase
https://jsfiddle.net/dutrieux/obcfgn4s/

## Screenshot (if possible)
![bug](https://user-images.githubusercontent.com/1622751/81507700-65c5d080-92ff-11ea-8f3d-9d9c826961f2.gif)

## Version
2.8.4

**Comment by lubber-de** [comment]
When you click on the dropdown arrow instead of the search input, the default item is not filtered as expected. Needs more investigation

**Comment by lubber-de** [comment]
fixed by #1414
