### ISSUE TITLE
[calendar] onChange event fires after selecting hour for datetime types

### ISSUE THREAD

**Issue by hughbris** [fomantic/Fomantic-UI#1460]
# Bug Report
When I select a date from a datetime type FUI calendar widget, onChange does not fire and the 1 hour blocks selectors are shown. After selecting an hour, onChange does fire and the (default 5 mins) increments within the hour are shown. When I select one of those, onChange fires again.

This is a problem for me because I don't want to make redundant AJAX calls. I am making them after datetime value changes.

## Steps to reproduce

Simple fork of JSFiddle I saw on a similar issue: https://jsfiddle.net/dL8s6h1f/

## Expected result

Depending on how onChange is defined/intended, it should either fire after each selection phase (day, hour, minute), or _only_ after the last. My preference is the latter. I would like an event for that ("onAfterChange"?) if that's not the intended behaviour of onChange.

## Actual result
onChange fires after both hour and minute selection, but not after day selection.

## Testcase
https://jsfiddle.net/dL8s6h1f/ - window.alerts are generated after onChange.

## Version
latest from CDN

**Comment by lubber-de** [comment]
This has been fixed by #1329

**Comment by lubber-de** [comment]
I adjusted your jsfiddle accordingly here
https://jsfiddle.net/bvLceg6y/

**Comment by hughbris** [comment]
Thank you so much! So glad to have found this active fork. Loving this all over again :)

I guess I can make do with a manual patch of some sort before it's officially merged. I'm not in the habit of also searching PRs when checking if an issue has been logged/solved before. I'm wondering if there's a better process (for me or the dev team) to avoid wasting time in future. Cheers.
