### ISSUE TITLE
Fomantic-UI install fails - tasks.js expects error.filename

### ISSUE THREAD

**Issue by CatalanCabbage** [fomantic/Fomantic-UI#1463]
Duplicate of this issue, carried over from Semantic-UI:
https://github.com/Semantic-Org/Semantic-UI/issues/2971

I'm getting this error in my GitLab-CI during installation of Fomantic-UI, due to which my build tasks fail:
```
TypeError: Cannot read property 'match' of undefined
     at DestroyableTransform.errorHandler (/builds/cataxcab/the-wall/node_modules/fomantic-ui/tasks/config/tasks.js:108:29)
     at DestroyableTransform.emit (events.js:203:15)
     at DestroyableTransform.EventEmitter.emit (domain.js:448:20)
   ...
   ...
   npm ERR! code ELIFECYCLE
   npm ERR! errno 1
   npm ERR! fomantic-ui@2.8.4 install: `gulp install`
   npm ERR! Exit status 1
   npm ERR! 
   npm ERR! Failed at the fomantic-ui@2.8.4 install script.
``` 
[Complete error link](https://gitlab.com/cataxcab/the-wall/-/jobs/551032356)

The corresponding line in tasks.js is:
```
if(error.filename.match(/theme.less/)) {
```
However, here, `filename` can be (and is) undefined.
The case where the property `filename` does not exist must be handled.

## Steps to reproduce
1. Set up a .gitlab-ci.yml task [like this](https://gitlab.com/cataxcab/the-wall/-/blob/5131b65919a33ca4bd20fee0e2e54fdb749392d0/.gitlab-ci.yml)
2. Run the Job

## Expected result
The job should succeed, Fomantic-UI should not face any errors

## Links
GitLab repo where the error is reproduced: https://gitlab.com/cataxcab/the-wall
[Corresponding issue in Semantic-UI](https://github.com/Semantic-Org/Semantic-UI/issues/2971)
[Complete error](https://gitlab.com/cataxcab/the-wall/-/jobs/551032356)
[My .gitlab-ci.yml file](https://gitlab.com/cataxcab/the-wall/-/blob/5131b65919a33ca4bd20fee0e2e54fdb749392d0/.gitlab-ci.yml)
[Corresponding question on SO](https://stackoverflow.com/questions/61780956/how-to-install-and-build-fomantic-ui-in-gitlab-ci)

## Version
**fomantic-ui** : 2.8.4
**npm** : 6.14.5
**electron** : 7.1.11

**Comment by lubber-de** [comment]
The proper property check is implementy by #1469 now.
What you could try in the meantime in case you are only using the default theme:
Use the [Fomantic-CSS  package](https://github.com/fomantic/Fomantic-UI-CSS) instead which only consists of the default theme and ready packed js/css files, so a separate gulp task is not needed 
You might  also try `npx gulp build`

**Comment by CatalanCabbage** [comment]
Thanks for your work, @lubber-de! 
Only now do I realize I could have submitted a PR since I knew what the issue was. Will look to contribute where I can in the future :)
