### ISSUE TITLE
Improved support for lerna / yarn workspaces

### ISSUE THREAD

**Issue by JMS-1** [fomantic/Fomantic-UI#1466]
# Feature Request
We are using fomantic-ui 2.8.4 in a lerna/yarn environment. The build process in a subfolder fails because it is not able to find the semantic.json configuration and falls back to some default - which in our case is of no help since our semantic.json is customized.

The reason is that in the **user.js task** **require-dot-file** ist called with only the single parameter "semantic.json". In this case require-dot-file will start looking up for the indicated file starting at its very own location in the lerna global node_modules which is wrong - in a single file structure with a single project in a folder this happens to be correct.

There is an ugly workaround using the nohoist feature of lerna/yarn workspaces. I think a far more better solution would be to add **process.cwd()** as a second parameter to the require-dot-file call in the user.js task. In fact this may be a more consistent and defensice programming style than rely on some starting folder randomly choosen by some external (to fomantic-ui) code.

I can't estimate the importance of this issue and but since I found no other report using lerna/yarn workspaces may be rare. But especially in combination of an application development in parallel to some library the concept is quite helpful. For example in our case we have a couple of applications using a common theming which has been outsourced to a separate npm module.

**Comment by lubber-de** [comment]
Seems legit. I put your suggestion into PR #1467
