### ISSUE TITLE
[Dropdown] API call triggered twice on first dropdown click

### ISSUE THREAD

**Issue by prudho** [fomantic/Fomantic-UI#1472]
# Bug Report
I encouter a very specific bug when I try to load remote data to a dropdown. The first time the dropdown is clicked, the API call is fired twice. It looks like an event bug.

## Steps to reproduce
1. Go to this [JSFiddle](https://jsfiddle.net/edanL3gf/).
2. Click on the dropdown (in the input zone).
3. Take a look at the console.

## Expected result
The `responseAsync` callback should be fired once.

## Actual result
The `responseAsync` callback is fired twice.

## Testcase
[JSFiddle](https://jsfiddle.net/edanL3gf/)

## Version
2.8.4 (`develop` branch also impacted)

**Comment by lubber-de** [comment]
🤔 When you click on the dropdown arrow, instead of the dropdown text, the event is only triggered once.
Somehow similiar/related behavior to #1459

**Comment by lubber-de** [comment]
Fixed by #1725 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/64gobhjx/
