### ISSUE TITLE
calendar on modals

### ISSUE THREAD

**Issue by ramonamg17** [fomantic/Fomantic-UI#1474]
My calendars aren't working in modals?? Is there any specific setting for that??

**Comment by ko2in** [comment]
@ramonamg17 What do you mean by not working? Here's fiddle (https://jsfiddle.net/cunhe9dg/), it's working properly.

Please read the community guideline (https://github.com/fomantic/Fomantic-UI#-community) to know how to submit the issue.

**Comment by prudho** [comment]
@ramonamg17 this is a bug I encounter too, but I dont know of to fix it properly :/

Be sure to initiate the calendar after initiate the modal:
```js
  // THIS WONT WORK
  $('#standard_calendar').calendar();
  $('.ui.modal').modal('show');
```

```js
  // THIS WILL WORK
  $('.ui.modal').modal('show');
  $('#standard_calendar').calendar();
```

**Comment by lubber-de** [comment]
It's not related to the `calendar`, but to the `popup` module, which calendar is using.
The same issue appears for the popup module, as @prudho  mentioned, the order matters

Works https://jsfiddle.net/0mLzfcvx/1/
```javascript
  $('.ui.modal').modal('show');
  $('#standard_calendar').popup({
    title: 'popup title',
    content: 'popup content'
  });
```

Does not work https://jsfiddle.net/0mLzfcvx
```javascript
  $('#standard_calendar').popup({
    title: 'popup title',
    content: 'popup content'
  });
  $('.ui.modal').modal('show');
```

**Comment by GammaGames** [comment]
Isn't this because the modal, upon creation, is reattached to the DOM inside a dimmer and in the process loses any events that have been bound to any elements inside the modal? I always use a sub-view helper object or instantiate objects in the modal's `onShow` callback when I need a form or anything dynamic inside the modal because of this.

**Comment by lubber-de** [comment]
@GammaGames Indeed! 👍 
The only way to use the other, previously not working, order (popup/calendar first, then modal) is to tell the modal to be undetachable
```javascript
  $('#standard_calendar').popup({
    title: 'popup title',
    content: 'popup content'
  });
  $('.ui.modal').modal({
    detachable:false
  }).modal('show');
```
See https://jsfiddle.net/631f05rj/

**Comment by lubber-de** [comment]
I am closing this, because reasons are explained and workarounds/solutions are given
