### ISSUE TITLE
[Help] Calendar 'set date' behaviour very slow on Mac Chrome

### ISSUE THREAD

**Issue by weixinwu** [fomantic/Fomantic-UI#1475]
# Help Wanted
Hello,
I noticed the calendar 'set date' is very slow in Angular, running in Chrome on Mac. 
I've tested on different browsers(Safari, Firefox), as well as Chrome on Windows. None of them have the slow issue. 
Here is the code:

    $('#some-calendar-id").calendar('set date', new Date());

How do I check what is causing this issue?
Thanks

**Comment by lubber-de** [comment]
I unfortunately cannot reproduce this behavior.
Whatever browser/OS i am trying i always get results around 23 milliseconds for the above mentioned `set date`  behavior.
Try my simple testcase: https://jsfiddle.net/agj07z5q/1/

### Chrome / OS X Mojave
![image](https://user-images.githubusercontent.com/18379884/82570187-8dc7f600-9b81-11ea-8fed-f2e43ca83dd7.png)

### Chrome / Windows
![image](https://user-images.githubusercontent.com/18379884/82570248-9fa99900-9b81-11ea-9574-18a9fb668e84.png)

### Firefox / Windows
![image](https://user-images.githubusercontent.com/18379884/82570426-db446300-9b81-11ea-8df8-79ef5a8c6969.png)

**Comment by weixinwu** [comment]
@lubber-de Yea I cannot reproduce it with a barebones Angular project.  I will close this now.
