### ISSUE TITLE
Attached Tabular menu, border broken inside overflow container

### ISSUE THREAD

**Issue by maidzen** [fomantic/Fomantic-UI#1478]
# Bug Report
Attached Tabular menu is not displyed correctly after second tab

## Steps to reproduce

1. Create Overflow hidden container
2. Create attached tabluar menu with content (Tabs) (more then 2 Tabs)
3. Click on third tab-item

## Expected result
Border should be styled as attached 

## Actual result
Border is cut off

## Testcase with possible fix
https://jsfiddle.net/3bu8yogv/

## Version
2.8.4

##Problem in CSS Code

https://github.com/fomantic/Fomantic-UI/blob/6da2101864203cd393ce17ca2ea6fbdc9e8ae66a/src/definitions/collections/menu.less#L682

Possible fix 
`.ui.tabular.menu.hotfix ~ .attached:not(.top).segment`

**Comment by lubber-de** [comment]
Confirmed. Your suggested fix seems to be good. 🙂 
Would you like to create a PR yourself or should we adopt your fix on our own?

**Comment by maidzen** [comment]
i create a PR later today. after work.
