### ISSUE TITLE
[Icon] Upgrade to Font Awesome 5.13

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#1484]
# Feature Request
Upgrade the icon set to font awesome 5.13, special COVID-19 icons were added 
https://fontawesome.com/icons?d=gallery&v=5.13.0&m=free

![image](https://user-images.githubusercontent.com/18379884/82812519-73e52680-9e93-11ea-99b6-d00ce9124620.png)

**Comment by InfoLibre** [comment]
You could use Forkawesome fonts instead, the community is more responsive : https://forkaweso.me/Fork-Awesome/
