### ISSUE TITLE
[Modal] when dragging inside an input in long modals (modal with browser scrollbar), modal scrolls up in some browsers

### ISSUE THREAD

**Issue by mohammadhossein1976** [fomantic/Fomantic-UI#1490]
# Bug Report
when modal is long and has a scrollbar, if it is in the scrolled down position (.scrollTop() not zero), then if you drag the mouse in an input, the modal scrolls up only in 'Firefox Browser 76.0.1' .
if the testing modal isn't long enough in your browser to have a scrollbar, then just duplicate some Fomantic-UI rows to the HTML (before the input)

## Expected result
i expect that the long modal doesn't scroll up when dragging inside an input in all browsers. not in just some. the bug occurs in Firefox Browser version 76.0.1

## Actual result
the long modal scrolls up when dragging inside an input (when the modal is scrolled down)

## Testcase
  How to create an example:
   1. Open the following JSFiddle - https://jsfiddle.net/hzk7vwa4/7/
   2. the minimum necessary HTML,CSS and JavaScript is already added in the example .If the testing modal isn't long enough in your browser to have a scrollbar, then just duplicate some Fomantic-UI rows to the HTML (before the input)
   3. Do the necessary changes if you want
   4. Click "Save" at the top
   5. Copy the URL of your fiddle and link it here

## Screenshot
![Untitled](https://user-images.githubusercontent.com/55906406/83356456-94bde800-a37b-11ea-8784-7e742e9aa300.jpg)

one browser version that this bug occurs is in the picture below
![photo_2020-05-31_20-22-05](https://user-images.githubusercontent.com/55906406/83356627-9f2cb180-a37c-11ea-9058-e46410917184.jpg)

## Version
2.8.4

**Comment by lubber-de** [comment]
Triggered by the perspective setting to the `page dimmer`. Whatever FF is doing there 

You could fix this by adding 

```css
.ui.page.dimmer {
    -moz-perspective: none;
}
```

See your adjusted jsfiddle here: https://jsfiddle.net/b8Lvj3xr/1/

Alternatively you can use `detachable:false` when initializing the modal (becuase that does not use a page dimmer)

**Comment by lubber-de** [comment]
Fixed by #1491
