### ISSUE TITLE
[BUG] In a lerna environment the version from semantic.json is not copied into the generated artifacts

### ISSUE THREAD

**Issue by JMS-1** [fomantic/Fomantic-UI#1498]
# Bug Report
I'm using fomantic-ui in a lerna environment. The root folder contains three folders for libs, servers and apps. In libs only a single subfolder [let's call it themes] contains a project using fomantic-ui. The lerna package.json makes sure that fomantic-ui is localized to this project using "nohoist": ["**/fomantic-ui"] to avoid messing with the update scripts - there is no semantic.json in the root folder which seems to bedazzle the script which runs the semantic.json initialisation. If inside the libs/themes folder the build script is called the version from  semnatic.json is not copied to the generated artifacts as semantic.css.

## Steps to reproduce
[report.zip](https://github.com/fomantic/Fomantic-UI/files/4716758/report.zip)

0. OS Ubuntu 2004
1. make sure node.js 12.17.0 and yarn 1.22.4
2. unpack the zip
3. in the lerna root folder (lerna.json) call yarn
4. in the libs/themes folder call yarn build
5. check src/semantic/dist/semantic.css line 2: version is missing

## Expected result
The version number from semantic.json schould be included in all generated artefacts.

## Actual result
The version number is missing.

## Testcase
n/a, may be fixed with https://github.com/fomantic/Fomantic-UI/pull/1497

## Screenshot (if possible)
n/a

## Version
2.8.5

**Comment by lubber-de** [comment]
Fixed by #1497, verified by @JMS-1 in https://github.com/fomantic/Fomantic-UI/pull/1467#issuecomment-637408757 😉
