### ISSUE TITLE
[Form Validation] Add optional fields programmatically

### ISSUE THREAD

**Issue by CodexAnima** [fomantic/Fomantic-UI#1500]
Hey there dear FUI Team,

right now my forms are all dynamically created (in combination with vue.js) and displayed in one modal dialog.

Depending on the content the user can choose from, the form is reconstructed (fields, labels, prompts, validation rules).

I can use `$el.form( "add rule", str_identifier, arr_rules);` to add rules to a specific field.
How can I set a field to optional like (https://fomantic-ui.com/behaviors/form.html#optional-fields) ?

Like `$el.form( "set optional", str_identfier, bool_value);` to un/set an optional field for validation process.

I tried in the js at Line 1653 (in the "module.set" Object:
<pre>optional: function(identifier, boolValue) {
  $.each(validation, function(fieldName, field) {
    if (identifier == fieldName || identifier == field.identifier) {
      field.optional = boolValue;
    }
  });
  module.verbose((boolValue ? 'S' : 'Uns') + 'etting field as optional', identifier);
}</pre>

If the first validation passes (no validation errors found), all is doing well.
If I insert an error (validation error occures and show error messages), the fields are no longer flagged as optional.

Is there a reset to all fields after one validation interation?

Keep on rocking,
Matthias

**Comment by CodexAnima** [comment]
Hey there dear FUI Team,
the Problem with the reset after the first validation iteration was my fault as i did reset validation values after each iteration.

Now it checks the form and reset after processing actions if the form was valid.

Still maybe you can add this feature to add optional fields programmatically in your next version.

Please keep on rocking,
Matthias.

**Comment by lubber-de** [comment]
Implemented by #1695
