### ISSUE TITLE
[dropdown] simple dropdown menu items positioned incorrectly

### ISSUE THREAD

**Issue by Kingo64** [fomantic/Fomantic-UI#1502]
# Bug Report
As of v2.8.5, simple dropdown menus will now go offscreen if the parent dropdown label is shorter than the child dropdown labels. This issue does not occur for Javascript dropdown menus.

PR that caused the issue: #1473 

## Steps to reproduce
1. Create a menu with a simple dropdown
2. Set the dropdown header / parent label to something short, such as an icon
3. Put a child item in the menu with a long label
4. The child item will not fit on the screen as it goes to the right instead of the left.

## Expected result
Simple dropdown menu items should be positioned correctly to fit on the screen

## Actual result
Simple dropdown menu items don't fit on the screen currently.

## Testcase
Bug version (v2.8.5): [https://jsfiddle.net/18jogrs9/](https://jsfiddle.net/18jogrs9/)
Working version (v2.8.4): [https://jsfiddle.net/t4ymose7/](https://jsfiddle.net/t4ymose7/)

## Screenshot
v2.8.5
![image](https://user-images.githubusercontent.com/22741730/83839823-67d55080-a740-11ea-8886-e787e67d9897.png)

v.2.8.4
![image](https://user-images.githubusercontent.com/22741730/83839842-74f23f80-a740-11ea-9005-c5e7318981db.png)

## Version
2.8.5

**Comment by lubber-de** [comment]
@ko2in Could you please look into this? You are most familiar with the changes of the mentioned PR 😉

**Comment by ko2in** [comment]
@lubber-de Thanks, I'll look into this tomorrow.

**Comment by lubber-de** [comment]
@ko2in 
I prepared 2 jsfiddles from the gitea PR to see the issue even for non simple , but js initated dropdowns as well

### 2.8.4 OK
https://jsfiddle.net/usfh3tpw
![image](https://user-images.githubusercontent.com/18379884/83892932-9870b680-a74f-11ea-8527-2655b716195b.png)

### 2.8.5 Broken
- Workaround here is to use `left menu`, but it should work without it as in 2.8.4
https://jsfiddle.net/usfh3tpw/1/
![image](https://user-images.githubusercontent.com/18379884/83892877-8a229a80-a74f-11ea-80d1-4a616831daed.png)
