### ISSUE TITLE
[table] scrollable tbody with sticky th

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#1519]
# Feature Request

It would be great with native support for scrollable tables with sticky header

https://stackoverflow.com/questions/29906134/semantic-ui-keep-thead-visible-when-scrolling-tbody

**Comment by jamessampford** [comment]
Wondering if perhaps this could expand to both a sticky thead and scrolling tbody (especially for mobile devices) but also have perhaps a sticky first column within the tbody (a use case would be the first column has some sort of reference so you can easily look at other data when scrolling on mobile)

**Comment by hughbris** [comment]
Sounds like you would like support for where the first column in each row of the `tbody` is a `<th>` (_"some sort of reference"_) and is rendered sticky? (I have no idea how easily this could be implemented, just thought I'd clarify.)

**Comment by jamessampford** [comment]
I wouldn't necessarily limit to `<th>` but a class would be needed for sure... Could be something like adding `.sticky-first-row` or `.sticky-first-column` to the `<table>` element

**Comment by lubber-de** [comment]
btw: Only having the table header sticky when the page scrolls is already possible using `ui fixed top native sticky` on the `tr` from the sticky module (without using JS!)

See https://jsfiddle.net/lubber/dpzthow2/3/

**Comment by lubber-de** [comment]
Sticky first and/or last column using horizontal scrolling is now supported by the new `stuck table` variant #2148
