### ISSUE TITLE
Dropdown menu incorrect width when attached to a button

### ISSUE THREAD

**Issue by puskala** [fomantic/Fomantic-UI#1520]
# Bug Report
When using the dropdown button as described in https://fomantic-ui.com/modules/dropdown.html#floating the dropdown menu does not adjust to correct width.

The same issue appears in the documentation (Floating > Save button, click on the arrow to open the menu) https://fomantic-ui.com/modules/dropdown.html#floating

The  problem is that the opening menu is too narrow and the texts extend beyond it.

1. Go to https://fomantic-ui.com/modules/dropdown.html#floating
2. Click on the down arrow beside the Save button
3. The opening menu is too narrow

## Expected result
The menu should be wide enough to host the content.

## Actual result
The menu is as wide as the button (way too narrow)

## Testcase
Described above in how to produce.

## Screenshot (if possible)
![Näyttökuva 2020-6-12 kello 22 44 18](https://user-images.githubusercontent.com/46228001/84540575-5c64c500-acfe-11ea-9a38-58295c01df6f.png)

## Version
2.8.5

**Comment by lubber-de** [comment]
This is already fixed by #1505
