### ISSUE TITLE
[Error] Modal class content scrolling destroy modal on Mozilla

### ISSUE THREAD

**Issue by Marcin1sto** [fomantic/Fomantic-UI#1522]
When i add class to modal content wthen modal looks like:
![obraz](https://user-images.githubusercontent.com/50157273/84694417-75ad8180-af49-11ea-8802-94fd76dc5780.png)

this same is in documentation.

**Comment by Marcin1sto** [comment]
I have so on the Mozilla browser in others it works fine

**Comment by lubber-de** [comment]
This is fixed by #1491 for the upcoming release 2.8.6 
In the meantime add this 
```
.ui.page.dimmer.modals {
    -moz-perspective: none;
}
```
