### ISSUE TITLE
[slider] $.fn.slider.settings.interpretLabel does not exist

### ISSUE THREAD

**Issue by bartocc** [fomantic/Fomantic-UI#1526]
# Bug Report

`interpretLabel` is listed on the [slider settings page](https://fomantic-ui.com/modules/slider.html#/settings) but the key `interpretLabel` is not set on `$.fn.slider.settings`.

Is this a bug or is it by design?

## Steps to reproduce

```js
$.fn.slider.settings.hasOwnProperty('interpretLabel');
```

## Expected result

```js
true
```

## Actual result

```js
false
```

## Version

2.7.8 and 2.8.5

**Comment by lubber-de** [comment]
It's by design, because it's `false` / non existing by default

**Comment by bartocc** [comment]
To give you some context, I usually use `$.fn.<moduleName>.settings` to determine what are the valid settings for a module.

On https://fomantic-ui.com/modules/slider.html#/settings, `interpretLabel` is said to default to `false`, which is not entierely correct since it is `undefined`.

<img width="978" alt="Capture d’écran 2020-06-18 à 16 44 02" src="https://user-images.githubusercontent.com/47953/85035095-18047980-b183-11ea-864c-e27ea0798cd3.png">

Would it be problematic to add `$.fn.slider.settings.interpretLabel: false` in a future release ?

**Comment by lubber-de** [comment]
Did that just now by #1528  😉
