### ISSUE TITLE
Gulp Install error on new build

### ISSUE THREAD

**Issue by sannamalai176** [fomantic/Fomantic-UI#1532]
After I install the latest fomantic-ui, when i run the command - gulp build, getting the following error

gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined

any idea?

**Comment by exoego** [comment]
Which version of gulp are you using?
`gulp -v`

**Comment by sannamalai176** [comment]
after running this command npx gulp build it worked. we can close this ticket.
