### ISSUE TITLE
2.8.5 has invalid class `20` in update to font awesome 5.13

### ISSUE THREAD

**Issue by nafg** [fomantic/Fomantic-UI#1544]
2.8.5 upgraded font awesome to 5.13 which has [stopwatch-20](https://origin-staging.fontawesome.com/icons/stopwatch-20?style=solid), however this is not valid CSS:

https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/elements/icon.overrides#L871

Class names are not supposed to start with a number (see https://stackoverflow.com/a/449000/333643).

I'm affected by this because I maintain https://github.com/nafg/css-dsl which does code generation based on CSS files, which it parses using https://github.com/phax/ph-css. It fails on the `.20` and can't parse it.

Thanks.

**Comment by exoego** [comment]
Thanks for reporting !
I am working on this issue in https://github.com/fomantic/create-fomantic-icons

**Comment by lubber-de** [comment]
fixed by #1546
