### ISSUE TITLE
[slider] Rounded value is not always rounded

### ISSUE THREAD

**Issue by bartocc** [fomantic/Fomantic-UI#1545]
# Bug Report
Despite the code I've spotted in the slider.js codebase to avoid a nasty JS rounding bug, it looks like there are still some cases where this happens.

## Steps to reproduce

Move a slider several times to get the value bug. It roughly happens 1 time out of 5 in my app.

## Expected result

A value rounded to the closest step (ex: 2.1)

## Actual result

(ex: 2.1000000001)

## Testcase

https://jsfiddle.net/dfj7urbz/

## Screenshot

<img width="1257" alt="Capture d’écran 2020-06-30 à 09 03 57" src="https://user-images.githubusercontent.com/47953/86094724-320e5800-bab1-11ea-9df7-49cb886418bd.png">

## Version

2.7.8
2.8.6

**Comment by lubber-de** [comment]
Fixed by #1547

**Comment by bartocc** [comment]
so much reactivity from this team 🎉

Thx!
