### ISSUE TITLE
[Search] Getting "false" instead of selected item from onSelect event

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1557]
Hello, I'm wrapping FUI [search module](https://fomantic-ui.com/modules/search.html) within my Angular application and I'm experiencing a bug in the selected item.

If I choose item by selecting with keyboard arrows (and then press Return) or by clicking it with mouse I get `false` instead of selected item as `result` parameter of `onSelect` property. Instead, if I write something and then press Return I do get the right selected item.

So, what could be the problem?

Here is part of my Angular wrapper in case it could be helpful:

```
init(source: (query: string) => Observable<Array<any>) {
    setTimeout(() => $('.ui.search', this.el.nativeElement)['search']({
        apiSettings: {
            responseAsync: (qry, callback) => {
                const searchQuery = qry.urlData.query.trim();

                this.pending = true;
                source(searchQuery).subscribe((data) => {
                    callback(data);
                },
                (error) => {
                    this.pending = false;
                },
                () => {
                    this.pending = false;
                });
            }
        },
        fields: {
            title: 'label'
        },
        minCharacters : 3,
        showNoResults: true,
        fullTextSearch: false,
        maxResults: 1000,
        onSelect: (result, response) => {
            console.log(result, response);
        },
        selectFirstResult: true,
        searchDelay: 650,
        cache: true
    }), 0);
}
```

I'm unable to create a JSFiddle due the [Angular integration issue](https://github.com/fomantic/Fomantic-UI/issues/1205). Anyway I have tried to play with similar code [here](https://jsfiddle.net/phgefmLw/), but it works with no problems.

**Comment by lubber-de** [comment]
Only a guess: The search module tries to cache its results in a data attribute . This is  probably not existing anymore by whatever angular is doing to the element. This is unexpected for the search module. Otherwise we cannot help here, because, as you already said, your above given jsfiddle using raw FUI is working fine.

**Comment by smartm0use** [comment]
I don't get the point about the `cache`. About the cache I see that it works, in fact if I make the same search no calls are made to server.
Anyway I get the same issue even I set it to `false`.

Do you have other hints for me?

**Comment by lubber-de** [comment]
mmh, i think this is the code where it returns false in your case, because it does not seem to get the existing results correctly. But without having reproducable code i really cannot help
https://github.com/fomantic/Fomantic-UI/blob/0269a8213ac2ff438965c6a82503e7561d2024ae/src/definitions/modules/search.js#L486

Try to debug the `get.results()` method. Use the semantic.js (not the min) version.
Either `results` in `get.results()` is empty or the current selected entry is not available in that object anymore .

**Comment by smartm0use** [comment]
Thank you for this hint.

I'm debugging and I'm here now:

```
  result: function(value, results) {
    var
      result       = false
    ;
    value = (value !== undefined)
      ? value
      : module.get.value()
    ;
    results = (results !== undefined)
      ? results
      : module.get.results()
    ;
    if(settings.type === 'category') {
      module.debug('Finding result that matches', value);
      $.each(results, function(index, category) {
        if(Array.isArray(category.results)) {
          result = module.search.object(value, category.results)[0];
          // don't continue searching if a result is found
          if(result) {
            return false;
          }
        }
      });
    }
    else {
      module.debug('Finding result in results object', value);
      result = module.search.object(value, results)[0];
    }
    return result || false;
  },
```

At the first row `result: function(value, results)` the value of the `value` variable is the item that I clicked... so it is weird that `result` becames `false` at the end of the function.
I think the row `result = module.search.object(value, results)[0];` set it to `false`. According to debug in that row `value` is the value (string) corresponding to the field I set in the `fields` property and `results` is the array of my objects.
Any idea?

**Comment by lubber-de** [comment]
The `search.object()` method does not seem to return false somwhere. It uses `$.merge` at the end.. I dont know if angular (which also has a merge command) overrides the jquery method..:thinking:
Check if your `searchFields` setting matches your resultset. Debug the `search.object()`  method, because it does not find your result by some reason... I don't have any other clue without having a working reproducable jsfiddle, i am sorry

**Comment by smartm0use** [comment]
In the meanwhile can you tell me what is `searchFields` property and what is the difference with `fields` property?

**Comment by lubber-de** [comment]
The `fields` setting is to map your API resultset objects to the template renderer (which expects certain object names to support for example category wrapping)
For example to cautomatically reate an action button the category template, it expects an object named `url` by default.
If your backend does not provide this but an object `link` instead (and you cannot change the backend) you can change this in the settings so the template searches for  `link` to render a button.
 
The `searchFields` setting is to define all object names, out of your api result, where local search should take place

**Comment by smartm0use** [comment]
So, in my case I have not to set any `searchFields` property since I'm not dealing with local searches. Am I right?

Anyway, going deep I reach this code:

```
  object: function(searchTerm, source, searchFields) {
    searchTerm = module.remove.diacritics(String(searchTerm));
    var
      results      = [],
      exactResults = [],
      fuzzyResults = [],
      searchExp    = searchTerm.replace(regExp.escape, '\\$&'),
      matchRegExp  = new RegExp(regExp.beginsWith + searchExp, 'i'),

      // avoid duplicates when pushing results
      addResult = function(array, result) {
        var
          notResult      = ($.inArray(result, results) == -1),
          notFuzzyResult = ($.inArray(result, fuzzyResults) == -1),
          notExactResults = ($.inArray(result, exactResults) == -1)
        ;
        if(notResult && notFuzzyResult && notExactResults) {
          array.push(result);
        }
      }
    ;
    source = source || settings.source;
    searchFields = (searchFields !== undefined)
      ? searchFields
      : settings.searchFields
    ;

    // search fields should be array to loop correctly
    if(!Array.isArray(searchFields)) {
      searchFields = [searchFields];
    }

    // exit conditions if no source
    if(source === undefined || source === false) {
      module.error(error.source);
      return [];
    }
    // iterate through search fields looking for matches
    $.each(searchFields, function(index, field) {
      $.each(source, function(label, content) {
        var
          fieldExists = (typeof content[field] == 'string') || (typeof content[field] == 'number')
        ;
        if(fieldExists) {
          var text;
          if (typeof content[field] === 'string'){  
              text = module.remove.diacritics(content[field]);
          } else {
              text = content[field].toString(); 
          }
          if( text.search(matchRegExp) !== -1) {
            // content starts with value (first in results)
            addResult(results, content);
          }
          else if(settings.fullTextSearch === 'exact' && module.exactSearch(searchTerm, text) ) {
            // content fuzzy matches (last in results)
            addResult(exactResults, content);
          }
          else if(settings.fullTextSearch == true && module.fuzzySearch(searchTerm, text) ) {
            // content fuzzy matches (last in results)
            addResult(fuzzyResults, content);
          }
        }
      });
    });
    $.merge(exactResults, fuzzyResults);
    $.merge(results, exactResults);
    return results;
  }
```

I noticed that `searchTerm` contains the string of the selected item but `searchExp` and then `matchRegExp` are `undefined`. Is this an attended behaviour?

**Comment by ko2in** [comment]
@smartm0use What is your API back-end returning? Can you capture and post here?

**Comment by smartm0use** [comment]
So, in my case I have not to set any `searchFields` property since I'm not dealing with local searches. Am I right?

Anyway, going deep I reach this code:

```
  object: function(searchTerm, source, searchFields) {
    searchTerm = module.remove.diacritics(String(searchTerm));
    var
      results      = [],
      exactResults = [],
      fuzzyResults = [],
      searchExp    = searchTerm.replace(regExp.escape, '\\$&'),
      matchRegExp  = new RegExp(regExp.beginsWith + searchExp, 'i'),

      // avoid duplicates when pushing results
      addResult = function(array, result) {
        var
          notResult      = ($.inArray(result, results) == -1),
          notFuzzyResult = ($.inArray(result, fuzzyResults) == -1),
          notExactResults = ($.inArray(result, exactResults) == -1)
        ;
        if(notResult && notFuzzyResult && notExactResults) {
          array.push(result);
        }
      }
    ;
    source = source || settings.source;
    searchFields = (searchFields !== undefined)
      ? searchFields
      : settings.searchFields
    ;

    // search fields should be array to loop correctly
    if(!Array.isArray(searchFields)) {
      searchFields = [searchFields];
    }

    // exit conditions if no source
    if(source === undefined || source === false) {
      module.error(error.source);
      return [];
    }
    // iterate through search fields looking for matches
    $.each(searchFields, function(index, field) {
      $.each(source, function(label, content) {
        var
          fieldExists = (typeof content[field] == 'string') || (typeof content[field] == 'number')
        ;
        if(fieldExists) {
          var text;
          if (typeof content[field] === 'string'){  
              text = module.remove.diacritics(content[field]);
          } else {
              text = content[field].toString(); 
          }
          if( text.search(matchRegExp) !== -1) {
            // content starts with value (first in results)
            addResult(results, content);
          }
          else if(settings.fullTextSearch === 'exact' && module.exactSearch(searchTerm, text) ) {
            // content fuzzy matches (last in results)
            addResult(exactResults, content);
          }
          else if(settings.fullTextSearch == true && module.fuzzySearch(searchTerm, text) ) {
            // content fuzzy matches (last in results)
            addResult(fuzzyResults, content);
          }
        }
      });
    });
    $.merge(exactResults, fuzzyResults);
    $.merge(results, exactResults);
    return results;
  }
```

At row `fieldExists = (typeof content[field] == 'string') || (typeof content[field] == 'number')` I see that `fieldExists` is `undefined`.
`content` variable contains the object of the selected item: `{ id: 1, label: 'my item', value: `some value' }` and `field` variable contains my custom field I set with `fields` property: `{ title: 'label' }`.
So it seems it is failing because it can't access to `label` property of my object, because it is trying to access to "myObject.title.label" instead of "myObject.label". Am I right?

**Comment by smartm0use** [comment]
@ko2in Back-end returning is something like this:

```
[
    { id: 1, label: 'Josh Smith', value: 48 },
    { id: 2, label: 'Foo Bar', value: 75 },
    { id: 3, label: 'Alice Red', value: 36 },
    { id: 4, label: 'Bob White', value: 63 },
]
```

**Comment by ko2in** [comment]
@smartm0use Your data looks fine. I can't reproduce with this either. If you can run the same implementation with your API server outside AngularJS, then something might probably mess up with your AngularJS.

**Comment by smartm0use** [comment]
I have updated my previous message, maybe we are closer to the solution...

**Comment by ko2in** [comment]
@smartm0use The default search fields are `id, title, description`. You didn't set `searchFields` in your fiddle and your source code above. You set `fields` which is for mapping the key from your API response.

If you can mock your AngularJS implementation, then it would help us to debug your problem in a better way.

You can try [codesandbox.io](https://codesandbox.io/) to mock the similar environment. You don't need to create your whole project, only the part with FUI search module and your AngularJS snippets.

**Comment by smartm0use** [comment]
@ko2in I finally solved... and before reading your message :)
I set `searchFields: ['label']` and it works now.

Thank you and thanks to @lubber-de ;)

PS: I'm using Angular, not AngularJS, and as I said I can't create a mock with Angular and Fomantic-UI. At the moment [none can't do it](https://github.com/fomantic/Fomantic-UI/issues/1205).
