### ISSUE TITLE
[Search] Search field with non-rounded borders

### ISSUE THREAD

**Issue by smartm0use** [fomantic/Fomantic-UI#1558]
[Search module](https://fomantic-ui.com/modules/search.html) page has a lot of example and all of them show search field with rounded borders.

I see that if I include search module within a form with `ui form` class then I get a [squared field](https://fomantic-ui.com/elements/input.html).

So, there is a way to have squared search field in case of use out of a form?

**Comment by lubber-de** [comment]
Sure, just override the border-radius
See https://jsfiddle.net/lubber/3dowLgsx/2/
![image](https://user-images.githubusercontent.com/18379884/86934605-30413600-c13c-11ea-85cd-1b3f7e5eb306.png)

**Comment by smartm0use** [comment]
What about improving Search module by adding a specific class to have it?

**Comment by lubber-de** [comment]
🤔 , unsure, because
- you can already define this according to your needs by changing the variable value at https://github.com/fomantic/Fomantic-UI/blob/0269a8213ac2ff438965c6a82503e7561d2024ae/src/themes/default/modules/search.variables#L13
- providing a `ui squared search` seems to be inconsistent. The search module is individual on its own. Having the same style like other input fields is already covered when the search field is used inside a form (as you found out already)
@fomantic/maintainers  What do you think?

**Comment by ko2in** [comment]
Yes. I agreed that it's unnecessary to have specific class name. Since the search field commonly have different style with goggle icon, loading icon etc, and I don't think it should mix with other input field styles. It should have individual customization on it's own.

**Comment by smartm0use** [comment]
>  Having the same style like other input fields is already covered when the search field is used inside a form (as you found out already)

In that case how to have api search within a search field inside a form?
I tried but it doesn't work: https://jsfiddle.net/d7a6zv5h


> Yes. I agreed that it's unnecessary to have specific class name. Since the search field commonly have different style with goggle icon, loading icon etc, and I don't think it should mix with other input field styles. It should have individual customization on it's own.

In my case I have a search field among other form fields. It is a form for personal data and users can search for cities in the search field...

**Comment by ko2in** [comment]
@smartm0use You need to wrap your search module within `ui search` container and the input field need the class name `prompt`. Here is fiddle (https://jsfiddle.net/4L2khmyu/).

Please read [documentation](https://fomantic-ui.com/modules/search.html) for complete details and usages.

**Comment by smartm0use** [comment]
@ko2in Your code doesn't work. It works because you add a CSS rule to have it squared.

Anyway the point is that the search field could be a common search box (rounded) and a regular input field (squared) in which users can make searches among thousands of items (as I said in my cities example).

Something like this: https://jsfiddle.net/gyaqj1tp

Don't you agree?

**Comment by lubber-de** [comment]
@smartm0use As said

-  the search module has its own purpose thus own design when used **outside** of a form
- When used i**nside** of a form, FUI **already** adjusts the border radius to match the other form fields
- Only when you want to have **squared** borders **outside** of a form, you have to adjust this yourself [as i mentioned](https://github.com/fomantic/Fomantic-UI/issues/1558#issuecomment-656106291) 

See https://jsfiddle.net/lubber/b3y9ksaj/4/

**Comment by smartm0use** [comment]
I see, anyway I dont' agree.

I think that we could have even a search module with it own purpose that has squared borders, just adding a dedicated class:

![image](https://user-images.githubusercontent.com/5399265/87434979-6aeb1880-c5eb-11ea-8c2d-654d9eddf7d7.png)

:D

**Comment by lubber-de** [comment]
ok, please create 2 PRs, one for the actual implementation and one for the docs page (the screenshot assumes, you already did that)

**Comment by TheJltres** [comment]
Search is rounded by default, but dropdown is not, should this mean we need a rounded class for dropdown, or make search squared by default and add rounded class instead of square ?

I don't like naming also, all components could be squared or rounded in a future and in many different sizes or ways (bottom-right, bottom-left)

**Comment by smartm0use** [comment]
@lubber-de I didn't any implementation, I just played with DOM :P

**Comment by smartm0use** [comment]
Is my first PR here, is the right way to do it?
https://github.com/fomantic/Fomantic-UI/pull/1576

**Comment by lubber-de** [comment]
> Is my first PR here, is the right way to do it?
> #1576
See my (and later other reviewers) comment inside the PR (you should have been notified by github already via email)
