### ISSUE TITLE
[Getting Started] Useing only selected CSS and JS files of the Fomantic Components

### ISSUE THREAD

**Issue by asantech** [fomantic/Fomantic-UI#1565]
hi, I have installed fomantic-ui css and js files locally, but inorder to make my website lighter, i only want to have some of the components files. 
The problem that i have is that the css files and js files dont work, what should i do?

**Comment by lubber-de** [comment]
> The problem that i have is that the css files and js files dont work

Could you please setup a jsfiddle or at least post your (minimum) html code so we can get an idea what might be the issue?

Basically two options to only need the features you need:

### Use precompiled files, i only the default theme is needed
Use the singe file components in either this repo or from the CSS only repo https://github.com/fomantic/Fomantic-UI-CSS/tree/master/components

### Build FUI yourself, to get the css files even smaller or have an individual theme
Compile FUI using this repo and adjust the
https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/globals/variation.variables
file to disable element variations you don't need (for example you need buttons, but no `basic buttons` then set `variationButtonBasic` to `false`
You can also adjust/reducde the colors in the central file
https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/globals/colors.less

If you need emojis, but only a few of them, remove the unwanted emojis in
https://github.com/fomantic/Fomantic-UI/blob/master/src/themes/default/elements/emoji.overrides

Build everything by `npx gulp build` and use the files from the dist folder

**Comment by asantech** [comment]
hi , here is a sample https://jsfiddle.net/ejpc2ohk/3/

**Comment by lubber-de** [comment]
🤔 It's basically working fine, see my adjusted fiddle.
Are you sure you have the same folder structure locally and both local files are loaded? This of course cannot be reproduced in a jsfiddle
https://jsfiddle.net/lubber/bvrth54w/3/
