### ISSUE TITLE
Model showing at improper location.

### ISSUE THREAD

**Issue by CmdrMahesh** [fomantic/Fomantic-UI#1575]
# Help Wanted
Hello Devs,
I have used this library for my project and now I have a problem with one of the modules named Model.

![Screenshot](https://user-images.githubusercontent.com/46396430/87444246-288a0180-c614-11ea-8c04-143ad8203400.png)

When I click on the question mark icon the model supposed to be shown in the middle of the page but it is adjusted to the left of the screen.

![Screenshot (1)](https://user-images.githubusercontent.com/46396430/87444392-5bcc9080-c614-11ea-848f-8d64cd71d777.png)

Here is the snippet I used:
------------------------------------------------------
HTML
-----------------------------------------------------
`<div id="help_modal" class="ui small modal"><div class="content">\\Lots of stuff here.</div></div>`

-----------------------------------------------------
JS
-----------------------------------------------------
```
jQuery("#help_modal").find(".content").html(_help_text); //changed the help text in the model
jQuery("#help_modal").modal('show'); //triggered to show the popup

```
Please help with this issue.

**Comment by TheJltres** [comment]
Hi!

Here is an example of a working modal: https://jsfiddle.net/TheJltres/hztfr3w9/2/
There are some more steps to reproduce your issue?
Can you provide some jsfiddle case?

Thanks!

**Comment by lubber-de** [comment]
Closing for now. Will reopen when you can provide a reproducable jsfiddle testcase
