### ISSUE TITLE
[Button] incorrect compact icon button padding value

### ISSUE THREAD

**Issue by ScorpioX** [fomantic/Fomantic-UI#1582]
# Bug Report
In older versions, the padding for a compact icon button was .58928571em
However in v2.8.6, that value got preceded by additional setting from .ui.icon.button:not(.animated)

## Steps to reproduce
1. Just check out document https://fomantic-ui.com/elements/button.html#compact, and you can see the middle icon button has bigger padding.

## Expected result
Compact icon button should exhibit a compact padding

## Actual result
Actual padding equals icon button without compact class

## Testcase
https://fomantic-ui.com/elements/button.html#compact

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/14276/87653582-4e381780-c788-11ea-80fc-74a0ee58028f.png)

## Version
2.8.6

**Comment by lubber-de** [comment]
This is already fixed by #1571 🙂
