### ISSUE TITLE
[Card] horizontal cards meta & actions are forced to the right

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#159]
# Bug Report

## Steps to reproduce
1. create a horizontal card
2. add some meta data or a button

## Expected result
The meta data or button should appear under the card

## Actual result
The meta data or button is forced to the right

## Description

This is caused because of `flex-direction: row` when setting `flex-wrap: wrap` buttons then flow under the card but meta data will force the content to go under the image. If the content is too long it will also wrap to the next row.

## Testcase
https://jsfiddle.net/Lwxau2yn/

## Screenshot
![image](https://user-images.githubusercontent.com/11588822/46597606-c1532b00-cad8-11e8-94ce-25a4382fa508.png)

## Version
2.6.2

**Comment by tcmal** [comment]
I'll do this
