### ISSUE TITLE
[Toast] Action Text

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#160]
# Feature Request

## Description
Add the option of allowing action text (like when sending/deleting an email in Gmail) to the toast prompt with a corresponding callback for when this part is specify clicked (eg. onActionClick)

An alternative could potentially allow action buttons like a MacOS notification, with primary/secondary button callbacks (eg. onButtonPrimary), however, on the other hand, buttons may not be quite suited for a toast

## Example
Action Text:
https://www.howtogeek.com/wp-content/uploads/2016/12/00_lead_image_undo_send.png

Action Button(s):
https://www.jamf.com/jamf-nation/discussions/26683/macos-notification-prompts

**Comment by hammy2899** [comment]
I think this is a good feature to have. I would also make it have an array of actions so you could have as many as you want.

**Comment by lubber-de** [comment]
Available by #1129
