### ISSUE TITLE
[Toast] Progress Bar not visible when class: 'error'

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1600]
# Bug Report
Progress Bar not visible when class: 'error' on toast

## Testcase
https://jsfiddle.net/dutrieux/vunftrhx/

## Screenshot (if possible)
![bug_toast](https://user-images.githubusercontent.com/1622751/88269816-00b23200-ccd5-11ea-93e1-ef929df38666.gif)
## Version
2.8.6

**Comment by lubber-de** [comment]
Fixed by #1601
