### ISSUE TITLE
[Form Validation] Ability to clear errors

### ISSUE THREAD

**Issue by dlynchcodes** [fomantic/Fomantic-UI#1610]
I've got mini "forms" inside modals that get reused on a page. If the form is invalid and the user exits the modal, upon reopening the modal the errors on the form still exist, and it doesn't appear there is a documented way to clear form errors, specifically inline errors in my case. This has been requested in the Semantic repository and I think it'd be great to see that in Fomantic. https://github.com/Semantic-Org/Semantic-UI/issues/702

**Comment by lubber-de** [comment]
Fixed by #1611 😉

**Comment by dlynchcodes** [comment]
Wow... were you already working on it, or are you just that fast?

**Comment by lubber-de** [comment]
We were just quick 😁 and I was very must astonished that this hasn't been fixed in Sui for such a long time

**Comment by dlynchcodes** [comment]
That's awesome. Thanks! Can I buy you a coffee or simply donate to Fomantic?

**Comment by lubber-de** [comment]
@dlynchcodes You can use the github sponsor button at the top :wink:
