### ISSUE TITLE
[Segment] Icon with `line` class name breaks layout

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#1619]
# Bug Report

Comes from https://github.com/Semantic-Org/Semantic-UI-React/issues/3888.

## Steps to reproduce
1. Use `ui segment placeholder` and an icon that contains `line` class name.

## Testcase
https://jsfiddle.net/kdjs0awe/2/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/14183168/88810066-264ba980-d1b5-11ea-974a-07b5e6b0508e.png)

## Version

2.8.6

**Comment by layershifter** [comment]
It happens because an icon receives unwanted CSS:

![image](https://user-images.githubusercontent.com/14183168/88810332-87737d00-d1b5-11ea-9345-505fa37cd4f3.png)

**Comment by lubber-de** [comment]
As suggested in #1620: To fix this we should add 2 one-word alias names for `line graph icon` and `chart line icon` : `linegraph` and `chartline` to avoid many selector changes from `.line` to `.line:not(.icon)`

**Comment by lubber-de** [comment]
As suggested above, let's just change `line graph icon`  to `linegraph icon` and `chart line icon` to `chartline icon` now.
@ko2in As you assigned this to yourself, would you want to do this little change in `icon.overrides` ? If yes, then please also create an appropriate PR in the https://github.com/fomantic/create-fomantic-icons repository, so the next time FA icons are created we still have this fixed.
If you don't have time, just tell me (or assign the issue to me) , i am doing it then 🙂 
@hammy2899 Last chance in case you don't agree 😆

**Comment by ko2in** [comment]
@lubber-de I'll look into this tomorrow and send PR.

**Comment by hammy2899** [comment]
@lubber-de @ko2in ye changing icon names is the best approach here IMO
