### ISSUE TITLE
[dropdown] when multiple, placeholder text is wrapped

### ISSUE THREAD

**Issue by Ikaer** [fomantic/Fomantic-UI#1623]
# Bug Report
When using a dropdown with multiple selection, placeholder text with spaces is wrapped. It's not when removing the multiple part.

## Steps to reproduce

cf. jsfiddle

## Expected result
text should not be wrapped in multiple like the no multiple dropdown

## Actual result
text is wrapped

## Testcase
This is the test case for latest version of fomantic (2.8.6) https://jsfiddle.net/jLn0wkv9/1/
Also we notice some kind of change between the 2.8.4 and 2.8.5 of this kind of input (but still with the wrap text issue) here the jsfiddle with 2.8.4 https://jsfiddle.net/1yxtrqen/1/

## Screenshot (if possible)
2.8.6 (multiple is on right)
![image](https://user-images.githubusercontent.com/7936075/89033720-bade1500-d337-11ea-9a41-d8d99967d4fc.png)
2.8.4 (multiple is on right)
![image](https://user-images.githubusercontent.com/7936075/89033750-ce897b80-d337-11ea-9241-9882101d3b2f.png)

## Version

2.8.6

## Notes
For the change between 2.8.4 and 2.8.6 its a css rule that override the padding of multiple dropdown
2.8.4:
![image](https://user-images.githubusercontent.com/7936075/89034560-83706800-d339-11ea-81a3-18d03b57226d.png)

2.8.6:
![image](https://user-images.githubusercontent.com/7936075/89034516-6b004d80-d339-11ea-9d80-922d5ee0e89b.png)

**Comment by lubber-de** [comment]
Should be fixed by #1656
