### ISSUE TITLE
[Flag]Duplicate 'Serbia' but different code

### ISSUE THREAD

**Issue by Michael-Pro** [fomantic/Fomantic-UI#1649]
I find that we have the same name of 'Serbia' but with different code 'cs','rs', is that correct?

**Comment by TheJltres** [comment]
Hi, yes that is correct.
RS is only for Serbia: https://www.iso.org/obp/ui/#iso:code:3166:RS

CS is for Serbia and Montenegro: https://www.iso.org/obp/ui/#iso:code:3166:CS
CS has no ISO flag as you can see heare: https://es.wikipedia.org/wiki/ISO_3166-1

Now Montenegro is ME

Should cs be changed or removed?

**Comment by lubber-de** [comment]
In #1190 we already removed `cs` as it does not have a separate ISO flag as @TheJltres pointed out and thus isn't supported by Tweemoji.
However, for backward compatibility we cannot remove 'cs' in the current branch.
