### ISSUE TITLE
[integrations] Add web components to ROADMAP.md

### ISSUE THREAD

**Issue by lukechu10** [fomantic/Fomantic-UI#1650]
# Feature Request

Web components have been mentioned numerous times in this thread: #319. There has not been, however, any sign that a web component integration is being worked on. I propose adding web components to the `Library Implementations` section of the v3 Road Map.

**Comment by lukechu10** [comment]
Can I just create a PR to modify ROADMAP.md and close this issue?
Thanks.

**Comment by lubber-de** [comment]
Yes, feel free to create a PR, much appreciated 😊
