### ISSUE TITLE
Focus to first input field after form validation.

### ISSUE THREAD

**Issue by qroft** [fomantic/Fomantic-UI#1659]
# Feature Request
I am working on an update of one of my online shops and it's UI is based on Fomantic.
At the one-page checkout process are several input fields (name, address, phone number etc.)
The form validation works perfectly.
But as i am using the onFailure event to show a toast, i also wanted it to jump to the field where the validation fails.
It would be great to have the example on the project's documentation IMHO.

- Why should we add this feature/enhancement
As i could not find any onFailture example i had to search the web for it. It would be great to have it inside the documentation.

- What problem(s) does it solve
To find out how the form validations work and can like in my case substitute the inline HTML error code with a toast, alert, console.log or similar.

- Complexity
Easy Peasy.

- How we should implement it
Putting the example in the following page as example:
https://fomantic-ui.com/behaviors/form.html

I have found one example of doing it on the Semantic Github pages. But as we all know SUI is not updated "that" "much" :)
BTW: the code on said page did not work.
https://github.com/Semantic-Org/Semantic-UI/issues/3059

So after searching the web for 5 minutes i found a asian page that had an example that worked out for me.
http://blog.starbug1.com/archives/1886

The code on that page is this:
`onFailure: function(erros, field) {
    var errorFields = $('.field.error input,.field.error select', this);
    setTimeout(function(){
      errorFields.first().focus();
    }, 100);
    return false;
  },`

**Comment by lubber-de** [comment]
The `onFailure` callback is basically documented in the settings tab
https://fomantic-ui.com/behaviors/form.html#callbacks
![image](https://user-images.githubusercontent.com/18379884/91399123-b37a3080-e83d-11ea-9c36-8e2d1fad0eab.png)
Adding examples to callbacks are a good idea, however we should make it generic, means, **every** callback should gain an example (PR volunteers for the [docs repo](https://github.com/fomantic/Fomantic-UI-Docs) are welcome 😉 )

However, especially for your usecase, i think of adding another option `errorFocus` which will do exactly what your mentioned code will do; focus the first error field on submit form validation
We have a similiar setting in modal `autoFocus`

**Comment by lubber-de** [comment]
New option `errorFocus` implemented by #1713
