### ISSUE TITLE
Dropdown right label

### ISSUE THREAD

**Issue by zdarin** [fomantic/Fomantic-UI#1667]
Hi, i would like to do Dropdown right label like input right label it is possible? or i should manually add styles as in picture ??
![Screenshot 2020-09-09 at 11 40 45](https://user-images.githubusercontent.com/42121280/92579417-d7099600-f295-11ea-9d38-a61ea23a0d95.png)
![Screenshot 2020-09-09 at 11 57 57](https://user-images.githubusercontent.com/42121280/92579422-d83ac300-f295-11ea-9130-4673e15e865e.png)

**Comment by ko2in** [comment]
Is that (https://jsfiddle.net/041hjwbt/) what you're looking for?

**Comment by zdarin** [comment]
> Is that (https://jsfiddle.net/bxh104kw/) what you're looking for?

almost yes but i searching like in second picture no bottom empty space

**Comment by ko2in** [comment]
What do you mean no bottom empty space? Can you provide your fiddle?

**Comment by zdarin** [comment]
https://jsfiddle.net/Lwfpyzc1/

![Screenshot 2020-09-09 at 11 57 57](https://user-images.githubusercontent.com/42121280/92584224-0a4f2380-f29c-11ea-9c04-16fbd12b161f.png)

**Comment by ko2in** [comment]
I don't think FUI doesn't support the label with action input. You can use it as button container for now (https://jsfiddle.net/18ca2m75/). Maybe, I'll submit PR to support label inside the action input.

**Comment by zdarin** [comment]
> I don't think FUI doesn't support the label with action input. You can use it as button container for now (https://jsfiddle.net/18ca2m75/). Maybe, I'll submit PR to support label inside the action input.

Yes like this, but button darken on click so i thought some combination possible but for now i think style that i added more beautiful. Waiting for dropdown labels 👍
