### ISSUE TITLE
[Help] Toasts inside iframe

### ISSUE THREAD

**Issue by cheesyMan** [fomantic/Fomantic-UI#1675]
# Help Wanted
I'm creating an  html page with Fomantic UI, using toasts. This html has to be embedded as a scrollable iframe in a wordpress page.

I've noticed that when the iframe is scrolled down the top toasts are not visible as they actually show-up at the topmost of the iframe.

Is there any way to make the toasts show at the top of the **iframe viewport** so that they are always visible no matter if the iframe is scrolled or not?

Thanks

**Comment by ko2in** [comment]
Please provide your fiddle. So, we can reproduce it properly and see your problem.

**Comment by lubber-de** [comment]
An iframe has it's complete own context. To accomplish your task you would have to call the toast from the iframes parent, so the whoe viewport can be accessed again.
