### ISSUE TITLE
[Slider] browser freezes upon window resize with step-less slider

### ISSUE THREAD

**Issue by mhthies** [fomantic/Fomantic-UI#1684]
# Bug Report
Resizing the browser window with a step-less slider (initialized with `step: 0`) on the page, freezes the overall browser tab.

## Steps to reproduce
1. Create a simple page with the slider module loaded and a slider initialized without steps (`<div class="ui slider"></div>` and `$(...).slider({ step: 0 });`)
2. Open the page
3. Resize the browser window

## Expected result
Nothing happens.

## Actual result
Browser tab hangs up. I assume, it enters some endless JavaScript loop or JavaScript <-> layout recalculation loop.

Tested with Chromium 85.0.4183.102 and Firefox 80.0.1.

## Testcase
https://jsfiddle.net/mthrcf5n/3/

--> Simply move JSFiddle's grid divider or resize your browser window

## Version
2.8.7

**Comment by TheJltres** [comment]
I think the bug is caused by dividing number/0 so it returns Infinity number, this hapens on `numLabels`.

https://github.com/fomantic/Fomantic-UI/blob/develop/src/definitions/modules/slider.js#L580

**Comment by ko2in** [comment]
@TheJltres You're right. The `numLabels` returns infinity when step is disabled and has value '0', and causes endless loop on resize event.

**Comment by TheJltres** [comment]
I'm preparing a PR, 2 minutes 😄
