### ISSUE TITLE
[Slider] labeled step-less slider

### ISSUE THREAD

**Issue by mhthies** [fomantic/Fomantic-UI#1685]
# Feature Request

I'm using the Slider module to create controls for setting a value in a contuinous range (0-100%). Now, I'd like to add labels to these step-less sliders, forming a scale, to give the user more feeling for the right knob position.

The result could look just like a slider *with* steps, but still have the knob freely movable to any position between the labels to represent any real number, just like a slider with `step: 0`:

## Screenshot
(I used a `ui ticked labeled slider` for this example image, with a custom `interpretLabel` function for generating the percentage labels.)

![labeled-stepless-slider](https://user-images.githubusercontent.com/8234059/94194702-56ac7d00-feb2-11ea-906d-d59cc4552505.png)

**Comment by TheJltres** [comment]
Hi @mhthies 
You can try like this: https://jsfiddle.net/TheJltres/z43vub60/

Is this what you want?

**Comment by mhthies** [comment]
Hi,
thanks for checking in on this feature request.

I actually tried a similar workaround already, but I missed the possibility to return an empty label in `interpretLabel`. Thanks for pointing me to this. Without that trick, I had major performance issues due to the large number of ticks, which were created with jQuery methods on page load.

However, there is still one minor downside with this approach, in comparison with a "true step-less" slider (`step: 0` + some way to get labels to it): The slider still snaps to the steps, which is unnecessary, as I'm actually processing a float value. I can workaround that by adding more steps (e.g. 1000 instead of 100), correcting the `interpretLabel` function and scaling the value correctly, so there is just no visiable snapping an any screen size.

And with `autoAdjustLabels: true`, the labels are even hidden responsively:
https://jsfiddle.net/9a3fbp4m/2/

So, with these workarounds in place, the slider looks and feels as expected, although a "true step-less" slider with labels would be nicer, of course. ;)

**Comment by lubber-de** [comment]
Fixed by #1687
