### ISSUE TITLE
[Progress] is stuck when total is not 100

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#1689]
## Testcase
https://jsfiddle.net/1rgLy39e/2/

## Screenshot (when possible)
![progress_stuck](https://user-images.githubusercontent.com/1622751/94691540-b7fca200-0331-11eb-840d-53513e4a6fae.gif)

Same problem with sample on example :  https://fomantic-ui.com/modules/progress.html#frequently-updated-progress
![progress_stuck_2](https://user-images.githubusercontent.com/1622751/94691850-1f1a5680-0332-11eb-8f0b-4df0b9ab1e3b.gif)

## Version
2.8.7

**Comment by lubber-de** [comment]
Confirmed... :eyes: i'll fix this tonight

**Comment by lubber-de** [comment]
Fixed by #1690
