### ISSUE TITLE
[dropdown] the dropdown made by a 'select' tag isn't shown as the fomantic website shows it

### ISSUE THREAD

**Issue by asantech** [fomantic/Fomantic-UI#1692]
# Bug Report
 the dropdown made by a 'select' tag isn't shown as the fomantic website shows it

## Steps to reproduce
1. add the fomatic-ui CSS files to your project 
2. copy the select dropdown's matching HTML from the fomantic-ui website and paste it in your file
3. run the code

## Expected result
the dropdown is shown as in the fomantic-ui website

## Actual result
the dropdown is shown as a pure javascript selection dropdown

## Testcase
https://jsfiddle.net/tpv3syoL/1/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/50336897/94990588-1623c200-058a-11eb-8b81-60972d2e3fcc.png)

## Version
2.8 (latest version)

**Comment by ko2in** [comment]
Using with `select` tag requires to invoke `dropdown` module. It cannot generate the dropdown rendering with DIV via CSS. A simple CSS dropdown can only build using DIV and the other HTML elements.

**Comment by ko2in** [comment]
Closed. Already explained the usage with `select` tag. If you've further issue, feel free to reopen.
