### ISSUE TITLE
"center aligned icon header" miss aligned using "content"

### ISSUE THREAD

**Issue by davekc** [fomantic/Fomantic-UI#1708]
# Bug Report
From v2.7.5 to v2.8.7 something got broken with "center aligned icon header" that miss aligned the "content" class.

## Steps to reproduce
1. Please see the JSFiddle
2. Removing the &lt;div class="content"&gt; work around the issue
3. Re-adding CSS .ui.icon.header .content { display: block; } works too

Seems like the CSS order changed from 2.7 to 2.8

## Expected result
Center aligned content (using a "content" class)

## Actual result
Left aligned content

## Testcase
https://jsfiddle.net/sLnaf9yg/

## Version
2.8.7

**Comment by lubber-de** [comment]
Thanks for the report. I fixed the specificity by #1710 and it was caused by #1593
