### ISSUE TITLE
[Dropdown] Search In-Menu positioning does not work correctly

### ISSUE THREAD

**Issue by jjylha** [fomantic/Fomantic-UI#1711]
1. Go to Search In-menu example in Docs: https://fomantic-ui.com/modules/dropdown.html#search-in-menu
2. Scoll the window so that the bottom of the window is close to "Filter posts" button. About 100-200px below is the sweet spot.
3. Open menu.

Result: 
Menu goes out of screen. If the dropdown is at the bottom of the page it can even be unaccessible.

Expected result: 
Menu should open above the field if it would go outside of view from the bottom.

![search-in-menu](https://user-images.githubusercontent.com/7629018/96242460-271dfb80-0fac-11eb-8a55-492cea0b4d01.jpg)

**Comment by ko2in** [comment]
Fixed and [PR](https://github.com/fomantic/Fomantic-UI/pull/1779) submitted.
