### ISSUE TITLE
[dropdown with remote content] callback of 'show' behavior doesn't fires.

### ISSUE THREAD

**Issue by tonynamy** [fomantic/Fomantic-UI#1712]
# Bug Report
There is callback parameter for 'show' behavior of dropdown.
But the callback never fires when I run the behavior for the dropdown with remote content.

## Steps to reproduce
1. Create dropdown.
2. Initialize the dropdown with remote content setting(api setting).
3. Run .dropdown('show', callback);
4. View console output.

## Expected result
callback function should be triggered.

## Actual result
callback function never be triggered.

## Testcase

Expected Result(It works well in case of dropdown without remote content) -
https://jsfiddle.net/fep02ctm/5/

Broken Result(It doesn't work in case of dropdown with remote content) -
https://jsfiddle.net/fep02ctm/6/

## Screenshot (if possible)

Expected Result(It works well in case of dropdown without remote content) -
![2](https://user-images.githubusercontent.com/36332025/96259002-e51aa700-0ff7-11eb-82aa-def1ec315903.gif)

Broken Result(It doesn't work in case of dropdown with remote content) -
![1](https://user-images.githubusercontent.com/36332025/96258976-d7fdb800-0ff7-11eb-9d50-bca7c9df6099.gif)

## Version

2.8.7 (Latest)
Tested under WIndows 10 with Chromium 86.0.622.38.

**Comment by lubber-de** [comment]
Fixed by #1714 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/1fks5rwt/

**Comment by tonynamy** [comment]
Thanks!

**Comment by tonynamy** [comment]
@lubber-de 
Hi :)
I applied your fixed js file, but it seems to make unexpected result. Could you check it this too?

https://jsfiddle.net/98eq30vf/7/

![Video_2020-10-19_145913](https://user-images.githubusercontent.com/36332025/96407203-cd236d00-121b-11eb-9474-9b29f19c2dc2.gif)

Although the value is selected, but it remains in value list.

Some weird thing is if you swap the position of `$('.container').append(student_dropdown);` and `$(student_dropdown).dropdown('show');` it works well.

**Comment by lubber-de** [comment]
@tonynamy This seems to be a general (and separate) issue, because the dropdown will retrieve the whole items list every time again when you open the dropdown (or call "show"). So, even if you do not provide your callback, but open the dropdown manually, then select "African Wild Dog" (it will vanish from the list), close the dropdown and reopen it again: The selected item is  shown in the items list again
Please open another issue for this, because it needs move investigation an is independent of the callback support which this issue here describes (and has been fixed)

**Comment by lubber-de** [comment]
@tonynamy The described issue (reloaded list returns the item although selected) seems to be fixed with #1414 🤔

**Comment by tonynamy** [comment]
Ok, I've found my mistake. I just forgot to add input tag inside dropdown div.
Thanks for your help.

Next time, I'll use select tag to reduce my mistake 😂😂

**Comment by lubber-de** [comment]
> Just in my opinion, providing error log may help developers who are suffering because of the same reason.

You can always turn on detailed console debugging for all JS modules by 
```
$('.ui.dropdown').dropdown({
 debug: true
})
```
