### ISSUE TITLE
LESS only Fomantic package is using jquery?

### ISSUE THREAD

**Issue by Ray-B** [fomantic/Fomantic-UI#1717]
# Bug Report

Hi, we are using the Fomantic-UI-LESS package to pull down enhancements into Semantic-UI React, and I noticed that jquery is being pulled in as a dependency.

```
    "fomantic-ui-less": {
      "version": "2.8.7",
      "resolved": "https://registry.npmjs.org/fomantic-ui-less/-/fomantic-ui-less-2.8.7.tgz",
      "integrity": "sha512-qCZmm/eG3cvJOfJmyFYkM+iP4BlBX+hflwQ3mxNJg7QnClYao5N1ff6XrOQVWV8at10etYmSoJ7Q70YZRBKPkQ==",
      "dev": true,
      "requires": {
        "jquery": "^3.4.0"
      }
    },
```

I realize that the _complete_ fomantic-ui library obviously needs jquery for now, but I was surprised to discover jquery when all we want is the LESS. 

Is this required? Workaround? Or something we can contribute a PR for?

Thanks!

## Steps to reproduce
1.  Add fomantic-ui-less
2. node_modules will now contain jquery
3.

## Expected result
I would have expected if all I am using is the eventually compiled/transpiled LESS, that jquery would not be needed

## Actual result
JQuery is being added, and adding substantial cruft to our release package.

## Testcase
N/A

## Screenshot (if possible)
N/A

## Version
2.8.7

**Comment by lubber-de** [comment]
The LESS Repo also includes the related js modules, to have a complete working fomantic package. That's why.
Of course don't need those js modules (and jquery) when using SUI React.

@hammy2899 What do you think? If we remove the jquery dependency form the package.json, shouldn't we remove the js modules inside the LESS package as well then? We have a similar situation in the CSS repo. 🤔

**Comment by Ray-B** [comment]
I'm not opposed to issuing a PR for this, FWIW

**Comment by TheJltres** [comment]
SUI React also loads jQuery using `semantic-css` (https://github.com/Semantic-Org/Semantic-UI-React/blob/master/package.json#L170).

This change, would leave all (CSS ?) LESS users without JS modules, that is a big change.
This can be seen also from JS modules perspective, there is no way of installing fomantic with only JS.

How would you use LESS and JS? You can use CSS and JS from Fomantic repo, but there would not be any fomantic less repo with JS.
What I think would be correct, is move all CSS/LESS JS modules, to a new repo 😪... Like this you could have CSS/LESS with or without JS

**Comment by lubber-de** [comment]
@Ray-B How are you packaging your final builds? Having another folder for jquery inside node_module isn't really an issue at install time, but what counts is the final package you use for your project. So maybe you can configure your packaging tool to exclude the "node_modules/jquery" folder?

**Comment by TheJltres** [comment]
And you can also fork the repository and delete that dependecy or all JS modules.
