### ISSUE TITLE
[multiple search selection dropdown with remote content] dropdown menu doesn't appear in mobile

### ISSUE THREAD

**Issue by tonynamy** [fomantic/Fomantic-UI#1718]
# Bug Report
Dropdown menu doesn't appear in mobile.

## Steps to reproduce
Please refer to JS fiddle & screenshot

## Expected result
Dropdown menu should apear.

## Actual result
Dropdown menu doesn't appear.

## Testcase
https://jsfiddle.net/qzunv2dj/4/

## Screenshot (if possible)

![RPReplay_Final1603170207](https://user-images.githubusercontent.com/36332025/96542571-5353b800-12dd-11eb-8506-7a2acf3ee6af.gif)

## Version

2.8.7
Tested under iPad OS 14.0.1 with Safari browser.

**Comment by tonynamy** [comment]
+ Same result also when tested with chrome developer tools' device toolbar.

**Comment by lubber-de** [comment]
Fixed by #1725 
See your adjusted jsfiddle here
https://jsfiddle.net/lubber/t6az41op/2/
or here for direct test on mobile devices 
https://fomantic-ui.com/jsfiddle/#!lubber/t6az41op/2/

**Comment by tonynamy** [comment]
@lubber-de Thanks!
