### ISSUE TITLE
[SUI] Merge 2.4.1

### ISSUE THREAD

**Issue by ColinFrick** [fomantic/Fomantic-UI#173]
# Feature Request

## Description
Merge Semantic UI 2.4.1 release

I propose only to merge following changes:
- **Embed** - Embed will now correctly remove DOM metadata on destroy Semantic-Org/Semantic-UI@620cb3fda37e06439d526667b72ae85e162fa76f
- **Grid** - Fix issue with very relaxed vertically divided grid having wrong margins on dividers https://github.com/Semantic-Org/Semantic-UI/blob/1724b3eff4d33ac90592ec85685ea6ef97022371/src/definitions/collections/grid.less#L1118-L1119

Will be fixed with #172:
**Dropdown** - clearable dropdown now works with dropdown that arent on:click, like hover or manual triggers. 

Already fixed with #135:
**Modal** - Fixed fullscreen modal having incorrect left offset with flex modals

Build system update to gulp 4 is almost finished. Additionally we have less 3.5.0 support since #97

**Comment by lubber-de** [comment]
Your fixes for modal and clearable are a bit different to Jack's ones from sui. Have you found out his fixes are still not working?

**Comment by ColinFrick** [comment]
@lubber-de We have a different implementation for clearable dropdowns.
Additionally as our code base diverges more and more, we can't merge just anything from SUI anymore, even if Jack's fix works in SUI.

**Comment by hammy2899** [comment]
Merged.
