### ISSUE TITLE
[calendar] selectAdjacentDays doesn't indicate active date

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#1734]
# Bug Report
When you click a date on a default calendar, that date becomes `.active`, changing color to indicate that it was selected. If you go forward a month, and then back, your selection is still `active`.

If you use `selectAdjacentDays: true`, and you click a date in the bottom row (beginning of next month), it will jump to that month, and your selection will be `active`. However if you then go back one month, you will see that date, but it will not be active.

## Steps to reproduce
1. Make a calendar with `selectAdjacentDays: true` 
2. Select a date in the last row (beginning of next month).
3. Nod in approval when your date is visibly active.
4. Go back one month to the original, prior month's view.
5. Get so confused that the date you just selected isn't active, that you accidentally spill coffee on your keyboard, causing an Archibald Tuttle / Buttle incident ala Brazil (1985).

## Expected result
Persistence of selected date.

## Actual result
Chaos, elevator music, hangnails, walking into walls.

## Testcase
https://jsfiddle.net/designosis/y2e1nLmq/

## Screenshot (if possible)
1.
![calendar_1](https://user-images.githubusercontent.com/146623/97738202-696b3080-1ab4-11eb-8f4f-121a5a554bf4.png)
2.
![calendar_2](https://user-images.githubusercontent.com/146623/97738340-961f4800-1ab4-11eb-8ff9-9310453c2986.png)
3.
![calendar_3](https://user-images.githubusercontent.com/146623/97738352-99b2cf00-1ab4-11eb-8a98-5b9bb546e7d3.png)

## Version
2.8.7

**Comment by lubber-de** [comment]
Fixed by #1735 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/c4s9dLm0/21/
