### ISSUE TITLE
[Slider] Add fireChange parameter to slider setting behaviors

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#1750]
# Feature Request
The **Calendar**'s `set date` behavior has the `fireChange` (default false) which toggles whether or not setting the date triggers its `onSelect` function. This is amazingly helpful:

![Screen Shot 2020-11-04 at 2 05 47 PM](https://user-images.githubusercontent.com/146623/98157159-e9273f80-1ea6-11eb-8338-25a1ab6cb2e0.png)

It would be wonderful if the **Slider** had this option as well, for both `set value` and `set rangeValue`. Currently, it has no such option, and the slider's `onMove` function fires when `set value` is called:

![Screen Shot 2020-11-04 at 2 05 55 PM](https://user-images.githubusercontent.com/146623/98157172-efb5b700-1ea6-11eb-8181-ce735dc85270.png)

I see an undocumented `setting.fireOnInit` in the js, but this defaults to false, so it must do something else?

**Comment by lubber-de** [comment]
`fireOnInit: true` will only work on instantiation time, so your feature request seems legit and shouldbe easy to implement

**Comment by lubber-de** [comment]
Implemented by #1751 😊
