### ISSUE TITLE
[Icons] Bordered icon together with a corner icon

### ISSUE THREAD

**Issue by Yrlish** [fomantic/Fomantic-UI#1753]
# Bug Report
I want to use a cornered icon, inside a bordered frame (bordered icon). I want to put an edit pen in the corner of a book, with a frame around it.

## Steps to reproduce
```html
<i class="bordered icons">
  <i class="book icon"></i>
  <i class="corner pen icon"></i>
</i>
```

## Expected result
How a bordered icon and a corner icon works, but together at the same time.

## Actual result
Corner icon as intended, without a border

## Testcase
https://jsfiddle.net/oz9hkube/5/

## Version
Am using Fomantic-UI 2.8.4, tested with 2.8.7 in the jsfiddle linked above with the same results.

**Comment by ko2in** [comment]
@Yrlish I don't think it's a bug. Border is only for individual icon, not for group as current implementation. Maybe, I'll submit PR for that or if you would like to contribute, feel free to submit your PR.

**Comment by Yrlish** [comment]
Yeah, calling it a bug may be a bit harsh. It's more like a missing feature.

**Comment by ko2in** [comment]
@Yrlish I've looked into the icon implementation and I couldn't see any reason to implement such feature. What you need is to use the square outline icon, the book and then top right corner pen icon.

See this fiddle (https://jsfiddle.net/ko2in/y5uvobwp/).

**Comment by Yrlish** [comment]
@ko2in I'm sorry, that wont work for me. I use these bordered icons as action buttons inside a table. They will look different, also the outline icons doesn't look as good.

https://jsfiddle.net/4afp061e/

**Comment by ko2in** [comment]
@Yrlish Can't you use the user and pen icon like the same as book (https://jsfiddle.net/ko2in/z86va2t7/)?

**Comment by Yrlish** [comment]
@ko2in I put together a PR with what I need.

**Comment by Yrlish** [comment]
@lubber-de I'm guessing this should be closed properly with your tagging routines, now that #1755 is done.

**Comment by lubber-de** [comment]
@Yrlish We are closing those issues once we create the related release, that's why we tag them with "next-release".
