### ISSUE TITLE
[Grouped icons][Menu] Padding between text and grouped icons is absent

### ISSUE THREAD

**Issue by Ikaer** [fomantic/Fomantic-UI#1765]
# Bug Report

## Steps to reproduce
1. Create a vertical menu 
2. Use grouped icons in front of some items
3. Use normal icon in front of some items for comparison

## Expected result
The padding between icons and text should be the same regardless its a grouped or normal icon.

## Actual result
No padding is applied to the grouped icons.

## Testcase
https://jsfiddle.net/fndmr6os

## Screenshot (if possible)
On first level:
![image](https://user-images.githubusercontent.com/7936075/99073659-9dffe180-25b6-11eb-839b-6bdda13cdc79.png)

On sub levels: 
![image](https://user-images.githubusercontent.com/7936075/99073679-a821e000-25b6-11eb-98e2-6f5f4b4cab8a.png)

## Version
2.7.8

## Related issues 
#936

**Comment by lubber-de** [comment]
Fixed by #1766 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/3qw8ck2o/2/
