### ISSUE TITLE
[install] compatibility npm7, pnpm, yarn, yarn2

### ISSUE THREAD

**Issue by jeffrson** [fomantic/Fomantic-UI#1767]
# Bug Report

Well, I wonder if fomantic-ui will become uninstallable. Currently, only npm6 can install it. All of the other usual package managers fail.

## Steps to reproduce

1. Create an empty folder, intialize package.json (npm init, yarn init)
2. npm i/pnpm i/yarn add fomantic-ui

## Expected result

Should install...

## Actual result

Failure to install.

## Version

2.8.7

There are issues regarding pnpm and yarn - closed or unanswered - is there anything done about it?

**Comment by devopg** [comment]
I have some problem with Fomantic-UI as CSS only with VUE 
$ npm install --save fomantic-ui-css
import 'fomantic-ui-css/semantic.min.css';   add to App.vue
After Run serve get error 

![image](https://user-images.githubusercontent.com/61819835/100737265-fb809480-33e4-11eb-8fb8-3fe34ec4e1d0.png)

**Comment by ko2in** [comment]
@devopg Is `semantic-ui-css` successfully installed in `node_modules` directory? Does Vue know to look `fomantic-ui-css` in `node_modules` directory when importing? I'm not Vue user, so I don't know how Vue handles the dependency when importing.

**Comment by devopg** [comment]
> @devopg Is `semantic-ui-css` successfully installed in `node_modules` directory? Does Vue know to look `fomantic-ui-css` in `node_modules` directory when importing? I'm not Vue user, so I don't know how Vue handles the dependency when importing.

yes 
![image](https://user-images.githubusercontent.com/61819835/100744586-1d7f1480-33ef-11eb-8ec2-67afec46144c.png)

**Comment by ko2in** [comment]
@devopg Then, you're posting irrelevant issue here. The original issue is about the failing of installing FUI with latest npm and yarn versions.

However, I've created a Vue [sandbox](https://codesandbox.io/s/fomantic-ui-css-qmuku) with FUI css package and it seems working fine. Do you install `post-css` in your project? Is your app working with your own imported CSS files?

**Comment by devopg** [comment]
i have clear vue project, i dont know why your sandbox work
I fix my project add full url with node_modules path:
@import '../node_modules/fomantic-ui-css/semantic.min.css';

but in app.vue i have other include librare from node_modules and they works example:
@import 'swiper/dist/css/swiper.css';

**Comment by ko2in** [comment]
@devopg Please create a discussion for your issue [here](https://github.com/fomantic/Fomantic-UI/discussions).

**Comment by lubber-de** [comment]
Should be fixed by #2272 and #2280
