### ISSUE TITLE
Fork Semantic-UI-React into this org and let people contribute

### ISSUE THREAD

**Issue by kevinresol** [fomantic/Fomantic-UI#1771]
As it is explicitly stated by the SUI-React maintainer that it won't support fomantic. So IMO fomantic as a community-supported org should just fork it and make it a starting point for people to contribute.

Also, FUI 3.0 is nowhere near completion I think we should just move forward with a forked SUI react for FUI 2.x.

**Comment by lubber-de** [comment]
AFAIK the SUI react people are working on a provider layer to support fomantic.
I am turning this issue into a discussions thread
