### ISSUE TITLE
[Dropdown] Clearing a multiple dropdown ignores preventChangeTrigger setting

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#1781]
# Bug Report

When using the behavior `$('#blah').dropdown('clear',true)` on a dropdown, it's supposed to not fire the dropdown's `onChange` function. However if the dropdown happens to be a multiple dropdown, the `onChange` is instead fired once for every selected option.

## Steps to reproduce
1. Make a multiple select dropdown
2. Init the dropdown, adding an `onChange` function with a console.log or whatever
3. Clear the dropdown with the "preventChangeTrigger" flag set to true (via `$('#blah').dropdown('clear',true)`)

## Expected result
The `onChange` should not be triggered.

## Actual result
The `onChange` is triggered once for every selected element, annihilating the world as we know it.

## Testcase
https://jsfiddle.net/designosis/ob4wLf6h/

## Screenshot
![Screen Shot 2020-11-25 at 1 54 51 PM](https://user-images.githubusercontent.com/146623/100270348-ed82cd80-2f25-11eb-9f05-e48d9ed2c7c7.png)

## Version
2.8.7

## Note
This is perhaps related to but not the same as https://github.com/fomantic/Fomantic-UI/issues/165

**Comment by lubber-de** [comment]
Fixed by #1782
