### ISSUE TITLE
[Button] Margins are too large when button is multiple with a placeholder.

### ISSUE THREAD

**Issue by Ikaer** [fomantic/Fomantic-UI#1783]
# Bug Report
When using a dropdown with multiple selection, the margin is a little too big. It's not when removing the multiple part.

## Steps to reproduce

cf. jsfiddle

## Expected result
button shouldn't be that large in multiple like the no multiple dropdown

## Actual result
text is wrapped

## Testcase
This is the test case for latest version of fomantic (2.8.7 at the time) https://jsfiddle.net/jLn0wkv9/1/

## Screenshot (if possible)
2.8.7 (multiple is on right)
![image](https://user-images.githubusercontent.com/7936075/100896971-7f0eb400-34bf-11eb-8ede-deda515f2d32.png)

## Version

2.8.7

Problem related:
https://github.com/fomantic/Fomantic-UI/pull/1571

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/1784
