### ISSUE TITLE
[Button] inverted animated fade button is not inverted when animating

### ISSUE THREAD

**Issue by guidouil** [fomantic/Fomantic-UI#1786]
# Bug Report
When adding the class inverted to an animated button, the shown button is inverted as expected but when animating by mouse over the button isn't inverted.

## Steps to reproduce
```
<div class="ui inverted animated fade button">
  <div class="visible content">Sign-up for a Pro account</div>
  <div class="hidden content">$12.99 a month</div>
</div>
```

## Expected result
The button should remain inverted when animating.

## Actual result
The button isn't inverted on mouse over.

## Version
2.8.7

**Comment by lubber-de** [comment]
The `inverted` variants are supposed to be used on a dark background. Otherwise add a color name
See
https://jsfiddle.net/lubber/qdvo8uyb/8/

If you still think this is a bug, please adjust the given jsfiddle accordingly to explain what should be changed. Thanks 🙂

**Comment by guidouil** [comment]
Sorry I did not realize it was also the case for normal inverted button ^_^
It's not a bug
