### ISSUE TITLE
Dropdown not displaying the `selected` element

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#1787]
You can check this bug here:

https://jsfiddle.net/3uqf0g8a/

You can see I have an `.item` with `.selected` so I assume that when I load the link above, the script would fill the element `.text` with the selected value. However that's not the case, the element `.text` remains empty.

Also, even using the `.selected`, I can see the selected value using `$('.ui.dropdown').dropdown("get value")` except if I explicitly click on an `.item`.

This bug also happens when adding the class `selection` on `.ui.dropdown`.

I had really a hard time trying to find a way to make the `selected` element load by default, but I cant find any example in the docs showing that or any information how I should do that.

And finally, if you allow me, can you please tell me if it's possible to align the icon (print below) on the left and the arrow `pointing` to the right?

![image](https://user-images.githubusercontent.com/8988923/101528365-fcc63a00-396d-11eb-93e4-9f47d01c6dd2.png)

![image](https://user-images.githubusercontent.com/8988923/101528597-4a42a700-396e-11eb-93b9-22485b754510.png)

**Comment by lubber-de** [comment]
### show selected item by default
The `selected` class only puts another background into the list (to indicate its selection when the dropdown list is openeed). The css class alone cannot change the DOM node for the selected text 😉 

However, to start the dropdown with a previous selected value use the `set selected` behavior instead
```javascript
$('.ui.dropdown').dropdown('set selected','Windows-1252');
```
See https://jsfiddle.net/lubber/46q3gy2s/4/

If you still only want to set the class without knowing the value, you could do this by fetching the date value to the `set selected` behavior
```javascript
var selectedItem = $('.ui.dropdown .item.selected').attr('data-value');
$('.ui.dropdown').dropdown('set selected',selectedItem);
```
See https://jsfiddle.net/lubber/46q3gy2s/8/ 

### display popup/tooltip arrow to the right
To show the popups arrow icon to the right (please ask this in a separate issue / discussions thread the next time):

Sure, it's possible (assuming there is enough space to the left to display the tooltip

use `position: 'bottom right'` either as JS or data attribute
![image](https://user-images.githubusercontent.com/18379884/101531222-3d847a00-3993-11eb-99f8-a68ceb0bddd2.png)


See https://jsfiddle.net/lubber/46q3gy2s/14/

**Comment by batata004** [comment]
Thank you so much my friend, it all worked perfectly as you said! It all became very clear :)
