### ISSUE TITLE
[dropdown] Dropdown menu not correctly rendered when another dropdown enables allowAdditions and additional texts is set

### ISSUE THREAD

**Issue by wyysoft** [fomantic/Fomantic-UI#1802]
# Bug Report
When two dropdowns are vertically placed, and the second dropdown set allowAdditions enabled and use customized text, the second dropdown's input box will show above the first dropdown's menu.

## Steps to reproduce
1. Goto: https://fomantic-ui.com/modules/dropdown.html#search-selection
2. $('.ui.dropdown').dropdown({allowAdditions: true})
3. Type some text in second (shorter) dropdown.
4. Click to show the first (longer fluid) dropdown.

## Expected result
The 1st dropdown's menu shows without any error.

## Actual result
The 1st dropdown's menu is corrupted by 2nd dropdown's input box.

## Testcase
https://jsfiddle.net/wyysoft/qzdbc54t/8/

## Version
2.8.7

**Comment by lubber-de** [comment]
Identified the issue. Similiar reason as in #1455 . The transition module does not remove an existing `visible` class when hiding the menu in certain situations. Will do more investigation

**Comment by lubber-de** [comment]
Fixed by #2474. It wasnt the transition module but a bug in dropdown which reshows an (empty/filtered) menu, thus again adding the visible class
