### ISSUE TITLE
Header with icon - center alignment issue

### ISSUE THREAD

**Issue by aanupam23** [fomantic/Fomantic-UI#1817]
# Bug Report
I tried to use header with icon but it doesn't get center but header without icon has not problem with center. Is it possible to do this with existing Fomantic-UI classes?

## Steps to reproduce
Try this code
```
<h1 class="ui center aligned header">Centered header</h1>
<h2 class="ui center aligned header">
  <i class="settings icon"></i>
  <div class="content">
    Not Centered
    <div class="sub header">Not centered</div>
  </div>
</h2>
```

## Version

2.8

**Comment by lubber-de** [comment]
If you don't need the subheader, do this

```css
<h1 class="ui center aligned header">Centered header</h1>
<h2 class="ui center aligned header">
  <i class="settings icon"></i>
    Centered
</h2>
```

For the subheader variant i will prepare a PR later, there are some CSS adjustments needed

**Comment by aanupam23** [comment]
@lubber-de This works 👍
