### ISSUE TITLE
[Icon] Bad corner position when using some icons in group

### ISSUE THREAD

**Issue by prudho** [fomantic/Fomantic-UI#182]
# Bug Report

## Steps to reproduce
Just create a group icon with a corner icon that contain a direction (eg. `right arrow`...)

## Expected result
For a `bottom left corner right arrow icon`
[![27b2d65bad48b312b17d3820f6ae06b3.png](http://tof.cx/images/2018/10/17/27b2d65bad48b312b17d3820f6ae06b3.png)](http://tof.cx/image/NLDl0)

## Actual result
[![c0738744c365befeb43cb160f058d65c.png](http://tof.cx/images/2018/10/17/c0738744c365befeb43cb160f058d65c.png)](http://tof.cx/image/NLJeZ)

## Testcase
https://jsfiddle.net/qhk32v79/

## Version
2.6.2

**Comment by hammy2899** [comment]
Fixed in 2.6.3
