### ISSUE TITLE
callback while hovering through dropdown items 

### ISSUE THREAD

**Issue by Berkdan** [fomantic/Fomantic-UI#1839]
Hi,
Is there any callback function while hovering through dropdown items? if not, is it possible to implement it?

Thanks

**Comment by lubber-de** [comment]
It's not built-in but you can implement is easily on your own
See https://jsfiddle.net/lubber/9ez0ofm3/5/

```javascript
$('.ui.dropdown').dropdown({});
$('.ui.dropdown .item ').hover(function(){
	console.log('You hovered over '+$(this).html())
})
```

**Comment by Berkdan** [comment]
Brilliant!
Thank you, that is what exactly i was looking for.
