### ISSUE TITLE
Regular Expression Denial of Service

### ISSUE THREAD

**Issue by FutureInventor** [fomantic/Fomantic-UI#1841]
Hello,

Recently I've started yo use fomantic-ui in my project (and it's fabulous) but i have one problem (and therefore the question) with dependencies. Package url-regex is no longer safe to use (bc of regular expression denial of service possibly attack https://www.npmjs.com/advisories/1550 ). I've done my research and find out that there's another package like url-regex but the safe one: url-regex-safe. Do you plan to use it in the future? Or resolve the problem in any other way?

Best, Karolina

**Comment by lubber-de** [comment]
Duplicate of #1646 
The main problem ist that regex-safe is a sub dependency. I don't think we should maintain other packages ourselves (unless there are other volunteers). So, i would rather implement the small package code into the core directly. Yes, that's not the idea of having dependencies and avoid redundant code and external packages, but dependency has the drawback of being...well..dependent of the maintenance of others...

Let's continue discussion at the other issue. I am thererefor closing this
