### ISSUE TITLE
[calendar] month cannot be changes using arrows using start/end calendars on endCalendar after selecting a future month on startCalendar

### ISSUE THREAD

**Issue by mgrulich** [fomantic/Fomantic-UI#1851]
# Bug Report
Many times its not possible to change to month using the arrow keys of the endCalendar after selecting a date within the startCalendar. After closing end reopening the selection window of the endCalendar its possible again.

## Steps to reproduce
Today is: 2021-01-21
I can reproduce it on this page: https://fomantic-ui.com/modules/calendar.html

1. I'm refreshing the Page using [Ctrl] + [F5]
2. I'm selecting a date in the startCalendar with a date on a future month, like 2021-03-30.
3. This will auto open the selection window from the endCalendar.
4. Now its many times not possible to change the month using the arrows on the top.

## Expected result
Pressing the arrows should change the current displayed month

## Actual result
Nothing is happen, no change of month. (Also no errors in console)

## Testcase
https://jsfiddle.net/yt1n06rb/1/

## Screenshot (if possible)
![fomantic-ui_calendar_issue](https://user-images.githubusercontent.com/781036/105416391-580c6d00-5c3a-11eb-8a1a-2eb9fe61949b.png)

## Version
2.8.7

**Comment by lubber-de** [comment]
Fixed by #2000
See your adjusted jsfiddle here https://jsfiddle.net/yt1n06rb/1/
