### ISSUE TITLE
[Card] Width of attached button exceeds width of card.

### ISSUE THREAD

**Issue by yumitsu** [fomantic/Fomantic-UI#1865]
# Bug Report

## Steps to reproduce
1. Place a card element.
2. Attach a button to the bottom of card.
3. Observe.

## Expected result
Attached button should have exact same width as card it was attached to.

## Actual result
Attached button width exceeds card width.

## Testcase
https://fomantic-ui.com/views/card.html#buttons

## Screenshot (when possible)
![Screen Shot 2021-02-06 at 22 50 39](https://user-images.githubusercontent.com/108335/107128332-d40ae400-68cd-11eb-919b-d89e9f70423b.png)
![Screen Shot 2021-02-06 at 22 50 47](https://user-images.githubusercontent.com/108335/107128331-d2d9b700-68cd-11eb-84ed-b50464d50f12.png)

## Version
2.8.6 with Google Chrome on OSX.

**Comment by lubber-de** [comment]
That's a docs issue. `attached` is not supposed to be used here.
Fixed by https://github.com/fomantic/Fomantic-UI-Docs/pull/342
