### ISSUE TITLE
Fix column

### ISSUE THREAD

**Issue by eleimt** [fomantic/Fomantic-UI#1874]
Hello.
Thanks for this project. I use in my ideas.

Are there any plans to add fixed columns?

**Comment by lubber-de** [comment]
No plans, but maybe someone will provide a proper PR which implements that feature...

**Comment by lubber-de** [comment]
I suggest to use https://datatables.net/  which is a stable and mature table framework

They offer fixed tables here
https://datatables.net/extensions/fixedcolumns/examples/initialisation/two_columns

And they also support for Semantic / Fomantic UI
https://datatables.net/examples/styling/semanticui.html

**Comment by GammaGames** [comment]
I've used DataTables a lot, definitely recommend. Tons of features and very customizable.
