### ISSUE TITLE
Change autocomplete="off" to autocomplete="stop" in Dropdown

### ISSUE THREAD

**Issue by yehudahkay** [fomantic/Fomantic-UI#1880]
In chrome, the dropdown gets hidden by an autocomplete menu. It is possible to fix this by changing .prop('autocomplete', 'off') to .prop('autocomplete', 'stop') (or a different random string) in the dropdown code.

In the meantime in my own code I've just added this.modal.find('input.search').prop('autocomplete', 'stop');

**Comment by lubber-de** [comment]
Can you please adjust the following jsfiddle. I am not able to reproduce the described behavior.
https://jsfiddle.net/lubber/a3nfoexp/4/

If the jsfiddle is fine, then please describe the exakt steps how to reproduce.

The code you are mentioning is bound to the dropdowns search input, if the input is not already available in the dom.
And the purpose of `autocomplete='off` is exactly to prevent showing the autocomplete. Giving it any other value makes it obsolete.

**Comment by yehudahkay** [comment]
I can reproduce with this fiddle, although I imagine you need to have saved autocomplete data in chrome.

https://jsfiddle.net/hw6eLymj/

![image](https://user-images.githubusercontent.com/9964988/107874514-d4554180-6ec2-11eb-9a2f-4d4738a427e9.png)

**Comment by lubber-de** [comment]
Thanks, i fixed it by #1887 now
