### ISSUE TITLE
[sidebar] panel layout alternative to menu

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#1885]
At present, the sidebar only really seems to support `.menu` - what I'm proposing is to add support for essentially a pane/panel that is essentially very similar to a modal (in terms of internal layout), but obviously in the sidebar

As a pane/panel, I think we should support the following:
- header (with optional close icon which could be used instead of clicking outside the sidebar to close)
- content (with optional scrolling content)
- actions (fixed to bottom with scrolling content; possibly with similar `onApprove` and `OnDeny` callbacks?)

May also wish to consider adding a way of using max width and or max height for if say a mobile view (depending on the direction the menu pops out) - possibly could have `fullscreenMobile` as an option

Could also be good to specify the direction within JavaScript as an alternative - with mobile potentially having a different opening direction to any other screen size (eg. non-mobile opens right, but mobile opens from bottom)

Attempt on adding the CSS to support a panel, mostly extracted from modal - possibly may need to tweak padding:
https://jsfiddle.net/p7z16ac4/

**Comment by lubber-de** [comment]
This seems to be the same feature request as the `flyout` component ? #121

**Comment by jamessampford** [comment]
Yes, this seems to be similar using a different name - will we need to wait until v3 before anything new is added in?

**Comment by prudho** [comment]
Thank @jamessampford for CSS sample, please see #2004 for further discussion.

**Comment by jamessampford** [comment]
@prudho nice one!

**Comment by prudho** [comment]
@fomantic/maintainers should we close this ?

**Comment by lubber-de** [comment]
Yes, i think everything is covered/possible using the new flyout component
