### ISSUE TITLE
Input search onSelect not working prevent default action

### ISSUE THREAD

**Issue by adnan358** [fomantic/Fomantic-UI#1895]
# Bug Report

## Steps to reproduce
1. İnclude js and css
2. Set js code
3. Type something
4. Click result

## Expected result
When click element then prevent default action 

## Actual result
The default action continued to work 

## Testcase
http://jsfiddle.net/b17ys2pt/2/

## Version
2.8.4 and up

**Comment by lubber-de** [comment]
Fixed by #1896 
See your adjusted jsfiddle here http://jsfiddle.net/lubber/9z4j5wqo/8

**Comment by adnan358** [comment]
Thanks for everything!

I want to ask questions. How can ı fix this bug in my project? Im using fomantic-ui-sass with my rails project.

@lubber-de

**Comment by lubber-de** [comment]
until this PR is merged and the SASS maintainer creates a new release afterwards, you can only adopt the changes from this PR manually in your local instance

**Comment by lubber-de** [comment]
What i did in the jsfiddle is overriding the semantic.js by the change via CDN
https://cdn.jsdelivr.net/gh/lubber-de/fomantic-ui@b7e9fb076551044a211d8e36ec884daa4fa598d2/src/definitions/modules/search.js
