### ISSUE TITLE
[Image] Img not showing on IE11

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#1900]
# Screenshot
As you can see it works on Chrome but not IE11.
![bug](https://user-images.githubusercontent.com/28552977/109313843-45bfb900-780e-11eb-981f-ceac40e75647.PNG)

# Code
```html
<div>
    <img class="ui medium image" src="no-user.jpg">
</div>
```

# Specs
```txt
Windows 7 | JQuery 3.5.1 | Fomantic UI - 2.8.6
```

Don't think I did something wrong there....

Thanks,

**Comment by lubber-de** [comment]
Sorry, i cannot reproduce this locally with IE11
What happens, when you remove the Fomantic-UI classes? Is the image being displayed then? (i believe, it's also not displayed in your IE11)
Where is "no-user.jpg" stored? The links assumes, its in the same folder than the website.
Or maybe the image is (for IE) corrupt?

**Comment by KiddoV** [comment]
All clear!
I tried a different image (.PNG) and it works. I guess IE11 somehow doesn't like .JPEG format.
Thank you!
