### ISSUE TITLE
[Dropdown] - Setting showOnFocus to false will prevent dropdown to open on click.

### ISSUE THREAD

**Issue by ibelar** [fomantic/Fomantic-UI#191]
# Bug Report

## Steps to reproduce
1. Create dropdown input
2. Set option 'showOnFocus' to false

## Expected result
Clicking the dropdown arrow icon should open dropdown.

## Actual result
Dropdown is not opening.

## Testcase
https://jsfiddle.net/ibelar/eokn6yv8/

## Version
2.6.2

**Comment by lubber-de** [comment]
Fixed in current release https://github.com/fomantic/Fomantic-UI/tree/2.6.4
