### ISSUE TITLE
[Flag] Missing flags for countries BQ, CW, SX, MF

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#1913]
# Bug Report

The following countries in the Caribbean:

BES Islands (BQ), Curaçao (CW), Sint Maarten (SX) and Saint Martin (MF)

are missing thier flags

## Steps to reproduce

Open the page [fomantic-ui.com/elements/flag.html](https://fomantic-ui.com/elements/flag.html): there are no flags for the country codes above.

## Expected result
Bq, cw, sx and mf have their flags.

## Actual result
Bq, cw, sx and mf don't have any flag.

## Testcase
https://jsfiddle.net/x0hnaL1g/

## Screenshot (if possible)
None provided.

## Version
2.8.7

**Comment by lubber-de** [comment]
We have all missing flags as part of the emoji component 
https://fomantic-ui.com/elements/emoji.html

For version 2.9 the sprite flags are going to be replaced by the same SVG icons, so every missing country code flag will be supported while the syntax stays backward compatible
#1190

See your missing flags here https://jsfiddle.net/lubber/nyapwr9L/11/

**Comment by donaggio** [comment]
Oh, thank you! Somehow I missed that! I'm closing this issue then.
