### ISSUE TITLE
[calendar] Disablig Days of Week disables random Months.

### ISSUE THREAD

**Issue by MrMarci666** [fomantic/Fomantic-UI#1927]
# Bug Report
If you disable specific Days of Week it automatically disables random Months.

## Steps to reproduce

1. Go to https://fomantic-ui.com/modules/calendar.html#days-of-week
2. Click into the input field, calendar pops out.
3. Click on "March 2021" in the headline.
4. Now you can see that there are disabled Months.

## Expected result
I expect, that disabling days won't disable months.

## Actual result
Disabling days disables months.

## Testcase
https://fomantic-ui.com/modules/calendar.html#days-of-week

## Screenshot (if possible)
<img width="509" alt="Screen Shot 2021-03-25 at 14 53 44" src="https://user-images.githubusercontent.com/40604602/112484076-e952a980-8d79-11eb-82e6-7958be604f4e.png">
<img width="674" alt="Screen Shot 2021-03-25 at 14 54 08" src="https://user-images.githubusercontent.com/40604602/112484134-f5d70200-8d79-11eb-8fc8-72bbe4538cd5.png">

## Version
2.8.7

**Comment by GammaGames** [comment]
It also disables certain years 🤔️

![image](https://user-images.githubusercontent.com/7832163/112502910-1a1de900-8d50-11eb-8ba7-fc0dee3c91da.png)

**Comment by MrMarci666** [comment]
> It also disables certain years 🤔️
> 
> ![image](https://user-images.githubusercontent.com/7832163/112502910-1a1de900-8d50-11eb-8ba7-fc0dee3c91da.png)

Yes, true.

**Comment by lubber-de** [comment]
Fixed by #1928
