### ISSUE TITLE
[Input] help/information icon with popup

### ISSUE THREAD

**Issue by stevekatsaras** [fomantic/Fomantic-UI#1940]
I would like to submit a feature request regarding the use of helper icons next to form fields - that a user can easily hover or click and be presented with information about the purpose of the field.

**Comment by lubber-de** [comment]
This is possible using current FUI elements.
See https://jsfiddle.net/lubber/27p6wxj4/28/

![image](https://user-images.githubusercontent.com/18379884/113481924-8f01c900-949c-11eb-9b40-bf655b65bdc0.png)

**Comment by lubber-de** [comment]
Closing as it is already possible
