### ISSUE TITLE
form with onkeyup calling function twice

### ISSUE THREAD

**Issue by ivangomes** [fomantic/Fomantic-UI#1942]
I'm using onkeyup to call a random function.

See example:

  <form class="ui form" name="sampleform">
          <input type="text" onkeyup="samplefunction(this)" name="demo">
</form>

<script>
 If I initialize my form 
$('form[name="sampleform"]').form();

The sample function will be called twice after onkeyup
function samplefunction(e) {
    console.log(e.value);
}
</script>

if I remove $('form[name="sampleform"]').form(); the onkeyup will call the samplefunction just one time.

Please see the example below.

https://jsfiddle.net/ivangomes/1395jucs/9/

**Comment by lubber-de** [comment]
Fixed by #1957 
Sedd your adjusted jsfiddle here https://jsfiddle.net/lubber/p51nx39y/1/
