### ISSUE TITLE
[Search] Uncaught TypeError: Cannot read property 'top' of undefined when ".message" div shows

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#1964]
# Bug Report
Try a local search or API search on the search bar. Make the "No Results" div display then hit the arrow down button, this <Uncaught TypeError: Cannot read property 'top' of undefined> error will appear.

## Expected result
Should it be doing nothing when we hit the arrow down button? Because no results found.

## Testcase
Try on any Fomantic Search Bar.

## Screenshot (if possible)
![issue-1](https://user-images.githubusercontent.com/28552977/118378360-ee252400-b598-11eb-9350-e1ca2bc9fc6b.PNG)
"Hit the arrow down key now. ERROR will be shown!"
![issue-2](https://user-images.githubusercontent.com/28552977/118378361-f1201480-b598-11eb-8f0c-c86e3c3d2c26.PNG)
![issue-3](https://user-images.githubusercontent.com/28552977/118378362-f2514180-b598-11eb-87d4-152753a83da6.PNG)

## Version
JQuery - 3.5.1
FUI - 2.8.6

**Comment by lubber-de** [comment]
Fixed by #1965

**Comment by KiddoV** [comment]
> Fixed by #1965

Thank you!
