### ISSUE TITLE
install problems

### ISSUE THREAD

**Issue by SamarashEugene** [fomantic/Fomantic-UI#1967]
1. I can't try Fomantic-UI, because i always getting this problem that is given below on screenshot
2. What can I do?
3. I try to use this in Angular

![image](https://user-images.githubusercontent.com/80860836/118624175-96253200-b7d1-11eb-9482-b5739c5d3d7e.png)

**Comment by lubber-de** [comment]
From the screenshot you are still trying to install the original semantic-UI 2.4.2 instead of fomantic.
I also guess, you have gulp 4 installed, which does not work with semantic (but fomantic!)

Try the fomantic-ui package instead and remove semantic-ui beforehand

```terminal
npm uninstall semantic-ui
npm install --ignore-scripts fomantic-ui@nightly
npx gulp install
npx gulp build
```
