### ISSUE TITLE
Disabled rating on a card is still partly interactive

### ISSUE THREAD

**Issue by Julien-Schneider** [fomantic/Fomantic-UI#1972]
# Bug Report
Using a disabled rating module on a card still triggers cursor and color change on hover.

## Steps to reproduce
https://jsfiddle.net/4zxbu68v/

## Expected result

The rating should not be interactive.

## Actual result
Using a disabled rating module on a card still triggers cursor and color change on hover.

## Testcase
https://jsfiddle.net/4zxbu68v/

## Version

2.8.7

**Comment by lubber-de** [comment]
Fixed by #1973
