### ISSUE TITLE
[dropdown] bug with an arrow in pointing dropdown

### ISSUE THREAD

**Issue by Doogls** [fomantic/Fomantic-UI#1995]
# Bug Report
The arrow is not under the button as in the examples in the documentation, but in the middle of the menu. 

## Steps to reproduce
Create a dropdown with a lot of text .

## Expected result
The arrow should have been under the button.

## Actual result
The arrow is in the middle of the menu, not below the button.

## Testcase
https://jsfiddle.net/Doogls/b8or4u75/4/

## Screenshot (if possible)
![Screenshot_6](https://user-images.githubusercontent.com/47123206/123332917-ccc93780-d549-11eb-8a33-ef0c1ab02a17.png)

## Version
2.8.8 and below

**Comment by lubber-de** [comment]
Add `top left` to your `pointing dropdown button`.
See https://jsfiddle.net/lubber/hc7jsy18/1/
![image](https://user-images.githubusercontent.com/18379884/123334236-15c9bd80-d543-11eb-8314-f5791a7bed8a.png)

**Comment by Doogls** [comment]
Thank you!
