### ISSUE TITLE
[Popup] CSS-only popups don't have a maximum width

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#1996]
# Bug Report
CSS-only popups (built using only the `data-tooltip` attribute without any javascript initialization) don't seem to have a maximum width set, so long tooltip text rapidly overflow the container width.

## Steps to reproduce
Add a CSS-only popup using the `data-tooltip` attribute with a container element:

`<span data-tooltip="Long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text long tooltip text">
    <i class="info icon"></i>
</span>`

## Expected result
The resulting popup should have a limited with, just like javascript-initialized ones.

## Actual result
Popup overflows page width.

## Testcase
[https://jsfiddle.net/k0qw3Lbe/](https://jsfiddle.net/k0qw3Lbe/)

## Version
2.8.7

**Comment by lubber-de** [comment]
Add `data-variation="fixed"`
See https://jsfiddle.net/lubber/b56gn89k/3/

It's also stated in the docs here
https://fomantic-ui.com/modules/popup.html#width
![image](https://user-images.githubusercontent.com/18379884/123416450-d9d04000-d5b6-11eb-86c9-70616fa48111.png)

**Comment by donaggio** [comment]
Sorry @lubber-de, usually I read throughly the docs, but somehow this bit of popup knowledge slipped under my radar! Thanks for your help!
