### ISSUE TITLE
Widgets are inaccessible to screen readers

### ISSUE THREAD

**Issue by Jookia** [fomantic/Fomantic-UI#2019]
# Bug Report
You can't use most widgets with a screen reader.

## Steps to reproduce
1. Open a screen reader
2. Try to use a dropdown

## Expected result
The dropdown should read elements as I use them and lock focus.

## Actual result
Nothing is read, focus is mismanaged.

## Version
any

**Comment by lubber-de** [comment]
Duplicate of #1332
