### ISSUE TITLE
Unexpected shift on attached tab segments

### ISSUE THREAD

**Issue by Apache02** [fomantic/Fomantic-UI#2024]
# Bug Report
Third and rest bottom attached tab segments have wrong margin. When you switch between second and third tab appears 1px shift.

## Steps to reproduce
1. Open https://fomantic-ui.com/modules/tab.html#/examples
2. Scroll to "Basic Tabs"
3. Click on First, Second and Third tab.

## Expected result
Perfect lines, without shifts.

## Actual result
1px shift.

## Screenshot (if possible)
https://i.imgur.com/E2cdk6D.png

## Version
2.4.1, 2.8.8

**Comment by lubber-de** [comment]
Duplicate of #1478

**Comment by lubber-de** [comment]
Fixed by #1480
