### ISSUE TITLE
Colored menu items not working unless when active

### ISSUE THREAD

**Issue by rlora** [fomantic/Fomantic-UI#2037]
# Bug Report
Colored menu items, such as the ones defined in:
```
<div class="ui menu">
  <a class="active red item">Red</a>
  <a class="orange item">Orange</a>
  <a class="yellow item">Yellow</a>
  <a class="olive item">Olive</a>
  <a class="green item">Green</a>
  <a class="teal item">Teal</a>
</div>
```

Don't work unless they are active. This is reproducible in the official documentation page. 

## Steps to reproduce
1. Create a menu with one active colored item and many inactive colored items.

## Expected result
Only the active item is rendered in color.

## Actual result
All items should be rendered in colors regardless of being active or not.

## Testcase
https://jsfiddle.net/tusm5hkn/

## Screenshot (if possible)
![Screen Shot 2021-08-06 at 5 19 01 PM](https://user-images.githubusercontent.com/1533339/128572962-07cbe58c-3ff7-44ed-8141-50fd40d5d3fe.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
That's intention of the default theme and not a bug.
If you want each inactive menu item being colored as well, you can wrap the items content into a `ui text` span
See https://jsfiddle.net/lubber/12ruxenf/8/

![image](https://user-images.githubusercontent.com/18379884/128574003-d45ba633-3d19-4388-82d2-aac6e9f5ddaf.png)

**Comment by rlora** [comment]
Understood. Thank you.
