### ISSUE TITLE
Margin of attached headers cannot be controlled anymore

### ISSUE THREAD

**Issue by laliluna** [fomantic/Fomantic-UI#207]
# Bug Report

A header can be _attached_, _bottom attached_ or _top attached_. The attachment removes the space to the next element.
- top attached to the element below.
- bottom attached to the element above.
- attached to the element below and above.

With this commit this behaviour is longer possible. The margin is always remove and ignores basically top and bottom.

https://github.com/fomantic/Fomantic-UI/commit/aa2591f44edf5ff9a30aaeac5f84cff5c8a4f50d

## Steps to reproduce

https://jsfiddle.net/45az9opm/4/

## Expected result

You can control where (top, bottom, both) to remove the margin.

## Actual result

Margin is always. removed on top and bottom

## Version
Latest

**Comment by ColinFrick** [comment]
We briefly talked about this internally and concluded that there can be only one `top attached` and one `bottom attached` element.
Your example could be implemented like this: https://jsfiddle.net/x31p69e7/

**Comment by laliluna** [comment]
I fully agree. My mistake was to wrap segment in segments which is used to group segment with no margin together. Once I remove this, I can fully control if a header should be attached to a segment.

https://jsfiddle.net/10qcfztr/2/
