### ISSUE TITLE
[Dropdown] bottom corner not properly rounded with upward

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#2075]
# Bug Report
bottom corner not properly rounded with upward css on dropdown

## Testcase
https://fomantic-ui.com/modules/dropdown.html#disabled

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/1622751/129720499-a986b91e-f18d-4776-9bbe-c9c51e47d370.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2076
