### ISSUE TITLE
[Table] Scroll-able Body Content for Table

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#2081]
# Feature Request
Some time we need a scroll-able table body for a long-content table (Instead of clicking the button on the footer). 
... With a **fixed** header and footer I meant.

## Screenshot (if possible)
Something like this would be nice.

![request-table](https://user-images.githubusercontent.com/28552977/130245692-a1e2ad15-f0bf-4e6f-8a70-caa6735b8cf5.PNG)

**Comment by lubber-de** [comment]
Also possible by #2148
