### ISSUE TITLE
minTimeGap

### ISSUE THREAD

**Issue by mrinalmondal123** [fomantic/Fomantic-UI#2092]
# Bug Report

## Steps to reproduce
1.
2.
3.

## Screenshot (when possible)
![]()

## Version
x.x.x
##semantic calender js not working
$('#calender_id_from_1').calendar({
        type: 'time',
        minTimeGap:10
});

**Comment by mrinalmondal123** [comment]
interval not working 
$('#calender_id_from_1').calendar({
        type: 'time',
        minTimeGap:10

**Comment by lubber-de** [comment]
Cannot reproduce. It is working as expected.
The minTimeGap Setting comes into account on the second selection step (You first select the hour, THEN the minutes
![image](https://user-images.githubusercontent.com/18379884/131396601-ce8eeb95-9098-4aaa-828c-6d06c792b608.png)

See https://jsfiddle.net/lubber/o9fb6y2e/3/
