### ISSUE TITLE
[Modal] uBlock Origin optional filter breaks modals

### ISSUE THREAD

**Issue by hdogan** [fomantic/Fomantic-UI#2098]
# Bug Report
If you use uBlock Origin browser extension (or probably other ad-blocker) and enabled `IRN: Adblock-Iran` filter, modals are immediately hidden by the extension. Dimmer and modal DOM elements remains.

## Steps to reproduce
1. Install uBlock Origin browser extension and enable it
2. Enable `IRN: Adblock-Iran` filter
3. Go https://jsfiddle.net/49vt3o2p/
4. Run fiddle

## Actual result
Modal immediately hides by uBlock Origin (and probably by other ad-blockers which uses that filter)

## Testcase
https://jsfiddle.net/49vt3o2p/

## Screenshot (if possible)
uBlock Origin logger details:

![ublock-origin-log](https://user-images.githubusercontent.com/777820/132757097-3c3553ff-d709-48b9-8448-0c3f37624975.png)

## Version
Fomantic-UI: 2.8.8
Browser: Google Chrome 93.0.4577.63 (Official Build) (64-bit)
Extension: uBlock Origin 1.37.2

## Other
Blocking rule/filter: https://github.com/farrokhi/adblock-iran/blob/master/filter.txt#L31
Related issue: https://github.com/farrokhi/adblock-iran/issues/62

**Comment by lubber-de** [comment]
I don't think we can do anything about that on our side. If Ublock declared the mentioned selector as possible ad, then it's their decision. Good, you already created an issue at the adblock repo, but i don't see that as a bug in fomantic.
What you can try is to use `detachable:false` in your modals, so the modal is not a childnode of the dimmer anymore.
This will still block the dimmer, but not necessarily the modal itself anymore. However, if the dimmer isn't present, we cannot guarantee the modal module to be fully working.

**Comment by hdogan** [comment]
Ok I'll try to get that meaningless filter removed. The reason was probably that some nasty Iranian sites were using Semantic/Fomantic UI modals)

Found the commit which adds that filter: https://github.com/farrokhi/adblock-iran/commit/641a9fc00a95a543cdcc6ff32415473d3955d495

It was in 2016 😱

**Comment by hdogan** [comment]
They've removed that filter.

Commit: https://github.com/farrokhi/adblock-iran/commit/ea0187bcab35486fc15956f588ed84ff3024fe7c
