### ISSUE TITLE
Toggle checkbox and slider checkbox should react to Left and Right key presses

### ISSUE THREAD

**Issue by chris-morgan** [fomantic/Fomantic-UI#2102]
https://fomantic-ui.com/, checkbox section, second and third items (slider checkbox and toggle checkbox): when the knob is on the left side, pressing the Right arrow key should shift it to the right side, and when it’s on the right side, pressing Left should shift it to the left side. (This is fairly standard behaviour.)

**Comment by lubber-de** [comment]
Implemented by #2111
