### ISSUE TITLE
[api] file input/upload support

### ISSUE THREAD

**Issue by hdogan** [fomantic/Fomantic-UI#2113]
# Feature Request

Current `serializeForm` setting/feature does not support file inputs (It uses jQuery serializeArray).
What about adding new `useFormData`/`useFormDataApi` setting? If it's set to `true` then ajax data can be generated by using [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData).

Instead of `useFormData` parameter it can be automatically detected by checking `enctype` form attribute. But user can also use submitting button `formenctype` attribute instead of form attribute. It might be tricky to detect.

Current workaround is probably generating `settings.data` with `FormData` API in `beforeSend`. (Not tested, it may also require not to pass `serializeForm` setting, if it's set, generated data will probably corrupted by `module.add.formData` method).

## Example
```js
$('.submit').api({
    action: 'upload file',
    serializeForm: true,
    useFormData: true
});
```

It can be added to:
https://github.com/fomantic/Fomantic-UI/blob/d11687dde71e26847e6d014246813b3e856a626a/src/definitions/behaviors/api.js#L198-L201

Theoretical/abstract imlementation:

```js
          if (settings.serializeForm) {
            if (settings.useFormData) {
              var formData = new FormData($form.get(0));
              // todo: append additional user passed data comes from settings.data
              settings.data = formData;
              // Need to set processData and contentType false
              // See: https://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax/5976031#5976031
              settings.processData = false;
              settings.contentType = false;
            }
            else {
              settings.data = module.add.formData(settings.data);
            }
          }
```

**Comment by hdogan** [comment]
Umm, I was preparing pull request, then I noticed that FormData is not directly related to file uploads. It's too generic and can be used with or without file inputs.

So, forcing `settings.contentType` value may not be appropriate. (Forcing `settings.processData` value to `false` still required, jQuery tries to generate string data from passed object).

Will two different new settings are too much? Like `useFormData` (uses FormData API) and `allowFileUpload` (sets contentType to false).

Or just skip this idea and let the users implement their own solution with using `beforeSend` callback? Or add simple upload example on docs?

Here is the changes I played with on `module.add.formData` method:

```js
          formData: function(data) {
            var
              formData = {},
              hasOtherData
            ;
            data         = data || settings.data;
            hasOtherData = $.isPlainObject(data);

            if (settings.useFormData) {
              formData = new FormData($form.get(0));
              // See: https://stackoverflow.com/questions/5392344/sending-multipart-formdata-with-jquery-ajax/5976031#5976031
              // Prevent jQuery to generate data string from a FormData object.
              settings.processData = false;
              // Prevent jQuery to send preflight OPTIONS request if it's cross-domain.
              settings.contentType = false;
              module.debug('Using FormData to serialize form', formData);
            } else {
              $.each($form.serializeArray(), function (i, element) {
                var node = formData[element.name];

                if ('undefined' !== typeof node && node !== null) {
                  if (Array.isArray(node)) {
                    node.push(element.value);
                  } else {
                    formData[element.name] = [node, element.value];
                  }
                } else {
                  formData[element.name] = element.value;
                }
              });
            }

            if (hasOtherData) {
              module.debug('Extending existing data with form data', data, formData);

              if (settings.useFormData) {
                $.each(data, function (key, value) {
                  formData.append(key, value);
                });
                data = formData;
              } else {
                data = $.extend(true, {}, data, formData);
              }
            }
            else {
              module.debug('Adding form data', formData);
              data = formData;
            }
            return data;
          }
        },
```

**Comment by hdogan** [comment]
Well, I've tested without setting `contentType`. jQuery sets is as `application/x-www-form-urlencoded; charset=UTF-8` (default value).

If you upload a file without setting `contentType` than request data includes broken boundary strings.
If you not upload a file without setting `contentType` then you get weird request data (looks like raw data).

So I think it's required to set `contentType` to `false` too with `FormData` even without uploading a file...

**Comment by lubber-de** [comment]
For an automatic decision to use the FormData API you could use

```javascript
var useFormData = $form.has('input[type="file"]').length > 0;
```

I also suggest to only set processData and contentType to false if they aren't already provided. This way a user is able to defined those settings on its own.

```javascript
// we unfortunatley cannot just use settings.processData ?? false, because we still support IE11 which does not support the ?? coalescing operator 
settings.processData = typeof settings.processData !== 'undefined' ? settings.processData : false;
settings.contentType = typeof settings.contentType !== 'undefined' ? settings.contentType : false;
```

**Comment by hdogan** [comment]
I've found something interesting when testing and couldn't solve it yet.

if `hasOtherData` is true than I append `data` items to `FormData` object (instead of merging `formData` with `data` by calling `$.extend`). Than assign `FormData` object to `data` variable which returns as function return value. But on sub-sequent requests for the same element, `hasOtherData` starts to return `false` and user provided data is not sent (it assumes `settings.data` is empty but it's not). First request is always work as expected.

Is there something special with the jQuery's `$.extend` call? https://github.com/fomantic/Fomantic-UI/blob/f5931a0f1b5a8b4491d546a3d7d7f8f5064350ff/src/definitions/behaviors/api.js#L450

**Comment by lubber-de** [comment]
You may have to enhance following check from

https://github.com/fomantic/Fomantic-UI/blob/f5931a0f1b5a8b4491d546a3d7d7f8f5064350ff/src/definitions/behaviors/api.js#L432

to

```javascript
hasOtherData = $.isPlainObject(data) || data instanceof FormData; 
```

**Comment by lubber-de** [comment]
I took your hints into a PR #2257, which also re-implements the original serializeObject logic and supports FormData and files

**Comment by hdogan** [comment]
I've been busy with an another project and couldn't finish my changes.

But I was struggling with the nested inputs (multiple files/checkboxes/array inputs) when using `FormData` api.
