### ISSUE TITLE
Uses Fomantic-UI in my nuxt project doesn't work 

### ISSUE THREAD

**Issue by antoinelaw** [fomantic/Fomantic-UI#2114]
# Bug Report
hello everybody,
I am new in web programming. I am making my first Nuxt project and i've choosen semantic instead of Boostrap. 
I've spent lot of days to install semantic with gulp but it doesn't work. Fomantic installation work using the documentation.

I dont want to use CDN. My app will run on a local machine. I've run :

`$ cd node_modules/fomantic-ui
$ npx gulp install
$ npx gulp build`

 And this step work well .

## Steps to reproduce
1. I want to use my own theming so I put   '~/semantic/dist/semantic.min.css' in my nuxt.config.js file under CSS propriety.

2. It seen like i should reference js fils such as /plugins/jquery/jquery.min.js and /semantic/dist/semantic.min.js in my nuxt config file. I put this line but it's not working.
` script: [
      { src: '~/plugins/jquery/jquery.min.js'},     
      { src: '~/semantic/dist/semantic.min.js'}
    ]`

************************************** nuxt.config.js ***************************************** 

`export default {
  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'qfq-store-app',
    htmlAttrs: {
      lang: 'en'
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
      { name: 'format-detection', content: 'telephone=no' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
    ],
    script: [
      { src: '../plugins/jquery/jquery.min.js'},     
      { src: '../semantic/dist/semantic.min.js'}
    ]
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [
    '../semantic/dist/semantic.min.css'
  ],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [
    //{ src: '../plugins/jquery/jquery.min.js', mode: 'client' },
   // { src: ../plugins/semantic/semantic.min.js', mode: 'client' }
  ],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {},

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
  }
}`

![image](https://user-images.githubusercontent.com/1155930/133937110-04b5a690-5929-45e2-b489-095ee6cb6d06.png)

## Expected result
Components should react ( drop down, pop-pup, change, ...) on click.

## Actual result
Everything display well but when I click on my component nothing happen. 
My first test was on menu component. I click on it too see my sub-menu items and it doesn't work . 
the list doesn't drop down as hope.

## Screenshot

![image](https://user-images.githubusercontent.com/1155930/133937007-ed78d978-853b-4cd7-9f0c-cc7e232883a4.png)

## Version
   fomantic-ui: ^2.8.8
   nuxt: ^2.15.7
   node v14.17.6

**Comment by lubber-de** [comment]
nuxt is a vue framework. vue uses virtual DOM to interact with the DOMtree. The original fomantic JS modules are based on jquery which in turn directly tries to access the DOM.
That's the basic reason why all js modules dont seem to work with nuxt/vue.

**Comment by antoinelaw** [comment]
> nuxt is a vue framework. vue uses virtual DOM to interact with the DOMtree. The original fomantic JS modules are based on jquery which in turn directly tries to access the DOM.
> That's the basic reason why all js modules dont seem to work with nuxt/vue.

Hello @lubber-de , thank you for you answer.

What can I do now to use fomatic-ui in local **(not with CDN)** with nuxt using my own theming ?

**Comment by lubber-de** [comment]
> What can I do now to use fomatic-ui in local (not with CDN) with nuxt using my own theming ?

I think, this question is better addressed at the [nuxt repository](https://github.com/nuxt/nuxt.js) to get an answer how to correctly import external CSS an JS files and how things might work with jquery modules accessing the DOM directly. 

As you confirmed, building Fomantic with your own theme does work (-> npx gulp build), everything else (like involving other frameworks) is unfortunately out of the FUI scope.

**Comment by lubber-de** [comment]
> My first test was on menu component. I click on it too see my sub-menu items and it doesn't work .
the list doesn't drop down as hope.

Does the console throw and errors, so you probably get a first idea what goes wrong.

**Comment by antoinelaw** [comment]
> > What can I do now to use fomatic-ui in local (not with CDN) with nuxt using my own theming ?
> 
> I think, this question is better addressed at the [nuxt repository](https://github.com/nuxt/nuxt.js) to get an answer how to correctly import external CSS an JS files and how things might work with jquery modules accessing the DOM directly.
> 
> As you confirmed, building Fomantic with your own theme does work (-> npx gulp build), everything else (like involving other frameworks) is unfortunately out of the FUI scope.

Thank for the answer, I will try to find the way  to correctly import external JS files in Nuxt

**Comment by antoinelaw** [comment]
> > My first test was on menu component. I click on it too see my sub-menu items and it doesn't work .
> > the list doesn't drop down as hope.
> 
> Does the console throw any errors, so you probably get a first idea what goes wrong?

It doesn't throw any error in the console. the live server still running well that is why I thing that must be Js files who don't load well because the CSS is apply correctly as I want. Only components don't react on click, hover, etc...

Thank you !!!
