### ISSUE TITLE
[toast] Click callback not called when closeOnClick is set to false

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#2125]
# Bug Report
When creating a toast, `onClick` callback not called when `closeOnClick` is set to false.

## Expected result
The `onClick` callback should work

## Actual result
The `onClick` callback doesn't work

## Testcase
https://jsfiddle.net/7fv4k0ag/

## Version
2.8.8

**Comment by lubber-de** [comment]
This was intentional, but i think i'll adjust the close logic inside the click event itself.
Workaround: add `closeIcon:true`, the the toast will handle the clickevent when clicking on the close icon only
See https://jsfiddle.net/lubber/u1zcepw4/

**Comment by GammaGames** [comment]
That would work, except I was using the toast as a floating status window with a span the user could click to copy the text. I don't want it to be closable, except when the application decides it should be closed. I should be able to use the `onVisible` callback to add the event listeners I want, so no worries.

**Comment by lubber-de** [comment]
Fixed by #2131 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/w025mr3p/
