### ISSUE TITLE
[Dropdown] Dropdown has 2x the width with input controls in a table

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2133]
# Bug Report

## Steps to reproduce

1. open https://ui.agiletoolkit.org/demos/form/html-layout.php
2. click add
3. select some age
4. select a different age and notice, the dropdown is resized, but incorrectly with much more width than needed

## Expected result

dropdown is resized no bigger than if it was these standard input

## Actual result

dropdown is twice as bit as the content

I belive it is because of the 2 other inputs on the left has width set to 0 with fluid layout.

## Testcase

n/a

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/2228672/135888804-9fc57272-2b44-405d-bbf7-db8603eeb0be.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
### Reason
That is intentional if you don't specify a column width.
### Solution
Add `four wide` (or whatever width you desire) to the first 2 columns (first name/last name). The checkbox already got a "one wide" class.
## Screenshot
When doing that the dropdown keeps its width for all available item
![fixedddwidthintable](https://user-images.githubusercontent.com/18379884/135892657-c860f5d2-bbf5-4968-99c1-9d6298d008b7.gif)

**Comment by lubber-de** [comment]
OK, you refer to the dropdowns width. That's because it's declared with `fluid` to fill the gap to the table column. Also, this is intentional.

**Comment by mvorisek** [comment]
Yes, I refer mainly to the fact a dropdown control should behave like an input control. Here the input does not resize (and has width of 0px), but dropdown does resize (as there is no 0px width hack).

If this can not be unified, feel free to close this issue.

**Comment by lubber-de** [comment]
Unfortunately the `width:0` hack does not work in this use case, as there is no input field inside the dropdown (it's not a `search selection`). Instead a `fluid down` uses `width:100%` as it is made out of a div.
I quickly tried to change that to `0!important` as well, but this messed it up completely. 
Again, i suggest to set a width to all other columns to keep the dropdowns width stable.

**Comment by mvorisek** [comment]
Ok, and thank you for your quick & to-the-point reactions.
