### ISSUE TITLE
[Dropdown] Dropdown menu isn't triggered/dropdown don't show when has active class

### ISSUE THREAD

**Issue by Yahav** [fomantic/Fomantic-UI#2136]
# Bug Report
Dropdown menu isn't triggered/dropdown don't show when has active class

## Steps to reproduce
add active class to a menu item that contains a dropdown

## Expected result
the menu item highlighted as active and when clicked the dropdown menu appears 

## Actual result
the menu item highlighted as active but when clicked the dropdown menu DOESN'T appear 

## Testcase
https://jsfiddle.net/7nvwgeaz/1/

## Version
2.8.8

**Comment by lubber-de** [comment]
Wrap the dropdown into an `<a class="active item"></a>`
See https://jsfiddle.net/lubber/ceq5rm3g/1/

**Comment by Yahav** [comment]
Why was this closed?
I do believe its a bug.
yes, it was `a` inside an `a`  since you asked me to wrap it with an `a` but in your fiddle all the submenu items are divs, which doesn't make any sense to me. those are suppose to be `a`'s.

**Comment by lubber-de** [comment]
🤔 Alright, according to the [Dropdown menu item](https://fomantic-ui.com/collections/menu.html#dropdown-item), `a` tags are supposed to be items for submenu entries.
However, `active menu item` and `active dropdown` will interfere, as you already figured out. 
I personally think a dropdown parent menu should never be active itself, but only the children. But even if my opinion does not matter: We would have to invent and swap a completely new classname for an active menu item which i dont should we should do.

So i still think my workaround using the wrapper is legit.
