### ISSUE TITLE
[icon] Update to FA 5.15.4

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#2138]
# Feature Request
There have been a handful of changes since FA 5.13.0, most recently being the Discord icon. 5.14.0 appears to have some backward-incompatible changes dealing with the Unicode Private Use Area.
 A handful of icons (mostly brands) have also been changed:

* A handful of sponsor brands were added
* Discord and yahoo were updated
* Adobe and Tripadvisor were removed 

(This isn't exhaustive, there's a bit [more](
https://github.com/FortAwesome/Font-Awesome/blob/master/CHANGELOG.md))

## Screenshot
| Old                                                                                                            | New                                                                                                            |
|----------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------|
| ![image](https://user-images.githubusercontent.com/7832163/137528162-62879f22-c6ca-4dce-80cd-a001739f6022.png) | ![image](https://user-images.githubusercontent.com/7832163/137528301-4c76e7d9-a252-4528-b0ab-9bbc51e2abbb.png) |

**Comment by lubber-de** [comment]
Implemented by #2227
