### ISSUE TITLE
[Table] Sortable, non-celled table header has border between cells

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#2149]
# Bug Report
Table header for sortable, non-celled table variant shouldn't have borders between cells for consistency with the table's body

## Steps to reproduce

1. Create a `ui sortable table`

## Expected result
Table header cells should have no left or right border, just as the rest of the table

## Actual result
Table header cells have the left border

## Testcase

[https://jsfiddle.net/efncg5d0/](https://jsfiddle.net/efncg5d0/)

## Version

2.8.8

**Comment by lubber-de** [comment]
Fixed by #2150
