### ISSUE TITLE
[Menu] Right Dropdown Item Align

### ISSUE THREAD

**Issue by nararock** [fomantic/Fomantic-UI#2160]
When I put the dropdown on the left menu item, some items of that dropdown look wrong.

https://jsfiddle.net/c3zru0dt/

![image](https://user-images.githubusercontent.com/32883208/141808291-ed43f417-8a6d-4f01-9df5-d206b0584351.png)

**Comment by lubber-de** [comment]
Use `displayType: 'block'` to fix this
See your adjusted jsfiddle here https://jsfiddle.net/lubber/3qauc5yp/8/
