### ISSUE TITLE
[scope] Lighthouse complaining about <a> not having href

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#2165]
The code below I took direct from your documentation at https://fomantic-ui.com/collections/menu.html :

```
<div class="ui text menu">
  <div class="item">
    <img src="/images/new-school.jpg">
  </div>
  <a class="browse item">
    Browse Courses
    <i class="dropdown icon"></i>
  </a>
  <div class="ui right dropdown item">
    More
    <i class="dropdown icon"></i>
    <div class="menu">
      <div class="item">Applications</div>
      <div class="item">International Students</div>
      <div class="item">Scholarships</div>
    </div>
  </div>
</div>
```

You see the `Browse Courses` element? When the user hovers it, it displays the submenu. Right, it works fine! However Lighthouse (which measures page speed, performance, accessibility... and many customers of mine use the score provided by Lighthouse in order to check if a website was well built) complains that the element `<a>` does not have `href` or that it's invalid. Of course it does not, it is not exactly a link! So I tried changing the `<a>` tag to `<span>` however the hover does not work anymore.

So I ask you: is there someway I can change the `<a>` tag to something else to avoid this score penalization of Lighthouse? The print follows below:

![image](https://user-images.githubusercontent.com/8988923/143505938-eb9c34a0-0f0f-4db2-82e1-b860e9635bb3.png)

**Comment by lubber-de** [comment]
## Two options:
### 1. Use link class
When using anything else than an `a` tag, add the `link` class to the menu item, so it gets hovered as well
```html
<span class="browse link item">
    Browse Courses
    <i class="dropdown icon"></i>
</span>
```
https://jsfiddle.net/lubber/ecfxm70u/3/

### 2. Use empty anchor for href
Just to satisfy lighthouse you may just add `href="#"` to each `a` item
```html
<a class="browse item" href="#">
    Browse Courses
    <i class="dropdown icon"></i>
</a>
```

**Comment by batata004** [comment]
Again,thank you so much! You are very nice.
