### ISSUE TITLE
[Dropdowns][Tags] Add in tokenization for Dropdowns when allowAdditions is true so user can input comma-delimited strings

### ISSUE THREAD

**Issue by shelbrudy** [fomantic/Fomantic-UI#2166]
# Feature Request

It would be really nice if fomantic had an option for tokenization in dropdowns when allowAdditions is set to true.  What I have in mind is the equivalent of [Select2's tokenization](https://select2.org/tagging#automatic-tokenization-into-tags) so that if a user input a comma delimited string (or any other character-delimited string), it would automatically separate those values. This way, users won't have to individually type in tags if they have a comma-delimited string elsewhere that they'd rather copy and paste.

## Example (if possible)

https://jsfiddle.net/9r57vm3e/2/

and then enter "third tag, fourth tag, fifth tag" in the dropdown. This will be saved as a single value. It would be really nice if it tokenized this and made them into separate tags.

## Screenshot (if possible)

Here's the desired behavior (screengrab from [Select2's tokenization](https://select2.org/tagging#automatic-tokenization-into-tags)):

In this example, i took the string `third, fourth, fifth` and pasted it into the box and it automatically separated it into three different values.

![tokenization](https://user-images.githubusercontent.com/25256436/144284738-51c275eb-c2ff-416a-a745-5ea8e499a8f1.gif)

**Comment by lubber-de** [comment]
Fixed by #2167 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/jc3xtshd
