### ISSUE TITLE
[table] Marked cells cannot be colored

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#2168]
# Bug Report
A table cell cannot be marked and colored at the same time.
This happens because the selector `.right.marked.blue` (for example) takes precedence over the simpler `.orange` (for example) selector. Maybe switching to something like `orange colored` as the classes required to get a colored cell and styling using selectors like `[class *= "orang colored"]` and `[class *= "marked blue"]` could solve the issue.

## Steps to reproduce
Set the classes `yellow right marked red` for a `<td>`

## Expected result
The cell gains a yellow background and text and a red marker on the right

## Actual result
Only the red marker is visible, background and text coloring are discarded

## Testcase
[https://jsfiddle.net/e24q89c7/](https://jsfiddle.net/e24q89c7/)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2377
