### ISSUE TITLE
[Button] Whatsapp + Telegram + Instagram + other updates to brand colors 

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#217]
# Feature Request

## Description
Some brand colors for social media buttons should be updated or newly created

### Original SUI PR 
https://github.com/Semantic-Org/Semantic-UI/pull/6153

**Comment by hammy2899** [comment]
> I think adding whatsapp, telegram, and fixing VK makes sense. I think we should probably just keep one color for instagram.

I agree with this and we should stick to it.

**Comment by lubber-de** [comment]
Fixed in current release https://github.com/fomantic/Fomantic-UI/tree/2.6.4
Instagram color gets a different issue/pr after final decision
