### ISSUE TITLE
[dropdown] readonly dropdowns from select

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2173]
# Bug Report

When building dropdowns from readonly `<select>` inputs with `$("select").dropdown();`, the dropdown is not readonly.

## Steps to reproduce
```html
<select class="ui fluid input" multiple readonly>
    <option>foo</option>
    <option>bar</option>
</select>
<script>
$("select").dropdown();
</script>
```

## Expected result
I would expect the dropdown to be readonly, even if I did not set the `read-only` class.

## Actual result
Users can select items in the dropdown.

## Testcase
https://jsfiddle.net/azmeuk/or13d76n/3/

## Screenshot
![Screenshot 2021-12-07 at 15-02-24 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/60163/145043091-55d03a6e-f163-4800-80de-69d96884e9dc.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
The `readonly` attribute is only supported for input html elements. `select` tags do not support that for standard HTML.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly

I would therefore not automatically fetch such non standard atttribute from the select statement within the dropdown code. 
Please add the `read-only` class if you want the dropdown to be readonly
