### ISSUE TITLE
[Progress] onSuccess trigger only the first time when value is set to 0 to 100%

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#2177]
# Bug Report
onSuccess event is trigger only the first time when value is set to 0 (reset) to 100%

## Steps to reproduce

1. click on reset button
2. click on 100% button 
3. check the console, the onSuccess event is trigger
4. click on reset button
5. click on 100% button
6. check the console, the onSuccess event is **not** trigger

## Expected result
onSuccess trigger everytime value is set to 0 to 100%

## Actual result
onSuccess trigger **only the first time** when value is set to 0 to 100%

## Testcase
https://jsfiddle.net/dutrieux/v85om3t1/

## Screenshot (if possible)
![progress gif](https://user-images.githubusercontent.com/1622751/145716860-71ca03d6-29b3-408c-beb6-cb4ca63045b7.gif)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2178 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/aqb5zjuo/

**Comment by grandeljay** [comment]
I am using `v2.9.0-beta.293` and also just noticed this. @lubber-de can you please double check it's still working?

**Comment by lubber-de** [comment]
@grandeljay 🤔  Still working for me using the latest nightly build
See https://jsfiddle.net/lubber/9xamt3je/1/

- click on reset button
- click on 100% button
- check the console, the onSuccess event is triggered
- click on reset button
- click on 100% button
- check the console, the onSuccess event is triggered again

**Comment by grandeljay** [comment]
Thanks for checking and sorry about all the noise! My code must be wrong, I'll get back to you if I am able to replicate the behaviour I am experiencing.

**Comment by grandeljay** [comment]
As mentioned, I wasn't able to achieve this behaviour in a fiddle but I would still like to share some of the output I am getting, maybe you have an idea why?

```js
progress.progress('increment', 1);

console.log('get percent: ' + progress.progress('get percent'));
console.log('get value: ' + progress.progress('get value'));
console.log('get total: ' + progress.progress('get total'));
console.log('is complete: ' + progress.progress('is complete'));
console.log('is success: ' + progress.progress('is success'));
```     

Output:
```log
get percent: 100
get value: 1 
get total: 1 
is complete: false 
is success: false 
```

How can percent be 100% and is complete be `false`?

**Comment by lubber-de** [comment]
@grandeljay That's because the bar is animated and the completion state is changed when the animation ends. So if you immediatly call "is complete" right after "increment", the animation has not ended yet, so the state has not been changed to "complete". That's the reason you should use the "on" callbacks instead.
To make your example work nevertheless, wrap the console.logs into a  delayed timeout function.
See https://jsfiddle.net/lubber/w3qd58ma/15/
