### ISSUE TITLE
Single Component Modules

### ISSUE THREAD

**Issue by Biosphakus** [fomantic/Fomantic-UI#2179]
I am using single component modules with NPM and Parcel like that:
```
// require modules
var $ = require("jquery");
    $.fn.search       = require('semantic-ui-search');
    $.fn.popup       = require('semantic-ui-popup');
    $.fn.dropdown = require('fomantic-ui-dropdown');

// initialize UI elements
$('.ui popup').dropdown();
$('.ui dropdown').dropdown();
```

With transitioning to Fomantic-UI (from Semantic UI), these single component modules don't seem to be widely available. I have tried to install the Fomantic UI version for the dropdown and managed to do so. 

```
npm install fomantic-ui-dropdown
```

However, it seems to be only 2.7.7 (not 2.8.8). This is also reflected in my package.json:

```
  "dependencies": {
    "fomantic-ui": "^2.8.8",
    "fomantic-ui-dropdown": "^2.7.7",
...
}
```

Seems like this was published two years ago: [Link on NPM](https://www.npmjs.com/package/fomantic-ui-dropdown). 

_Background:_ I'm trying to use a Javascript-initalized description in my dropdown menu but the descriptions won't show (no error messages). I think the issue is that I can't install the latest version as this feature might not be present in 2.7.7?

```
<div class="ui dropdown">
  <span class="description"></span>
  <span class="text"></span>
  <i class="dropdown icon"></i>
</div>
```

```
$('#verticaldescription').dropdown({
    placeholder: 'Show descriptions',
    values:[{
      "name": "name1",
      "value": "value1",
      "description": "description1"
    },
    {
      "name": "name2",
      "value": "value2",
      "description": "description2",
      "descriptionVertical": true
    }]
})
;
```

Would it be possible to provide the single component modules or is there a better solution?

**Comment by lubber-de** [comment]
There are currently no plans to provide and maintain separate repositories for each single module. Even SUI did not continue to follow that approach long before the whole project went to sleep 3 years ago. (All those single component SUI packages are out of date and do not contain the latest SUI code which makes them kind of useless).

The above mentioned NPM package is not an official Fomantic package and therefore not maintained by the Fomantic Team.
And, as you already figured out, it's also not maintained anymore as it is stuck at FUI 2.7.7 which is also 2 years old.
 
However, the base Fomantic Repository here, as well as the precompiled precompiled CSS/JS package https://github.com/fomantic/Fomantic-UI-CS package as well as as the CDN, always have each single components available as single files. So you don't need to always include the whole semantic.js / semantic.css if you don't want to.

https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/components/dropdown.js

There also exists an official precompiled CSS/JS package https://github.com/fomantic/Fomantic-UI-CSS

Please also keep in mind that some modules might have dependencies to other modules to function properly. That's maybe one reason even SUI gave up maintaining single packages, but that's just a guess.

If you really need single components out of single npm packages, please ask the maintainer of the mentioned repo to upgrade Fomantic to 2.8.8.

**Comment by Biosphakus** [comment]
Thank you for your help! By the way, the link you provided to the dropdown.js doesn't work.

In principle, I could include the entire .js file instead of single modules but I don't really know how to make this work. It works with the current setup:
```
// require modules
var $ = require("jquery");
    $.fn.search       = require('semantic-ui-search');
    $.fn.popup       = require('semantic-ui-popup');
    $.fn.dropdown = require('fomantic-ui-dropdown');

$('.some-div-class').search(
//...
)
```

I tried just requiring fomantic-ui for itself:
```
var $    = require("jquery");
require('fomantic-ui');

$('.some-div-class').search(
//...
)
```

But then I get an error for each of the javascript modules I try to use, e. g.: `Uncaught TypeError: s(...).search is not a function`

Would it be possible to elaborate on how to use this correctly?

**Comment by Biosphakus** [comment]
Thanks again! Unfortunately both these options do not seem to work for me. 

I tried the first option:

_index.html_
``` 
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.8/dist/semantic.min.js"></script>
    <script src="myscript.js"></script>
```

_myscript.js_
```
var $    = require("jquery");        // embed jQuery
$('.ui.search')
  .search({ 
  // ... 
});
```

But I get the same error message:
`Uncaught TypeError: s(...).search is not a function`

Or, with the second solution:
`Uncaught ReferenceError: importScripts is not defined`

Unfortunately, I'm still on Parcel 1 for the time being but I think the first solution should actually work. I can't really understand why it doesn't. Sorry if this is a very basic problem; any further help would be very much appreciated.

**Comment by lubber-de** [comment]
When you try the first option (means you include jquery from a CDN), you should _NOT_ declare jquery as a package requirement anymore, because it has already been globally available.
So this `var $    = require("jquery"); ` is not necessary, or even worse, destroys the existance of the CDN jquery, making the following `$().search` faulty (you redeclare jquery, after fomantic was invoked, so its not available anymore

**Comment by Biosphakus** [comment]
This was indeed the solution for my problem. Now the new features from Fomantic UI work. Thanks so much!
