### ISSUE TITLE
[installation] While installing and choosing components to include, show the list in alphabetical order

### ISSUE THREAD

**Issue by arethk** [fomantic/Fomantic-UI#2180]
I am currently installing the fomantic on the command line via "npx gulp install" and I'm selecting/unselecting components. The list is in a random order. It would be a lot nicer if this component list was in alphabetical order.

![Screenshot at 2021-12-14 10-53-02](https://user-images.githubusercontent.com/16406449/146061544-dd8cd0d6-b771-4cc1-a824-6a37f64475c8.png)

**Comment by arethk** [comment]
Also, form is in the list twice.

**Comment by hugopeek** [comment]
This order is also implanted in the brains of seasoned SUI/FUI veterans. It is reflected in the docs too, so it makes sense (to me at least) to see the same order in the installer.

So I would be careful with changing this. Consider it part of your Kung-FUI training instead @arethk ;). Too bad the library doesn't let you group them @lubber-de, that would have been perfect.

As for the double `form` component: maybe the second one should be renamed to `validation`? That also better reflects that it's behavioural.

**Comment by lubber-de** [comment]
I added kind of "grouping headers" by #2209

I decided against renaming the form validation component, see my thoughts inside the above mentioned PR descripton
