### ISSUE TITLE
[modal] multiple modals close buttons come on each other

### ISSUE THREAD

**Issue by MRAlirad** [fomantic/Fomantic-UI#2195]
# Bug Report
when you have two modals on top of each other, if the height of both of them are the same and close buttons are out of the modal, the close buttons are on each other which has a bad user experience.

## Steps to reproduce

1. make the scope (browser window screen) at a big size so that the close buttons of the modal come outside of the modal scope
2. open the background and foreground modal

## Expected result
a better UI for the close buttons which are on top of each other

## Actual result
the  close buttons of both modals fall on top of each other (based on the modals sizes and headers height)

## Testcase
https://jsfiddle.net/208c45nt/1

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/77621358/148225403-7d8085e3-d928-4713-be00-b6cd636c7f84.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
I tagged this as an enhancement. In the meantime you can force the close icon to stay inside the modals regardless of the viewport size by adding `inside` to the `close icon`
See https://jsfiddle.net/lubber/3Lve8tn1/

it is mentioned in the docs here
https://fomantic-ui.com/modules/modal.html#via-existing-dom-node
![image](https://user-images.githubusercontent.com/18379884/148230292-aea305d8-6076-4457-a63e-9cebaf13c516.png)

**Comment by lubber-de** [comment]
Oups, i tag this as a bug again, because the close icon from the parent modal is still clickable! 👀 
See https://jsfiddle.net/lubber/zbt5ex69/1/

**Comment by lubber-de** [comment]
Fixed by #2196 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/dm7pj3gf/

**Comment by MRAlirad** [comment]
Thank you very much for working on this enhancement 👍
