### ISSUE TITLE
calendar date setting error when monthFirst: true

### ISSUE THREAD

**Issue by janbkrejci** [fomantic/Fomantic-UI#2200]
# Bug Report

With option "monthFirst" set to true, there seems to be a parsing problem when setting calendar value.

## Steps to reproduce

Try setting calendar value to '10. 6. 2021' (with spaces) and to '10.6.2021' (without spaces).

## Expected result

value == 2021-06-10

## Actual result

In the first case with spaces included the value is '2021-10-06' instead of '2021-06-10'. In the second case without spaces the result is OK.

## Version

2.8

**Comment by lubber-de** [comment]
Fixed by #2218
