### ISSUE TITLE
[site] icon headers misaligned

### ISSUE THREAD

**Issue by hugopeek** [fomantic/Fomantic-UI#2208]
# Bug Report

I just noticed that the icon headers are misaligned on the site. Some images are also stretched out of proportion.

## Steps to reproduce

Visit the homepage at fomantic-ui.com.

## Expected result

This problem does not occur on semantic-ui.com.

## Actual result

Comparing it to semantic-ui.com, it seems the styling for `.ui.icon.header .icon` is no longer being applied. 

## Screenshot

![image](https://user-images.githubusercontent.com/5436121/150626428-48e21a36-4fd3-443d-bf2e-f6635068d910.png)

## Version

I don't know the version of the site. Is it being built with nightlies perhaps?

**Comment by lubber-de** [comment]
Fixed by #2210
