### ISSUE TITLE
[api] Array API repsonse parsed as plain object in onResponse()

### ISSUE THREAD

**Issue by jchook** [fomantic/Fomantic-UI#2220]
# Bug Report

When API returns a "bare" Array JSON response, Fomantic parses it as plain object instead of an `Array`.

Related: https://github.com/fomantic/Fomantic-UI/issues/263

## Steps to reproduce

**Step 1**

API endpoint returns, say `[{"id":1, "desc":"Sun"}, {"id":2, "desc":"Moon"}]`

**Step 2**

```html
<div class="ui search selection dropdown" id="myDropdown">
  <div class="default text">Select Celestial Body</div>
</div>
```

```js
$('#myDropdown').dropdown({ 
  apiSettings: {
    cache: false,
    url: "/celestialBodies",
    mockResponse: [{"id":1, "desc":"Sun"}, {"id":2, "desc":"Moon"}],
    onResponse: (data) => {
      console.log(data); // Plain object!
      return { results: data.map((item) => ({ name: item.desc, value: item.id })) } // ERROR!
      // Uncaught TypeError: data.map is not a function
    },
  }
});
````

## Expected result

Ideally `onResponse()` exposes a parsed `Array` object

`[{"id":1, "desc":"Sun"}, {"id":2, "desc":"Moon"}]`

## Actual result

Instead the object is a plain JS object that is not iterable.

`{"0":{"id":1, "desc":"Sun"}, "1":{"id":2, "desc":"Moon"}}`

## Testcase

https://jsfiddle.net/jchook/4xc5v0b3/15/

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/193530/151908036-4d26cc44-ef1e-475e-b4f3-9a1566866a07.png)

## Version

2.8.8

---

## Workaround

```js
$('#myDropdown').dropdown({ 
  apiSettings: {
    cache: false,
    url: "/celestialBodies",
    mockResponse: [{"id":1, "desc":"Sun"}, {"id":2, "desc":"Moon"}],
    onResponse: (data) => {
      const results = []
      for (const key in data) {
        if (data.hasOwnProperty(key)) {
          const item = data[key]
          results.push({ name: item.desc, value: item.id })
        }
      }
      return { results }
    },
  }
});
```

**Comment by lubber-de** [comment]
Use `rawResponse: true`
See your adjusted jsfiddle here https://jsfiddle.net/lubber/7oLk854d/1/

From the docs page:
https://fomantic-ui.com/behaviors/api.html#/settings
![image](https://user-images.githubusercontent.com/18379884/151999101-7e3fadb4-574c-4f1a-9fad-30c50423c707.png)

**Comment by jchook** [comment]
I still feel like this is a bug.

It violates "the principle of least surprise". I cannot imagine a scenario where parsing an array into something other than an array is desirable.

Also it's kind of silly to say, "you need an extra option to circumvent our bug"

**Comment by lubber-de** [comment]
@jchook As a compromise i proposed changing the default for  `rawResponse` to be true so JSON arrays are not converted by default anymore by #2230
