### ISSUE TITLE
[calendar] hide days not in viewed month

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2224]
Not 100% sure if this already exists, but it may be nice from a user-perspective if the days outside of the month could be optionally hidden to avoid any potential confusion. Essentially, to look similar to below:

![image](https://user-images.githubusercontent.com/1376843/152547814-86fd1c6a-b0a0-43e4-bd21-e8e729ea6841.png)

**Comment by lubber-de** [comment]
You can already achieve this by providing a custom `formatter.cell` function which, for example removes the cell content or replaces it by some custom value

The following shows an `x` in any disabled cell and removes any content in an adjacent cell which results in your feature request 🙂 
```javascript
$('.ui.inline.calendar').calendar({
    type: 'date',
    initialDate: '2022-03-01',
    disabledDates: [
      '2022-03-15'
    ],
    constantHeight: false,
    formatter: {
      cell: function(cell, cellDate, cellOptions){
        if(cellOptions.disabled) {
          cell.text('x');
        }
        if(cellOptions.adjacent) {
          cell.html('');
        }
      }
    }
  })
```
See https://jsfiddle.net/lubber/t01Ld2kn/9/

**Comment by jamessampford** [comment]
Nice, thanks - think was looking for an example or a simple flag to use in the docs - didn’t think of the formatter; but this works just as well 🙂
