### ISSUE TITLE
[Card] Add "Primary" and "Secondary" colored cards

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#223]
# Feature Request
## Description
> It would be useful to have a colored card variant that has the accent in the primary and secondary brand colors.

### Original SUI Issue
https://github.com/Semantic-Org/Semantic-UI/issues/5784

### Original SUI PR 
https://github.com/Semantic-Org/Semantic-UI/pull/5788

**Comment by hammy2899** [comment]
This has already been added as of 2.4.
