### ISSUE TITLE
[container] Add wider container variations

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#2231]
# Feature Request

It would be nice to have larger variations of `ui container`, in addition to the `fluid` one, for example a `ui wide container`.
I find the maximum container width (computed by default from the `@largeMonitorBreakpoint` value) to be a little bit too narrow in most cases, considering that nowadays almost all desktop monitors are (at least) 1920px wide.

**Comment by prudho** [comment]
PR #2256 submited to implement this.

**Comment by donaggio** [comment]
Awesome, thanks!
