### ISSUE TITLE
[dropdown] Ability to hide unpopulated headers in search dropdown

### ISSUE THREAD

**Issue by neokio** [fomantic/Fomantic-UI#2235]
# Feature Request

Picture a dropdown with 10 headers (e.g. tag categories), each followed by 10 items (e.g. tags).
Searching for a tag shows ALL the headers, even if none of the items beneath it are shown.

It would be optimal if ONLY those headers with items beneath them would appear.

## Example
```
        <div class="ui labeled icon multiple search selection very long dropdown" multiple="">
            <span class="label">Tags</span>
            <input type="hidden" name="tags">
            <i class="dropdown icon"></i>
            <div class="default text">Tags</div>
            <div class="menu">

               <div class="header">
                    <i class="tags icon"></i>
                    Category 1
                </div>

                <div class="item nowrap" data-value="1">
                    Tag 1
                </div>
                <div class="item" data-value="2">
                    Tag 2
                </div>

                <!-- ADD MORE ITEMS HERE -->

               <div class="header">
                    <i class="tags icon"></i>
                    Category 2
                </div>

                <div class="item" data-value="3">
                    Tag 1
                </div>
                <div class="item" data-value="4">
                    Tag 2
                </div>

                <!-- ETC. -->

            </div>
        </div>
```

## Screenshot
![Screen Shot 2022-02-15 at 3 46 49 PM](https://user-images.githubusercontent.com/146623/154162792-7bafe9c9-65c5-4a7e-bf1b-f8f0485a6e13.png)

**Comment by lubber-de** [comment]
That's already possible by using `hideDividers: 'empty`
See https://jsfiddle.net/lubber/dmh6qjzv/4/

Form the docs https://fomantic-ui.com/modules/dropdown.html#/settings
![image](https://user-images.githubusercontent.com/18379884/154318164-e8a69bad-341f-4c9d-ab3a-cec7a74af296.png)

**Comment by neokio** [comment]
That's just so beautiful.
