### ISSUE TITLE
Async completion bug in install script

### ISSUE THREAD

**Issue by jeffrson** [fomantic/Fomantic-UI#2236]
# Bug Report

In between
https://github.com/fomantic/Fomantic-UI/blob/develop/tasks/install.js#L79
and
https://github.com/fomantic/Fomantic-UI/blob/develop/tasks/install.js#L80
there needs to be another call of "callback" in order to satisfy gulp.

So please insert
```
callback()
```

## Version

2.8.8

**Comment by lubber-de** [comment]
Fixed by #2248
