### ISSUE TITLE
unmet peer dependency "@octokit/core@>=3"

### ISSUE THREAD

**Issue by jeffrson** [fomantic/Fomantic-UI#2237]
# Bug Report

Apparently, fomantic-ui requires "@octokit/rest", which in turn requires "@octokit/plugin-request-log" which has a peer dependency to "@octokit/core@>=3".

Hence, fomantic-ui needs to depend on "@octokit/core@>=3".

This is courtesy of npm
```
npm WARN @octokit/plugin-request-log@1.0.4 requires a peer of @octokit/core@>=3 but none is installed. You must install peer dependencies yourself.
```

**Comment by lubber-de** [comment]
Fixed by #2309
