### ISSUE TITLE
[flag] South Sudan is missing

### ISSUE THREAD

**Issue by zyzniewski** [fomantic/Fomantic-UI#2244]
# Bug Report
South Sudan flag is missing

## Steps to reproduce
`<i class="ss flag"></i>`

## Expected result
to see South Sudan flag

## Actual result
nothing is displayed

## Testcase
https://jsfiddle.net/35rex2n8/

## Version
2.8.8

**Comment by lubber-de** [comment]
This is fixed in the nightly beta.
See https://jsfiddle.net/lubber/e8qh9y3r/

**Comment by zyzniewski** [comment]
Thanks!
