### ISSUE TITLE
[dropdown] `allowAdditions` (with multiple values allowed) breaks the "words" on some characters

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2245]
# Bug Report

## Steps to reproduce
1. create dropdown with multiple values allowed and `allowAdditions` option
2. focus it and write `test?bar` or `test<bar`

## Expected result

one `test?bar` (or `test<bar`) value (after hitting enter) is expected

![image](https://user-images.githubusercontent.com/2228672/155759598-7d4fd327-859a-4980-8e35-dab542588209.png)

## Actual result

as soon as `?` (or `<`) key is pressed, the previous value is finished, the `?` (or `<`) key is ignored, and a new value is started

this is problematic to enter values with such characters, workaround is to write such value in a text editor and copy it to the component in one shot instead

![image](https://user-images.githubusercontent.com/2228672/155759676-e13f214a-6e53-409d-b211-28b5881d723a.png)

maybe more non alphanum characters are affected, but the enter/finish characters should be configureable (probably TAB and ENTER by default)

## Version
2.8.8

**Comment by lubber-de** [comment]
I cannot reproducce this behavior.
PLease adjust the following jsfiddle to reproduce the mentioned bug, so we can figure out what's wrong in your use case.
https://jsfiddle.net/lubber
![multipledropdown](https://user-images.githubusercontent.com/18379884/155858781-17da818a-4c98-449c-9ebc-1be816e5d497.gif)
/27whu5tf/3/

**Comment by mvorisek** [comment]
Very strange.

I tried your fiffle https://jsfiddle.net/lubber/27whu5tf/3/ and bug is present on my side in these testing enviroments:
- Firefox 94.0.1 on Windows 10
- Chrome 98.0.4758.102 on Windows 10 via RDP

I open the jsfiddle, click inside the drowdopwn control in the bottom-right window, type `t`, `e`, `s`, `t`, `?`, `b`... via keyboard and as soon as I hit `?`, a `test` "item" is finished and a new `b` is started.

Can you please test on Windows 10 and/or different browsers to check if reproducible in at least one on your side?

**Comment by lubber-de** [comment]
I tried on Windows 10 and Windows 11, Chrome  98.0.4758.102 and Firefox 97.0.1
Works fone for me any time.

Do you probably happen to have some browser/Windows plugins installed which fetch the "?" or other keys ?

**Comment by mvorisek** [comment]
I think I have figured out one common keybord key that is causing the issue.

It does not depend on pressed "characted", but instead of pressed "keyboard button".

The problematic characters I mentioned are on one place with Czech keyboard.

Please try to press the following key after some alphanum characters type:

![image](https://user-images.githubusercontent.com/2228672/155859620-20d383a4-35b8-49a1-b286-61df1f398c0b.png)

I can reproduce with that key pressed only, and also with shift (that's how we type `?` in CZ) or right alt (that's how we type `<` in CZ) together.

**Comment by lubber-de** [comment]
Yes, that's intented, because the comma is set as the default `keys.delimiter` setting.
Try to change that setting to `false`

From the docs
![image](https://user-images.githubusercontent.com/18379884/155859770-ed73c722-6062-4b2f-a5cd-ecf75c9e54fe.png)

**Comment by mvorisek** [comment]
Thank you for clearing this up!

However, I belive such behaviour should be present only with pure keypress, eg. without any shift or alt modifier or the actual typed character (not sure if accessible from JS) should be checked.

**Comment by lubber-de** [comment]
I fixed this now by #2247 
I adjusted the jsfiddle accordingly here:
https://jsfiddle.net/lubber/27whu5tf/12/

Please test, if this fixes the issue for yourself as well

**Comment by mvorisek** [comment]
Thank you ❤️ 

I confirm the PR fixes this issue and `,` as a delimiter continues to work.

One question - if I want to use that patch also for 2.8.8, is it safe to patch `src/definitions/modules/dropdown.js` and include that JS file without any additional compilation?

**Comment by lubber-de** [comment]
Sure :)
