### ISSUE TITLE
[calendar] time-only calendar arrow-selection clash

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2249]
# Bug Report
When using a time-only calendar, if selecting the time in the top left corner where the arrow/pointer/diamond is to the input, the colours clash - ideally, the bottom half of the arrow/pointer/diamond should be the same colour as the selection (grey, not white) in this case
 
This can easily be replicated when viewing the docs

## Screenshot
![image](https://user-images.githubusercontent.com/1376843/156752835-9e269545-d340-4d55-a982-63f5e5e5bcc4.png)

**Comment by lubber-de** [comment]
Duplicate of #744

**Comment by jamessampford** [comment]
Ah! Thought I'd seen this before but didn't think it was so far back
