### ISSUE TITLE
Icons are corrupted when using the Material theme

### ISSUE THREAD

**Issue by asiral** [fomantic/Fomantic-UI#2261]
# Bug Report
Icons are corrupted when using the Material theme

## Steps to reproduce
1. Go into project folder
2. Run `npm init`
3. Run `npm install --ignore-scripts fomantic-ui`
4. Run `cd node_modules/fomantic-ui`
5. Run `npx gulp install`
6. Edit `semantic/src/theme.config` and change `@site` to `material`
7. Run `npx gulp build`
8. Add an icon to an index.html in project root referencing the stylesheet `semantic/dist/semantic.min.css`

## Expected result
Icons appear uncorrupted

## Actual result
Icons are corrupted

## Testcase
https://jsfiddle.net/9ontkbzm/ index.html referencing the compiled stylesheet

## Screenshot (if possible)
![Screenshot from 2022-03-11 16 26 09](https://user-images.githubusercontent.com/2885971/157866684-e06477fb-1f13-42d4-8ba3-3d14379d420c.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2262
