### ISSUE TITLE
[Modal] Dynamicly created modal takes the content from the previous one as long as "detachable" is set to true.

### ISSUE THREAD

**Issue by qroft** [fomantic/Fomantic-UI#2290]
# Bug Report
I have set up a website with Winter CMS and Fomantic-UI.
In Winter you have the option to create so called "partials" that can be updated via Ajax.
My website hast like 20 buttons. Each button calls the same Fomantic-Ui modal but should show individual content.
When i have the modal setting "detachable" activated, the modal shows the content from the previous modal.

## Steps to reproduce

**With "detachable" set to TRUE (default)**
1. I press for example button number 15 and the modal appears with the correct content.
2. I close the modal
3. I press button number 8 and the modal shows the content from button number 15
4. I close the modal
5. I press the button number 11 and the modal appears with the content from button number 8

**With "detachable" set to FALSE**
Everything works as expected showing the correct content per button call.

## Expected result
The correct AJAX content should be loaded and not the previous one.

## Actual result
Apart of the first modal, the following modals always show the content from the previous one.

## Testcase
Unfortunatly on a member restricted area.

## Version
2.8.8

**FROM MY POINT OF VIEW:**
I am only a JS scriptkiddie but for me it looks like that when the modal is "moved" or copied to the center of the page, the new defined modal still shows the last modal. I suggest.

**Comment by lubber-de** [comment]
This really needs a testcase, can't you copy the relevant code from your members area and remove all sensitive content?
How are you using the modal component? via existing HTML nodes? do you have 20 modal html nodes? is evey button reusing the same HTML template? Are you using config templates? Are you using dynamic js modal?
Please try to at least provide a jsfiddle skeleton, even if the API cannot e reached but prepare an example response (using anonymized data)

**Comment by lubber-de** [comment]
Closing until a reproducable testcase jsfiddle is provided
