### ISSUE TITLE
Partial ratings graphics glitch on Chrome & Opera

### ISSUE THREAD

**Issue by userpointfi** [fomantic/Fomantic-UI#2295]
# Bug Report

## Steps to reproduce
1. Go to [Fomantic rating documentation](https://fomantic-ui.com/modules/rating.html)
2. Scroll down to Partial Ratings
3. On Chrome 99 (Mac, Windows and Linux) and Opera 84 (at least Mac), the non-full rating icon has a colouring outside the actual icon

## Expected result

That the non-full rating icon looks like the full ones, except that it is not full

## Actual result

The non-full raring icon has its background gray and fill color (background outside the icon)

## Testcase

[Fomantic 2.8.8](https://jsfiddle.net/8typLacw/) DOES NOT work
[Fomantic 2.7.8](https://jsfiddle.net/pqkavxrd/) DOES work

## Screenshot
![Screenshot from Romantic documentation](https://user-images.githubusercontent.com/87081871/161175588-c4a52fe7-6b16-4c85-b8e2-4d25d825e548.png)

## Version
Fomantic UI 2.8.8
Chrome 99
Opera 84

Note: On Safari 15.3 everything looks correct. Also, with Fomantic 2.7.8 everything works as well.

**Comment by userpointfi** [comment]
The fix has already been merged https://github.com/fomantic/Fomantic-UI/pull/2023 but a new release has not been done so the fix is not available.

**Comment by lubber-de** [comment]
The fix is available in the nightly build on npm or cdn
