### ISSUE TITLE
Checkbox - Required class on checkbox misplace the check symbol

### ISSUE THREAD

**Issue by etshy** [fomantic/Fomantic-UI#231]
## Steps to reproduce
Make a chackbox with required class (I konw it may sound idiot, but symfony Forms, for example, add the class by default to the input if not specified) and the check symbol is misplaced.

## Expected result
Symbol well placed even with required class on the input

## Actual result
symbol is missplaced, a bit too much to the right

## Testcase
https://jsfiddle.net/9dqkhosL/

## Screenshot (when possible)
![here](https://i.imgur.com/pQ4wDKm.png)

## Version
2.6.3 (updated to see if it was fixed before posting this issue)

Problems comes from the rule that place the red required star (acting on the label:after)

**Comment by exoego** [comment]
My understanding is that `.required` class should be added to `.field`, not to `label` for `checkbox`
https://fomantic-ui.com/collections/form.html#required

**Comment by hammy2899** [comment]
@exoego I agree and by doing so the check is in the correct place. I am closing this as wontfix.
