### ISSUE TITLE
Horizontal Cards bug on mobile

### ISSUE THREAD

**Issue by smallevil** [fomantic/Fomantic-UI#2314]
version:2.8.8

Horizontal Cards on pc (chrome mac)
![image](https://user-images.githubusercontent.com/198904/162608980-9beccba5-d590-4b25-881e-f5e82b04a992.png)

Horizontal Cards on mobile (safari iphone)
![image](https://user-images.githubusercontent.com/198904/162612328-eaebf409-15d0-4477-b8bc-d15c6e18d396.png)

**Comment by lubber-de** [comment]
This is intentional as the cards wont fit on small mobile screens, thus they wrap automatially.

**Comment by smallevil** [comment]
My mobile phone is iphone11, and it is not the one with the smallest screen. It can't be displayed in one line, which is a bit unreasonable

**Comment by lubber-de** [comment]
The Fomantic Docs page is defined to be viewed in responsive mode via the [viewport meta tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag)

it is therefore set to
```html
<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
```

which in turn scales the screens according to the detected device (not resolution!)

Only because your iphone has a high resolution screen it is still not considered to be shown in desktop mode as long as the above meta tag is used.

In your own project, you can force to use desktop resolution even on your iphone to test the difference yourself.
To accomplish this simply use a different meta tag like this

```html
<meta name="viewport" content="width=1024">
```
 
or even
```html
<meta name="viewport" content="">
```

That will show the horizontal cards on your ipone, but they will appear very tiny.

**Comment by lubber-de** [comment]
You can even force the fomantic website to be shown in desktop mode by requesting it directly in apple safari
https://appleinsider.com/articles/21/11/03/how-to-request-desktop-versions-of-websites-in-safari-on-iphone-and-ipad

**Comment by smallevil** [comment]
I see what you mean. It just seems to me that what you're talking about is just a compromise.
This kind of card is a very practical and common form in shopping malls. If it can be unified, it is the most convenient, otherwise I will write a card with the text on the left and the right text for the mobile phone, which is equivalent to repeating it again. This The card loses its importance on the phone.
I still hope that you can reconsider how to better take into account the mobile phone.
I'm a backend developer myself, and I'm not familiar with CSS, so I can only give some advice from my work, I hope it didn't make you embarrassed.
Love this project very much, thank you and this project

**Comment by lubber-de** [comment]
> I still hope that you can reconsider how to better take into account the mobile phone.

Again, it's not us / FUI to be really able to adjust this. As i explained above, it's basically the browser (by the meta viewport setting) which is causing the wrap as it _thinks_ there is not enought space anymore.
FUI itself is  not even wrapping horizontal cards via a specific breakpoint manually.

The related code is here
https://github.com/fomantic/Fomantic-UI/blob/03890cad95af0a3ea8e0ec29a19d6aeeac710736/src/definitions/views/card.less#L538-L541

The flex settings make the browser decide when it's time to wrap.

If you have a better solution/support for that, don't hesitate to help and provide a proper PR 😉 (I currently have no idea myself)

As i mentioned earlier, by adjusting your projects meta viewport tag, you can make your iphone behave just as a desktop website using your native resolution. However, your horizontal card smost probably appear too tiny then, but you are completely free to have it as you like.
