### ISSUE TITLE
Extra semi colon causing problems in webpack

### ISSUE THREAD

**Issue by ahmed6262445** [fomantic/Fomantic-UI#2323]
Due to extra semi colon in font url webpack is unable to build the fomantic-ui.
To use it with webpack currently I have to explicitly go to node_modules and delete the extra semi-colon.

![Screenshot from 2022-04-14 22-42-11](https://user-images.githubusercontent.com/57043614/163449836-97bb0f59-e4f7-4c89-b141-69cf1c8bb814.png)

**Comment by lubber-de** [comment]
Duplicate of #2027 and fixed by #2028
Please try the develop branch or CDN nightly build
