### ISSUE TITLE
[Segment] A basic segment within .segments should be basic

### ISSUE THREAD

**Issue by lubber-de** [fomantic/Fomantic-UI#233]
# Feature Request

## Description
> This PR try to fix a problem and add a new functionality :
> 
> * The fix : when we have a `.ui.basic.segment` inside of `.ui.horizontal.segments`, the basic segment doesn't loose the border and shadow.
> * The new functionality : Add a `.ui.basic.segments` with **s**
>   It comes in handy when we want to do something like this
> 
> ```css
> .ui.horizontal.basic.segments>(.ui.basic.segment+.ui.basic.right.aligned.segment)
> ```
> 
> Edit: This is an example from my app
> 
> Before the PR
> Jsfiddle example : https://jsfiddle.net/h4nycLoj/
> ![image](https://cloud.githubusercontent.com/assets/1449151/20519654/0ef94610-b0a4-11e6-99ea-2b4680f9d45a.png)
> 
> After the PR
> 
> ![image](https://cloud.githubusercontent.com/assets/1449151/20519578/c4253ebe-b0a3-11e6-83d9-c1561b1f2509.png)
> 
> The markup used in the images
> 
> ```
> <div class="ui horizontal basic segments"> 
>     <div class="ui basic segment"> ... </div>
> 
>     <div class="ui basic right aligned segment"> ... </div>
> </div>
> ```

### Original SUI PR 
https://github.com/Semantic-Org/Semantic-UI/pull/4773

**Comment by prudho** [comment]
This is already fixed in #32 (original issue was Semantic-Org/Semantic-UI#3801).
