### ISSUE TITLE
[Label] pointing interferes with pure icon

### ISSUE THREAD

**Issue by ararunaufc** [fomantic/Fomantic-UI#2334]
# Bug Report
I'm trying to render a pointing label that contains only an icon. The result contains incorrect centering.

I get this result image 
![wrong-padding-label](https://user-images.githubusercontent.com/19910857/164957757-91b681f7-6a8c-4bfa-8445-896fa0ffea63.png)
 when I use the following markup:

```html
<div class="ui right pointing horizontal basic grey icon label">
  <i class="book reader icon"></i>
</div>
```

The problem is that the icon does not appear correctly centered. If I remove the `right pointing` I get this image 
![correct-padding-label](https://user-images.githubusercontent.com/19910857/164957767-459e5d65-f9fa-43d9-9a42-bcbae67a0a78.png)
 where everything looks correct.

```html
<div class="ui horizontal basic grey icon label">
  <i class="book reader icon"></i>
</div>
```

## Steps to reproduce

1. Use the following classList: `"ui right pointing horizontal basic grey icon label"`

## Expected result

The correct padding, as seen on this other variant: ![correct-padding-label](https://user-images.githubusercontent.com/19910857/164957767-459e5d65-f9fa-43d9-9a42-bcbae67a0a78.png)

## Actual result

This is the result as of today: ![wrong-padding-label](https://user-images.githubusercontent.com/19910857/164957757-91b681f7-6a8c-4bfa-8445-896fa0ffea63.png)

## Testcase

https://jsfiddle.net/d6ntx2a8/

## Screenshot (if possible)

![wrong-padding-label](https://user-images.githubusercontent.com/19910857/164957757-91b681f7-6a8c-4bfa-8445-896fa0ffea63.png)

## Version

2.8.8

**Comment by lubber-de** [comment]
Fixed by #2336
