### ISSUE TITLE
[dropdown] { selected: true } values not returned with 'get value'

### ISSUE THREAD

**Issue by jchook** [fomantic/Fomantic-UI#2342]
# Bug Report

Dropdown values marked `{ selected: true }` are missing from `$(ele).dropdown('get value')`.

## Steps to reproduce

Initialize a dropdown using the `values` setting, and set some as `{ selected: true }`.

```html
<select id="select1" class="ui search dropdown" multiple></select>
```

```typescript
$('#select1').dropdown({
  values: [
    { name: 'Sun', value: 'Sun', selected: true },
    { name: 'Mercury', value: 'Mercury' },
    { name: 'Venus', value: 'Venus' },
    { name: 'Earth', value: 'Earth', selected: true },
    { name: 'Mars', value: 'Mars' },
  ]
})

console.log(
  $('#select1').dropdown('get value')
)
```

Access the value of the dropdown using `$(ele).dropdown('get value')`

## Expected result

```json
["Sun", "Earth"]
```

## Actual result

```json
[]
````

## Testcase

http://jsfiddle.net/cf4a7yoL/5/

Includes a workaround using `$(ele).dropdown('set exactly', [...])` for comparison.

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/193530/165402664-bdb5d8c8-56fc-4a8c-9c9a-1429933ba59d.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2344 
See your adjusted jsfiddle here http://jsfiddle.net/lubber/yv4f0ces/

Thanks for testing the nightly beta!
