### ISSUE TITLE
[dropdown] Default text matching option text stays in grey color

### ISSUE THREAD

**Issue by Eizens** [fomantic/Fomantic-UI#2350]
# Bug Report
When selecting the option from the dropdown that matches the default text value (e.g.`<div class="default text">2</div>`), the color of the selected value in the dropdown stays grey instead of turning black. This also applies if the value is already set (e.g. `<input value="2" />`). This is confusing as it states that the value has not been selected although it is. When reopening the dropdown menu the selected option is in bold and the value retrieved from the dropdown is correct. The issue is with the color not changing. And it only happens if the the option's text matches the default text.

If selecting other option and then again the option matching the default text - color is black as expected.

## Steps to reproduce
1. Create dropdown element.
2. Add some default text.
3. Create dropdown menu with some options (best to use same value and text) from which one matches the default text.
4. Select or set the option that matches the default text.

## Expected result
If dropdown has already value set or if dropdown doesn't have any value, then on value selection if the particular option's text matches the default text, color in the dropdown should be black.
https://jsfiddle.net/bfderc3y/1/

## Actual result
Selected option's text matches default text - color stays grey:
https://jsfiddle.net/zcpewvo9/

## Testcase

Value already set:
https://jsfiddle.net/zcpewvo9/

Choose the value that matches default text:
https://jsfiddle.net/bfderc3y/

## Screenshot (if possible)
https://imgur.com/a/vArnEfY

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #2485
