### ISSUE TITLE
Use native font stack, remove Lato font download

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2355]
# Feature Request

![image](https://user-images.githubusercontent.com/2228672/84135218-023bd980-aa4a-11ea-9cee-686b5e1fc241.png)

`non-nglish` characters like `ř` are displayed very differently than the others without diacritics

word like `Řeřicha` should be exactly/pixelly the same as `Rericha` (ignoring the accents)

quite important for European languages where accents are very common

it seems like a Lato does not have a support for these characters and also the Lato v1 is still used (Lato v2 is not however available thru Google Fonts)

see https://getbootstrap.com/docs/5.1/content/reboot/#native-font-stack

I propose to use the native font stack also for Fomantic UI, it will fix issues with non-English characters and also remove HTTP requests to Google Fonts

**Comment by mvorisek** [comment]
related to https://github.com/fomantic/Fomantic-UI/issues/367, same solution (native font stack) proposed

**Comment by mvorisek** [comment]
this is what Bootstrap use: https://github.com/twbs/bootstrap/blob/v5.1.3/scss/_variables.scss#L577

**Comment by lubber-de** [comment]
Fixed and implemented by #2359 
- Google Import removed (they used Lato 1.0 anyway)
- Bundled Lato 2.0 for offline usage which also covers all missing diacritic letters
