### ISSUE TITLE
LICENSE.md should be included in npm package

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2356]
Currently (tested with v2.8.8), README.md is included, but LICENSE.md is not.

This is a feature request to include LICENSE.md, so when `npm install fomantic-ui-css` is run, the license file is present.

This is a standard practice with the most popular packages.

**Comment by mvorisek** [comment]
@lubber-de would it be possible to publish nightly versions for https://www.npmjs.com/package/fomantic-ui-css?activeTab=versions too the same as for https://www.npmjs.com/package/fomantic-ui?activeTab=versions?

**Comment by lubber-de** [comment]
License file is now included in the 2.9.0 release of the CSS/LESS packages
