### ISSUE TITLE
[Icons] update to FontAwesome 5.6.x

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#236]
# Feature Request

## Description
Update icons to FA 5.5.0

https://github.com/FortAwesome/Font-Awesome/blob/4f4cb7c2f55d14d24f10390ebfeab0d25af612f3/CHANGELOG.md

**Comment by hammy2899** [comment]
FA released 5.6 last night, I will update straight to that.

**Comment by Atulin** [comment]
The changelog link you posted is giving me 404, probably because ``Font-Awesome-Pro`` has restricted access.
Release notes of the free version here: https://github.com/FortAwesome/Font-Awesome/releases/tag/5.6.0

**Comment by hammy2899** [comment]
@Atulin oh yeah sorry, thanks for posting the free link 😄

**Comment by hammy2899** [comment]
The time has come where docpad is incapable of building the docs because there is so many icons 😄 

We will have to wait until we rewrite the docs or until I figure out a new way to display the icons on the current docs before I can update the lib with the new FA versions.

**Comment by exoego** [comment]
> The time has come where docpad is incapable of building the docs because there is so many icons

What happens while you run docpad?
It seems that my environment can build using docpad@v6.79.4 and I see the icons rendered on the built docs on localhost.

**Comment by hammy2899** [comment]
@exoego Weird 🤔  I will have another go when I next can
