### ISSUE TITLE
Form validation with Regex failure

### ISSUE THREAD

**Issue by kiw3** [fomantic/Fomantic-UI#2374]
# Bug Report

Form validation with Regex failure

## Steps to reproduce

1. go https://fomantic-ui.com/behaviors/form.html#passing-parameters-to-rules
2. try value 'rgb(a, a, a)'
3.

## Expected result

prompt error

## Actual result

no response

## Screenshot (if possible)

![圖片](https://user-images.githubusercontent.com/105871985/169740739-311ad3b4-8169-4c50-8f20-b04bb2c62bfb.png)

## Version

2.8.8

**Comment by lubber-de** [comment]
Fixed by #2141
