### ISSUE TITLE
Slider set option

### ISSUE THREAD

**Issue by gaspardwilliam** [fomantic/Fomantic-UI#2383]
How can I set an option after initialized the slider,

I would like to make something like : 
$(sliderPrice).slider('set start', start)
$(sliderPrice).slider('set max', max)
$(sliderPrice).slider('set step', 80)

I can do this $(sliderPrice).slider({step:80}) but It will lose other options and events

**Comment by lubber-de** [comment]
You can use the  'setting' behavior to change settings afterwards. However you also would have to redraw the layout and labels
```javascript
$('.ui.slider').slider();
$('.ui.slider').slider('setting','step',10);
$('.ui.slider').slider('setup layout');
$('.ui.slider').slider('setup labels');
```
See https://jsfiddle.net/lubber/hk43o0sf/4/
