### ISSUE TITLE
[Slider] Non-functional after programmatically removing disabled class

### ISSUE THREAD

**Issue by Gliptal** [fomantic/Fomantic-UI#2389]
# Bug Report

Sliders remain non-functional after programmatically removing the `disabled` class.

## Steps to reproduce

1. Add a `disabled` slider: the `disabled` class can either be set in the markup, or programmatically.
2. Remove the `disabled` class with jQuery's `removeClass()` function.
3. Attempt to move the slider.

## Expected result

The slider should be functional after removing the `disabled` class.

## Actual result

The slider isn't functional anymore after removing the `disabled` class.

## Testcase

https://jsfiddle.net/Lm5tv2bh/3/

## Version

2.8.8

**Comment by lubber-de** [comment]
Confirmed. As a workround add
```javascript
$('.ui.slider').slider('bind events');
```
after you have removerd the disabled class
See https://jsfiddle.net/lubber/e9f3p5q0/

**Comment by lubber-de** [comment]
Fixed by #2721
