### ISSUE TITLE
[scope] dropdown displayed incorrectly

### ISSUE THREAD

**Issue by yarglory** [fomantic/Fomantic-UI#2391]
Dropdown submenu in "clearable multiple selection dropdown" not see![IMG_20220707_000407_250.jpg](https://user-images.githubusercontent.com/24853383/177643294-d01de671-c9df-4af1-b2e2-f9cbe6f23c84.jpg)

**Comment by lubber-de** [comment]
Submenus are not supported in (multiple) selection dropdowns. Your screeenshot also shows a scrollbar because the submenu overflows the dropdown menu container, might also causes the left extra border and margin.

Please provide a jsfiddle with your code so we could try something to fix the visuals nevertheless

**Comment by yarglory** [comment]
`            <div class="ui green segment">
                <h4 class="ui horizontal left aligned divider header">
                    <i class="stream icon"></i>
                    Основное
                </h4>

                <div class="two fields field">
                    <div class="eight wide field">
                        <div class="ui right labeled left icon input">
                            <i class="bullseye icon"></i>
                            <input type="text" name="title" placeholder="Введите заголовок">
                            <div class="ui label">0 / 140</div>
                        </div>
                    </div>      
                    <div class="eight wide field">
                        <div class="ui clearable multiple selection dropdown"  id="imagelabels">
                            <input type="hidden" name="categories" value="1">
                            <i class="dropdown icon"></i>
                            <div class="default text">Выьерите категорию</div>
                            <div class="menu">
                                <div class="item" data-value="1"><img class="image" src="https://cdn-icons-png.flaticon.com/512/808/808439.png">Игры

<i class="dropdown icon"></i>
                                <div class="menu">
                                <div class="item" data-value="11"><img class="image" src="https://cdn-icons-png.flaticon.com/512/808/808439.png">-Игры 1</div>
                                <div class="item" data-value="13"><img class="image" src="https://cdn-icons-png.flaticon.com/512/808/808439.png">-Игры 2 </div>
                               </div>







                                </div>






                                <div class="item" data-value="2"><img class="image" src="https://cdn-icons-png.flaticon.com/512/2920/2920329.png">Программы</div>
                                <div class="item" data-value="3"><img class="image" src="https://cdn-icons-png.flaticon.com/512/1420/1420880.png">Темы</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>`

**Comment by yarglory** [comment]
```
            <div class="ui green segment">
                <h4 class="ui horizontal left aligned divider header">
                    <i class="stream icon"></i>
                    Основное
                </h4>

                <div class="two fields field">
                    <div class="eight wide field">
                        <div class="ui right labeled left icon input">
                            <i class="bullseye icon"></i>
                            <input type="text" name="title" placeholder="Введите заголовок">
                            <div class="ui label">0 / 140</div>
                        </div>
                    </div>      
                    <div class="eight wide field">
                        <div class="ui clearable multiple selection dropdown"  id="imagelabels">
                            <input type="hidden" name="categories" value="1">
                            <i class="dropdown icon"></i>
                            <div class="default text">Выьерите категорию</div>
                            <div class="menu">
                                <div class="item" data-value="1"><img class="image" src="https://cdn-icons-png.flaticon.com/512/808/808439.png">Игры

<i class="dropdown icon"></i>
                                <div class="menu">
                                <div class="item" data-value="11"><img class="image" src="https://cdn-icons-png.flaticon.com/512/808/808439.png">-Игры 1</div>
                                <div class="item" data-value="13"><img class="image" src="https://cdn-icons-png.flaticon.com/512/808/808439.png">-Игры 2 </div>
                               </div>







                                </div>






                                <div class="item" data-value="2"><img class="image" src="https://cdn-icons-png.flaticon.com/512/2920/2920329.png">Программы</div>
                                <div class="item" data-value="3"><img class="image" src="https://cdn-icons-png.flaticon.com/512/1420/1420880.png">Темы</div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
```

**Comment by lubber-de** [comment]
@yarglory Thanks. I put your code into a jsfiddle using the lates 2.9.0 nightly
https://jsfiddle.net/lubber/s7odqtw0/5/

By resetting the overflow on the first dropdown menu, your issue is gone and submenus are shown.
So, given your example, you can add
```css
.ui.multiple.selection.dropdown > .menu {
  overflow: initial;
}
```

**Comment by yarglory** [comment]
Thanks

**Comment by finlabhk** [comment]
> @yarglory Thanks. I put your code into a jsfiddle using the latest 2.9.0 nightly https://jsfiddle.net/lubber/s7odqtw0/5/
> 
> By resetting the overflow on the first dropdown menu, your issue is gone and submenus are shown. So, given your example, you can add
> 
> ```css
> .ui.multiple.selection.dropdown > .menu {
>   overflow: initial;
> }
> ```

@lubber-de Sorry for disturbing the discussion. I found that if the number of items in a dropdown more than 4, the the border of dropdown cannot cover the whole item list, please refer to [https://jsfiddle.net/sz0yoj7L/1/](https://jsfiddle.net/sz0yoj7L/1/) for your reference. Thank you

**Comment by lubber-de** [comment]
@finlabhk In that case use `max-height: initial`. 
https://jsfiddle.net/bhq9vu2z/
But all of this is not necessary when using normal items which do not contain a sub menu.

**Comment by finlabhk** [comment]
> @finlabhk In that case use `max-height: initial`. https://jsfiddle.net/bhq9vu2z/ But all of this is not necessary when using normal items which do not contain a sub menu.

Thank you very much. But I find this solution can also fix the issue I faced half year ago : https://github.com/fomantic/Fomantic-UI/discussions/2187

But it seems that the above solution  does not work if there is a second level sub menu :[https://jsfiddle.net/zfhpgu63/](url)
