### ISSUE TITLE
[checkbox] Additional radio variations

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2393]
# Feature Request
A couple of extra radio variations showing in large clear groups

## Screenshot
![image](https://user-images.githubusercontent.com/1376843/177776961-16c8f849-99be-4193-bb6b-282e07824a5f.png)
![image](https://user-images.githubusercontent.com/1376843/177776987-698af1bf-19ea-4826-ac11-9b16f4fab55d.png)

**Comment by GammaGames** [comment]
I've done the first version with segments before: https://jsfiddle.net/xmgds9po/
![image](https://user-images.githubusercontent.com/7832163/178016961-64caece5-5e9b-4181-9009-72c79090e275.png)

**Comment by lubber-de** [comment]
Implemented/Possible by #2773
