### ISSUE TITLE
More rounded corners

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2394]
# Feature Request
Have a class that allows buttons, modals, etc to have more rounded corners as opposed to just the suttle rounded corners that are currently present (possibly rounder and roundest?)

**Comment by lubber-de** [comment]
This is something designed to be changed via LESS variables in your theme.
This can be done globally by changing `@defaultBorderRadius` in https://github.com/fomantic/Fomantic-UI/blob/0ffef84e2d78f74a2268973637b555ea84c09110/src/themes/default/globals/site.variables#L145

**Comment by jamessampford** [comment]
My thinking was a class override so different components could use different radius

**Comment by lubber-de** [comment]
Well, then we would either have to implement that for each possible element (i believe some elements probably need other adjustments like padding or child element adjustments if the border radius exceeds a certain value) or provide a central helper class for the border-radius property... which is the tailwind world which FUI is not.

**Comment by jamessampford** [comment]
> some elements probably need other adjustments like padding or child element adjustments

Yeah, that's true if they're not auto-calculated - even if `rounder` was strictly 2x bigger than default and `roundest` was strictly 4x bigger than default, without the auto-calculation it could be tricky
