### ISSUE TITLE
[modal] Action button alignment + border + background

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2395]
# Feature Request
Allow `left aligned` to left align the action buttons

Having a class to use the modal background and no seperator would look nice for both the header and footer

## Screenshot
![image](https://user-images.githubusercontent.com/1376843/177780228-8c924780-81b7-4507-836f-7edb8b7dc7db.png)

**Comment by lubber-de** [comment]
Implemented by #2403
