### ISSUE TITLE
[menu] Icons on the left

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2397]
# Feature Request
At present, icons are hardcoded to be right floated - I suggest that there is an option available to optionally float them left where a `left aligned` or `left floated` class is provided (where the margin is also adjusted accordingly)

## Screenshot
![image](https://user-images.githubusercontent.com/1376843/177785923-e7fbcd15-171b-4df7-869f-03f7ae6c85ec.png)

**Comment by lubber-de** [comment]
Duplicate oif #2234

**Comment by jamessampford** [comment]
My thinking was a class override so either position could be used
