### ISSUE TITLE
[Popup] Positioning ignores popup classes

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#240]
### Steps

Create an inline popup with positioning classes, ex. "bottom center"

### Expected Result

Triggering element opens popup honouring positioning classes

### Actual Result

Triggering element opens popup in top center position as if no positioning classes were specified, even if it ends partially off screen

### Version
2.6.3, used to work in 2.6.2

### Testcase
https://jsfiddle.net/d6w9hcab

**Comment by prudho** [comment]
This one was really hard to find out... Seem to be introduced by 05655ef9f0311d64a166ffff44432733cf09d35b.

@lubber-de if you comment this line [here](https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/transition.less#L51), the bug does not appear anymore.

@donaggio if you need a hotfix, please edit the file `src/definitions/modules/transition.less`, delete the line 51 (`.hidden.hidden.transition,`) and then rebuild fomantic-ui. Your problem should be solved...

...or wait some days for the next awesome FUI release 😉

**Comment by donaggio** [comment]
Thanks @prudho for so quiclky looking into it. I'm not in a hurry, so I'll wait for the next release.

In the meantime, other possible workarounds I've found, which does not involve rebuilding, are:

- positioning the popup through javascript:
`$('#trigger').popup({
    position: 'bottom center'
});`

- positioning through attribute "data-position" in **triggering element**

Anyway, with my workarounds, while it will actually position the popup in the specified spot, it will not check if the popup will end off screen and, eventually, reposition it.

**Comment by lubber-de** [comment]
:thinking: The main reason for this are the initially set, but IMHO not neccessary classes `transition hidden` to the popup div. popup divs are hidden by default and if you just remove either `transition` or `hidden` everything works as expected.
Nevertheless, i saw those classes are also defined in the example docs for popup, so you might had used those examples as codebase. I'll investigate more to provide a better fix, because just removing the css line as suggested will introduce an older bug again.

**Comment by lubber-de** [comment]
@donaggio Forget about my last comment. It's the forced `display:none` in hidden state (even if you remove `transition`or `hidden`, it would happen again the second time you open the popup. 
I'll take care of it!
@prudho Thanks for the hard finding!

**Comment by lubber-de** [comment]
Fixed in current Release https://github.com/fomantic/Fomantic-UI/tree/2.6.4
