### ISSUE TITLE
[api] Adding `onSuccess` breaks the API

### ISSUE THREAD

**Issue by grandeljay** [fomantic/Fomantic-UI#2401]
# Bug Report
Adding the `onSuccess` function via the dropdown `apiSettings` seems to break the API call or mapping of the results.

## Steps to reproduce
1. Initialize dropdown with `apiSettings`
2. Add `apiSettings`
3. Add `onSuccess` callback to `apiSettings`

## Expected result
The dropdown should show the API results.

## Actual result
The dropdown has no items.

## Testcase
https://jsfiddle.net/34z06c2e/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/45571053/179188795-6abad094-8980-49a8-947c-5571929fb9b1.png)

## Version
2.9.0-beta.298

**Comment by lubber-de** [comment]
Fixed by #2402 See your adjusted jsfiddle here https://jsfiddle.net/lubber/3kj1b0wL/1/
