### ISSUE TITLE
Release a 2.9 alpha package

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2408]
Version 2.9 has a lot of bugfixes and features, but it is still [80 bug away](https://github.com/fomantic/Fomantic-UI/milestone/27) from being released, and the last 2.8.8 version was released 1 year ago.

I suggest releasing a 2.9 alpha package containing the current state of the repository, so one can use the new thing in 2.9, at their own risks.

What do you think?

**Comment by hammy2899** [comment]
If you want to use 2.9 early you can use the nightly build which is updated every night if there is changes pushed.

```bash
npm install fomantic-ui@nightly
```

This is not 2.9 specific, you can use the nightly build to use any release/changes early.
