### ISSUE TITLE
[tab] Equally spaced tabs with active area differ in width

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2410]
# Bug Report
The pixel width differs from the attached tabs to the attached segment (attached segment is 2px wider)

The same can be seen on Centered Item https://fomantic-ui.com/modules/tab.html#centered-item

## Expected result
Right-side border (tab + segment) to be aligned

## Actual result
Right-side border (tab + segment) is not aligned

## Testcase
https://jsfiddle.net/vy8e9h3a/

## Screenshot
![image](https://user-images.githubusercontent.com/1376843/180801610-32ee42df-35c1-4762-a57f-3e912848e165.png)

## Version
2.8.8

**Comment by lubber-de** [comment]
Fixed by #1480
