### ISSUE TITLE
[Accordion] Firefox 103 throws: Transition: Element is no longer attached to DOM 

### ISSUE THREAD

**Issue by Astabil** [fomantic/Fomantic-UI#2412]
# Bug Report
After latest Firefox upgrade on 103 version Accordion feature throws error: Transition: Element is no longer attached to DOM. Unable to animate.  Use silent setting to surpress this warning in production. fade in .

Same behavior is on the Fomantic-UI site https://fomantic-ui.com/modules/accordion.html, and on similar jsfiddle code snippets

## Steps to reproduce
Go on the https://fomantic-ui.com/modules/accordion.html site, with latest Firefox, Firefox dev, and just use the accordion and open the inspection tool.

https://jsfiddle.net/d2s8nhw3/

## Version

2.7.0, 2.8.
![full](https://user-images.githubusercontent.com/39694859/181504073-77a1e206-47b0-44c6-99cf-d19e4bfa320d.JPG)
![Capture](https://user-images.githubusercontent.com/39694859/181504079-06f3ecb0-1ca9-4378-ad5b-f095e58ee195.JPG)

**Comment by GammaGames** [comment]
Just ran into this in production, glad I saw the issue before getting that ticket. Is there any workaround?

**Comment by Tomaslrr** [comment]
Also having this problem in production

**Comment by lubber-de** [comment]
Fixed by #2417 
See https://jsfiddle.net/lubber/3ybfs51n/3/

**Comment by MacLake** [comment]
Great that this issue has been fixed so fast. Do you have an idea when you will release a version with this fix? As we have a website highly relying on FUI accordions, I’m considering using the development branch.

**Comment by lubber-de** [comment]
Asap, a few bugs and docs are open before 2.9.0 officially sees the light In the meantime you may use the nightly build (or use the develop branch).
