### ISSUE TITLE
[form] inverted label is not inverted

### ISSUE THREAD

**Issue by grandeljay** [fomantic/Fomantic-UI#2421]
# Bug Report
When inverting a form, the label color does not seem to be inverted anymore.

## Steps to reproduce
1. Add an inverted form
2. The label color is black instead of white

## Expected result
The label color should be white.

## Actual result
The label color is still black.

## Testcase
https://jsfiddle.net/rz5u34gv/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/45571053/183582830-2304c458-d4b6-40de-9109-9c6fd511657c.png)

## Version
2.9.0-beta.301+42e68bc

**Comment by lubber-de** [comment]
Fixed by #2422
