### ISSUE TITLE
fomantic-ui doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module

### ISSUE THREAD

**Issue by zeddrix** [fomantic/Fomantic-UI#2427]
# Bug Report
I'm using SvelteKit. Every time I run my project that uses the fomantic-ui package, I keep on getting this message on my terminal:

`fomantic-ui doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

Now I don't know if this is alright or not. But everything seems to be working fine. It's just that this message keeps on showing whenever I run my project.

## Steps to reproduce
1. Install fomantic-ui to your project.
2. Use it.
3. Then run your project to your browser. 
4. In your terminal, you'll see this:

<img width="839" alt="Screen Shot 2022-08-15 at 4 13 35 PM" src="https://user-images.githubusercontent.com/37854513/184600148-37c295f3-0f16-4d46-afe2-da8d22987d95.png">

## Expected result
No message like that on the terminal and everything should be fine.

## Actual result
<img width="839" alt="Screen Shot 2022-08-15 at 4 13 35 PM" src="https://user-images.githubusercontent.com/37854513/184600148-37c295f3-0f16-4d46-afe2-da8d22987d95.png">

## Version
^2.8.8

**Comment by lubber-de** [comment]
Yes, Fomantic UI is not an ES6 or CJS module, but plain ES5 JS. You may check the docs for VITE/SvelteKit how to import plain JS Files
