### ISSUE TITLE
[modal] Unable to dismiss dropdown / calendar / search using escape key without closing the modal

### ISSUE THREAD

**Issue by mat128** [fomantic/Fomantic-UI#2428]
# Bug Report
It is not possible to close a calendar picker via the escape key when it is embedded in a modal.
It appears the issue is not limited to the calendar picker. The dropdown menu, the checkbox and the search components are also affected. The components behave normally when used directly inside a page, outside of a modal.

It should be possible to use the escape key to dismiss an open dropdown, or a date picker.
Such behavior is natural when using native components.

**Edit**: It should be possible to close the modal when interaction is not on a dropdown / calendar / search

## Steps to reproduce
1. Add a dropdown/calendar/search to a modal
2. Open the modal
3. Open the dropdown
4. Hit the escape button

## Expected result
The dropdown/calendar/search popup is closed. The modal stays visible.

## Actual result
The modal is closed.

## Testcase
https://jsfiddle.net/mat128/e5of9mdg/83/

## Screenshot (if possible)
![fomantic-escape](https://user-images.githubusercontent.com/234168/184693176-2dc3b0a2-c1eb-4099-a3c2-a4726adfa3bc.gif)

## Version
2.8.8

**Comment by lubber-de** [comment]
Use `closable: false` for the modal, which prevents that. However it will also prevent closing the modal by clicking on the dimmer.
See your adjusted jsfiddle here https://jsfiddle.net/lubber/khdqz97p/
