### ISSUE TITLE
[Sidebar] Removing Background Color from body

### ISSUE THREAD

**Issue by ivangomes** [fomantic/Fomantic-UI#2448]
# Bug Report

## Steps to reproduce
1. Click at the Open Side Bar Button at the test case
2. Click at the page to close the 
3.

## Expected result

Keep the background color 

body {
  background-color: #4b4b4b !important;
}

## Actual result

 background-color: white

after calling the sidebar

## Testcase

https://jsfiddle.net/ivangomes/frtmsax2/10/

## Version
Fomantic UI - 2.9.0-beta.312+86121ef

**Comment by lubber-de** [comment]
Thats because of the sidebar logic need to have your content inside a `pusher`
if you also add your background value to the `.pusher` element, it seems to work as you expect.
https://jsfiddle.net/lubber/fev9csz5/2/

**Comment by ivangomes** [comment]
Thank you @lubber-de
