### ISSUE TITLE
[Form] Submit via enter with one field is broken (submit twice)

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2462]
# Bug Report

reproducible on 1st form https://dev.agiletoolkit.org/demos/form/form.php - open a browser's developer console, focus the 1st form field and press enter. Notice, the form is submit twice. (when form is submit via submit/Subscribe button, form is submitted correctly only once)

related atk4/ui issue: https://github.com/atk4/ui/issues/1789

initializing the Fomantic UI form with `keyboardShortcuts: false` solves the problem, but the problem should be fixed in next Fomantic UI release

I belive the problem is in Fomantic UI because the issue is present only when the form has exactly ONE field. With multiple fields, the problem is NOT present, neither when pressing enter on first nor last field.

**Comment by lubber-de** [comment]
Fixed by #2038 
https://jsfiddle.net/lubber/e83wr4ub/9/
