### ISSUE TITLE
[build] version in semantic.css should be mentioned only once

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2468]
# Feature Request

`semantic.css` file is built from many source files and all of them have version in a CSS comment. This is a feature request to remove such comments when merging into one file (ie. put version on top of the file only once) to allow easier diff.

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/2228672/192240167-270ca6d3-46ad-4e45-a5b2-f175266fa225.png)

also the build year should be removed:

![image](https://user-images.githubusercontent.com/2228672/192241309-11a1ed37-b75c-4cf9-96e7-d429bb728c2a.png)

in favor of `Copyright GitHub Contributors`

**Comment by lubber-de** [comment]
The (multiple) comment header is (at least) already removed inside the minimized files (semantic.min.js).
What's wrong with the build year? It is bound to a specific version release, which in turn happened in a specific year :thinking:

**Comment by mvorisek** [comment]
> The (multiple) comment header is (at least) already removed inside the minimized files (semantic.min.js).

in non minified files, the version should be mentioned only once per file to prevent many other changed lines

> What's wrong with the build year? It is bound to a specific version release, which in turn happened in a specific year 🤔

we started building Fomantic UI in our CI and assert the commited files are 1:1, my point is the year must not change when actual year changes - is the copyright year defined somewhere statically or will it change when we will build the files "next year"?

**Comment by mvorisek** [comment]
> We could think about making such internal variables customizable via semantic.json so your CI could provide a fixed value

I would expect the year to be fixed and changed on release/"nightly build/tag"

**Comment by mvorisek** [comment]
the non-stable year should be fixed by hardcoding the current year in https://github.com/fomantic/Fomantic-UI/blob/863d7123323f642238daaa5c92f005073fb9e204/tasks/config/project/release.js#L47 like other constants or removing year completely

**Comment by lubber-de** [comment]
> if the Fomantic-UI build cannot be easily adjusted, I would prefer the regex to be applied officially in the build process

i quickly tried 2 approaches 
- gulp-decomment (which will also remove any other comments in the non-minimized file...which does not really hurt...but maybe not desired for debuggin ?)
- uglify ... well this was really ugly, as it did not only remove the comments but completely reformats the code (there is no (working)option to really only remove the comments)... i discarded that approach quickly as i wasnt sure the original code is till completely working

**Comment by mvorisek** [comment]
I find other comments helpful to better understand the code and locate the original source component/file.

**Comment by lubber-de** [comment]
> here is how I solved this using regex: [atk4/ui@d762ae1#diff-dd4b1be756ae0f06ec70a162b6d3cc20aba8a6f33c3a567aa17ff3bd4bd4ed01R194-R207](https://github.com/atk4/ui/commit/d762ae18ee6a8d8d41ade5f7a066ee737ef19c23#diff-dd4b1be756ae0f06ec70a162b6d3cc20aba8a6f33c3a567aa17ff3bd4bd4ed01R194-R207)
> 
> if the Fomantic-UI build cannot be easily adjusted, I would prefer the regex to be applied officially in the build process

I created #2498  using your regex as base (thanks! 👍🏼 )
This will allow to customize everything you werementioning via your own `semantic.json`
