### ISSUE TITLE
[API] meta data action is not being called and throwing an missingURL error

### ISSUE THREAD

**Issue by iappa1** [fomantic/Fomantic-UI#2473]
Hi All,
I am using semantic UI API and when I specified the action in meta data it's giving me error: 
API : No URL specified for api event
Basically, I am facing the same issue with  a div element.
`<div class="dashboard-top cards-row js-list-fetch loading" data-action="get all items">`

and defined global settings like 
```
$.fn.api.settings.api = {
	"get all items": "/items"
}
```
and initialising like below don't work
```
$(".js-list-fetch").api({
		on: "now"
                 .....
});
```

but the following works
```
$(".js-list-fetch").api({
		on: "now",
                action: 'get all items'
                 .....
});
```

and when it don't work, it produces message like
**API : No URL specified for api event**  
Please help me resolve this.

**Comment by iappa1** [comment]
Thanks @lubber-de for quick response. 
It's happening for me when I am using it in a global scripts.js file and running in production environment(using grunt to bundle and minify and FYI, my app is based on sails js)

**Comment by lubber-de** [comment]
Pleae prepare a jsfiddle where we can reproduce your issue (you may adjust my example above), otherwise we cannot help if your issue is related on other framework/custom code. I am closing this until you can provide such jsfiddle for housekeeping.

**Comment by lubber-de** [comment]
@iappa1 Last thing i can imagine: You most probably set the global api URL _after_ you have initialized the api.
When i am doing this  using the jsfiddle above, the problem also occurs. See https://jsfiddle.net/lubber/6psh8mfq/1/

So you may check your build workflow / grunt bundler to make sure the api setting code inside your global scripts.js is included / running before before the api calltakes place (so just as i did in https://jsfiddle.net/lubber/n7tjhvga/3/
