### ISSUE TITLE
[Accordion] expand/close animation is not smooth

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2479]
# Bug Report

## Steps to reproduce

1. open https://dev.agiletoolkit.org/demos/form/form-section.php
2. navigate to `Accordion Section in Form`
3. click `Section 1` accordion title
4. click it again and notice the close animation is very jerky

## Expected result

both accordion section open/close must be reasonably smooth

## Actual result

especially the close animation is very noticeably jerky

## Version

2.8.8 and also the latest 2.9.0 beta

**Comment by lubber-de** [comment]
The forced `min-height` of your content node is causing this. You should either remove it or add the min-height style to your custom id node (first child of your content) to fix it

**Comment by mvorisek** [comment]
thank you for the hint, super smooth then :)
