### ISSUE TITLE
[transition] "Element is no longer attached to DOM" animate error

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2481]
# Bug Report

<details>
  <summary>original report for fixed issue, see post below for a report of related but still present issue</summary>

## Steps to reproduce
1. open https://jsfiddle.net/65rgakbm/3/ (repro reply can be downloaded from https://github.com/atk4/ui/blob/292e18208b2b8f32551cc0ad037c93c6d87e9533/repro.json)
2. click "Save" button
3. click "Section 1" accordion section title (to expand it)
4. notice
   ![image](https://user-images.githubusercontent.com/2228672/193636513-a6c3f8bd-6b2a-4c8b-b6c0-f20136782e0b.png)
   in the browser console

Observations:

When accordion section is opened before "Save", the problem is not present.

When AJAX return non-toast like `alert`, example response:
```
{
    "success": true,
    "message": null,
    "atkjs": "alert(\"x\")",
    "portals": []
}
```
the issue is not present neither.

There is some atk4/ui js code involved - https://github.com/atk4/ui/tree/develop/js/src/services - but based on the stack trace, the issue seems to be in Fomantic-UI.

I did my best to be minimize the code needed to reproduce, but once the issue is identified, it can be probably simplified even more, ie. /wo AJAX toast reply needed.

Browser: Firefox

## Expected result

No error in browser console, accordion section must always close/open.

## Actual result

Browser console error, when accordion section is reopened, it is blank.

## Version

2.8.8
</details>

**Comment by mvorisek** [comment]
fixed in latest 2.9.0 beta, also a duplicate of https://github.com/fomantic/Fomantic-UI/issues/2412

**Comment by mvorisek** [comment]
reopening as #2412 fixed https://github.com/atk4/ui/issues/1821 but not https://github.com/atk4/ui/issues/1817, tested with `Fomantic UI - 2.9.0-beta.320+c4b3a74` version.

how to reproduce:

1. see https://github.com/atk4/ui/issues/1817 issue and hosted https://dev.agiletoolkit.org/demos/form-control/lookup.php public demo
2. copy these loaded
   ![image](https://user-images.githubusercontent.com/2228672/193902970-cba6e06d-45bf-4b5e-8f7c-b9fcdbaaa660.png)
   resources locally
3. copy the latest Fomantic UI 2.9.0 beta resources (semantic.js/css files)
4. in the public demo, fire the Save and save the AJAX response locally too
5. update the saved demo with links to the saved local resources/reply
6. notice the problem described in https://github.com/atk4/ui/issues/1817 is still present

![image](https://user-images.githubusercontent.com/2228672/193904099-4b9f5182-687b-45a7-a742-961c3682709f.png)

**Comment by lubber-de** [comment]
Please try to reduce the testcase into a simple jsfiddle. debugging through the whole minimized atk.min.js to figure out what it happening after the ajax response isn't fun....  
The interesting part would be what happens after the ajax request responds. Maybe the form validation is triggered and the form is set to be inline ?

You may try to reuse the example from https://fomantic-ui.com/behaviors/form.html#reset--clear-fields where a form with inline prompts is given. 

And your use case seem to also happen on Chrome, while #2417 was fixing a firefox only situation, this really need a quick reproducable testcase with a minimum of code needed.

**Comment by mvorisek** [comment]
I will create a test repo with a static html and local unminified resources.

**Comment by mvorisek** [comment]
here is a repro code /w static/rendered html and Fomantic-UI 2.9.0 beta 320 - https://github.com/atk4/ui/tree/repro_unattached_dom_fui2481/repro_fui2481

the atk4/ui glue logic js files are not-minified

repro code can be also tested thru https://raw.githack.com/atk4/ui/repro_unattached_dom_fui2481/repro_fui2481/page.html

**Comment by lubber-de** [comment]
Thanks for the reproducable code.

Your ajax response returns a field id where a prompt should be added. But "atk_fp_country__id" is not available inside the form, thus no identifiers for the field are found , nor the field group `.field` is found nor any prompt inside the (non existing group) is found. The `add prompt` behavior then tries to create a dynamic prompt, but this fails as the fieldGroup is not available. In the end it tries to transition a node which does not exist in the DOM and this is what the transition warning is telling you.

I added a debug warning so you can see the cause of the issue by #2484

**Comment by mvorisek** [comment]
Thank you. jQuery is silent when a contructor matches zero elements and in Fomantic-UI it cannot probably be addressed in general neither.

https://github.com/fomantic/Fomantic-UI/pull/2484 LGTM to help with debugging simillar usecases. maybe it can produce even a console warning 👍

closing this issue as the problem is in atk4/ui where we can even add assertions around `$('#...')` selectors as exactly one element is always expected
