### ISSUE TITLE
[form] `pointer-events: none` should be removed

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2486]
# Bug Report

`pointer-events: none` CSS rule for disabled form fields is preventing any mouse operations with the disabled field like:

- select and copy field text
- resize textarea (using drag of the bottom-right corner)

demo: https://dev.agiletoolkit.org/demos/form-control/input2.php

The `pointer-events: none` CSS rule should be removed.

**Comment by lubber-de** [comment]
I am not sure if this is the right intention. This was implemented in SUI because of https://github.com/Semantic-Org/Semantic-UI/issues/555#issuecomment-134414889.
Just removing it might have impact on other unwanted behaviors like hover , so we have to test this for every possible form component (dont forget dropdowns, checkboxes , etc.)

Anyway, you can still mark the content of the inputs/textarea by double clicking on the text. Yes, textarea resize does not work, but i wonder, if this is really wanted on a disabled field.

**Comment by prudho** [comment]
Agreed with @lubber-de. `disabled` mean that the field is at an unusable state atm. If I want to do some action with a field, then you should use the attribute `readonly` instead.

**Comment by lubber-de** [comment]
I prepared #2538 so you could set the value to 'auto' instead of 'none' if desired via a variable

**Comment by mvorisek** [comment]
thank you - the more we do customize/parametrize Fomantic-UI, is there any Fomantic-UI testing suite we can run in our CI?

**Comment by lubber-de** [comment]
There is https://fomantic-ui.com/kitchen-sink.html
 
For the dark theme approaches, I once prepare a jsfiddle containing almost every component (but several variations are possibly missing).
https://jsfiddle.net/lubber/vpgyu9j1/

**Comment by mvorisek** [comment]
I mean a testing suite runnable from CLI like https://github.com/atk4/ui/blob/54e8e90ea33dbbca6970d676b720fd8c69bf7352/tests-behat - Behat cannot detect cosmetic problems, but asserts if all required elements are visible, interactable and provide correct results.

**Comment by lubber-de** [comment]
This is really something we should have and we don't at the moment.
Any suggestions?

**Comment by mvorisek** [comment]
The whole idea around atk4/ui framework is everything is in PHP, tests and even the frontend :)

so if tests can be run via PHP, I can recommend https://github.com/Behat/Behat, but any testing software with webdriver support should work

I should also mention Istanbul - https://github.com/istanbuljs/nyc - it can collect JS coverage from real webdriver testing, adding it to the CI is quite simple - https://github.com/atk4/ui/pull/1891/files, here is an example output https://app.codecov.io/gh/atk4/ui/blob/develop/js/src/services/modal.service.js
