### ISSUE TITLE
[Question] Calendar component vs mdehoog calendar.

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#249]
Hi,

Today I'm using semantic-ui with [mdehoog's calendar component](https://github.com/mdehoog/Semantic-UI-Calendar).
I'm planing to move to fomantic-ui, but it has the calendar module integrated to fomantic-ui. 

Is the calendar module the exactly same? just forked into fomantic-ui? or is there any differences in the api?

**Comment by hammy2899** [comment]
The calendar component in FUI is the exact same as mdehoog's repo. In fact, we merged the repo into FUI.

You can see the issue [here](https://github.com/fomantic/Fomantic-UI/issues/8) where you can find some more information.

**Comment by hakeem86** [comment]
Complete forgot to say thank you.. thanks for the answer :)
