### ISSUE TITLE
[modal] tab key is not trapped on modal open

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2490]
# Bug Report

## Steps to reproduce

1. have a page with several links (`<a...` tags) and a button which can open a modal (with blured background) on click with 2 input fields
2. click the button to open the modal
3. press `tab` key on keyboard and notice the links can/are focused (browser usually shows the focused link URL in the bottom left browser window corner)
4. notice, once you cycle thru all the links and move the tab/focus into the modal input, the tab is then trapped correctly (cycles in modal input fields only), given this fact/functionality, I belive the tab key must be trapped immediatelly on open

env: FIrefox, modal `observeChanges` enabled

## Expected result

tab key is trapped immediatelly once the modal is open

## Actual result

tab key is NOT trapped until it hit some focusable element in the modal for the first time

## Version

2.9.0

**Comment by lubber-de** [comment]
Do you happen to have `autoFocus: false` set? otherwise it should work, have to create a testcase for that

**Comment by mvorisek** [comment]
I seached our complete codebase for `autoFocus` and we never set/clear such option.

But we load the AJAX modal content using AJAX.

We create modal first, show loading icon inside and then replace the content. It seems Fomantic-UI does handle the `autoFocus` if there is no input field to focus initially (there is only a loading icon image).

\- on load:
I would expect Fomantic-UI to trap the tab even for usecase when there is no input field to focus initially.

\- on modal refresh (at least with observeChanges):
I would expect Fomantic-UI to check if any input is focused, if not, focus the first input as if the modal is newly open.

**Comment by lubber-de** [comment]
Ok, that's a valid use case. Thanks for explanation. Will fix that

**Comment by lubber-de** [comment]
Fixed by #2575
