### ISSUE TITLE
Fixed menu dropdown sub-menu not working

### ISSUE THREAD

**Issue by jakkepedder** [fomantic/Fomantic-UI#2500]
# Bug Report
Sub-menu in Dropdown in Menu is not working as expected. The sub-menu does not pop-out but stays inside the "area" and you must scroll to the side or up and down to see the sub-menu item.

## Steps to reproduce
1. Go to https://fomantic-ui.com/examples/fixed.html
2. Go to the menu and open Dropdown
3. Open Sub-Menu

## Expected result
In Fomantic-UI 2.8.8 the sub-menu pop-outs as if it is a normal dropdown with sub-menu

## Actual result
The sub-menu does not pop-out but stays inside the "area" and you must scroll to the side or up and down to see the sub-menu item

## Testcase
Go to https://fomantic-ui.com/examples/fixed.html

## Screenshot (if possible)
<img width="696" alt="fixedmenu" src="https://user-images.githubusercontent.com/48975829/195980803-608b5a00-26ab-4416-a1fe-f5801a6fc267.png">

## Version
2.9.0

**Comment by prudho** [comment]
@lubber-de seems to be introducted by 344ec4c7df7e6e5e2e458c7861f2fc901a755836. Reverting the `overflow` rule to `visible` fixes it, but i'm no sure about consequences elsewhere.

**Comment by lubber-de** [comment]
Yes, the examples from #2219 wont work when just reverting the overflow setting.
I'll investigate how to fix both 😉

**Comment by lubber-de** [comment]
Fixed by #2561
