### ISSUE TITLE
[scope] node does not support 12

### ISSUE THREAD

**Issue by 332lfgb6** [fomantic/Fomantic-UI#2511]
# Bug Report

## Steps to reproduce
![image](https://user-images.githubusercontent.com/51245335/196422086-bd5793ef-b80b-4d55-b0e7-8264cc95d88e.png)

![image](https://user-images.githubusercontent.com/51245335/196421985-760592f1-01a5-447b-a36a-94165383a074.png)

## Expected result
node support 12, because node 12 support windows7

## Actual result
node does not support 12

## Node version
```v12.22.10```

**Comment by lubber-de** [comment]
Fixed by #2512 
In the meantime you can use `yarn add fomantic-ui --ignore-engines`
