### ISSUE TITLE
[build] Many "Created:" lines without explanation

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2513]
# Bug Report

## Steps to reproduce
1. `npx gulp build`

## Expected result

Understandable output that is letting the developer to know what is going on.

## Actual result

![image](https://user-images.githubusercontent.com/2228672/195956164-65d4bb68-ae26-4d62-b3e5-8b29596b9d64.png)

## Version

2.9.0

**Comment by lubber-de** [comment]
Is the text really not there? Or is it the same color as the background? Can you mark/select a possible invisible text after the "created"?

**Comment by lubber-de** [comment]
see, the time values are "after" are invisible as well for you, i my guess is your local color settings are causing this

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/196483006-53964945-c663-4be8-8266-395fb761dee3.png)

Windows 10x 64 + Powershell

tested on 2 different machines

**Comment by mvorisek** [comment]
![image](https://user-images.githubusercontent.com/2228672/196483618-28017dca-d9ee-4f7d-b9e7-4f7a826a7ef8.png)

you are right about the colors! The text is there, but the text color is wrongly unified to the background color.

**Comment by lubber-de** [comment]
Do you happen to have changed the powershell/win/ansi default colors? Maybe this helps
https://4sysops.com/wiki/change-powershell-console-syntax-highlighting-colors-of-psreadline/

When i am using Powershell (win 11) i have the same output as via cmd.exe: Both black background, magenta colors)
![image](https://user-images.githubusercontent.com/18379884/196486714-7bd0cdde-2522-45ca-96ec-7bc05b6fe694.png)

**Comment by mvorisek** [comment]
Definitely default settings, I tested in on two Windows machines, one with very clean/factory configured one.

Windows 10 needs probably some configuration like https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes . I am closing this issue for now as it is probably fixed in Windows 11 and linux users are not affected at all.
