### ISSUE TITLE
[Progress] Multiple Progress Bar Doesn't Show Custom Labels

### ISSUE THREAD

**Issue by TSyndrome** [fomantic/Fomantic-UI#2518]
# Bug Report

## Steps to reproduce

1. Use doc snippet [code](https://fomantic-ui.com/modules/progress.html#multiple-bars-with-text-proportion) for multiple progress bars
2. Add custom label in the div tag
3. Can only see % value and not custom text appended to it

## Expected result

Multiple progress bar should show custom labels
![image](https://user-images.githubusercontent.com/407935/197228765-33b15978-0002-4ef4-8593-0e68f635c83a.png)

## Actual result

each bar should have % along with my custom text
![image](https://user-images.githubusercontent.com/407935/197228848-c263324b-579d-46c7-81a4-65087604fb3b.png)

## Testcase

https://jsfiddle.net/73wktb9m/2/

## Version

2.9

**Comment by lubber-de** [comment]
You have to adjust the settings for `text` to make this work. 
```javascript
  text: {
  	percent : '{bar} {percent}%',
  	bars: ['WIP', 'TRY', 'TO', 'WORK']
  }
```
However the third progress is too small by the percentage so the text isn't readable
See https://jsfiddle.net/lubber/vm67sb4n/2/

I have to admit, the example in the docs should also show the related JS to make this more clear. I added that to the docs by https://github.com/fomantic/Fomantic-UI-Docs/pull/391
