### ISSUE TITLE
API generates wrong json structures when using formdata and dynamic arrays

### ISSUE THREAD

**Issue by lfpommes** [fomantic/Fomantic-UI#2520]
# Bug Report
The new version of fomantic 2.9.0 has an optimization when using formdata serialization. This causes an error when using arrays as names.
Formdata looks like: "item[][name]=1" "item[][name]=2". 
This will result in 
{ "item": [
         "name": 1
     ],
     [
         "name" : [ 1, 2 ]
     ]
}
## Steps to reproduce
using html form data with brackets as names:
<input type="hidden" name="item[][article]" value="1" />
<input type="hidden" name="item[][article]" value="2" />
 we are using the form-bahavior with additional api:
 $(".ui.form").form({
	    inline : true,
		on     : 'blur'
  	}).api({
			 url: "/api/table/{id}/order",
	         method:"POST",
	         serializeForm: true,
...
## Expected result
{ "item": [
         "name": 1
     ],
     [
         "name" : 2 
     ]
}
## Actual result
{ "item": [
         "name": 1
     ],
     [
         "name" : [ 1, 2 ]
     ]
}

## resultion
To resolve the issue, we have to remove the line 471 in api.js
"value = pushValues[pushKey];"

## Version
2.9.0

**Comment by lubber-de** [comment]
Fixed by #2562
