### ISSUE TITLE
[label] pulsating circular labels

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2522]
# Feature Request
It would be quite nice to show a circular label as pulsating outwards if data is updated live and wanted the end user to draw attention to it, without the actual label itself moving (like the transition modules)

## Example (if possible)
![IMG_1436](https://user-images.githubusercontent.com/1376843/197411791-bd1c6992-c94e-4ac1-988e-c2970f2b6d38.jpeg)

**Comment by lubber-de** [comment]
Implemented by #2544
