### ISSUE TITLE
[Input][Form] Everything is not Perfectly Align

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#2529]
# Bug Report
I found that in the new version, everything is not perfectly align, for example in this image:

![Capture](https://user-images.githubusercontent.com/28552977/199010139-17d7518a-3f83-464e-9351-e59c48532846.PNG)

Looks like everything seem to go up a bit.

I tried to use the FUI CSS old version (2.9.0-beta.163 or 2.9.0-beta.301+42e68bc), and everything perfectly align again. 
## Testcase
https://jsfiddle.net/KiddoV/x5tjgcLk/17/

## Version
2.9.0

**Comment by lubber-de** [comment]
Something is wrong with the original Lato 2.0 font 😢 causing this.
Have to investigate and compare Lato 1 from google via FontForge 

Testfiddle adds font "bla", which is Lato 1 from google and removes the issue.
https://jsfiddle.net/lubber/hjoe4n8b/12/

**Comment by lubber-de** [comment]
Fixed by #2531

**Comment by KiddoV** [comment]
Should we close this issue? 🤔

**Comment by lubber-de** [comment]
We close such issues on the related next release.
