### ISSUE TITLE
[scope] How to disable email input validation in newest version (2.9.0)

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#2533]
In previous versions this problem didnt happen, but in the latest one it happens. The minimum code to reproduce this is at:

https://jsfiddle.net/pksvnr0e/

It has a `email` input field and if I fill it with anything that is not a valid email, it becomes red. It's a nice feature but I would like to disable this, even better if it was possible to be disabled using the `build` in order to minimize the `semantic.js` and `semantic.css` files.

This "problem" started happening only in the latest version. 

Thank you in advance for all the great work!

**Comment by lubber-de** [comment]
At the moment you would need to exlude the `error` state from `@variationFormStates`. But,tbh, the error state is most probably needed all the time. 
I prepared #2534  to be able to exclude the automatic browser validation styling

**Comment by batata004** [comment]
Unfortunately I really need `error` for other components. Anyway, I appreciate your attention and I am glad FUI is still alive and being mantained! You guys are doing a great job!

**Comment by exoego** [comment]
Not closed yet
