### ISSUE TITLE
[statistic] fluid statistic

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2536]
# Feature Request
At present, if one just wants to show one statistic and have it centred taking up the available width (as opposed to it just appearing) one needs to wrap it with `ui one statistics`

I propose that optionally the same can be done by adding the `fluid` class

## Example

So instead of:
```
<div class="ui segment">
  <div class="ui one statistics">
    <div class="statistic">
      <div class="value">
        5,550
      </div>
      <div class="label">
        Downloads
      </div>
    </div>
  </div>
</div>
```

One could do:
```
<div class="ui segment">
  <div class="ui fluid statistic">
    <div class="value">
      5,550
    </div>
    <div class="label">
      Downloads
    </div>
  </div>
</div>
```

**Comment by lubber-de** [comment]
Added by #2568
