### ISSUE TITLE
Dropdown and forceSelection=true; can't click away from dropdown

### ISSUE THREAD

**Issue by scblack** [fomantic/Fomantic-UI#2537]
# Bug Report
When using the Dropdown module with forceSelection=true, after selecting a list item _by clicking on it_, if the user clicks elsewhere, the dropdown opens and immediately closes without allowing focus to go to a different input. If the user selects an option by using the tab key, then it works as expected. The issue is evident in Chromium-based browsers, but not in Firefox. The issue is evident in Fomantic-UI 2.9.0 and jQuery 3.6.x. Using an older version of Fomantic-UI or jQuery does not produce the issue.

## Steps to reproduce
1. Use Chrome, Edge, or another Chromium-based browser
2. Use Fomantic-UI 2.9.0 and jQuery 3.6 or 3.6.1
3. Add a dropdown with forceSelection = true
4. On the page, click the dropdown and click on a list item to select it
5. Click on another field on the page

## Expected result
The other field should take focus.

## Actual result
The dropdown opens and closes. The other field does not take focus.

## Testcase
https://jsfiddle.net/qjd7ur6L/
1. Click State dropdown.
2. Click Alabama
3. Click the Search textbox. The State dropdown opens and closes, and the Search textbox does not take focus.

## Version
2.9.0
jQuery 3.6.x

**Comment by lubber-de** [comment]
Fixed by #2634 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/thzxcjp4/4/
