### ISSUE TITLE
[dropdown] it's impossible to paste text into multiple selection remote content dropdown (starting from 2.9.0)

### ISSUE THREAD

**Issue by Thanty** [fomantic/Fomantic-UI#2541]
Greetings!

Starting from version 2.9.0 it's impossible to paste text from clipboard into multiple selection remote content dropdown. 
New 2.9.0 logic works great in case you search in previously loaded items. 

```
            if(module.is.multiple() && module.is.searchSelection()) {
              $module
                  .on('paste' + eventNamespace, selector.search, module.event.paste)
              ;
            }
```

Is there a chance to disable this behaviour for multiple remote dropdowns like so?

```
            if(module.is.multiple() && module.is.searchSelection() && !module.is.remote()) {
              ...
            }
```

## Testcase

https://jsfiddle.net/hsL1djun/1/

## Version

2.9.0

**Comment by lubber-de** [comment]
This a bug, as it also happens when not using remote api. If the pasted value is not found in the already (remote or not) item list, the pasted text should just be set as search query... I'll prepare a PR

**Comment by lubber-de** [comment]
Ok, in your specific jsfiddle the `value` is not mapped, thus it always undefined and does not match anything you are pasting
See https://jsfiddle.net/21c7wazy/ and search for "x", then clear the x and paste "x".

However, the search logic for pasted values should be optimized, i'll take care of that too
