### ISSUE TITLE
[input dropdown] Extraneous padding in dropdown when input has left icon

### ISSUE THREAD

**Issue by mat128** [fomantic/Fomantic-UI#2547]
# Bug Report
Since 2.9.0, there is extraneous padding to the left of the dropdown label.
This seems to have been introduced in PR #2183

## Steps to reproduce
Use the right action left icon example from the documentation:
```
<div class="ui right action left icon input">
  <i class="[search icon](https://fomantic-ui.com/elements/icon.html)"></i>
  <input type="text" placeholder="Search">
  <div class="[ui basic floating dropdown button](https://fomantic-ui.com/elements/button.html)">
    <div class="text">This Page</div>
    <i class="[dropdown icon](https://fomantic-ui.com/elements/icon.html)"></i>
    <div class="menu">
      <div class="item">This Organization</div>
      <div class="item">Entire Site</div>
    </div>
  </div>
</div>
```

## Expected result
Padding similar to screenshot from the [2.8 release using archive.org](https://web.archive.org/web/20211220015310/https://fomantic-ui.com/elements/input.html#action).
<img width="712" alt="Screen Shot 2022-11-08 at 2 07 57 PM" src="https://user-images.githubusercontent.com/234168/200653511-28c22419-93d5-4da7-8923-45b2859fb61f.png">

## Actual result
Extraneous padding, see screenshot.
<img width="702" alt="Screen Shot 2022-11-08 at 2 08 07 PM" src="https://user-images.githubusercontent.com/234168/200653528-d25d8cd0-664f-4244-be6f-b147c0d10d46.png">

## Screenshot (if possible)
<img width="2000" alt="Screen Shot 2022-11-08 at 1 52 58 PM" src="https://user-images.githubusercontent.com/234168/200653183-8d3f98ba-0c18-421e-8cfb-4e9b5207a224.png">

## Version
2.9.0

**Comment by lubber-de** [comment]
Fixed by #2576
