### ISSUE TITLE
Calendar refresh after flushing eventDates 

### ISSUE THREAD

**Issue by THBE81** [fomantic/Fomantic-UI#2551]
# Bug Report
It seems the calendar refresh doesn't set back the cells to the default cell style when they are removed from the eventDates array.

## Steps to reproduce
1. Create an inline calendar
2. Add some events with eventDates setting
3. refresh calendar using .calendar('refresh');
4. remove events by passing empty array to eventDates setting
5. refresh calendar using .calendar('refresh');

## Expected result
All the cells are back to default cell style

## Actual result
Once a date has been declared as an event, the corresponding cell keeps the event styling

## Testcase
https://jsfiddle.net/7fg6haze/10/

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/93429118/201338895-da04af80-f0c5-400f-a711-db53ee17bee7.png)

## Version
2.9.0

**Comment by lubber-de** [comment]
The `setting` behavior uses a deep objects extension when the given value is an opject itself. This means it will internally extend the array instead of overwriting it. This is jqueries .extend logic.
To solve this, set the setting "eventDates" explicitely

```javascript
allCalendars
    .calendar('setting', 'eventDates', [
        new Date(2020,5,3),
        new Date(2020,5,7)
      ]
    )
  ;

allCalendars
    .calendar('setting', 'eventDates', [])
  ;
```
See https://jsfiddle.net/lubber/29kyxt3r/1/

**Comment by THBE81** [comment]
Thank you very much for the solution. Tested and all good!
