### ISSUE TITLE
Date change with calendar is not reflected in input

### ISSUE THREAD

**Issue by benzen** [fomantic/Fomantic-UI#2558]
# Bug Report

Date change (with keyboard or mouse) is not reflected in the value attribute of the inner input
https://jsfiddle.net/r3z62g50/7/

## Actual result

When the date is changed, the attribute value from the input element should be updated accordingly.

## Version
2.9.0

**Comment by lubber-de** [comment]
This is not a bug, but a general input field browser behavior. The value attribute contains the default value on render time and the browser creates a DOM node out of it. The calendar field infact changes the input fields value, not it's attribute.
See https://stackoverflow.com/questions/6003819/what-is-the-difference-between-properties-and-attributes-in-html/6004028#6004028
