### ISSUE TITLE
Compatability with jQuery 3.4+ JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos semantic.min.js:11

### ISSUE THREAD

**Issue by freedmandil** [fomantic/Fomantic-UI#2569]
# Bug Report
Basically I'm upgrading our system to be jQuery 3.4+ compliant and Fomantic-UI is giving deprecation errors

## Steps to reproduce 
1. install Jquery Migrate
2. Run Fomantic ui - i.e. use the modal etc.
3. open up developer console and see deprecation warnings related to usage

## Expected result
I was expecting to see no deprecation warnings 

## Actual result
There were deprecation warnings

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/17168031/203349432-4a47480d-1351-410e-a650-a81b7492da11.png)
![image](https://user-images.githubusercontent.com/17168031/203349499-0fd70b8b-c5bf-480c-ab66-9eaac53d2022.png)
![image](https://user-images.githubusercontent.com/17168031/203349698-508ce334-e04e-45cb-82f1-20aacb815feb.png)
![image](https://user-images.githubusercontent.com/17168031/203349777-ab20d92b-7e93-4d00-8bbd-f3a4ea985edc.png)

## Version
2.9.0

**Comment by lubber-de** [comment]
Fixed by #2572
