### ISSUE TITLE
Column width cannot work with scrolling table 

### ISSUE THREAD

**Issue by caleeq** [fomantic/Fomantic-UI#2571]
# Column width cannot work with scrolling table 

## Steps to reproduce
In order to make sure tbody data can align with thead column, I have to add the width class for every row, which looks dumb. Any good idea?

## Expected result
![image](https://user-images.githubusercontent.com/16436405/203542149-74a9c0c2-e6c6-4604-9f37-1a85b8b1cb92.png)

## Actual result
![image](https://user-images.githubusercontent.com/16436405/203541955-bace376d-0929-4dce-a5ec-5b5bb560a342.png)

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/16436405/203542584-7d828cef-e5bc-44f7-a97d-acf224e8f8bc.png)

## Version
2.9.0

**Comment by lubber-de** [comment]
Use `head foot stuck table` instead
See https://jsfiddle.net/lubber/fas7wbey/1/
