### ISSUE TITLE
Possible undesired pull-to-refresh look on iPadOS when using scrolling

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#2573]
# Bug Report
I spotted that by trying the JSFiddle within #2571 on iPad the whole table pulls down (like pull down to refresh). This similarly also happens when using `.scrolling` on a `<table>` (with the `<tbody>` pulling down to refresh). This also happens with a dropdown menu that uses scrolling as well.

## Steps to reproduce
Either table scenario can only be spotted if the table appears without needing to scroll down the page, or if scrolling slightly down the table then back up too far. The same happens on drop-down menus too.

## Expected result
In a way don’t expect it to pull down, unless of course the data will update, but then it may be ‘useful’ to know that one is at the top. Not sure if one can listen to this with JS, or would be useful to implement as a feature if it were to do some kind of refresh . . .

## Possible Solution
For the first (JSFiddle) scenario, the below seems to work in preventing the ‘pull down to refresh’ look:

```
.scrolling {
  overscroll-behavior: none;
}
```

The second scenario seems to like the below:

```
.scrolling tbody {
  overscroll-behavior: none;
}
```

**Comment by lubber-de** [comment]
Implemented by #2574
