### ISSUE TITLE
[sidebar] menu with accordion

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#258]
Hi,

I have made this sidebar with accordion menu items, works great for my projects, but maybe something like this could natively be implemented to (se|fo)mantic-ui?

Just a suggestion.
https://jsfiddle.net/adf13s6b/

**Comment by mpgr04** [comment]
That's truely awesome!
I totaly want to see this implemented - definetly a missing feature!

**Comment by hammy2899** [comment]
I have had to make this sort of menu a few times myself and it seems in demand so we should look to implementing this.

**Comment by prudho** [comment]
This can be already done without adding code to FUI. Here's my implementation: [![444e3eb2d614fef70f15e869f6afb8a2.gif](http://tof.cx/images/2019/01/15/444e3eb2d614fef70f15e869f6afb8a2.gif)](http://tof.cx/image/snX86)

Maybe we should add an example section in next documentation version...

**Comment by prudho** [comment]
@lubber-de it might be possible to do so by adding `exclusive: false` in accordion settings.

@hammy2899 i'm not sure about this. The sidebar should remain component agnostic (i.e. don't rely on anyone else).

**Comment by lubber-de** [comment]
@prudho Awesome hint! Thanks :sunglasses: 
@hakeem86 I adjusted your fiddle accordingly, so you only need one accordion. https://jsfiddle.net/bzw27hxd/
Please tell us, if your feature request is obsolete now

**Comment by hakeem86** [comment]
Thanks I only need one accordion now, but you would still need all the custom CSS to get it to work.. 
Feel free to close it if you think it's obsolete.

**Comment by lubber-de** [comment]
Closing, because i also don't feel we should auto-initiate an accordion when initiating a sidebar.
The solution is shown in the above jsfiddle.
Just because _any_ module could be part of the sidebar. Menus, accordions, calendar, dropdown, progress, search..... And how should sidebar know which attributes any existing module inside sidebar should they be initiated with? Let's keep this to the developer.
