### ISSUE TITLE
[api] Explicitly passed URL should honored over $el.data.url

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2581]
# Bug Report

It seems like a bug, explicitly passed URL to `$el.api()` should be always preffered.

I have discovered this issue in atk4/ui where we set `$modal.url` for our purposes - https://github.com/atk4/ui/blob/4.0.0/js/src/plugins/create-modal.plugin.js#L18 - but then query API using the same element like `$modal.api(...)` with different URL for another purpose.

(for me - https://dev.agiletoolkit.org/demos/interactive/modal.php `Multi Step Modal` is broken for this reason)

## Steps to reproduce

see https://jsfiddle.net/xj02cbog/

## Expected result

Explicitly passed URL is preffered over URL from  jQuery element data.

## Actual result

URL from jQuery element data is preffered.

## Version
2.9.0

**Comment by lubber-de** [comment]
Fixed by #2582  See your adjusted jsfiddle here https://jsfiddle.net/lubber/t5jokpqd/2/
