### ISSUE TITLE
Use font-display parameter

### ISSUE THREAD

**Issue by Atulin** [fomantic/Fomantic-UI#262]
# Feature Request

## Description
Use ``font-display`` descriptor when loading external fonts (Lato), as per [Google's recommendation](https://developers.google.com/web/updates/2016/02/font-display)

## Example
``font-display: swap``

**Comment by hammy2899** [comment]
I have just done some testing and research and this doesn't seem like a bad thing to add. I will add it to the 2.7 milestones.

**Comment by Atulin** [comment]
Nice, Lighthouse audit should stop screaming at me about that 🤣

**Comment by exoego** [comment]
Hmm, Google Font does not support `font-display` yet for 3 years.
https://github.com/google/fonts/issues/358#issuecomment-337299472

If `@font-feature-values` is implemented in browsers, `font-display` can be configured in use-site (FUI/SUI) but it seems not ready in browsers so far.
https://caniuse.com/#search=font-feature-values

**Comment by exoego** [comment]
FYI: Google announced that Google Fonts will soon support font-display https://github.com/google/fonts/issues/358#issuecomment-490730397

**Comment by jsimomaa** [comment]
`display=swap` is also now the default what Google Fonts suggest as the URL to copy: 

![image](https://user-images.githubusercontent.com/4503494/63923577-72dfaf80-ca4f-11e9-9611-ef926a6a77b5.png)

https://fonts.google.com/selection?selection.family=Lato

Would be really nice to see this included in Fomantic-UI (and Fomantics-UI-CSS)!
