### ISSUE TITLE
[theme] MaxCDN  is retiring soon

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#2626]
# Feature Request

Refer https://www.stackpath.com/blog/maxcdn-and-securecdn-are-retiring-heres-what-it-means-for-you

https://github.com/fomantic/Fomantic-UI/blob/0b65a824be9d1117ace8d3ce7f3e7652dc18b4f5/src/themes/default/elements/flag.variables#L8

**Comment by lubber-de** [comment]
Thanks for the hint 👍🏼 
Adjusted CDN links by #2627

**Comment by bborn** [comment]
@lubber-de any chance of pushing this to jsdeliver soon?

**Comment by pulien** [comment]
Hello, 
Could we have a fix for the fomantic-ui-css and fomantic-ui-less versions?
Thanks

**Comment by lubber-de** [comment]
> Hello, Could we have a fix for the fomantic-ui-css and fomantic-ui-less versions? Thanks

Done. See 2.9.1 releases
