### ISSUE TITLE
Flag failed to load SVG

### ISSUE THREAD

**Issue by pengham** [fomantic/Fomantic-UI#2655]
When doing `<i class="sg flag"></i>` , Chrome console will prompt the follow error:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
https://twemoji.maxcdn.com/v/latest/svg/1f1e8-1f1f3.svg

and when I visit https://fomantic-ui.com/elements/flag.html, all the flags there are not working and have similar error message.

![image](https://user-images.githubusercontent.com/71136861/212468756-c2165590-edb9-4d68-b252-aca6aa59e285.png)

**Comment by donaggio** [comment]
Same on Firefox: no error in console, but no icon displayed either

**Comment by jamessampford** [comment]
See #2627

Will need to change from maxCDN to JSDeliver manually until 2.9.1 is released
