### ISSUE TITLE
[Transition] Problem with Default Transition for Popup

### ISSUE THREAD

**Issue by KiddoV** [fomantic/Fomantic-UI#2659]
# Bug Report
I have just updated FUI to ``2.9.1``, and this happened:
The console keep popping up this errors:
![Capture](https://user-images.githubusercontent.com/28552977/212931548-bbaafa4f-04f7-4bfc-9a3f-6350321d4a7a.PNG)

## Steps to reproduce
1. Put a FORM in a popup. (Or anywhere, I am not sure.)
2. Type in the input field.
3. The transition between error and valid make this happen (See gif).

## Expected result
No ERROR would pop up in the console

## Screenshot (if possible)

![bug](https://user-images.githubusercontent.com/28552977/212933034-46950956-510f-47e9-812b-eeae4fa1facd.gif)

## Version

2.9.1

**Comment by lubber-de** [comment]
Fixed by #2661

**Comment by KiddoV** [comment]
That was quick!
Thanks!
