### ISSUE TITLE
Make inputs and search bars work better with icons and labels

### ISSUE THREAD

**Issue by Atulin** [fomantic/Fomantic-UI#266]
# Feature Request

## Description
* search -> right icon left labeled
  * Icon disappears, label is on the right
  * Both input and label retain full border radius 

* search -> left icon right labeled
  * Label retains border radius on the left side 

* right icon left labeled
  * Icon disappears, label is on the right
  * Both retain their full border-radius 

* left icon right labeled
  * Label retains its left border radius 

Both retain their full border-radius 

## Example and testcase
https://jsfiddle.net/Angius/sz5kawre/9/
Added more visible borders to better picture the issue

## Screenshot
![image](https://user-images.githubusercontent.com/11233299/49120047-60133100-f2ab-11e8-8faa-6787bf39ccf6.png)

**Comment by lubber-de** [comment]
Turns out, it all works without any change to FUI as expected, if you always order the dom-tags for icon, input and label in the desired and described order:

#### left icon right labed
```html
<div class="ui left icon right labeled input">
    <i class="icon"></i>
    <input>
    <div class="label"></div>
</div
```

#### right icon left labed
```html
<div class="ui left icon right labeled input">
    <div class="label"></div>
    <input>
    <i class="icon"></i>
</div
```

See here
https://jsfiddle.net/051prbce/1/
