### ISSUE TITLE
[buttons] Wrapped (wrapping/fluid) buttons style is not perfect

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2673]
# Bug Report

When `buttons` are allowed to wrap (/w `wrapping` or `fluid` class), then only the corners of the whole buttons block can be rounded.

## Steps to reproduce

https://jsfiddle.net/9fer5tvz/

## Actual result

![image](https://user-images.githubusercontent.com/2228672/213957124-676766b9-8b54-47ed-8175-ee2087c60301.png)

**Comment by lubber-de** [comment]
Add the additional `wrapped` class to the buttons group to solve this.
See https://jsfiddle.net/lubber/d5veum86/
It cannot be detected automatically via pure css.
Mentioned in the docs here
https://fomantic-ui.com/elements/button.html#wrapping-buttons
![image](https://user-images.githubusercontent.com/18379884/214004315-457685bb-d4b6-4cd1-9d62-8b2363022652.png)

**Comment by mvorisek** [comment]
Thank you for the explanation. Watching all changes with mutation observer will be probably too costly for this small imperfection.
