### ISSUE TITLE
[Form] The "add errors" behavior does not work with inline errors

### ISSUE THREAD

**Issue by designosis** [fomantic/Fomantic-UI#2677]
# Bug Report

The "inline" form setting is excellent. It works beautifully for form validation. However the `add errors` behavior only works without inline.

The jsfiddle below shows the issue. If you run as-is, it breaks. If you comment out `inline: true`, however, it works as expected.

## Steps to reproduce

1. Run the fiddle.
2. Enter a name, and click CONTINUE
4. Examine the errors in the console.
5. Comment out `inline: true`, re-run the code, and repeat 1-2. This time it works.

## Expected result
The error "That's a lovely name" appearing in the inline popup under the name.

## Actual result
An empty popup/arrow thingie and console errors.

## Testcase
https://jsfiddle.net/h8n4kr7a/1/

## Screenshot (if possible)
![Screen Shot 2023-01-26 at 7 33 44 PM](https://user-images.githubusercontent.com/146623/214998033-0e205738-73ee-4935-b59d-a0ec04e07dcf.png)

## Version
2.9.0
(Haven't updated to 2.9.1 yet, but the jsfiddle uses 2.9.1, and the error still happens.)

**Comment by lubber-de** [comment]
You basically used the behavior in a wrong, but i liked your approach to use an object as "errors" parameter for the "add errors" behavior, so i implemened support for that by #2680 

### What was wrong with your code?

`add prompt` is supposed to display a given error to a given identifier. Your omitted the error parameter, therefore it broke
By providing an error String it would have worked as expected
https://jsfiddle.net/lubber/vcxsd3gt/3/

`add errors` was expecting an array of string. You provided an object, which was not support.
As said above, i liked that so it is now supported (you dont need "add prompt" beforehand, as "add errors" is now doing that for you automatically if `inline:true`
https://jsfiddle.net/lubber/vcxsd3gt/2/
