### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by Gokujo** [fomantic/Fomantic-UI#2693]
# Feature Request
Responsive menu items required for better browser and device compatibility

## Example (if possible)
I tried to recreate something I would like to see out of the box. On any resolution, the menu has to be adapted to the device. If some elements couldn't fit in the browser, they had to be collected and put in a tab.

Sample: [jsfiddle](https://jsfiddle.net/Googledono/jedam581/)

## Screenshot (if possible)
![2023-02-07-12-29-45](https://user-images.githubusercontent.com/19776684/217233927-d4b942ff-b16e-4854-b9b0-170e461771ae.gif)

**Comment by lubber-de** [comment]
Did you try the new `wrapping` or `centered fluid wrapping` variants?
https://fomantic-ui.com/collections/menu.html#wrapping
https://fomantic-ui.com/collections/menu.html#centered-fluid-wrapping

**Comment by lubber-de** [comment]
There also exists `stackable` which would put menu elements vertically on smaller devices.
https://fomantic-ui.com/collections/menu.html#stackable
If you expect something completely different please go into more detail or provide an example.

**Comment by lubber-de** [comment]
Closing because of no more feedback and menu is a css only component where existing variations have were mentioned and we won't turn ithe menu component into a js module .
