### ISSUE TITLE
[modal] autofocus should focus inputs only

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2698]
# Feature Request

related with past #2490 / #2674

please see also related issue https://github.com/fomantic/Fomantic-UI/pull/2674#issuecomment-1431561128

Steps to reproduce:
1. open https://dev.agiletoolkit.org/demos/_unit-test/crud-nested.php
2. open modal using "book" icon:
   ![image](https://user-images.githubusercontent.com/2228672/218516669-fa897f6c-93d8-43ea-9c22-199526f40fa7.png)
3. and notice the
   ![image](https://user-images.githubusercontent.com/2228672/218516816-8c6a0d2e-c22d-470a-ad8c-dcc0cdb4f9ee.png)
   paginator item is focused (with blue border)

I expect no hard autofocus by default. I expect the tab key to be trapped only. This is also how browser works when a page is open, nothing is autofocused.

Buttons, anchors etc. should be focuseable by tab key, but not autofocused (the first one) by default.

**Comment by lubber-de** [comment]
Agreed and fixed by #2708 
See https://jsfiddle.net/lubber/rfmb4hdp/3/
