### ISSUE TITLE
Interaction with dropdown inside a modal makes modal to jump to top

### ISSUE THREAD

**Issue by Eizens** [fomantic/Fomantic-UI#2700]
# Bug Report
The following setup is used:
Modal that contains a Form with a long content. The content has one or more Dropdown elements.
When changing / selecting a dropdown value the modal content jumps to the top.

## Steps to reproduce
1. Click button to open a modal.
2. Ensure that dropdown is below initial viewport (so that not entire modal is fully visible).
3. Scroll down to the dropdown.
4. Interact with dropdown (click and select any value).

## Expected result
No scrolling or jumping happens.
Works fine with 2.8.8:
https://jsfiddle.net/zbvhwqm9/1/

## Actual result
Modal instantly jumps/scrolls (no animation) to the top.

## Testcase
https://jsfiddle.net/zbvhwqm9/ (2.9.1)
https://jsfiddle.net/fd34qy61/ (2.9.2)

## Screenshot
![gif](https://user-images.githubusercontent.com/5373178/219048033-80cfc702-8247-486c-a3d7-de1c3b17875a.gif)

## Version
2.9.1

**Comment by lubber-de** [comment]
Fixed by #2708 
See your adjusted jsfiddle here
https://jsfiddle.net/lubber/7qLh8sky/

**Comment by Eizens** [comment]
The reported behaviour seems to be fixed. Thanks!
But I just noticed an additional issue related to the same cause - autofocusing.

When using your adjusted jsfiddle or the original test case jsfiddle, if you click somewhere outside of the results iframe where the modal is opened and then click back into modal (dropdown, input or whatever the place) the first input is autofocused. Even if I explicitly clicked on the dropdown or second input field.
![issue](https://user-images.githubusercontent.com/5373178/220195310-e44d7f33-5ffb-488b-b565-2be7d14e394c.gif)

In 2.8.8 it seems to be working as expected - first click on dropdown or second input field, actually selects that input/dropdown.
![working](https://user-images.githubusercontent.com/5373178/220195511-2a460e16-9eb1-4805-8410-2edef5ebe1b0.gif)

**Comment by lubber-de** [comment]
@Eizens Thanks. I adjusted this behavior so clicked inputs are respected after the window was refocused. If you click somewhere else inside the modal (non focussable elements), the autofocus will again trigger. This will make sure the focustrap stays intact especially when the modals does NOT contain any inputs (so the modal itself gets focussed when clicked)
Adjusted jsfiddle: https://jsfiddle.net/lubber/7qLh8sky/1/

**Comment by Eizens** [comment]
@lubber-de Heh, almost...almost! But it seems that in some cases additional elements needs to be respected. It works as you described until I click on a dropdown placeholder (e.g. "Category" in jsfiddle example).

![placeholder issue](https://user-images.githubusercontent.com/5373178/221296671-911bd6db-3e3f-45f5-8f28-0c435ef6b2e4.gif)

I haven't yet checked cases where, for example, dropdown contains something like a flag, but probably click on that would case the same issue.

**Comment by lubber-de** [comment]
@Eizens Thanks again! I again adjusted the detection, so it should work now when clicking non-focussable elements inside focusable elements (like dropdown/calendar/etc)
See adjusted jsfiddle https://jsfiddle.net/lubber/7qLh8sky/2/

**Comment by Eizens** [comment]
@lubber-de Perfect! Thanks!
Nothing else to add here.
