### ISSUE TITLE
[modal] setting context parameter to $(window.parent.document.body) causes a js error

### ISSUE THREAD

**Issue by g-bonalumi** [fomantic/Fomantic-UI#2701]
# Bug Report

if you try to open a modal in an iframe by setting the `context` parameter to `$(window.parent.document.body)`, the modal will not be displayed and a js error will be generated in the code.

in the example clicking on the "show modal" button
![image](https://user-images.githubusercontent.com/82115010/219425408-3d3f3370-0bef-471e-8f05-6a19d888491d.png)

this is the expected behavior of the component (working up to version 2.8.8)
![image](https://user-images.githubusercontent.com/82115010/219425932-c43825ca-a437-450e-8f0d-5b8d373e20ea.png)

thank you

## Steps to reproduce

1. create an iframe that contains a modal and a button
2. set the `context` parameter of the modal to `$(window.parent.document.body)`
3. bind a `click` event to the button to open the modal 
![image](https://user-images.githubusercontent.com/82115010/219430033-72fd8f2b-7cdc-4d40-bd10-b8914ee3a2b8.png)
4. click the button

## Expected result

the modal is shown in the `window.parent.document.body` element.

works fine with 2.8.8:
https://jsfiddle.net/gary_bonalumi/0vj3mkzf/33/
![image](https://user-images.githubusercontent.com/82115010/219418834-7e3545da-60b3-4bed-8ade-694e5cb8c12a.png)

## Actual result

the modal is not displayed following the error
`TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.bodyMargin (semantic.min.js:11:190970)
    at Object.showDimmer (semantic.min.js:11:189755)
    at Object.showModal (semantic.min.js:11:187698)
    at HTMLDivElement.show (semantic.min.js:11:187424)
    at Object.invoke (semantic.min.js:11:198794)
    at HTMLDivElement.<anonymous> (semantic.min.js:11:199111)
    at Function.each (jquery.min.js:2:3003)
    at E.fn.init.each (jquery.min.js:2:1481)
    at W.fn.modal (semantic.min.js:11:180068)`
## Testcase

https://jsfiddle.net/gary_bonalumi/2bj3Lyaq/23/ (2.9.2)

## Version

2.9.2

**Comment by lubber-de** [comment]
Fixed by #2702 
See your adjusted jsfiddle here [jsfiddle.net/lubber/1z48xugd/1](https://jsfiddle.net/lubber/1z48xugd/1/)
