### ISSUE TITLE
Multiple search controls no longer work in modal / flyout

### ISSUE THREAD

**Issue by ericndar** [fomantic/Fomantic-UI#2703]
This feature worked in 2.8.8.
I have 3 "ui search" components in a form which reside in a modal. When pointing to 2.9.2 only the 1st Search component works. The subsequent 2 appear to be read-only.

Here is a simple example:
https://jsfiddle.net/qro3we4y/1/

**Comment by lubber-de** [comment]
Fixed by #2708 
See your adjusted jsfiddle here
https://jsfiddle.net/lubber/yczjfh27/
