### ISSUE TITLE
[dropdown] Dropdown in Modal captures focus from textarea field upon Enter

### ISSUE THREAD

**Issue by mkrecek234** [fomantic/Fomantic-UI#2723]
# Bug Report
When having a dropdown and a textarea/trumbowyg field in a modal, typing enter in the textarea will move focus to the dropdown field in recent FUI develop version.

## Steps to reproduce
1. Create modal and have a form with dropdown and textarea fields
2. Go to textarea and enter line-breaks ("enter")

The issue did not exist in previous FUI versions, and is unrelated to the used trumbowyg textarea component.

## Expected result
Line-breaks are added in textarea

## Actual result
dropdown captures focus

## Screenshot (if possible)

https://user-images.githubusercontent.com/28671486/222420546-70b83406-7693-4576-8bb1-3e2685f4148f.mov

## Version
2.9.3-beta

**Comment by lubber-de** [comment]
Please provide a reproducable jsfiddle for quicker investigation.
In the meantime use `autoFocus: false;`

**Comment by lubber-de** [comment]
Cannot reproduce unfortunately
When i press enter inside the textarea the fui dropdown does not get focused
It uses
- latest FUI 2.9.3 beta nightly
- latest trumbowyg 2.27.3
 https://jsfiddle.net/lubber/gz1bysnc/2/

 Please adjust the following jsfiddle accordingly so the issue can be reproduced. Thanks

**Comment by mkrecek234** [comment]
Thanks a lot for trying to reproduce. I will check separately if this is related to Atk4/Ui which uses FUI. The jsFiddle which resembles the situation is closer to https://jsfiddle.net/h0q1ntks/ - however also this does not reproduce the issue. Will keep you posted

**Comment by mkrecek234** [comment]
@lubber-de I could correctly reproduce the issue now - it requires the textarea to be pre-filled with some HTML code like the included. Not sure if this is a bug of Trumbowyg which just gets visible now with the new FUI, as before it never created an issue. See here 
https://jsfiddle.net/yk1evctn/

**Comment by lubber-de** [comment]
@mkrecek234 Thanks a lot! I was able to detect the reason and fixed it by #2724 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/krghmwuv/
