### ISSUE TITLE
Issue vertically centering a ribbon

### ISSUE THREAD

**Issue by ben-ekw** [fomantic/Fomantic-UI#2728]
I'm trying to vertically center a ribbon but either the ribbon is not aligned correctly or it won't center vertically:

https://jsfiddle.net/3kzh6pr5/1/

![image](https://user-images.githubusercontent.com/105461985/224450222-aa8f468b-8419-4550-bde3-d69dc48eb04c.png)

https://jsfiddle.net/3kzh6pr5/2/

![image](https://user-images.githubusercontent.com/105461985/224450366-83693917-fd5d-49b6-a556-436349e9915f.png)

Any suggestions?

**Comment by lubber-de** [comment]
Added by #2729 
I adjusted your jsfiddle here https://jsfiddle.net/lubber/tsjzw5am/1/

**Comment by ben-ekw** [comment]
Thanks for the quick response and my apologies for not being clear. I wanted the segment to be centered vertically _on the page_. When the segment is centered vertically on the page the ribbon is too far to the right and when the ribbon is in the right location the segment is stuck at the top of the page and not centered on the page.

**Comment by lubber-de** [comment]
@ben-ekw Ok, then the reason is the nested `center aligned grid`, which also centers the label ribbon.
by removing it from the outer grid, your issue is solved
See https://jsfiddle.net/cv4d6wsx/

**Comment by ben-ekw** [comment]
Awesome, thank you!
