### ISSUE TITLE
[menu] equal width menu

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2732]
# Feature Request
I would love if we could use `equal width menu` in the same fashion than `equal width grid`, where the menu items would be equally sized no matter how much they are.
This would be very convenient in cases the menu items are displayed programatically.

## Example (if possible)
https://jsfiddle.net/1fjabhs5/

**Comment by lubber-de** [comment]
Implemented by #2734 as the feature was pretty simple. 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/tLao3b6c/
