### ISSUE TITLE
[Popup] - content from title has priority over inline content

### ISSUE THREAD

**Issue by jeanjann** [fomantic/Fomantic-UI#2733]
# Bug Report
Popups can specify content in different ways:
    using HTML title attribute
    pre-existing popup markup (with inline: true)
    ...   
When an activating element has a title, the title is used for the popup - although the inline option is set to use the pre-existing markup. IMHO in this case the pre-existing markup should be used.

## Steps to reproduce

1. create a popup with pre-existing content (using option inline: true)
2. add a title to the activating element
3. activate the popup

## Expected result
The popup should show the content from the pre-existing markup

## Actual result
The popup shows the content from the title

## Version
... 2.9.2

**Comment by lubber-de** [comment]
Agreed and fixed by #2736
