### ISSUE TITLE
[menu] Strange margins with attached secondary menu

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2735]
# Bug Report
When attaching a menu and a secondary menu, the secondary menu items have strange top and bottom margins. This might be a matter of taste but I find it does not feel *attached*, like two *primary* attached menus would. I am not sure how to improve this though as I have very poor design skills. I would understand you want to close this ticket.

## Testcase
https://jsfiddle.net/j2qgtr7x/

```html
<div class="ui attached four item menu">
    <a class="item">Foo</a>
    <a class="item">Bar</a>
    <a class="item">Baz</a>
    <a class="item">Boo</a>
</div>
<div class="ui attached four item secondary menu">
    <a class="item">Foo</a>
    <a class="item active">Bar</a>
    <a class="item">Baz</a>
    <a class="item">Boo</a>
</div>
```

## Screenshot (if possible)

Currently :
![Screenshot 2023-03-14 at 23-12-02 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/60163/225154062-6b23f5d1-2d14-4402-8771-1a5b277560a3.png)

This looks better to me with if I fix the CSS with:

```css
.ui.attached.menu .item{
  padding: 13px 0px;
}
```
![Screenshot 2023-03-15 at 09-14-14 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/60163/225247648-2062a78d-d69a-4022-b95e-71644b5332e4.png)

## Version
2.9.2

**Comment by lubber-de** [comment]
I cannot reproduce this. Here is a jsfiddle. Could you please adjust it so we can reproduce your screenshot?
https://jsfiddle.net/3b9avm81/

This looks ok:
![image](https://user-images.githubusercontent.com/18379884/225268269-d89cceee-a10b-4071-8573-07f062b9bfc0.png)

**Comment by lubber-de** [comment]
btw a secondary menu is intended to have a padding around the hover background. "attached" just means the whole menu is attached to the other menu (basically just removing the extra border). The only thing that i cannot reproduce is the different bottom padding which seems smaller than expected in your screenshot. But, as said, i cannot reproduce this

**Comment by lubber-de** [comment]
> On your screenshot, the whitespace around the secondary menu active items looks weird to me, but as I said, maybe this is just a matter of taste?

Yes, that's intended.

But, to achieve what you need, you can try a `borderless menu` instead
https://jsfiddle.net/3b9avm81/2/

![image](https://user-images.githubusercontent.com/18379884/225272869-994208ac-942c-4c78-a464-2356f0a24bf5.png)

**Comment by azmeuk** [comment]
I did not know that option, this is what I needed.
Thank you, and sorry for the noise.
