### ISSUE TITLE
[input] double space in the class name provokes a behavior change

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2738]
# Bug Report
Depending on if a double space is present in the class parameters, an input with an icon and a label will have a display issue where both elements are at the same place.

I am really not sure of what is happening, but I can tell having control on the number of spaces might be tricky when classes are set programatically with a template engine like jinja.

## Steps to reproduce
```html
<!-- here the label and the icon are next to each other -->
<div class="ui corner labeled input right icon">
    <i class="question circle icon"></i>
    <input type="email" value="admin@mydomain.tld">
    <div class="ui corner label">
        <i class="asterisk icon"></i>
    </div>
</div>
<br>

<!-- here the label and the icon are at the same place -->
<div class="ui corner  labeled input right icon">
    <i class="question circle icon"></i>
    <input type="email" value="admin@mydomain.tld">
    <div class="ui corner label">
        <i class="asterisk icon"></i>
    </div>
</div>
```

## Testcase
https://jsfiddle.net/8u5grwx3/45/

## Screenshot (if possible)
![Screenshot 2023-03-16 at 13-04-56 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/60163/225611602-efe7ade1-c854-4846-90c8-d59bf4962a23.png)

## Version
2.9.1

**Comment by azmeuk** [comment]
That makes sense. Is this documented somewhere that I have missed?

**Comment by lubber-de** [comment]
> That makes sense. Is this documented somewhere that I have missed?

I added such info by https://github.com/fomantic/Fomantic-UI-Docs/pull/446 now ;)

**Comment by lubber-de** [comment]
I empowered required word order info in the docs by https://github.com/fomantic/Fomantic-UI-Docs/pull/449
