### ISSUE TITLE
[menu] submit input as pagination menu items

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2739]
# Bug Report

`<input type="submit">` as pagination menu items are not displayed as expected:

```html
<div class="ui pagination menu">
  <div class="disabled item">1</div>
  <div class="disabled item">
    ...
  </div>
  <input type="submit" class="item" value="10">
  <input type="submit" class="item" value="11">
  <input type="submit" class="item" value="12">
</div>
```

## Testcase
https://jsfiddle.net/jwonkc0b/1/

## Screenshot (if possible)

Actual:
![Screenshot 2023-03-16 at 18-56-11 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/60163/225710219-11b2dcbb-b156-416f-8d62-92b9ea353686.png)

Expected:
![Screenshot 2023-03-16 at 19-00-11 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://user-images.githubusercontent.com/60163/225711084-24a43528-53db-49b6-b67e-4c6e5b3bd5e1.png)

## Version

2.9.2

**Comment by lubber-de** [comment]
- input type submit is a button and should be declared as such via `ui button`.
- Having multiple submit buttons as pagination items is an obvioulsy non-real-world example 😉 

However, your example is fixed by a custom CSS selector (which we won't implemend into the core for the above mentioned reasons)
```css
.ui.menu > input[type="submit"] {
  border: none;
  border-left: 1px solid rgba(34, 36, 38, 0.1);
}
```
https://jsfiddle.net/lubber/ckyx7b8a/6/

**Comment by azmeuk** [comment]
> * Having multiple submit buttons as pagination items is an obviously non-real-world example wink

Well, it is actually a real use-case to me but I can understand this might be too edgy to integrate in the core. Anyways, thank you for your help once again.
