### ISSUE TITLE
[Dropdown] Item description dissappear after selection.

### ISSUE THREAD

**Issue by phongha-trueanthem** [fomantic/Fomantic-UI#2757]
# Bug Report

When initializing a dropdown from a `select` tag, the item placeholders or vertical placeholders dissappear after a selection.

## Playground
https://jsfiddle.net/PhongHa/9eyjL718/3/

## Version

2.9.2

**Comment by lubber-de** [comment]
Already fixed in the nightly beta by #2705 (because the mutationobserver was adjusted there which fixes your issue)
See your adjusted jsfiddle here https://jsfiddle.net/lubber/93ws706z/
