### ISSUE TITLE
[dropdown] onChange does not fire when pasting a value in multiple search dropdown.

### ISSUE THREAD

**Issue by tei6** [fomantic/Fomantic-UI#2764]
# Bug Report
onChange does not fire when pasting a value from the clipboard in multiple search dropdown.

## Steps to reproduce
1. Create multiple search dropdown.
2. Paste choice values (e.g., "AL" or "AL, AK") into a multiple search dropdown.

<img src="https://user-images.githubusercontent.com/5271038/233790072-d29f6f11-5a60-4755-b4ee-c1dc50cd6daf.gif" width="400px">

## Expected result
It is expected that onChange will fire when a value is pasted,
just as onChange will fire when a selection is made by clicking on a choice.

## Playground
https://jsfiddle.net/m7x18fvr/1/

## Version
2.9.2

**Comment by lubber-de** [comment]
Fixed by #2765 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/13e0pn8q/

**Comment by tei6** [comment]
@lubber-de 
I can confirm that the issue has been fixed. Thank you for your prompt response!
