### ISSUE TITLE
Snyk: Code Injection Vulnerability

### ISSUE THREAD

**Issue by velsonjr** [fomantic/Fomantic-UI#2770]
When our application was run through Snyk recently, We found Code Injection vulnerability.

Found in: fomantic/src/definitions/behaviors/api.js (line : 594)

Found in: fomantic/src/definitions/behaviors/api.js (line : 926)

Description: Unsanitized input from data from a remote resource flows into setTimeout, where it is executed as JavaScript code. This may result in a Code Injection vulnerability.

**Comment by velsonjr** [comment]
The version would be "fomantic-ui": "^2.9.2"

**Comment by velsonjr** [comment]
[Snyk test report.pdf](https://github.com/fomantic/Fomantic-UI/files/11380684/Snyk.test.report.pdf)

**Comment by lubber-de** [comment]
Fixed by #2771

**Comment by velsonjr** [comment]
@lubber-de Can you please get this merged and let me know the upgraded version?

**Comment by lubber-de** [comment]
@velsonjr It's now available in the latest nightly beta 2.9.3-beta.28
https://www.npmjs.com/package/fomantic-ui/v/2.9.3-beta.28
