### ISSUE TITLE
[menu] Option wrapping in secondary menu with border-right in last-child item

### ISSUE THREAD

**Issue by ursoforte** [fomantic/Fomantic-UI#2772]
# Bug Report
The Wrapping option on new in 2.9.2 is perfect. But when using with the `secondary.menu` option, the last item is gettin a `border-right`. - https://fomantic-ui.com/collections/menu.html#wrapping

## Steps to reproduce
In the collections Menu, adding CSS class `wrapping` with `secondary` option. The last item has a border-right. If you add the CSS `centered` the border-right is removed, but the last item centered is not wanted.

## Expected result
The correct is with border-right none. 

## Testcase
https://jsfiddle.net/crg0qtfo/

## Screenshot (if possible)
The second example is correct.
![image](https://user-images.githubusercontent.com/578063/236010229-b5444d41-fe63-4f76-8f3f-a2675b7ecb8b.png)

## Version
2.9.2

**Comment by lubber-de** [comment]
Fixed by #2774
