### ISSUE TITLE
[bug?] By default, MENU items are not reponsive?

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#2775]
Hi,

I use the MENU feature of Fomantic UI to put at the header of my website all the necessary links (some of the MENU links are dropdown, I mean, when the user hover those links they show more sublinks below). It works great on computers, however on smartphones they dont fit the screen, so usually I hide the menu and I create another HTML element inside an hamburger icon to show the same links/sublinks. I need to duplicate all the links in the MENU to inside the hamburger.

Isnt there any responsive way FOMANTIC UI could solve this? When the screen width is smaller than 600px, then shows an hamburger icon aligned to the right and it places all the links/sublinks inside this hamburger menu automatically? If this is already implemented please forgive me, but I couldnt find it in the docs nor in the demo.

**Comment by lubber-de** [comment]
You could try the new `wrapping` variant which was introduced in 2.9.2
https://fomantic-ui.com/collections/menu.html#wrapping

**Comment by batata004** [comment]
Hello @lubber-de  ! Thanks for replying, but I tried the wrapping demo and look below how it shows:

![image](https://user-images.githubusercontent.com/8988923/236838797-c95bfcfb-bab4-46d8-8d9d-996f0ee4a88f.png)

I emulated an iPhone screen and nothing changed when using the responsive design, the only happened is that the buttons displayed in 4 lines instead of only 2. Am I expecting something wrong?

**Comment by batata004** [comment]
Thank you so much, so it looks like having duplicate menus is still very common on websites. Giving a little bit more thought, it would indeed be very hard to create a good plugin to accomplish that, because there are many use cases (menus with dropdowns, with icons..). Anyway, I appreciate your kindness to reply me here. Have a nice week my dear friend.
