### ISSUE TITLE
[table] `fixed` with `width: 100%` is ignoring scrollbar width

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2785]
# Bug Report

See the repro, with `fixed` the table data are set to `100%` width, but the data on the right side are covered by a scrollbar.

## Steps to reproduce

1. open https://dev.atk4.org/demos/interactive/scroll-grid-container.php

## Expected result

no data covered/hidden by anything

## Actual result

![image](https://github.com/fomantic/Fomantic-UI/assets/2228672/972411c3-f070-4db4-9646-f8ab688b7fe1)

## Version

latest + Firefox

**Comment by lubber-de** [comment]
In your use case the column just isnt wide enough. As the docs say `fixed` uses `table-layout` which does not adjust the columns by its content. Your example would not even display the other missing button inside the last column.

To solve this add a propriate `wide` class to the last column, so it gets a fixed width.
Sidenote: Adding `scrolling` would also remove the need to have the fake extra header 

See https://jsfiddle.net/lubber/807q5h9p/13/

Of course if the the whole table gets too small but also has too many columns at the same time (and also should not stack) the whole table layout inside the related app should be thought about again.

**Comment by mvorisek** [comment]
> Sidenote: Adding `scrolling` would also remove the need to have the fake extra header

separated header is never good, thank you for the native `scrolling` hint
