### ISSUE TITLE
[dropdown] `clearable` is not working when form is initialized with `$('#form_id').form()`

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2791]
# Bug Report

## Steps to reproduce
1. open https://jsfiddle.net/01y3cf9z/
2. select some country
3. notice there is no clearable icon even if the dropdown was initialized with `$('#dd_id').dropdown({ 'clearable': true })`
4. notice when `$('#form_id').form()` is removed, the clearable icon is present with exactly the same steps as described above!

## Expected result

`$('#dd_id').dropdown({ 'clearable': true })` must imply clearable icon always present

## Actual result

clearable icon is not present when form is initialized with Fomantic-UI JS

## Screenshot (if possible)

![image](https://github.com/fomantic/Fomantic-UI/assets/2228672/029b1ed1-37f5-49d5-af15-c53f892a4382)

## Version

2.9.2 / latest

**Comment by mvorisek** [comment]
I have probably identified the main problem. In the jsfiddle, the `.form()` is called on owning div of a form tag instead of on the form tag directly.

Am I right `.form()` must be always called on a `<form>` DOM element only?

**Comment by lubber-de** [comment]
It doesn't matter if `.form` is used on a div or a form tag.
The reason for your behavior is, that you initialized the form before initializing the dropdown.

When a form is initialized it automatically also initializes an existing dropdown or calendar (to be able to set their defaults or bind to a clear/reset event.
I added that important info to the Docs by https://github.com/fomantic/Fomantic-UI-Docs/pull/469

So to solve this, you have two options:

-  Init the dropdown before the form https://jsfiddle.net/lubber/cy7hwxe2/4/
- Only init the form but add `clearable` class to the dropdown (the form init will recognize that when the dropdown gets auto created) https://jsfiddle.net/lubber/cy7hwxe2/3/

BTW: Your jsfiddle included an empty form (the closing tag was set right after the opening form tag)

**Comment by mvorisek** [comment]
## Nested forms theory and current Fomantic-UI impl.

please see https://github.com/atk4/ui/pull/1275
> Nesting html <form> tags is not possible, hovewer they can be closed immediatelly and linked with the input controls/tags, see https://stackoverflow.com/questions/3430214/form-inside-a-form-is-that-alright#21900324
>
> forms spec: https://www.w3.org/TR/html52/sec-forms.html

In atk4/ui all html forms code look like `<div id="fff"><form id="fff_form"></form><input form="fff_form">` to overcome the form tag limitation and allow form nesting. This is the only possible solution per html forms spec.

In atk4/ui I tried to fix all JS `.form()` calls to be done on `form` tag (`$('fff_form').form(` instead of `$('fff').form(`) but this is not working with Fomantic-UI as well, as:

a) `success` class is not added to the owning form div (with id `fff`) causing all success messages to be hidden
b) `$('fff_form').form('add prompt', ...)` errors with `Form: Field identifier email1 not found`

So calling `.form()` on a form tag is not a solution either.

Looking into https://github.com/fomantic/Fomantic-UI/blob/develop/src/definitions/behaviors/form.js code Fomantic-UI simply expects all form components to be a contained in the module element.

## Current atk4/ui impl./usage

In https://github.com/atk4/ui/pull/1275 I found some sweet spot to do some `.form()` calls on the owning div and some on the form tag directly:

- https://github.com/atk4/ui/blob/97515e971970649a9590879b3c0e10a226205d16/src/Form.php#L549 (form initialized on the owning div causing this issue)
- https://github.com/atk4/ui/blob/97515e971970649a9590879b3c0e10a226205d16/src/Form.php#L551 (form api processing on the form tag directly)
- https://github.com/atk4/ui/blob/97515e971970649a9590879b3c0e10a226205d16/src/Form.php#L171 (hack needed because of this back, should be not needed)
- https://github.com/atk4/ui/blob/97515e971970649a9590879b3c0e10a226205d16/src/Form.php#L300 (add prompt on the owning div)

This is obviously a hack. As Fomantic-UI module expects the module to be a parent of all form subviews, I propose to fix the nested forms (via official/W3 immediately self closing form tag) support by:

a) allow to specify the form element selector explicitly
b) if the selector is not specified, locate&use the first form tag relative/within the module
c) if the explicitly passed element is not a form tag or no form tag was found, emit an error

**Comment by lubber-de** [comment]
New setting `ignoreModulesOnInit` implemented by #2793 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/3pLrgvsa/1/

**Comment by lubber-de** [comment]
I started from scratch again, because usually whenever a module is instantiated a second (third, forth...) time, the previous instance gets detroyed, so i was wondering myself because your code should have worked from th every beginning.

So this issue is fixed by https://github.com/fomantic/Fomantic-UI/pull/2794 rather than the other PR which i think will close without merging

See your adjusted original jsfiddle here, which fixes the issue without caring about internal instantiation or not.
https://jsfiddle.net/lubber/n60so4xq/
