### ISSUE TITLE
[css] Allow one special element to be skipped when first child is matched

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2798]
# Feature Request

See https://github.com/atk4/ui/issues/1970 for usecase.

## Expected result

In some special cases, the first child is some technical element, usually hidden, which should not be matched by `:first-child` style. The problem is, when `:first-child` is hardcoded, there is not way for the developer to fix it as long as the technical element needs to be present as the first child.

The solution is simple - https://jsfiddle.net/fg3kcn85/ - replace any `X:first-child` selector with `X:first-child, .ignore-first:first-child + X` where `ignore-first` is a class name, that will tell the browser to select the "2nd element as if it was 1st".

---

In very simillar way https://github.com/atk4/ui/issues/1928#issuecomment-1374440445 can be fixed, ie. fix selectors like `A > B` to `A > B, A > .ignore-wrap > B`.

**Comment by ko2in** [comment]
What you're saying is your custom requirements. You can override the styles of any FUI components from your own CSS file as you've done in your JS fiddle.

Also, there's an option to create the theme for any customization that suits your need.

**Comment by mvorisek** [comment]
I agree this is feature request is quite specific usecase. I can probably postprocess the CSS by myself, but the usecase might be helpful for more users.. How hard will be do postprocess the selectors in regular Fomantic-UI LESS build and how much will the dist CSS size increase?

**Comment by mvorisek** [comment]
> Your empty form tag doesn't even need for visual representation. Isn't it possible to generate last in your markup?

Not easily, as the element can be empty (with the problematic first element inside) and more elements/first can be added later.

But I think I can solve this in my project with:

a) CSS postprocess as proposed in the description
b) OR with JS observer as only a very few DOM ops needs to be monitored...
