### ISSUE TITLE
[Toast] Build from html 

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#280]
## Description
It would be great if it was possible to build toast from HTML.. Would be useful when you have POST some data to the server and you want to show an error/info toast message due to user input error etc. 

## Example
Maybe something like this or another syntax that make more sense. 
>     <div class="toast success compact visible" data-position="top left" data-displayTime="5000">
>         <div class="icon info ui toast">
>             <i class="info icon"></i>
>             <div class="content">
>                 <div>Hello world</div>
>             </div>
>         </div>
>     </div>

> $('.toast').toast();

**Comment by lubber-de** [comment]
We are already working on this feature :wink: Stay tuned.

**Comment by lubber-de** [comment]
Finally possible by #1129
