### ISSUE TITLE
[bug] Dropdown not working as expected

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#2802]
I am using the dropdown with the search and I am using categories. A normal dropdown is like this:

![image](https://github.com/fomantic/Fomantic-UI/assets/8988923/ffb169c1-44f9-4e09-a907-b05a82afb2b3)

You can see in the image above, I searched for "tr" and it correctly displayed 2 categories and inside of each it showed the matches. This is expected. Now see the print below, when I search for "trindade":

![image](https://github.com/fomantic/Fomantic-UI/assets/8988923/3cebefa1-9630-4c5c-8ee6-b688adfd0892)

You can see that Fomantic ui algorithm correctly found the only match, and it displays the Header element (category) and the matched item, however on the other categories it keeps showing all the names of the categories with no items inside. I think the default behaviour should be to hide the all the categories that dont have any items inside that match the search.

This bug only happens with the `dropdown` component, because when I use the `search` component alone it works fine. See the example below (taken directly from your documentation):

![image](https://github.com/fomantic/Fomantic-UI/assets/8988923/1790ab00-828a-428d-a87e-82dbb93e180a)

I searched for the letter `a` and it worked as expected displaying all the categories that have an item that matches. Now take a look when I search for "brazil":

![image](https://github.com/fomantic/Fomantic-UI/assets/8988923/b1f049fd-8508-4f12-8529-1351b3862176)

It correctly displayed the only category that matches the search and hide all the other categories AND items.

The example I gave at the top, you can test in this website https://www.federalsc.com.br -> right at the very top there is a very simple `ui dropdown search` element which you can use to check the bug yourself.

IMHO both components should have a similar behaviour and I believe te correct/expected behaviour is hiding the categories that dont have any items matching the searched item, and this is even more important when the user is using a smartphone where the screen is very small and any space saved it a nice UI practice. Also, the bug reported here makes another items that are matched in the search to be shown at the very bottom of the list because many categories names are shown above which have absolutely no match. So it's a very bad UI practice.

Thanks a lot for all the work you guys are doing!

**Comment by ivangomes** [comment]
@batata004 tudo bem? Me avisa, se você precisar de ajuda com o seu problema okay?

**Comment by batata004** [comment]
> Try `hideDividers: 'empty'` which will give the expected results. You can test in this [fiddle](https://jsfiddle.net/kLxgzo40/).

That worked perfectly thank you so much!

**Comment by batata004** [comment]
> @batata004 tudo bem? Me avisa, se você precisar de ajuda com o seu problema okay?

Obrigadão amigo, agradeço pelo carinho e atenção :)
