### ISSUE TITLE
[input] labeled action input overlap

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2829]
# Bug Report
An input being [labeled](https://fomantic-ui.com/elements/input.html#labeled) and [action](https://fomantic-ui.com/elements/input.html#action) with both elements on the same side does not display correctly: the label and the button overlap where I would have expected them to be displayed side by side.

## Testcase
https://jsfiddle.net/t9w6cv8y/3/

## Screenshot (if possible)

![Capture d’écran du 2023-06-19 18-38-42](https://github.com/fomantic/Fomantic-UI/assets/60163/ac669a85-c3d1-40b5-9040-73d3b0b91a9f)

## Version

2.9.2

**Comment by ko2in** [comment]
You're using `corner labeled` which is supposed to be displayed like in your fiddle. So, there's nothing wrong. Only border-radius should be adjusted.

Are you expecting to have like this?

![input-label-with-action](https://github.com/fomantic/Fomantic-UI/assets/930315/8ee2344f-8850-4d8a-b17f-144a675ba16e)

Here's [fiddle](https://jsfiddle.net/ko2in/6m9rfgno/).

This is only a feature request in my opinion.

**Comment by azmeuk** [comment]
Actually I was looking for something like this:
![Sans titre](https://github.com/fomantic/Fomantic-UI/assets/60163/ef211b4b-4455-4691-87c1-8e10b5946538)

**Comment by ko2in** [comment]
Well, you can use create like [this](https://jsfiddle.net/ko2in/6m9rfgno/9/).

**Comment by azmeuk** [comment]
Ok. I did not realized this was already possible.
Thank you for your help!
