### ISSUE TITLE
[dropdown] the cross for disabled dropdown select items is misleading

### ISSUE THREAD

**Issue by azmeuk** [fomantic/Fomantic-UI#2862]
# Bug Report
`readonly` and `disabled` dropdown still show crosses for the selected items, and to clear the input. 
I would have expected those crosses to not appear, as they suggest users that they can interact with the dropdown.
I would suggest no displaying them.

## Testcase
https://jsfiddle.net/mfowvc2z/

## Screenshot (if possible)
![Screenshot 2023-07-28 at 19-01-03 Fomantic-UI Sandbox - JSFiddle - Code Playground](https://github.com/fomantic/Fomantic-UI/assets/60163/f5d06456-c52a-4ed5-b16f-9b47d0e15ce6)

## Version

2.9.2

**Comment by lubber-de** [comment]
Fixed by #2865 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/18okh92g/5/
