### ISSUE TITLE
[slider] Range slider Value does not go to max when step < 1

### ISSUE THREAD

**Issue by Grosskopf** [fomantic/Fomantic-UI#2877]
# Bug Report
When I initialize a Slider with min 0, max 0.94, start 0.94 and step 0.01, I expect the Value to be 0.94 at the start, it is however roughly 0.93

## Expected result
0.94

## Actual result
0.9299999999999999

## Testcase
[Testcase](https://jsfiddle.net/4robkn7u/1/)

## Version
2.9.2

**Comment by Grosskopf** [comment]
strangely, the values 0.2 and 0.46 work as expected, so it is not only about step being 0.01

**Comment by Grosskopf** [comment]
I believe this to be a floating point rounding issue, adding step * 0.1 to the max value yields the expected result

**Comment by lubber-de** [comment]
Fixed by  #2878 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/qbs3cn9e/1/
