### ISSUE TITLE
Minifying keeping comments

### ISSUE THREAD

**Issue by TivoSoho** [fomantic/Fomantic-UI#2880]
Could the comments for the library version etc be `/* `instead of `/*!` so that they would be removed during minification process? That is a lot of extra info being added. Before we had the option to remove them with a postcss plugin, but with vite there is no option to transform it after it has been converted from scss to css.

**Comment by lubber-de** [comment]
The fomantic inbuild minification via gulp already removes all comments except a single header (which only starts with `/*` (without "!" as you suggested) for the minified file
https://github.com/fomantic/Fomantic-UI/blob/871052f6ae11c8fc117846e98f129d275e7792e1/dist/semantic.min.css#L1

For your custom builds, [you can add `stripHeaders: true` to your semantic.json](https://github.com/fomantic/Fomantic-UI/pull/2498) to completely get rid of the comment headers in the non minified file
