### ISSUE TITLE
code branch icon not displaying

### ISSUE THREAD

**Issue by gbook** [fomantic/Fomantic-UI#2912]
# Bug Report
When displaying the "code" and "code branch" icons, they are not displayed correctly. Other icons do appear correctly. The icon is displayed correctly in the fomantic-ui documentation, so I'm not sure it's a browser issue.

## Steps to reproduce
Display the following code `<i class="cog icon"></i> <i class="code branch icon"></i> <i class="tree icon"></i>`

## Expected result
It should display the code branch icon

## Actual result
It displays a question mark inside a gray box

## Screenshot (if possible)
![image](https://github.com/fomantic/Fomantic-UI/assets/8302215/31b87642-dfbe-414b-8013-f950579700f9)

## Version
2.9.3

**Comment by ko2in** [comment]
I cannot reproduce https://jsfiddle.net/ko2in/gtzv9hnm/. What browser and OS are you using?

**Comment by gbook** [comment]
I couldn't reproduce it either outside of my own website. It's on Windows 10, latest Chrome browser.

But I found the issue... I have a class in my global stylesheet named "code". It is conflicting with icons that have "code" in their class name. If I remove my code class, the icon shows up correctly.

My stylesheet had `div .code { ... }`... with a space. Removing that space fixed the issue and now both my class and the icons work.
