### ISSUE TITLE
Duplicate subtext issue into the dropdown

### ISSUE THREAD

**Issue by vishalmandloi** [fomantic/Fomantic-UI#2930]
![image](https://github.com/fomantic/Fomantic-UI/assets/7326266/4ec396d1-fc35-4bb6-bf88-c789d279f513)

Facing a duplicate subtext issue in the dropdown, although it's not reproducible every time. Please advise on how to address this problem

Thank you,

Vishal

**Comment by ko2in** [comment]
Please provide jsfiddle with the source code that you're using for your dropdown.

**Comment by lubber-de** [comment]
Closing because of no more feedback. Happy to reopen when a reproducable jsfiddle is provided
