### ISSUE TITLE
[form.rule] Rename `empty` rule to be consistent

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2937]
# Feature Request

originally posted in https://github.com/atk4/ui/issues/2129

Currently, the `empty` form rule is very, very confusing as the logic is negated with the remaining names.

`empty` means "nothing", but the rule validates the form field is "filled / not empty".

here https://github.com/atk4/ui/issues/2129#issuecomment-1816389051 is this fact more evident when compared with other rules like `checked` or `is[dog]`

This is a feature request to rename `empty` form rule to something like `notEmpty` or `mandatory`. For BC, the `empty` can be kept with a console warning.

**Comment by mvorisek** [comment]
I would be happy if the better named `empty` rule can be implemented in v2.9.x. The `empty` rule can be deprecated with a console warning (or whatever the minimal default verbosity level it). In v2.10.x, it can be removed or kept until v3.

**Comment by lubber-de** [comment]
Ok, i am preparing a PR. I thought about naming the new rule `required` instead of `notEmpty`?
This would at least fit the existing "autocheckRequired" functionality

Opinions?

**Comment by lubber-de** [comment]
Mmh, `notEmpty` would indeed fit better in the same terms as all the other rules, as the validation checks for "not empty" and not "if the field was required"....

**Comment by jamessampford** [comment]
Perhaps `required` should be added to ensure that there is a value of sorts (even a space)

`notEmpty` on the other hand could check that there is something useful there, but would need to trim the value to make sure that it isn’t just white space (space, tab, new line, etc)

There could possibly be use case where one needs to check that a field is `empty` with no value/whitespace. Such as do not complete this field if entered something elsewhere

**Comment by mvorisek** [comment]
Good points. I personally would prefer one function/name for "the 99%" usecases, ie. a function that will check if the length is not zero after whitespaces are trimmed from the ends.

The reason I do not support additional function to check if an input is:

- strictly empty without trimming
- or "value is empty" like `'0'`

is that the first is not much useful in practice and the second is hard to define and basically any app needs a different criateria, like for some apps `-1` is empty too. So user should define custom rule for these scenarious.

About the name, `required` or `notEmpty` LGTM, I have no preference.

**Comment by mvorisek** [comment]
Thank you for supporting this issue, but `present` is NOT name I support nor frequently used by any common core, especially string, API.

**Comment by lubber-de** [comment]
I prepared that by #2949 
Please take a look 😉
