### ISSUE TITLE
[Visibility] Wrong minimum height set for placeholder element

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#296]
# Bug Report

## Description
When a `.ui.segment` is made fixed using the visibility API, a placeholder element is created 
> to ensure that the page's position does not change when the element is "fixed" and removed from normal layout flow

## Expected result
The placeholder element should have the same height of the "fixed" element

## Actual result
The placeholder element has a `min-height: 18em` CSS property which makes it a lot taller then needed in the majority of cases

## Testcase
https://jsfiddle.net/m97k6rqw/1/

## Version
2.6.4

**Comment by ColinFrick** [comment]
The visibility API uses the class name `placeholder`, which is now used in the new 2.4 placeholder module. Changing the placeholder class name in `visibility.js` should fix this issue:
https://jsfiddle.net/73ysw1zp/

**Comment by hammy2899** [comment]
We will do this for 2.7 since it is an API breaking.
