### ISSUE TITLE
[tooltip] must not be cropped by owning overflow viewport

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2972]
# Bug Report

## Repro

https://jsfiddle.net/bjptg85n/

I belive no FUI component must use `position: relative` as it does not play well with `overflow` and it seems there is no way to recover from the cropped viewport then.

## Screenshot

1. cropped by owning overflow viewport

![image](https://github.com/fomantic/Fomantic-UI/assets/2228672/8efd9bba-995f-4a9f-9f2f-9198c5969539)

2. badly positioned

![image](https://github.com/fomantic/Fomantic-UI/assets/2228672/6b9b78a8-a286-4073-a55e-44eb9f194f9d)

## Version

2.9.3/latest

**Comment by lubber-de** [comment]
Tooltip is a css only solution which needs position relative to make sure the tooltip appears next to the related element.

**Comment by mvorisek** [comment]
Yes, but consider any viewport with scroll, like a table. Such viewport needs `overflow`.

And as the `viewport` is needed, `position: relative` cannot be used.

I belive this must be fixed as the usecase of viewport with scroll and tooltip inside is legit.

**Comment by lubber-de** [comment]
I think, this isn't fixable via CSS only, as we cannot detect (yet) via CSS if an element is actually overflown or wrapped
If one needs this inside an overflowing container, the regular JS "popup" needs to be used instead.

**Comment by lubber-de** [comment]
After a quick investigation, the only fix i can offer is an additional variation class like "absolute" as always using "absolute" will break lots of cases.
For example doing this for https://fomantic-ui.com/modules/popup.html#tooltip-position it will result in
![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/b1627ca0-dc1e-4ca2-9928-ae9e11ca2980)

I also cannot tell if it would be ok for each inline element like the icon you used in the jsfiddle

As i cannot determine a general approach, i can only think of some custom support like

```css
    [data-tooltip][data-variation~="absolute"] {
        position: absolute;
    }
```
would support your use case. (i am not yet sure if "absolute" would be a good enough term though

```html
<span class="ui icon link " data-tooltip="foo" data-variation="absolute"><i class="ui icon info circle blue"></i></span>
```
See https://jsfiddle.net/lubber/ghuxpe80/
![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/3579fae7-532a-4f4b-b680-4393b1dad2ee)

**Comment by lubber-de** [comment]
The "absolute" setting has one drawback: it wont be part of the scrolling container anymore. If you scroll down, the icon gets misplaced (however the tooltip is still working fine :D)
![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/a8ed7a2e-1c6f-4d7b-8ca2-ea2cff431ac4)

Try to scroll down inside the containers
https://jsfiddle.net/lubber/ghuxpe80/2/

**Comment by mvorisek** [comment]
https://jsfiddle.net/x4fkmc7L/ is the best I managed to fix it but it is not a solution, as it requires different HTML structure and known size of the internal content.

I am closing this issue as we should use Fomantic-UI Popup which solves this issue by placing the tooltip div outside the wrapping div (the one with `overflow` set).
