### ISSUE TITLE
[Dropdown] render is very slow with large dataset

### ISSUE THREAD

**Issue by mvorisek** [fomantic/Fomantic-UI#2999]
# Performance Bug Report

## Steps to reproduce

1. open https://dev.atk4.org/demos/form/html-layout.php
2. open F12 console and network tab
3. click "Destination" input field (the once with "Select your destination" placeholder)
4. notice (by observation) the Fomantic-UI dropdown takes some time to open (300 - 1000 ms)
5. notice (in F12 console) the http response itself is fast (about 100 ms)
6. repeat step 3 and notice the dropdown takes even more time to open

the list in the demo has about 200 items (country names), I would expect it to be rendered in less than 10 ms (after http response is fully received)

## Version

latest / 2.9.3

**Comment by lubber-de** [comment]
Mmh, do you happen to use Firefox? Because in chrome, i cannpt reproduce. It's always around 110 - 140ms in total.
Perhaps it's the same reason as of #2971 ? if so, please try the nightly Firefox 123.

**Comment by mvorisek** [comment]
Yes, I use Firefox. I do not have FF 123 on hand, but when I cherrypicked #2973 into atk4/ui the issue is gone. So I can confirm it is a duplicate of #2971.

I agree with https://github.com/fomantic/Fomantic-UI/pull/2973#issuecomment-1887124199 to wait until FF 123 is released so no action is needed.
