### ISSUE TITLE
[dropdown] ui simple dropdown does not work on mobiles

### ISSUE THREAD

**Issue by Bodenhaltung** [fomantic/Fomantic-UI#3018]
# Bug Report
The ui simple dropdown doesn't work on chrome/safari mobile,

I am comming from:
https://github.com/Semantic-Org/Semantic-UI/issues/6465

Using Fomantic-UI now as drop in replacement, which worked fine. But the issue is still there.

Maybe there is a workaround?

I am not very familiar with UI components, sorry about that.

## Testcase
https://reactgirl.github.io/portifolio/issue01.html (Stolen from: https://github.com/Semantic-Org/Semantic-UI/issues/6465)

## Version
2.9.3

**Comment by lubber-de** [comment]
This seems to be an issue on iOS devices only as Android supports `:hover` just as a click would do.
[This page](https://stackoverflow.com/questions/35187970/css-hover-not-working-on-ios-safari-and-chrome) shows some solutions to make it work in iOS as well. (google "ios css hover not working" and you will find lots of general issues. This is not FUI/SUI specific)
You basically need to use a clickable element.

Here is an example which uses `tabindex="0"` on the dropdown and (important!) on body
jsfiddle: https://jsfiddle.net/lubber/ko3zy1es/4/
try directly on mobile: https://fomantic-ui.com/jsfiddle/#!lubber/ko3zy1es/4/

It's all up to your markup, we cannot fix it via CSS only

**Comment by Bodenhaltung** [comment]
wow, thank you!

I don't really understand why, but with `tabindex="0"` it worked also in Safari Mobile.

> This seems to be an issue on iOS devices only
Firefox on iOS always worked

Thanks again! I close this issue.
