### ISSUE TITLE
[bug] modal `closable` set to `true` not closing

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#3030]
Please take a look at this simple code:

https://jsfiddle.net/sb05motp/

It opens a modal (`closable` set to `false`) and after 3 seconds it sets `closable` to `true` but I still cant close the window when clicking in the dimmer/dark region. Am I doing something wrong?

Also, when clicking in the dimmer region I see this error message in the console (using latest Chrome on Win11)

![image](https://github.com/fomantic/Fomantic-UI/assets/8988923/e36ddc85-e0b0-4f77-8153-68e1de5a13d7)

**Comment by GammaGames** [comment]
You're still recreating the modal, you have to change the setting:

```js
$("#janela_mensagem").modal("setting", "closable", true);
```

https://jsfiddle.net/67a9kyj8/

**Comment by batata004** [comment]
In some cases, I really want to recreate the modal because I want all the other settings reverted to default (for example, I may have set `onHide` event and now I want to set `closable` to `true` at the same time that all the other events/settings get reverted to the default).

Yet, this is still a bug, right? Because I call `modal` twice, but at the second time some settings (like `closable`) are not setted correctly. Or is it prohibited to call `modal` twice on the same element?

**Comment by batata004** [comment]
@lubber-de @GammaGames So here is exactly my problem: I already opened a modal (it's already showing to the user). Now I need to change the `onHide` event. As you said in another thread, I cant change `onHide` after the modal is already showed and I also cant change `onHide` using `setting` feature. So how I change the `onHide` after I already opened the modal?

In my specific case, I showed the modal to the user and after the user interact with it (filling a form) I want the `onHide` event to be different depending on the answers the user provided in the form inside the modal.

So how do I change the `onHide` event after the modal is already displayed? I was trying to make a `hack` with `closable` but it didnt work, so I am back to the square 0.

**Comment by lubber-de** [comment]
@batata004 Here you are :)
https://jsfiddle.net/lubber/gv6sudry/

You **can** change `onHide` while the modal is shown, but only via the `setting` behavior (which i explained [in the other thread](https://github.com/fomantic/Fomantic-UI/issues/3020#issuecomment-2014420535))

**Comment by batata004** [comment]
Now I understood what you said! I was being stupid, I was not understanding how the logic worked! Now I do: if I need to change settings on an already opened modal, I need to use `setting`. Thank you so much for your patience with me !
