### ISSUE TITLE
[Cards] Even column count cards bug

### ISSUE THREAD

**Issue by wdmeest** [fomantic/Fomantic-UI#3037]
# Bug Report
When you add an even number of columns to the cards group, that is within a grid div, the number of cards in a row does not match the number of columns of the cards group

## Steps to reproduce
1.Create grid element with two columns, example one with a twelve wide and four wide column 
2. Add cards group (with an even number of column count, example two, four, six, ...) within the grid column element

## Expected result
When card column count is four, we expect to see 4 cards on one row

## Actual result
When card column count is four, we see 3 cards on one row

## Testcase
https://jsfiddle.net/91rcvu7e/

## Version
2.9.3

**Comment by GammaGames** [comment]
I see it in Firefox (it's also really flickery when you resize the window):
![image](https://github.com/fomantic/Fomantic-UI/assets/7832163/0e4a603f-d8f9-4182-a27f-a3268fa34700)

But not Chrome:
![image](https://github.com/fomantic/Fomantic-UI/assets/7832163/9b092cf4-bca9-4c7e-a502-cc6999b92109)

Weird!

**Comment by lubber-de** [comment]
This also happens when not using FUI. Firefox seems to wrongly calculate the width `calc(25% - 1em)` is some cases
I filed an issue using a minimum html/CSS example here https://github.com/webcompat/web-bugs/issues/136609

**Comment by lubber-de** [comment]
I just tries the same jsfiddle using an older firefox version (115) and the issue does not exist there, so it's definately something the the firefox developers have to fix

**Comment by lubber-de** [comment]
I also filed a bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1895485

**Comment by lubber-de** [comment]
Issue is fixed in next Firefox Release

**Comment by wdmeest** [comment]
Thxs for the follow up!
