### ISSUE TITLE
[dropdown] clearable multiple search selection dropdown

### ISSUE THREAD

**Issue by mdrxy** [fomantic/Fomantic-UI#3043]
# Feature Request
I understand that selection dropdowns can be made to allow users to [clear their selection](https://fomantic-ui.com/modules/dropdown.html#clearable-selection), but I can't seem to make this feature work on multi select dropdowns. Each selection pill can be removed individually (via the <kbd>x</kbd> button) though I would appreciate a "clear all" <kbd>x</kbd> for the field like in the screenshot below. 

## Example (if possible)
<img width="784" alt="Screenshot 2024-05-07 at 18 51 03" src="https://github.com/fomantic/Fomantic-UI/assets/61371264/5bdbb7c1-042a-40cd-b028-2043ea20fce8">

## Screenshot (if possible)
<img width="568" alt="Screenshot 2024-05-07 at 18 48 27" src="https://github.com/fomantic/Fomantic-UI/assets/61371264/66d34cd8-85fd-413b-a78a-10edebf80793">
<img width="557" alt="Screenshot 2024-05-07 at 18 57 15" src="https://github.com/fomantic/Fomantic-UI/assets/61371264/8d58db5e-4f5d-4566-a6e6-56d88a3f5397">

**Comment by lubber-de** [comment]
This is already working as expeced (even at the linked example on the fomantic website)
See https://jsfiddle.net/lubber/1ockrwnd/2/

Please adjust the jsfiddle according to your code/ use case where it does not seem to be working for you

**Comment by mdrxy** [comment]
I found the issue I was facing: the ordering of the `dropdown icon`. If it is placed as the last child of the dropdown div, the clear <kbd>x</kbd> button doesn't appear.

Problematic code:
<img width="781" alt="Screenshot 2024-05-11 at 17 15 50" src="https://github.com/fomantic/Fomantic-UI/assets/61371264/148225fb-3a02-4778-bcfc-e033bd6778d9">

Fixed:
<img width="778" alt="Screenshot 2024-05-11 at 17 16 21" src="https://github.com/fomantic/Fomantic-UI/assets/61371264/50bfedca-854d-4d31-81cb-0fd494e2ceee">

The only thing now would be exploring whether the two icons could be centered vertically:
<img width="78" alt="Screenshot 2024-05-11 at 17 16 51" src="https://github.com/fomantic/Fomantic-UI/assets/61371264/7a3fc86d-bf0c-4532-9214-21f7bdce4fae">
