### ISSUE TITLE
[dropdown] inline validation on submit

### ISSUE THREAD

**Issue by mdrxy** [fomantic/Fomantic-UI#3045]
# Feature Request
Currently, if `inline` validation is set to `true`, it is not possible to override the validation's `on` trigger, which is set to `blur`. I'd appreciate the option to specify a different setting such as `on: 'submit'`.

**Comment by lubber-de** [comment]
Mmh, i think this is already working

```javascript
$('.ui.form')
  .form({
    fields: {
    	"first-name": "empty" 
    },
    inline : true,
    on     : 'submit'
  })
;
```

See https://jsfiddle.net/lubber/sx1y9tab/5/
It validates only on submit and shows the errors inline.

Please adjust the jsfiddle according to your use case.
