### ISSUE TITLE
[Card] Link card layout breaks when there is anchor tag inside card

### ISSUE THREAD

**Issue by ghabriel25** [fomantic/Fomantic-UI#3054]
# Bug Report
[Link card](https://fomantic-ui.com/views/card.html#link-card) layout breaks when there is anchor tag inside card

## Steps to reproduce
1. Create a link card
2. put `<a href="#">Link</a>` inside `.extra.content` of the link card

## Expected result
Link card layout stay as expected like another card

## Actual result
Layout breaks

## Testcase
JSFiddle - https://jsfiddle.net/h8a1r6u3/1/

As a reference, here is an example video from [Laracasts](https://laracasts.com/series/jeffreys-larabits/episodes/38) how to handle this specific case

JSFiddle - https://jsfiddle.net/ftzcvqxw/

## Screenshot (if possible)
![image](https://github.com/fomantic/Fomantic-UI/assets/151924216/54bbe670-edce-453b-bdbd-19027babbf8a)

## Version
2.9.3

**Comment by GammaGames** [comment]
You can't nest `a` tags

**Comment by ghabriel25** [comment]
> You can't nest `a` tags
> 
> ```
> <a href="google.com">
>   test
>   <a href="github.com">
>     test 2
>   </a>
> </a>
> ```
> 
> is rendered as ![image](https://private-user-images.githubusercontent.com/7832163/337322788-329ef847-c38d-4635-8bd4-077b22118506.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODg5NzYsIm5iZiI6MTcxNzY4ODY3NiwicGF0aCI6Ii83ODMyMTYzLzMzNzMyMjc4OC0zMjllZjg0Ny1jMzhkLTQ2MzUtOGJkNC0wNzdiMjIxMTg1MDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTU0NDM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk3M2JhNzgxMzQwNDk5YWY4OThhMzU4YTdhYzQwOGEzN2JkMmQxMzNjMDBlNTkzN2E2NmQ5YzZlMGRhYjAzOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.syP7Ipw2jdf6O9EORc4RopWyhbR9G6KTResm7NHvj4s)

Yes, thats why I put some reference so the link card can support `href` to another page while the card content has another anchor tag

**Comment by GammaGames** [comment]
Apologies, this is magic! I was able to get something working: https://jsfiddle.net/7v3ru4nf/

**Comment by lubber-de** [comment]
The `link` class is not bound to an anchor tag element. 
If the card itself is not an `a` tag, but something else like a `div`, you can still add the `link` class to the card to support the visual effects like hand cursor or moving card and have as many (non nested) a tags inside wherever you want
https://jsfiddle.net/wkx2ht7c/
