### ISSUE TITLE
[Dropdown] search text cut off in Edge

### ISSUE THREAD

**Issue by hammy2899** [fomantic/Fomantic-UI#312]
> Bug:
> On Microsoft Edge when adding a new entry to search dropdown the text cuts off at start. Please see the video below for clarification
> 
> https://jmp.sh/lvX8aN0
> 
> ### Steps
> 1. Open https://jsfiddle.net/xjaus15o/ in MS Edge
> 2. Click inside Dropdown.
> 3. type foo
>    Notice the f of foo is cut off from the start.
> 
> ### Expected Result
> f of foo should not be cut off from the start.
> 
> ### Actual Result
> f of foo is cut off from the start.
> 
> ### Version
> 2.4.2
> 
> ### Testcase
> Open https://jsfiddle.net/xjaus15o/
> 
> <img alt="screen shot 2018-12-18 at 2 35 54 pm" width="643" src="https://user-images.githubusercontent.com/10061444/50145052-73c21e00-02d2-11e9-9a56-750904e8793c.png">

Original Issue: https://github.com/Semantic-Org/Semantic-UI/issues/6713

**Comment by hassam7** [comment]
@hammy2899 This ticket has good first issue label. Can I get a little guidance approaching this ticket?

**Comment by hammy2899** [comment]
@hassam7 Sure 😃

So as far as I'm aware the bug is due to Edge not returning the same width value as other browsers (https://jsfiddle.net/7n5qwm0L/) and therefore it sets the input box width `1px` too little so it cuts the text off. If you keep typing letters you will see that the text "jumps" around and some amounts its fine and some it isn't.

A simple fix would be to change this https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/dropdown.js#L1744 to add `2px` instead of `1px` but if you can think of any other way feel free.

**Comment by hassam7** [comment]
I tried it by setting 2px but the text was still cutting. Adding 3 to $sizer.width() worked.

**Comment by j055** [comment]
![semantic](https://user-images.githubusercontent.com/6011428/79893296-c7c7a000-83fb-11ea-9b6a-88e3f2b319f7.png)

Is there a fix for this? Still seems to be an issue in Edge.

Try typing in here:
https://fomantic-ui.com/modules/dropdown.html#multiple-search-selection

**Comment by lubber-de** [comment]
This seems to fix it as well without the need to change the JS as suggested above
```css
.ui.dropdown .sizer {
  width:100%;
}
```

**Comment by j055** [comment]
Looks like an attempt has been made in the latest version to address this:

https://github.com/fomantic/Fomantic-UI/blob/3f3045c09176875bd3db674c0874bc4b96d0d3f7/src/definitions/modules/dropdown.js#L1777

But is doesn't fix the above issue.

Could do with a workaround while we wait for EdgeHTML to be replaced by Chromium.
