### ISSUE TITLE
[Icon/Button] Change Twitter to X

### ISSUE THREAD

**Issue by wdmeest** [fomantic/Fomantic-UI#3124]
# Feature Request
Update the Twitter icon and button to X

**Comment by lubber-de** [comment]
This needs an update of the font awesome set to at least 6.4.2 which we may consider in a later fui version (2.10.x+) as the icon set will drastially grow and will also be a slight breaking change as front awesome dropped/renamed some icons.
In the meantime you can create a custom build of Fomantic-UI together with the latest font awesome version using our [create-fomantic-icons](https://github.com/fomantic/create-fomantic-icons) package

**Comment by wdmeest** [comment]
Oke thxs for the information. It is only about the X-twitter icon - so the new svg will do the job ;)
