### ISSUE TITLE
[scope] web page examples do not work for CDNs

### ISSUE THREAD

**Issue by pete312** [fomantic/Fomantic-UI#3135]
# Bug Report

Tried an example which didnt work.

copied CDNs from here into a blank html file.
https://fomantic-ui.com/introduction/getting-started.html#using-a-cdn-provider

went to examples on accordion copied with the copy icon, then pasted into the body tag in the html.  Did this one 1st but none of them work
https://fomantic-ui.com/modules/accordion.html#fluid

my file `test_formatic.html` looks like this. 
```
<!DOCTYPE html>

<head>
    <title> test formatic </title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.9.3/dist/semantic.min.js"></script>
</head>

<body>

    <div class="ui styled fluid accordion">
        <div class="active title">
          <i class="dropdown icon"></i>
          What is a dog?
        </div>
        <div class="active content">
          <p>A dog is a type of domesticated animal. Known for its loyalty and faithfulness, it can be found as a welcome guest in many households across the world.</p>
        </div>
        <div class="title">
          <i class="dropdown icon"></i>
          What kinds of dogs are there?
        </div>
        <div class="content">
          <p>There are many breeds of dogs. Each breed varies in size and temperament. Owners often select a breed of dog that they find to be compatible with their own lifestyle and desires from a companion.</p>
        </div>
        <div class="title">
          <i class="dropdown icon"></i>
          How do you acquire a dog?
        </div>
        <div class="content">
          <p>Three common ways for a prospective owner to acquire a dog is from pet shops, private owners, or shelters.</p>
          <p>A pet shop may be the most convenient way to buy a dog. Buying a dog from a private owner allows you to assess the pedigree and upbringing of your dog before choosing to take it home. Lastly, finding your dog from a shelter, helps give a good home to a dog who may not find one so readily.</p>
        </div>
      </div>
    
</body>
</html>

```

opened it in browser  ( firefox Version 133.0 (64-bit)  on Fedora 41 distro  )

## Expected result

Wanted to see accordion arrows reveal content

## Actual result

Accordion did not operate

**Comment by lubber-de** [comment]
You probably forgot to instantiate the accordion via `$('.ui.accordion').accordion()`
https://fomantic-ui.com/modules/accordion.html#/usage

**Comment by pete312** [comment]
> You probably forgot to instantiate the accordion via `$('.ui.accordion').accordion()` https://fomantic-ui.com/modules/accordion.html#/usage

Confirmed that was it.   Bit of feedback on this as a new user who got lost.  I would have seen this if a link appeared at top as a note or perhaps it was more conventional tabbed view.  The button strip is an unconventional tabbed view and I didnt make the connection that it mattered.  It took comparing  your link comparing it with mine.  Now I am aware of that button strip is a tabbed view i will take note for other examples. Thank you for your help. 

Thank you very much for your quick reply.
