### ISSUE TITLE
Toast needs to have shadow.

### ISSUE THREAD

**Issue by romaninsh** [fomantic/Fomantic-UI#315]
# Bug Report

Shadow is used by various elements, which are "floating", e.g.:

<img width="309" alt="image" src="https://user-images.githubusercontent.com/453929/50170047-e937e980-02e6-11e9-8a2a-4cf9b776fac2.png">

However toast does not have shadow. 

<img width="367" alt="image" src="https://user-images.githubusercontent.com/453929/50170069-f3f27e80-02e6-11e9-9200-8582f22be9a7.png">

It's reasonable to expect it to be styled consistently to tooltips and pop-overs.

## Steps to reproduce
1. https://fomantic-ui.com/modules/toast.html
2. Run Code

## Version
2.6.4

**Comment by romaninsh** [comment]
I wrote a more detailed analysis on #316.

**Comment by lubber-de** [comment]
Implemented by #1129
