### ISSUE TITLE
[Segment] Basic attached segment have borders

### ISSUE THREAD

**Issue by etshy** [fomantic/Fomantic-UI#330]
## Steps to reproduce
1. Make a basic attached segment

## Expected result
Segment doesn't have borders

## Actual result
Segment have border

## Testcase

https://jsfiddle.net/1Lz6nm9w/4/

## Version
2.7.1 (from npm show fomantic-ui)

The attached class is "stronger" than the basic class so border are still there.

Edit: Updated the fork for another problem. when I have the attached class (with borders, so) I don't have the "top border" between the tab and the segment.

Edit2: Seems the problem with the top border comes from the inverted class.

Edit3 : updated again for another problem.
As you can see on the link, the first tab group > When you select the last tab, the segment below is not the size (width) as the others tabs

You can see the same problem on fomantic-ui example : [Here](https://fomantic-ui.com/modules/tab.html#centered-item)
when you select the latest tab, the width of the segment change

It's not the same behaviour though, in my jsfiddle the border is one more pixel to the left while on the fomantic site it's one pixel more to the right.

**Comment by etshy** [comment]
Update here.

I searched a bit for some fixes.

Here is a fiddle with some tweaks : https://jsfiddle.net/xkp5e731/

**Comment by lubber-de** [comment]
Basic attached segment border fixed by #2163 
Everything else you mentioned was fixed by #2082
