### ISSUE TITLE
Commit message format seems required but documented as optional

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#341]
# Help Wanted

## Problem
Commitlint bot marks PR ❌ if commit message does not follow commit message format.
![image](https://user-images.githubusercontent.com/127635/50572998-8a0dc500-0e0e-11e9-9263-e9955da1755b.png)

However, the commit message format is documented as not required.
> https://github.com/fomantic/Fomantic-UI/blob/7f6bd29db53f17a2c4e2c47e2dc0e81568d1ea5f/CONTRIBUTING.md#pencil-pull-requests-guide
> - Please commit using the [AngularJS Git Commit Message Convention](https://gist.github.com/stephenparish/9941e89d80e2bc58a153) this is more of a nice to have and isn't required.

I initially did not know what is valid `type` for commit message...

I agree that enforcing message format is required to make history useful, 
but the CONTRIBUTING.md should be updated. 
It is good to include commit message format and examples.

**Comment by hammy2899** [comment]
The bot which checks your PR commits doesn't block merging and is just a check mainly for us maintainers.

We might want to consider self hosting the bot and customizing who's PR's it checks etc.
