### ISSUE TITLE
Better API debugging

### ISSUE THREAD

**Issue by aardbol** [fomantic/Fomantic-UI#362]
# Feature Request

## Description
I'd like the API debugging information to be more useful. Currently the API actions are very informative but the details (when wanting to look at what data was sent for example) are very verbose and useless and seem to be looping forever, see screenshot.

## Example
See screenshot.

## Screenshot (when possible)
https://postimg.cc/KKwGmDyS

**Comment by exoego** [comment]
Could you add detaild steps to get the verbose detail that contains a loop of `prototype`?

I tried [API Example (`Follow` button)](https://fomantic-ui.com/behaviors/api.html#/usage) and got `console.table` like below on Firefox 66.0.3. It seems that it does not contain loop of `prototype`
![image](https://user-images.githubusercontent.com/127635/57188493-b5c6c600-6f3a-11e9-8ba5-76277c234d6a.png)

**Comment by lubber-de** [comment]
Closing because of no response and missing Testcase. Happy to reopen if the asked details and a reproducable jsfiddle are provided

**Comment by aardbol** [comment]
Here's another image:
![Peek 2019-07-16 12-16](https://user-images.githubusercontent.com/14614620/61286687-a29a6700-a7c3-11e9-90ba-2a5152047eeb.gif)

Here's a Jsfiddle: https://jsfiddle.net/5kgh0Loc/
The loop prototype log also appears in the table.

**Comment by lubber-de** [comment]
Thats the browser console default bahavior when objects/arrays are logged to the console. Avoiding that would mean to redefine the console function . I dont think we should do that in the core.
