### ISSUE TITLE
Hard to find this library

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#365]
Hi,

If you go to google (for example) and search only for "fomantic ui" it's impossible to find the FOMANTIC UI GITHUB page not even at the third page of results! I dont know if you need some SEO expert to help into this but it's freaking hard to find FOMANTIC UI in the internet. I just wanted to check the latest release notes and had to track the fomantic repository link in a forum discussion outside github.

**Comment by idmarinas** [comment]
This has an easy solution, use Bing. :laughing:

Google interprets  "Fomantic UI " As you have been mistaken when writing and that your intention was to use "Semantic UI ". But to ignore that, you can give it to  "Search instead for fomantic UI"

With Bing, not have this problem.

Maybe this is not solved only with SEO.
