### ISSUE TITLE
[Dropdown] Using integer as value

### ISSUE THREAD

**Issue by ibelar** [fomantic/Fomantic-UI#379]
# Bug Report

Using integer as value for dropdown will cause an error. 

- TypeError: option[fields.value].replace is not a function.

Prior to 2.7.0 we were able to pass integer as value.

## Steps to reproduce
1. Create dropdown using integer value.

## Expected result
Dropdown open

## Actual result
Dropdown does not show.

## Testcase
https://jsfiddle.net/ibelar/qf1b5yn8/

## Version
2.7.1

**Comment by lubber-de** [comment]
Sorry for this :hushed: 
Fixed by #381
