### ISSUE TITLE
Drop down with sub-menu doesn't display in menu

### ISSUE THREAD

**Issue by singhda8** [fomantic/Fomantic-UI#382]
# Bug Report

A drop down with a sub menu displays inline if it's placed inside another menu. See the attached jfiddle.

## Expected result
Each option within sub menu should shown on its own line.

## Actual result
All options are displayed on the same line.

## Testcase
https://jsfiddle.net/u1f02thp/

**Comment by douglasg14b** [comment]
@lubber-de  this is CSS only, the JS pulls and adds the `display: flex !important` from the already existing element style.
