### ISSUE TITLE
CSS media queries for grid fail when windows is snapped to right

### ISSUE THREAD

**Issue by singhda8** [fomantic/Fomantic-UI#385]
# Bug Report
The CSS media queries used for the grid, such as _computer only, tablet only, etc_, don't work when the window is resized to half of the screen.

## Steps to reproduce
1. Navigate to https://fomantic-ui.com/collections/grid.html#/definition
2. Scroll down to the Device Visibility section. 
3. On Windows, drag the top bar to the right side of the screen to snap the window. The issues can also be reproduced by slowly resizing the browser to exactly half of the screen.

## Expected result
Certain content should be hidden as the window is resized.

## Actual result
All content is displayed when the the browser is at the halfway point of the screen.

The following screenshot is taken on a laptop with a full resized window. Tablet and mobile content is hidden as expected.
![image](https://user-images.githubusercontent.com/32823510/51058442-c54e8780-15b6-11e9-88f4-4fce8eaedc0e.png)

The following screenshot is taken after snapping the window to the right side of the screen. As show, all content is being displayed:
![image](https://user-images.githubusercontent.com/32823510/51058498-f29b3580-15b6-11e9-9ee7-2c5594c4ef6e.png)

**Update**: Looking a bit more into this, this happens during that one pixel crossover from computer to tablet and tablet to mobile.

**Comment by lubber-de** [comment]
I cannot seem to reproduce this unfortunately 😢 (1920x1080 native resolution by 100% DPI Win10, Chrome/Edge  and even IE11! 😨 
I did as you said and tried a lot by also zooming int/out and everything always looked as expected.
In addition i also checked all `@media only screen` settings for their `min-width` and `max-width` if they probably overlap somwhere  (which would explain the 1px behavior) but they don't,
Which browser are you using? Do you have Windows-DPI settings decreased ? Which native resolution does the notebook have?

**Comment by singhda8** [comment]
It would appear the issue is because of dpi scaling. I'm also running Windows 10. My laptop resolution is 1920x1080 but my dpi was set to 125%. If I tone it down to 100%, I can't reproduce the issue an longer. The dimensions of the page when I reproduce the issues are as follows:
![image](https://user-images.githubusercontent.com/32823510/53306634-8ec68680-385d-11e9-95ea-0b31631e50ac.png)

**Comment by lubber-de** [comment]
😱 Confirmed using 125% dpi settings and viewport width at 767.2 ( 0.2 pixel?)

**Comment by singhda8** [comment]
Yup. Seems that on higher dpi settings, the browser can actually render fractions of a pixel.

**Comment by lubber-de** [comment]
Fixed by #567
