### ISSUE TITLE
Popup content blocks by sticky sidebar

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#394]
# Bug Report
When the popup element places near the sticky sidebar, the popup overlaps by the sticky content because of less 'z-index' value.

## Steps to reproduce
1. Put a sticky sidebar in HTML page
2. Create an element with popup and place near the sticky sidebar
3. Force the popup element to display the content

## Expected result
The popup content should display without blocking.

## Actual result
The popup content is partially blocked by the sticky sidebar.

## Testcase
Go to this [fiddle](https://jsfiddle.net/ep8dhutg/). Scroll the result window until the button is aligned next to the sidebar. Place the mouser over the button to display popup.

## Screenshot
![popup fomantic ui](https://user-images.githubusercontent.com/930315/51113349-1c12c600-1830-11e9-9d6a-bedf03d54f13.png)

## Version
Might be effected in all versions of Fomantic UI and Semantic UI. I didn't submit this issue in Semantic UI repo, since it has no significant activities lately.

**Comment by hammy2899** [comment]
@ko2in Fixed in https://github.com/fomantic/Fomantic-UI/pull/395, should be in next release 😉

**Comment by ko2in** [comment]
@hammy2899 Thanks for the quick fix. Looking forward to the next release. Have a nice day.
