### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by subramn** [fomantic/Fomantic-UI#396]
Are there any type definition files associated with it or do we need to use the existing type defs  from @types/semantic-ui

**Comment by qJake** [comment]
This would be a great addition. It's been almost a year and I find myself writing shims into my TypeScript to get around some missing definitions (e.g. `$.fn.calendar(...)`, a new component not defined in Semantic 2.4.x).

+1 for a `@types/fomantic-ui` npm package!

**Comment by mvorisek** [comment]
should be closed in favor of https://github.com/fomantic/Fomantic-UI/issues/1205

**Comment by lubber-de** [comment]
@prudho once started to add such for the DefinatelyTyped project
https://github.com/fomantic/DefinitelyTyped/tree/fomantic-ui

Don't know if he got time to follow this up ?

**Comment by prudho** [comment]
Nope... Totally forgot about this... I'll try to investigate further more.

**Comment by mvorisek** [comment]
In our usecase type definitions will help us a lot, as we render Fomantic-UI code on server and it would be great if we can check the options/types on render stage.

**Comment by prudho** [comment]
Hey, you should take a look at #2822 😃
