### ISSUE TITLE
Checkboxes fire onChange twice

### ISSUE THREAD

**Issue by andreyvk** [fomantic/Fomantic-UI#399]
# Bug Report

Hi guys,

Checkbox seems to fire two `onChange` events, when checked/unchecked. That's a big problem. Please fix asap.

## Steps to reproduce
First, here's a [fiddle](https://jsfiddle.net/andreyvk/tapLj362/) and second the same problem exists on the site https://fomantic-ui.com/modules/checkbox.html#/examples

## Version
2.7.1

**Comment by prudho** [comment]
Seems to be induced by 3fec1ecd191ffb362eb22b02062c531d50617f6c

onChange callback is fired twice, by `check` function, then `change.event` function.

**Comment by lubber-de** [comment]
Fixed it in https://github.com/fomantic/Fomantic-UI/pull/403 The whole thing had a more deeper background. #295 just brought it to daylight :laughing: I described the technical reason in the PR

**Comment by lubber-de** [comment]
Testcase https://jsfiddle.net/7vjLsr1f/
