### ISSUE TITLE
"set checked" fires a callback although it shouldnt

### ISSUE THREAD

**Issue by andreyvk** [fomantic/Fomantic-UI#400]
# Bug Report
Hello again,

According to https://fomantic-ui.com/modules/checkbox.html#/usage `set checked`, `set unchecked`, etc. are not supposed to fire callbacks.

This might be related to issue #399. 

## Steps to reproduce
Here's a [fiddle](https://jsfiddle.net/andreyvk/sea8cnfd/)

## Version
2.7.1

**Comment by prudho** [comment]
Yeah this is related to #399 bug.

@lubber-de: disabling the `change` event seem to fix those 2 issues and does not looks usefull for us. Do we really need it ?

**Comment by lubber-de** [comment]
@prudho The change event was necessary to make the keynav recognize the change for #295 .
 I'll fix this today together with #399 and make sure #295 will still work.

**Comment by lubber-de** [comment]
Fixed it in https://github.com/fomantic/Fomantic-UI/pull/403 The whole thing had a more deeper background. #295 just brought it to daylight :laughing: I described the technical reason in the PR

**Comment by lubber-de** [comment]
Testcase https://jsfiddle.net/3sbreo71/
