### ISSUE TITLE
[Menu] missing color in secondary pointing menu

### ISSUE THREAD

**Issue by j5k** [fomantic/Fomantic-UI#406]
# Bug Report

## Steps to reproduce
1. go to fiddle
2. see missing green in menu items
3. in my previous version (2.6.3) it is functional

## Expected result
Colored items

## Actual result
Only black items

## Testcase
https://jsfiddle.net/ak5920y3/

## Version
2.7.1

**Comment by lubber-de** [comment]
Fixed by #406
Testcase https://jsfiddle.net/uvg6e4af/
