### ISSUE TITLE
[Menu] missing color when menu item hovered

### ISSUE THREAD

**Issue by j5k** [fomantic/Fomantic-UI#408]
# Bug Report

## Steps to reproduce
1. go to fiddle
2. hover the active menu item
3. color change from green to black
4. it's a new behaviour in version 2.7.x

## Testcase
https://jsfiddle.net/s75qhpr9/

## Version
2.7.1

**Comment by lubber-de** [comment]
This is also fixed by #409 :blush: 
See https://jsfiddle.net/bfnos9gm/
