### ISSUE TITLE
[Text] add size variation

### ISSUE THREAD

**Issue by AlexandreGagner** [fomantic/Fomantic-UI#413]
# Feature Request

## Description
It would be nice to have size with text module, to change the size of selected text with element.

## Example
```
<div class="ui segment">
  This is <span class="ui large red text">red</span> inline text and this is <span class="ui small blue text">blue</span> inline text and this is <span class="ui purple text">purple</span> inline text
</div>
```

## Testcase (when possible)
https://jsfiddle.net/msn8keg9/
Exemple with font-size set in % with CSS

😘, Alex

**Comment by lubber-de** [comment]
@AlexandreGagner Your suggestion will be part of FUI 2.7.2 :grin:

**Comment by AlexandreGagner** [comment]
\o/
