### ISSUE TITLE
[Progress] Uninitialized progress bar already has some progress

### ISSUE THREAD

**Issue by andrewgorpenko** [fomantic/Fomantic-UI#424]
# Bug Report

## Steps to reproduce
1. Case 1: add progress to the page and do not initialize it. You can see that the bar already has some progress.
2. Case 2: add progress to the page and initialize it with 0%. You can see that the bar has some progress, however the percentage is 0.

## Expected result
No pre-loaded color bar then not initialized or initialized with 0%

## Actual result
Has a color bar even when not initialized or initialized with 0%

## Screenshot (when possible)
When not initialized:
![When not initialized](https://image.prntscr.com/image/xYLbvMprSsCcLFkN25UwjQ.png)
When initialized with 0%:
![When initialized](https://image.prntscr.com/image/reNghZFMTRWrMOEmWGS9ew.png)

_P.S. Maybe this is needed then you are using bar label with percentage. But it is not always necessary._

## Version
2.7.x

**Comment by lubber-de** [comment]
@andrewgorpenko  No, this is not covered by the PR...but i will fix it :grin: 
See fix here https://jsfiddle.net/ba51wkjm/

**Comment by andrewgorpenko** [comment]
Yas, now there we go! Looking forward to seeing your PR ASAP 💃
