### ISSUE TITLE
Close modal with a scrollbar page generate an unsightly effect

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#427]
# Bug Report

## Steps to reproduce
When you close a modal and the page have a scrollbar, the scrollbar is re-display before the modal is completely hidden then the modal is move to the left and that's generate an unsightly effect (it's almost invisible)

## Expected result
The scrollbar of page need to be display only after completly hidden the modal

## Screencast
I make a slowmotion video to see the problem :
https://youtu.be/3MWSA2P-bYI

## Version
2.7.1

**Comment by ko2in** [comment]
Yes. I agree. We need more smoother transition when closing modal.

**Comment by lubber-de** [comment]
Fixed by #468
