### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by brunotourinho** [fomantic/Fomantic-UI#436]
# Bug Report

## Steps to reproduce
1. Create a icon tag
2. Style some color to it ie.: `<i class="red trash icon">`

## Expected result
Beautiful colored icon

## Actual result
Icon color inherited from list item

## Testcase
`http://jsfiddle.net/9aruhkn8/2/`

## Version
2.7.1

**Comment by hammy2899** [comment]
Works when the `.item` is a div and not a `a` tag. Seems to be due to this overriding the icon color https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/elements/list.less#L192

**Comment by lubber-de** [comment]
i'll increase the specifity of the icon colors
