### ISSUE TITLE
gulp-help won't install - blocked by firewall

### ISSUE THREAD

**Issue by Kingo64** [fomantic/Fomantic-UI#439]
# Bug Report

Fomantic UI fails to install as the dependency "gulp-help" as the github: protocol decorator is blocked by my firewall.

Currently Fomantic will use "github:chmontgomery/gulp-help#gulp4" as the gulp-help version which will not install on my environment.

Removing gulp-help or replacing the gulp-help version with a direct file reference results in a successful installation.

Previous versions of Fomantic UI also work before gulp-help v4.0.0 was a dependency.

## Steps to reproduce
1. npm install fomantic-ui

## Expected result
fomantic-ui successfully installs all dependencies and runs install script

## Actual result
ECONNREFUSED error when installing gulp-help

Both removing gulp-help and replacing gulp-help with a URL hosted direct reference results in fomantic-ui successfully installing.

## Version
fomantic-ui v2.7.1
npm v6.5.0

**Comment by ColinFrick** [comment]
@fomantic/core Should we remove gulp-help altogether? Gulp 4 added similar functionality with `gulp --tasks` / `gulp-tasks-simple`
Also the author of gulp-help remarked that there is no _release_ of gulp-help#gulp4 planned https://github.com/chmontgomery/gulp-help/issues/31#issuecomment-449979322

**Comment by hammy2899** [comment]
@ColinFrick Yeah we can do, I don't see any reason for it to stay.
