### ISSUE TITLE
Allow modal centering with "detachable: false"

### ISSUE THREAD

**Issue by andrewgorpenko** [fomantic/Fomantic-UI#445]
# Feature Request

## Description
Currently setting the "detachable" option to false makes the model center within the div it is placed in (shown in the test case). It would be useful to allow centering relatively the window or the dimmer.

## Usage cases
1. Vue component
Because of the specific behavior of the Vue components, they are unable to clean up after themselves, leading to further bugs with Fomantic (modal won't re-open if the component was unloaded)
2. Grids and columns
If the modal code is located in one of the N columns and the "detachable" is false then the modal will shift to the center of that specific column which is not good from the design perspective.

## Testcase (when possible)
https://jsfiddle.net/c75qjh3f/9/

**Comment by lubber-de** [comment]
A `modal` is supposed to be a direct child of `body` , you should not put the code into any other component

**Comment by lubber-de** [comment]
See https://jsfiddle.net/dwnfjk2o/

**Comment by andrewgorpenko** [comment]
I see... But this restriction leads to decreasing scalability... Think about Vue components. There is no way to pass the data there except VueX data. But that is another story.
By the way, thanks.
