### ISSUE TITLE
fomantic  UI offlince docs understanding issue for me

### ISSUE THREAD

**Issue by crewow** [fomantic/Fomantic-UI#447]
# Help Wanted

fomantic  UI offlince docs issue

## Problem
Describe your problem in great detail

https://github.com/lubber-de/Fomantic-UI-Docs using this i tried to download docs but do not know about some steps.

I created fomantic folder and created UI and docs folder

Clone both repos to respective folders (** I did not find repo for docs and ui, please share link**)
npm install in both directories
Go through Fomantic UI installer steps (auto) (**how it will work**)
In ./ui folder gulp build-docs (builds files to ./docs)
In ./docs folder docpad install then docpad run
Go to http://localhost:9778/ docs should be there
Optionally run gulp serve-docs in ./ui to serve any changes from ./ui/src to ./docs

Please share detail method how i can downlaod fomatic ui locally

**Comment by hammy2899** [comment]
@crewow You can find the docs here https://github.com/fomantic/Fomantic-UI-Docs, if you want to find any repositories related to FUI check the [`fomantic org`](https://github.com/fomantic).

The easiest way to setup the docs is using following commands

```bash
$ mkdir fomantic && cd fomantic
$ git clone https://github.com/fomantic/Fomantic-UI ui
$ git clone https://github.com/fomantic/Fomantic-UI-Docs docs
$ cd ui && npm install && npx gulp build-docs
$ cd ../docs && npm install
$ npx docpad run
```

Then visit [http://localhost:9778](http://localhost:9778)

**Comment by crewow** [comment]
> @crewow You can find the docs here https://github.com/fomantic/Fomantic-UI-Docs, if you want to find any repositories related to FUI check the [`fomantic org`](https://github.com/fomantic).
> 
> The easiest way to setup the docs is using following commands
> 
> ```shell
> $ mkdir fomantic && cd fomantic
> $ git clone https://github.com/fomantic/Fomantic-UI ui
> $ git clone https://github.com/fomantic/Fomantic-UI-Docs docs
> $ cd ui && npm install && npx gulp build-docs
> $ cd ../docs && npm install
> $ npx docpad run
> ```
> 
> Then visit http://localhost:9778

Hopefully, this will be added to the main site as new users cannot understand docs easily.

**Comment by crewow** [comment]
@hammy2899  it's working now. thanks for easy way :)
