### ISSUE TITLE
Calling modal on non-existing element does nothing (no exception, error, warning...)

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#453]
Sorry for posting again about a similar issue I posted earlier but now I am really facing something that just might be a "bug".

Synopsis: I have dozens of modals on my page and Google PageSpeed Insights gives me a "penalty" of 12 points when I load all modals on page load (I mean, when I make lots of calls like `$("#janela1").modal( "setting",...);` on page load).

So previously, @ColinFrick  and @lubber-de gave me an alternative to ONLY call those `modal("setting")` inside `$.fn.modal.settings.onShow` once. So the settings would only be applied to the modals just before they are shown. That's really great.

It worked perfectly. BUT now I wondered: what if I only place the HTML code (of the modals) AFTER any "onShow" fired?

Bear with me. Currently my HTML code looks like this (with dozens of modals):

```
<div class="ui basic modal small" id="janela_mensagem">

	<i class="icon-cancel close icon"></i>

    <div class="ui icon header">
    	
        <span class="title"></span>
        
    </div>
    
    <div class="content" align="center"></div>
    
    <div class="actions">
        
        <button class="ui red button fechar"><i class="icon-ok icon"></i> Fechar</button>
    
    </div>
    
</div>

```

So I decided to make this:

```
	$.fn.modal.settings.onShow = function() {
		
		
        //The line below is to allow the code below to be run just once.
	if (typeof already_loaded_modals === "undefined") {
			
		already_loaded_modals = true;
	
			
                 $("body").append(`
                
                <div class="ui basic modal small" id="janela_mensagem">
                
                    <i class="icon-cancel close icon"></i>
                
                    <div class="ui icon header">
                        
                        <span class="title"></span>
                        
                    </div>
                    
                    <div class="content" align="center"></div>
                    
                    <div class="actions">
                        
                        <button class="ui red button fechar"><i class="icon-ok icon"></i> Fechar</button>
                    
                    </div>
                    
                </div>
            
                `);
            
		$("#janela_mensagem").modal(
			
				"setting",
				{
					closable:false,
					transition:"vertical flip",
					autofocus:!eh_movel
					
				}
					
			);
            
		}
        
	};
```

You see how beautifull it is? After doing that Google saved me 19 points on Google Pagespeed Insights! And the page load time performance is noticeable faster!

The problem? Well, on hundreds of places in my pages I have calls like this `$("#janela_mensagem").modal("show")` and I cant change that cause it require lots of time.

The problem is that calling that "show" method, the modal never opens, actually the `onShow` never fires. Why? Simple. The element `#janela_mensagem` is not yet on the page so Fomantic/Semantic does not fire the "onShow". 

Well that's expected and I wont complain about that cause if the element does not exist on the HTML DOM, it should never fire the "onShow" event.

However, Fomantic at its documentations on https://fomantic-ui.com/modules/modal.html#/settings says there is an "error" event (surelly I cant call that an event). However it's not firing. If it fired, I know I called `modal` on some element that does not exist and with that I could initialize my modals properly!

You dont need to go very far to test this "bug": just call `$("#fdlskjfldskjf").modal("show")` on any page where there is no element "#fdlskjfldskjf". Nothing simply happens. No error logged, no handler function triggered that could help me solve this situation.

So I ask you: is there some way I can handle this problem? Maybe a "bug fix" to allow some exception/error/callback function to be executed when there is no element to be "modaled"?

**Comment by ColinFrick** [comment]
Seems to be the jQuery default behaviour, when working with selectors that return no element.
There is no "error" event in modal, what you are referring to is the collection of error messages.

**Comment by batata004** [comment]
@ColinFrick so jQuery is not passing the "chain" when the selector returns zero elements? I mean, if the selector returns 0 elementos you are saying that jquery will not execute anything chained, like `.modal` or any other thing? If so, I probably found a dead end and sure enought it's not up to semantic/fomantic to solve this. :(

**Comment by lubber-de** [comment]
Exactly. jquery iterates through all found elements and applies the given method.
As the element list is an empty array, it just does nothing. This is wanted behavior.

```javascript
var result=[];
for (var i=0,il=result.length;i<il;i++) {
//this will never be reached because i an il are both 0
    result[i].modal();
}
```
How should it work otherwise without breaking the syntax?
`$('.does.not.exist).modal()`

if `$('.does.not.exist)` would return `undefined` then the whole app would break with an uncatched console error (`cannot call modal() of undefined`). So it's natural/logical/as designed by jquery to always return an array, be it empty or not, to still keep the flow valid.

What _you_ can do of course is checking for an empty result first instead of chaining the method:
```javascript
var elements = $('.does.not.exist');
if (elements.length >0 ) {
    elements.modal();
}
```

**Comment by batata004** [comment]
@lubber-de great explanation about that. I was not aware of how jquery worked regarding 0 elements returned by a selector. Really nice to know how it works.

You suggestion of how I could solve the problem is nice BUT it would require me to change all the hundreds of calls `$("#element").modal("show");` spread all over this website. Certainly it would work but would require lots of changes cause sometimes I call `$("#element").modal("show");`  when the user clicks a button, hover a imagem, clicks a link, loads a page... my modals can show on very specific situations.

So, for now I am stuck :(   I was so proud of the code I had put together and I was very proud that it helped me score much better at Google Pagepeed.

I was taking a shower a few minutes ago and I had a small idea: what if I just create empty `<div>` elements at my HTML code with every single ID of each the modals I need. THEN when the user call the `modal` method the `onShow` would still fire and I could remove the empty `<div>` and replace with my own huge HTML code using JS. I think this could work but I am still searching and thinking of a better way.

I am still amazed how `modal` affects page load so I am pretty decided to optimize this part of my code as far as I can but for now I am stuck. If you guys come up with any idea that wouldnt require me to change all of my `.modal("show")` calls I would be very grateful and in the future it would help lots of other people! There is no point importing unnecessary HTML code into the DOM until you really need to use a modal, then you can inject the HTML relative to the modal, initialize it with the `settting/events` needed and finally show it.
