### ISSUE TITLE
Inline dropdown breaks styles

### ISSUE THREAD

**Issue by brunotourinho** [fomantic/Fomantic-UI#458]
# Bug Report

## Steps to reproduce
1. Create a form with two inline dropdowns
2. Set them to smaller size i.e. small, tiny

## Expected result
Dropdown icon perfectly aligned inside the field
Dropdown opens, smoothly

## Actual result
Dropdown icon a little displaced down
The right hand side dropdown breaks its right border in 1px

## Testcase
http://jsfiddle.net/xja85wpL/3/

## Version
2.7.1

**Comment by lubber-de** [comment]
Fixed in 2.7.7 by #838
