### ISSUE TITLE
[Sticky] Sticky bound to bottom when the page height changed dynamically

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#466]
# Bug Report
Sticky element bounds top to bottom or bottom to top when the page height changed dynamically. I've collapsible content which controls by individual button in a page. And when I clicked the button and expand the content, the sticky element is bounding for certain situations.

## Steps to reproduce
Open this fiddle (https://jsfiddle.net/4dtmz2wk/).
1. Scroll the page at the end of the page
2. Click the two buttons
3. Check the reaction of sticky element upon the changed of page height by collapsible content

Better copy the source and test in full tab, the fiddle iframe is too narrow to notice this issue.

## Expected result
The sticky shouldn't bound top to bottom and vice versa.

## Actual result
The sticky element is bounding top to bottom and vice versa.

## Screenshot
With full screen in my browser.

![sticky](https://user-images.githubusercontent.com/930315/52407900-e051e000-2aff-11e9-9919-65350e05d67c.png)

## Version
2.7.1

## Note
I'm not sure whether it actually is a bug or it's the way sticky component works. Anyway, it's unwanted behavior in my case.

**Comment by ColinFrick** [comment]
Check **Refreshing Cached Values** in the sticky documentation: https://fomantic-ui.com/modules/sticky.html#/usage

**Comment by ko2in** [comment]
@ColinFrick Thanks. It solved when I refresh again after collapsed/expanded the content. 

It would be better, if the offset caching is optional and can be turned off via settings since initialized the sticky component.
