### ISSUE TITLE
Less-loader error

### ISSUE THREAD

**Issue by mkapiczy** [fomantic/Fomantic-UI#476]
I tried to switch from the `semantic-ui-less` to `fomantic-ui-less` and I hoped for it to be seamless. However, I get an error from the `less-loader`:

```
ERROR in ./node_modules/fomantic-ui-less/semantic.less (./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./node_modules/fomantic-ui-less/semantic.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):


  @isDark                     : @colors[@@color][isDark];
  @_labelColor                : @colors[@@color][color];
                                     ^
Unrecognised input
      in /Users/user/Projects/project/node_modules/fomantic-ui-less/definitions/elements/label.less (line 622, column 39)
 @ ./node_modules/fomantic-ui-less/semantic.less 4:14-92 14:3-18:5 15:22-100
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

I tried different versions of the `fomantic-ui-less` and `less-loader`. My webpack and loader configuration worked with `semantic-ui-less` so I believe it should work the same with `fomantic-ui-less`.

**Comment by murbanowicz** [comment]
@mkapiczy I am glad it helped! :)

**Comment by mkapiczy** [comment]
@murbanowicz 

I had an issue with global variables from site.variables not being visible to the fomantic UI, and I found that the issue was an alias in webpack. Fomantic ui expects the `site` directory to be in `../semantic-theme/site` instead of `../semantic-ui/site`, so the webpack alias needs to be:

`'../semantic-theme/site': path.join(__dirname, '../semantic-theme/site')`

Instead of:
`'../semantic-ui/site': path.join(__dirname, '../semantic-theme/site')`

**Comment by murbanowicz** [comment]
Not true I think. It depends on your `theme.config` file

**Comment by mkapiczy** [comment]
Oh yeah. You're right, I must have copied the theme.config variables from my previous configuration. False alarm then :D
