### ISSUE TITLE
Horizontal segments ignore compact class

### ISSUE THREAD

**Issue by PhilippGrashoff** [fomantic/Fomantic-UI#477]
See the jsFiddle below. Though the single segments in the "ui horizontal segments" container do have the "compact" class, they stretch full width

## Expected result
.ui.compact.segment only takes needed space

## Actual result
.ui.compact.segment takes full width

## Testcase
https://jsfiddle.net/hf21Lsgz/

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed. See https://jsfiddle.net/eL4usw6n/
