### ISSUE TITLE
[Button] Borders no longer present for basic grouped buttons

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#495]
The basic buttons are no longer showing borders when grouping together within `ui buttons` container. They have borders till version 1.6.4. I'm not sure this is the change of design specification or bug.

Here's [fiddle](https://jsfiddle.net/3Ln4wt9h/) that uses version 1.6.4 and the buttons still have borders. Here's [fiddle](https://jsfiddle.net/tbsxwn74/1/) that uses version 2.7.0 and the borders were no longer present.

**Comment by lubber-de** [comment]
Fixed by #487
