### ISSUE TITLE
[Dropdown] On click dropdown field the result is not showing with the Setting minCharacters

### ISSUE THREAD

**Issue by MartiVB** [fomantic/Fomantic-UI#496]
In the old Semantic the dropdown with apiSettings are also show the whole list if you click on the dropdown icon. In the Fomantic is this not possible, only if i set the minCharacters to 0.

With the settings :
showOnFocus: false
filterRemoteData: true

The result remains the same, you can click the dropdown icon, but the query search for any Character ( which there is non ) so the dropdown url is then looping, searching for result to show.

## Version
Latest version

`$(this).dropdown({
        fullTextSearch: 'exact',
        showOnFocus: false,
        minCharacters: dataSource.includes('{query}') ? 3 : 1,
        apiSettings: {
            url: dataSource,
            onSuccess: function (response, element) {
                let searchText = element.find('input.search').val();

                if (response.all !== undefined && response.all === true) {
                    element.dropdown({ fullTextSearch: 'exact', apiSettings: null, values: response.results });
                    element.dropdown('show');
                    element.find('input.search').val(searchText).change();
                    element.find('.text.default').addClass('filtered');
                    element.dropdown('search');
                } else {
                    element.dropdown('change values', response.results);
                    element.data('search-only', 'true');  // disable get all elements
                    if(response.count !== undefined && response.count !== 0) {
                        element.dropdown('show');
                    }
                    element.find('.text.default').addClass('filtered');
                }
            },
            cache: true
        },
        onShow: function () {
            let element = $(this);

            if(element.data('search-only') !== 'true') {
                element.addClass('loading');
                $.ajax(dataSource.replace('/{query}', '').replace(/\?\w+={query}&/g, '?').replace(/&\w+={query}/g, '')).done(function (response) {
                    var selectedValue = element.dropdown('get value');
                    element.dropdown('change values', response.results);
                    if (response.all !== undefined && response.all === true) {
                        element.dropdown({ fullTextSearch: 'exact', apiSettings: null, values: response.results });
                    } else {
                        element.data('search-only', 'true'); // disable get all elements
                    }
                    element.dropdown('set selected', selectedValue);
                    element.removeClass('loading');
                });
            }
        },
        filterRemoteData: true // dataSource.includes('{query}')
    }).on('keyup', function (event) {
        if (event.keyCode === 8 && $(this).find('input.search').val() === "" && !$(this).hasClass('multiple')) {
            $(this).dropdown('clear');
        }
    });`

**Comment by lubber-de** [comment]
Could you please provide a simplified but reproducable jsfiddle including working datasource so we can easily investigate? You may fork https://jsfiddle.net/31d6y7mn and adjust the code accordingly. Thank you 🙂

**Comment by MartiVB** [comment]
So here's the example : https://jsfiddle.net/1fvrphsa/2/

**Comment by lubber-de** [comment]
Thank you! Confirmed. I'll investigate

**Comment by lubber-de** [comment]
Fixed it by #510 , see your adjusted fiddle here: https://jsfiddle.net/nkhg3cs8/

**Comment by MartiVB** [comment]
Great to hear! When is the next release for this one?

**Comment by hammy2899** [comment]
@MartiVB Possibly sometime early march, we try to release once a month. If you want to use the fix now you can build the develop branch which is basically a beta of the next release.
