### ISSUE TITLE
[Dropdown] Unable to search dropdowns in 2.7.2

### ISSUE THREAD

**Issue by jprateragg** [fomantic/Fomantic-UI#500]
I'm using Fomantic-UI 2.7.2 currently. I'm using both IE 11 and Chrome 72. I'm creating a `<select>` searchable dropdown using the below code:

`$('#repayment_source_1_id, #repayment_source_2_id').dropdown({ fullTextSearch: 'exact', match: 'text'});`

```
<div class="five wide field">
	<label>Repayment Source 1:</label>
	<select class="ui search selection dropdown" id="repayment_source_1_id" name="repayment_source_1_id">
		<option value="">-- SELECT --</option>
		<option value="162">350 Soil Preparation Services</option>
		....
	</select>
</div>
```

For some reason, I'm only able to search the start of the text value. In the above example, if I enter "S" to find "Soil..." I will get no results. I can only search by the number that precedes the text (350 in this example). I've tried this in both Chrome 72 and IE11 and get the same results. Our production code is using Semantic-UI still and it works as expected. Thanks!

**Comment by jprateragg** [comment]
I apologize for the formatting, but whenever I enter this issue it's not formatting even though it should be. Preview makes it look the exact same way as well. Tried on both Firefox and Chrome.

**Comment by lubber-de** [comment]
🤔 I unfortunately cannot reproduce this.
I set up a jsfiddle with the given data and it works as expected:
https://jsfiddle.net/pmyjhfr8/
If if enter a "s" it finds the entry. If i enter a "x" it won't find it (to make sure its not always showing the list)

Could you please adjust the jsfiddle to match your code where the issue is reproducable?
What am i missing?

**Comment by jprateragg** [comment]
Aaaaarrrrggggg. I had declared a `$('.ui.dropdown').dropdown();` at the top of my code I was experimenting with earlier and that was causing it. Please delete this issue.
