### ISSUE TITLE
[Set-up] Incorrect format of file permission octal value in semantic.json

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#502]
# Bug Report
When installing Fomantic-UI with custom method and set the permissions for output files, the permission octal number stores with quotes in `semantic.js` which fails build process and throws error as below.

> [17:10:32] Using gulpfile ~/Desktop/fomantic/semantic/gulpfile.js
> [17:10:32] Starting 'build'...
> Building Semantic
> [17:10:32] Starting 'build-css'...
> [17:10:32] Starting 'Building uncompressed CSS'...
> [17:10:32] Starting 'Building compressed CSS'...
> [17:10:32] 'Building uncompressed CSS' errored after 13 ms
> [17:10:32] TypeError: Expected mode to be null/undefined/number/Object
>     at module.exports (/home/koko/Desktop/fomantic/node_modules/gulp-chmod/index.js:30:9)
>     at build (/home/koko/Desktop/fomantic/semantic/tasks/build/css.js:80:40)
>     at buildUncompressed (/home/koko/Desktop/fomantic/semantic/tasks/build/css.js:130:41)
>     at bound (domain.js:396:14)
>     at runBound (domain.js:409:12)
>     at asyncRunner (/home/koko/Desktop/fomantic/node_modules/async-done/index.js:55:18)
>     at process._tickCallback (internal/process/next_tick.js:61:11)
> [17:10:32] 'build-css' errored after 15 ms
> [17:10:32] 'build' errored after 17 ms
> [17:10:32] The following tasks did not complete: <series>, Building compressed CSS
> [17:10:32] Did you forget to signal async completion?
> 
My `semantic.json` file created as follow when I installed Fomantic-UI with custom method and set the permission for files.
```
{
  "base": "semantic/",
  "paths": {
    "source": {
      "config": "src/theme.config",
      "definitions": "src/definitions/",
      "site": "src/site/",
      "themes": "src/themes/"
    },
    "output": {
      "packaged": "dist/",
      "uncompressed": "dist/components/",
      "compressed": "dist/components/",
      "themes": "dist/themes/"
    },
    "clean": "dist/"
  },
  "permission": "644",
  "autoInstall": false,
  "rtl": false,
  "components": ["reset", "site", "button", "container", "divider", "flag", "header", "icon", "image", "input", "label", "list", "loader", "rail", "reveal", "segment", "step", "breadcrumb", "form", "grid", "menu", "message", "table", "ad", "card", "comment", "feed", "item", "statistic", "accordion", "calendar", "checkbox", "dimmer", "dropdown", "embed", "modal", "nag", "placeholder", "popup", "progress", "slider", "rating", "search", "shape", "sidebar", "sticky", "tab", "text", "toast", "transition", "api", "form", "state", "visibility"],
  "version": "2.7.2"
}
```

## Steps to reproduce
1. Run command `npm install fomantic-ui` in terminal
2. Choose 'Custom' method for set-up
3. Proceed the next steps as required. When asking whether to set the permissions for outputted files or not, choose 'Yes' and set the desire permission value, (in my case, it's 644). And continue and finish set-up process.
4. Go to the directory where `gulpfile.js` is located. And run the build process via `gulp build`

## Screenshot
![gulp-build](https://user-images.githubusercontent.com/930315/53086930-6de7f380-3534-11e9-98c7-4e91d533f9cf.png)

## Version
2.7.2

## Note
As far as I tested, if I typed something for permission value, it stored in `semantic.json` file surrounded by the quotes, which led to this problem.

If I ignored to set permission, it store as `false` in `semantic.json`. If I hit enter to leave as default value (744), the permission value store `744` without quotes and build process has no problem. In both cases, build process has no problem and working fine.

If I manually edited the `semantic.json` file and removed the quote from `permission` property. The build process works as expected.

I'm not sure whether it's the problem from Fomantic-UI/Semantic-UI or npm itself.

I've already posted this [issue](https://github.com/Semantic-Org/Semantic-UI/issues/6684) in Semantic-UI repo before and no reply so far.

**Comment by ColinFrick** [comment]
I'll look into this this evening.

**Comment by lubber-de** [comment]
I guess, it might fix it when we change:
https://github.com/fomantic/Fomantic-UI/blob/783786b5c27bf0252dc47c0277746b4a695210ca/tasks/config/project/install.js#L185-L188

to
```javascript
// add permissions
    if(answers.permission && !isNaN(answers.permission)) {
      json.permission = parseInt(answers.permission,10);
    }
```

**Comment by lubber-de** [comment]
gulp-chmod is the culpit here which seems to  expect a real numeric value and has no exception for a given string. That said, my above suggestion for a fix will not work if one would provide a permission value with leading zeroes (but that would mean to deny access to the file anyway, which should never be the case)

**Comment by ColinFrick** [comment]
@lubber-de After just a quick glance, it should work if we just call `parseInt(config.permission, 8)` where chmod is called. Having the string `755` in the config file makes more sense than `493` because gulp-chmod wants the octal representation of the permission.
