### ISSUE TITLE
[Calendar] jumps to the last day of the month if short year (YY) is provided 

### ISSUE THREAD

**Issue by MarcelMpunkt** [fomantic/Fomantic-UI#507]
# Bug Report

Calendar jumps to last day of month if user only provides two characters of the year (yy) instead of four (yyyy)
[in german date notation]

## Steps to reproduce
1. click in calendar ui form
2. change date (in german notation dd.mm.yy) 
- only provide short form of year
- e.g. **5.6.88**
3. click so that focus is lost

## Expected result
date should be 5.6.1988
## Actual result
date is 30.6.1988

## Testcase
https://jsfiddle.net/to7c056b/1/

## Screenshot (when possible)

![unbenannt](https://user-images.githubusercontent.com/18383682/53178994-2f653e00-35f3-11e9-8587-12ea3b8b3283.PNG)

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #513 
See https://jsfiddle.net/mar7xzvu/
