### ISSUE TITLE
[Modal] 'onDeny' callback runs only one time

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#511]
# Bug Report
If a modal opens another modal using `onDeny` callback, the `onDeny` method of that modal works only one time and it never works again which means the modal cannot be closed.

## Steps to reproduce
Please go to this [fiddle](https://jsfiddle.net/1qo9nkre/).

1. Click the button to open Modal 1.
2. Inside Modal 1, click the button to open Modal 2. 
3. Close Modal 2, which will re-open Modal 1 again.
4. Click again the button in Modal 1 to open Modal 2 again.
5. Try to close Modal 2 and it cannot be closed.

If the dimmer is clicked, the modals still close though.

## Expected result
The Modal 2 should be closed and Modal 1 should be opened again.

## Actual result
The Modal 2 can only close one time, and not able to close again.

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #511, see https://jsfiddle.net/0m1pukaw/
