### ISSUE TITLE
[Calendar] century handler for short year (dd.mm.yy) input

### ISSUE THREAD

**Issue by MarcelMpunkt** [fomantic/Fomantic-UI#514]
# Feature Request

## Description
if the user inputs the year in short form like this: dd.mm.yy
it is automatically corrected to: dd.mm.yyyy

there should be an option to control which years are put in which centuries

At the moment if you input:
 **11.12.59** it is corrected to **11.12.2059**
if you input:
 **11.12.60** it is corrected to **11.12.1960**

## Example

maybe it could be controlled via years

e.g.  100 years (2019-100=1919)
**>= currentYear**
19 -> 1919 
20 -> 1920
88 -> 1988
**< currentYear**
18 -> 2018
  4 -> 2004
12-> 2012

## Testcase 
https://jsfiddle.net/mar7xzvu/

**Comment by lubber-de** [comment]
Prepared in #527
