### ISSUE TITLE
[Dropdown] Add clear icon for single search selection dropdown

### ISSUE THREAD

**Issue by vengaar** [fomantic/Fomantic-UI#519]
# Feature Request

As for single dropdown, have with remote content a option 'clearable: true' wich to clear selection

## Description
To have clearable icon wich do a clear action on dropdown this apiSettings defined
```
$('#id').dropdown({
	apiSettings: {
		url: '/...',
		cache: true
	},
	clearable: true,
});
```

## Screenshot (when possible)
![]()

**Comment by lubber-de** [comment]
This is already supported
See https://jsfiddle.net/lubber/hdfewams/7/
