### ISSUE TITLE
[Modal] Fullscreen modal option that covers entire screen

### ISSUE THREAD

**Issue by keshmir** [fomantic/Fomantic-UI#522]
# Feature Request

## Description
Current Fullscreen modal, still does not take over the entire screen.  There are many cases that the modal content needs the entire screen.

## Screenshot (when possible)
![]()

**Comment by lubber-de** [comment]
Implemented by #526

**Comment by keshmir** [comment]
just saw the implementation.  looks great!  can't wait to test it out on my code.
