### ISSUE TITLE
Meteor JS Integration

### ISSUE THREAD

**Issue by lesliechw** [fomantic/Fomantic-UI#528]
# Help Wanted

## Problem
Hello all, I have questions about Formantic UI integration with Meteor JS.

https://fomantic-ui.com/introduction/integrations.html

The above link mentioned to have the integration, one need to install it by "meteor add semantic:ui".

But I believe this is just a direct copy of the original Semantic UI documentation.

How about the integration with Formantic UI? What are the proper steps to have it integrate? Please advice. Thanks in advance.

**Comment by hammy2899** [comment]
Personally I have never used Meteor before so I can't advise you. What I can tell you however is that the SUI org has 2 repos
 - [Semantic-UI-Meteor](https://github.com/Semantic-Org/Semantic-UI-Meteor)
 - [Semantic-UI-Meteor-Data](https://github.com/Semantic-Org/Semantic-UI-Meteor-Data)

The `Semantic-UI-Meteor` repo is the Meteor package and it has a dependency on `Semantic-UI-Meteor-Data` which contains the SUI styles. I am fairly confident you could fork both packages and change the LESS dist inside `Semantic-UI-Meteor-Data` to the FUI version and then change the dependency in your `Semantic-UI-Meteor` fork to use your `Semantic-UI-Meteor-Data` fork. If I understood correctly those steps should work.

**Comment by lesliechw** [comment]
Thanks for the tips and I'll try it. Will update it here and if success, will share it out to your project. Have a good day.

**Comment by lesliechw** [comment]
Hi,

Because Meteor JS support NPM, I install Formantic into new Meteor project to test it out. I just follow your regular installation guide, test add class "ui button", it seems to be working as expected.

However, when ever I start the Meteor app, I got the following warning message and I'm not sure how much harm it will cause and which part should I fix it. Please advice, the following are the warning message:

```
app/semantic/dist/components/site.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/semantic/dist/components/site.min.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/semantic/dist/semantic.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
app/semantic/dist/semantic.min.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
```

**Comment by hammy2899** [comment]
@lesliechw As I have mentioned I am not familiar with Meteor so I can't advise much in that area but from the message you have posted it seems to just be some warnings about the CSS. I think it should be fine to just ignore them since they are just warnings and they don't have any issues when using them normally.

**Comment by LarsBuur** [comment]
@lesliechw meteor and fomantic-ui works great in my envoronment. Only hassle is that the combination with meteor-up (used for deployment) fails. There is a separate #782 issue in this regards. If you still have problems then try to post your semantic.json file here

**Comment by louwers** [comment]
Seems to work out of the box.
1. meteor npm install --save fomantic-ui
2. save to `imports/semantic`
3. `npx gulp build`
4. use `import '/imports/semantic/dist/semantic.css'` and `import '/imports/semantic/dist/semantic.js'`

**Comment by hammy2899** [comment]
No response so I am assuming this is solved.
