### ISSUE TITLE
Multi modal + "Disabling Vertical Centering"

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#530]
# Bug Report

Multi modal + "Disabling Vertical Centering"

## Steps to reproduce
1. click button [Procceed]

## Expected result
The first and second modal are display on the top of the window : same position of first modal before the second modal is display

## Actual result
the first and second modal are display vertical center

## Testcase
https://jsfiddle.net/9pnmzgkc/

## Screenshot (when possible)
![dialog](https://user-images.githubusercontent.com/1622751/53601249-f2c5b380-3bab-11e9-82b7-8b2d24fd5e54.gif)

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #532

**Comment by dutrieux** [comment]
Your are a boss !
