### ISSUE TITLE
Model + dropdown with showOnFocus=false

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#533]
# Bug Report

## Steps to reproduce
1. Open the dialog with button
2. Display error message on console

## Expected result
No error on console

## Actual result
Error message on console : "ReferenceError: event is not defined"

## Testcase
On firefox 60.5.2esr (this issue does not occurs on Chrome or Microsoft Edge)
https://jsfiddle.net/dutrieux/7gwko0L6/14/

## Screenshot (when possible)
![dialog](https://user-images.githubusercontent.com/1622751/53684367-9c23bb00-3d0c-11e9-9522-8a3a5376d497.gif)

## Version
2.7.2 on Firefox v65.0.2 or 60.5.2esr

**Comment by lubber-de** [comment]
@dutrieux Thanks for the bugreport. Fixed by https://github.com/fomantic/Fomantic-UI/pull/534
See your adjusted fiddle here https://jsfiddle.net/zhgwbLjd/

**Comment by dutrieux** [comment]
It seems okay !
@lubber-de very very thx for your works
