### ISSUE TITLE
[Proposal] Add a new input – increment/decrement value

### ISSUE THREAD

**Issue by andriihorpenko** [fomantic/Fomantic-UI#536]
Hi 👋 I’d like to propose a new kind of input – increment/decrement switch. Basically you could see that when you’re buying something online and there is quantity “switch”. 

I tried to achieve this by button and input grouping, but that did not work, cause for now Fomantic is unable to combine buttons by both sides of the input field simultaneously.

I believe this would be cool to have separate input like this. Thanks in advance.

P.S. Model: 
![e5349d2a-393a-4256-b6da-c327c8373ddd](https://user-images.githubusercontent.com/13716167/53720174-bffc1380-3e68-11e9-9d99-18d6c3154731.jpeg)

**Comment by hammy2899** [comment]
Hi @andrewgorpenko thanks for the proposal. I don't think we need to add any new components to FUI. I think the best option here is to make the input actions have the same behavior as the the input labels.

input with double label:
![image](https://user-images.githubusercontent.com/11588822/53720609-11040b80-3e59-11e9-9bfa-c9966e4e99be.png)

You could then put a button on each side of the input.

**Comment by andrewgorpenko** [comment]
Not component, just extend input component. Btw, inputs with 2 labels work perfectly, but with buttons on each side... I mean the button on the right is attaching, while the button on the left is not. Strange behavior or I’m a newbie 🤓

**Comment by hammy2899** [comment]
@andrewgorpenko Your correct the buttons don't attach to the input when they are on both sides like the labels do, that would be what we fix.

**Comment by andrewgorpenko** [comment]
Oh ya, that would be awesome 😎

**Comment by PhilippGrashoff** [comment]
Hi,
HTML5 input type="number" offers kind of that on most browsers, they usually display up and down arrows at the end of the input. Only works for full numbers though.

**Comment by andrewgorpenko** [comment]
You’re wrong about “only for full numbers”. You can specify the “step” option in order to specify increment value.
