### ISSUE TITLE
[Bug] Buttons behavior inconsistent between semantic and fomantic

### ISSUE THREAD

**Issue by douglasg14b** [fomantic/Fomantic-UI#539]
# Bug Report

Honestly not sure if bug or not, but it seems undesirable?

### 1

Individual button styles are ignored for the `buttons` parent when it comes to `inverted`. If I have an `inverted` button under a `buttons` div, the `inverted` class is ignored. With semantic-ui stylesheets, it would apply the `inverted` class on a per-button basis.

### 2

The buttons borders (box-shadow) are swallowed inbetween buttons, this is also new in fomantic-ui. It seems like potentially unwanted behavior over not swallowing the edges?

**Semantic-UI:** 
![image](https://user-images.githubusercontent.com/1400380/53855005-a948e000-3f80-11e9-9dbd-667e3104973e.png)

**Fomantic-UI:** 
![image](https://user-images.githubusercontent.com/1400380/53854974-88808a80-3f80-11e9-9e6e-1d832a212c28.png)

## Testcase
For 1: https://jsfiddle.net/jwzykb14/

## Version
2.7.2

**Comment by douglasg14b** [comment]
If this is expected behavior, I suggest a class that removes the 2px negative left margins on all but the first button? Maybe `bordered`?

**Comment by lubber-de** [comment]
This is already fixed by https://github.com/fomantic/Fomantic-UI/pull/487 for 2.7.3
See adjusted fix for your example:
![boxshadowbutton](https://user-images.githubusercontent.com/18379884/53880995-c5955d00-4012-11e9-9b66-b40fac0f251c.gif)
