### ISSUE TITLE
[Table] Wrong slider alignment in definition table

### ISSUE THREAD

**Issue by helmi77** [fomantic/Fomantic-UI#547]
# Bug Report

## Steps to reproduce
1. Create a definition table
2. Add a fitted slider in the first column
3. (Alternatively check out the one in the [docs](https://fomantic-ui.com/collections/table.html#definition))

## Expected result
Properly aligned slider (as in Semantic UI)

## Actual result
Slider is aligned to the bottom right of the cell.

## Testcase
https://jsfiddle.net/woa3bv1t/

## Screenshot (when possible)
![slider](https://user-images.githubusercontent.com/1245519/54033227-08db0180-41b4-11e9-824a-f41be9eb784c.png)

## Version
2.7.2

**Comment by helmi77** [comment]
The problem might be the padding of the slider:
```css
.ui.slider:not(.vertical) {
    padding: 1em 0.5em;
}
```
If you set the padding to `0` the alignment seems okay again.

**Comment by lubber-de** [comment]
This seems to be a basic problem because the (new) `slider` component conflicts with the `slider checkbox`  here (which is meant differently and also exists in SUI)

**Comment by lubber-de** [comment]
Fixed by #553 Supposed to be part of v2.7.3
