### ISSUE TITLE
[Form Validation] form("get validation", x) is inconsistent

### ISSUE THREAD

**Issue by iarspider** [fomantic/Fomantic-UI#548]
# Bug Report

form("get validation", x) is inconsistent: it expects it's argument to be DOM node, not string - while all other form methods consume string.

## Steps to reproduce

Run fiddle and press button

## Expected result

Middle text field should contain `{"rules":[{"type":"empty"}],"identifier":"foobar"}`, 
and lower text field should (probably) contain `false`

## Actual result

Lower text field contains `{"rules":[{"type":"empty"}],"identifier":"foobar"}`, 
and middle text field contains `false`

## Testcase
https://jsfiddle.net/qv75f0jL/1/

## Screenshot (when possible)
![]()

## Version
2.7.2

**Comment by prudho** [comment]
Actually, this is not really a bug. The `get validation` is used internally by Fomantic and should expect a node as argument since it has to check validation for grouped fields too, like this one:
```html
    <div class="grouped fields">
        <label>Pick one fruit</label>
      <div class="field">
        <div class="ui radio checkbox">
          <input type="radio" name="fruit" tabindex="0" class="hidden">
          <label>Apples</label>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <input type="radio" name="fruit" tabindex="0" class="hidden">
          <label>Oranges</label>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <input type="radio" name="fruit" tabindex="0" class="hidden">
          <label>Pears</label>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <input type="radio" name="fruit" tabindex="0" class="hidden">
          <label>Grapefruit</label>
        </div>
      </div>
    </div>
```

4 fields sharing the same identifier, here's the catch.

**Comment by lubber-de** [comment]
As @prudho pointed out, this is not a bug.
