### ISSUE TITLE
[Calendar] Setting initialDate doesn't update text field

### ISSUE THREAD

**Issue by iarspider** [fomantic/Fomantic-UI#549]
# Bug Report
Not sure if it's a bug or "by design"...

## Steps to reproduce
Run fiddle

## Expected result
Text box should contain `April 26, 2018`

## Actual result
Text box contains prompt text

## Testcase
https://jsfiddle.net/3znhvqat/

## Screenshot (when possible)
[Example](https://screenshots.firefox.com/A0evqp9G8LhyEdb4/jsfiddle.net)

## Version
2.7.2

**Comment by prudho** [comment]
It's a bug, definitely. Some rewrite is needed to fix this and to tidy a little the code base. I'll try to submit a PR on Monday.

**Comment by prudho** [comment]
Fixed in #559.
