### ISSUE TITLE
[Header] Strange icon header behavior

### ISSUE THREAD

**Issue by andrewgorpenko** [fomantic/Fomantic-UI#551]
# Bug Report

## Steps to reproduce
1. Create  a header with the icon
2. Refresh the page a few times and notice icon "jumping" over the header.

## Expected result
Proper position of the icon

## Actual result
Sometimes the icon "jumps" to the top of the header

## Testcase
I was unable to reproduce this issue on the JSFiddle. However, I am using a clean Fomantic installation without any modification of LESS files.

## Screenshot (when possible)
Abnormal behavior (happening randomly, ~every third page visit):
![Abnormal](https://image.prntscr.com/image/BZt-aQOzSiOgILcjtKG-Fg.png)
Normal behavior:
![Normal](https://image.prntscr.com/image/By4NpKsbTq__vmjmkwoRHw.png)

## Version
2.7

**Comment by lubber-de** [comment]
If you are unable to create a reproducable jsfiddle, how did you manage to create the screenshots then? Do you have additional code which probably changes/adds (inline) styles? Without reproducable code it's gonna be hard to provide a fix 🤕

**Comment by andrewgorpenko** [comment]
This screenshots were taken on my local website. No additional inline styles and, as I mentioned above, Fomantic is freshly installed.

**Comment by andrewgorpenko** [comment]
Idk how this is happening, miracle 🙌

**Comment by andrewgorpenko** [comment]
More screenshots:
### DOM
![](https://image.prntscr.com/image/6G_ru8rYTVWgUucXMQQCJQ.png)

### Styles
#### Header
![](https://image.prntscr.com/image/RQNvOFq4RsishV2LfHIojg.png)
#### Icon
![](https://image.prntscr.com/image/dYGBr4kGQMuNrJnv1sOf9g.png)
#### Content(text)
![](https://image.prntscr.com/image/QlZdPaI3TbqQIiTuASUHfg.png)

**Comment by andrewgorpenko** [comment]
Found the cause: headers with icons are not compatible with fonts other than Lato. I was using Open Sans and this was causing the strange bug. I've temporary switched to Lato and everything is working as it should be. Why is it happening and will it be fixed?

**Comment by andrewgorpenko** [comment]
Just reinstalled Fomantic from scratch and the same issue.

**Comment by lubber-de** [comment]
I unfortunately still cannot reproduce this behavior. 😢 
I prepared a jsfiddle given your above stated informations using the Open Sans Font and the same codesnippet.
Please adjust this until it gets reproducable. Thank you
https://jsfiddle.net/qyf4mzhn/

**Comment by andrewgorpenko** [comment]
I must close this issue because I am unable to reproduce this on JSFiddle... I've adjusted the snippet above and refreshed fiddle for a lot of times. Nothing. Strange. Nevertheless, thanks for the fast response.
