### ISSUE TITLE
Get value slider

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#552]
[slider]How get value slider

**Comment by lubber-de** [comment]
2 options here:
```
$('.ui.slider).slider('get value');
```javascript
Or retrieve them in a `onChange` Method

```javascript
$('.ui.slider')
    .slider({
      onChange: function(value) {
        console.log('Your slider was changed to ' + value)
      }
    })
```
I must admit, the docs are missing information about behaviors. We will add those.

**Comment by apple-idn** [comment]
I really appreciate this answer, indeed the documentation is not available, thank you very much

**Comment by lubber-de** [comment]
Behavior docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/156

**Comment by migmolrod** [comment]
I found out that for a _range_slider_ it works like this:

```javascript
$('.ui.slider')
    .slider({
      onChange: function(value, min, max) {
        console.log('Your first slider was changed to ' + min)
        console.log('Your last slider was changed to ' + max)
        console.log('The difference between both your sliders is now ' + value)
      }
    })
```

where

**Comment by YongxinZz** [comment]
> 2 options here:
> 
> ```
> $('.ui.slider).slider('get value');
> ```
> 
> Or retrieve them in a `onChange` Method
> 
> ```js
> $('.ui.slider')
>     .slider({
>       onChange: function(value) {
>         console.log('Your slider was changed to ' + value)
>       }
>     })
> ```
> 
> I must admit, the docs are missing information about behaviors. We will add those.

I'm wondering all these js code can it moves til a separate js file instead of having them all inside index.html?

**Comment by lubber-de** [comment]
Make sure your external JS file is loader AFTER jquery is included, should work then

**Comment by YongxinZz** [comment]
So I have included it like this now, app.js is my external JS file, but it still not working somehow

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.js"></script>
    <script src="../semantic/dist/semantic.min.js"></script>

    <script type="text/javascript" src="app.js"></script>

**Comment by lubber-de** [comment]
You included semantic.min.js twice
```
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.8.7/dist/semantic.min.js"></script>
<script src="../semantic/dist/semantic.min.js"></script>
```
Is the second entry perhaps an old SUI version 2.4? The slider module does not exist there.
Remove the second line and just leave the CDN Import. Please open a new [discussions](https://github.com/fomantic/Fomantic-UI/discussions) thread if you still have issues.

**Comment by YongxinZz** [comment]
Thanks for help, things working now :)
