### ISSUE TITLE
[toast]Toast with Actions - approve, deny 

### ISSUE THREAD

**Issue by apple-idn** [fomantic/Fomantic-UI#566]
# Feature Request
on Actions - Approve and deny and right image(Whatever it is)
## Description
feature same OSX Notification Center with active Approve and deny

## Example
![image](https://user-images.githubusercontent.com/33564576/54219315-403a0d00-452a-11e9-8359-15afabbdb1af.png)

**Comment by lubber-de** [comment]
Duplicate of #160

**Comment by lubber-de** [comment]
Possible by #1129
