### ISSUE TITLE
[Calendar] Calendar's months navigation doesn't work when it is inside definition table

### ISSUE THREAD

**Issue by dfsmirnov** [fomantic/Fomantic-UI#575]
# Bug Report

## Steps to reproduce
1. Create "ui definition table"
2. Add thead, tbody, tr, td, and calendar code inside it, 
3. add js code, 
4. run it, 
5. click on control

## Expected result
When u inside calendar edit field, calendar opens and u can navigate to next/prev months

## Actual result
Calendar opens with inactive header, so you can't navigate through months and years

## Testcase
https://jsfiddle.net/dfsmirnov/8o2tr1hL/
Here is both - definition and not definition table.
in first navigation disabled, in second definition works

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #604 
See your adjusted fiddle here: https://jsfiddle.net/jyL2rfx6/
