### ISSUE TITLE
[Transition] strange behaviour since 2.7.2

### ISSUE THREAD

**Issue by j5k** [fomantic/Fomantic-UI#581]
## Steps to reproduce
open fiddle and run code

## Expected result
Feed items scale up one after another. Before 2.7.2 it works very well.

## Actual result
Feed items scale up and **disappear** again

## Testcase
http://jsfiddle.net/xwf438t7/

## Version
since 2.7.2

**Comment by lubber-de** [comment]
This has already been fixed in shortly upcoming 2.7.3 🙂 
See your adjusted fiddle here http://jsfiddle.net/nakb2vyd/

**Comment by j5k** [comment]
Thank you very much for the fast response! Therefore I will close this bug report.
