### ISSUE TITLE
Multiple Sub Menu Items in Dropdown

### ISSUE THREAD

**Issue by jakkepedder** [fomantic/Fomantic-UI#590]
# Bug Report

Issues selecting second Sub Menu Item in Fixed Menu (Dropdown)

## Steps to reproduce
1. Add multiple items with submenu
2. Not possible to select Link Item 2

## Expected result
To be able to select Link Item 2 in the dropdown menu

## Actual result
When trying to select Link Item 2 the "main" Dropdown and sub menu opens.
It only works on the last Sub Menu Item.

## Testcase

https://jsfiddle.net/L7eabtcj/3/

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by #594
