### ISSUE TITLE
Bugs: [Dropdown] Can't click after adding something to dropdown

### ISSUE THREAD

**Issue by WilliamMayor** [fomantic/Fomantic-UI#591]
# Bug Report

This feels very weird, not sure if it's something I'm doing, or a bug.

If you have a dropdown on a page with `{allowAdditions: true}` and you try to add a new thing then you can no longer click on links or submit forms.

I've tried this on FF Developer Edition on macOS and Windows 10, as well as Chrome on macOS.

## Steps to reproduce
1. Go to https://fomantic-ui.com/modules/dropdown.html#tagging-and-user-additions
2. Click on the "Single" dropdown and type "New" into the search box
3. Press enter, or click away from the dropdown

## Expected result
After typing a new option you can now submit the form you're filling in. Or click a link to navigate away.

## Actual result
Clicking on links doesn't result in a page navigation. If you try to submit the form, you can't (including using the keyboard).

I've noticed that the links on the docs page that are anchors to somewhere else on the same page still work. My guess is that they're listening on the click event and then scrolling the page to that element? If that's the case then it feels like there's a click event listener that's attached when you open the dropdown and isn't removed when you try to add a new addition.

## Version
2.7.2

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/593
See https://jsfiddle.net/zwceqvtm/1/

**Comment by WilliamMayor** [comment]
Wow that was fast! Thanks!
