### ISSUE TITLE
[List] Icons in lists don't line up

### ISSUE THREAD

**Issue by Merlin04** [fomantic/Fomantic-UI#597]
# Bug Report

## Steps to reproduce
1. Make a list with different icons like in the List examples

## Expected result
The left side of the text lines up

## Actual result
The left side of the icon lines up

## Testcase

https://jsfiddle.net/4gkvha2b/

## Version
2.7.2

**Comment by globophobe** [comment]
How about a reasonable default min-width?

```
.ui.list > .item > i.icon {
  min-width: 1.55em;
}
```

https://jsfiddle.net/tkuyoj4r/
