### ISSUE TITLE
compact labeled button icon misaligned

### ISSUE THREAD

**Issue by davekc** [fomantic/Fomantic-UI#598]
# Bug Report
The icon of "compact labeled icon button" is simply misaligned... don't now since when neither how to fix this (since the source is exactly as it was). Maybe it has something to do with Awesome Font update!? Thanks!

## Steps to reproduce
https://fomantic-ui.com/elements/button.html#compact

## Version
2.7.2

**Comment by prudho** [comment]
Seems to be introduced by 1f7160203ee8a4c7c42dad2815113967571e97b9.

**Comment by lubber-de** [comment]
Fixed by #601
See http://jsfiddle.net/0vp6kz2g/

**Comment by davekc** [comment]
Great, thanks a lot! (I don't know if I have to close the issue, so I leave it as-is)

**Comment by hammy2899** [comment]
@davekc Leave it open, we will manage it 😉
