### ISSUE TITLE
[Modal] Broken "image content" layout

### ISSUE THREAD

**Issue by donaggio** [fomantic/Fomantic-UI#599]
# Bug Report

Modal with "image content" has broken layout: textual content flows under the image instead of staying at its right

## Steps to reproduce
1. https://fomantic-ui.com/modules/modal.html#scrolling-modal
2. Click on Scrolling Modal or Internally Scrolling Content "Run Code" button

## Expected result
1. https://semantic-ui.com/modules/modal.html#scrolling-modal
2. Click on Scrolling Modal or Internally Scrolling Content "Run Code" button

## Version
2.7.2

**Comment by prudho** [comment]
Introduced by 6f4f09c5c45c5416b90505d97f9757ce398f624d. Removing the line `flex-wrap: wrap;` seems to fix this issue.

**Comment by lubber-de** [comment]
@prudho Yes, but then #209 will not work anymore. 😢 
 I'll investigate

**Comment by lubber-de** [comment]
Fixed by #599
See https://jsfiddle.net/kdvum7ho/2/

@prudho You were right, in the end i had to remove the flex-wrap.
