### ISSUE TITLE
npm install of fomantic-ui@2.7.3 not working - missing dependencies

### ISSUE THREAD

**Issue by prmdhost** [fomantic/Fomantic-UI#607]
# Bug Report

The modules for gulp moved to devDependencies in the package.json, thus after running npm install on a new project, the devDependencies won't be installed and the 'gulp install'-hook fails. 

## Steps to reproduce
1. $ npm init
2. $ npm install --save fomantic-ui

## Expected result

Installation and setup of all required modules.

## Actual result

Missing gulp and other modules. Only jquery is installed.

## Version
2.7.3

**Comment by dutrieux** [comment]
I have the same problem :s

**Comment by hammy2899** [comment]
I'm on it 😱

**Comment by hammy2899** [comment]
@prmdhost @dutrieux Should be fixed now 👍

**Comment by dutrieux** [comment]
You push a 2.7.3.1 or we need to wait 2.7.4 ? because a this time I can't install refresh install or update to 2.7.3 :s

**Comment by dutrieux** [comment]
> 
> 
> @prmdhost @dutrieux Should be fixed now 👍

You are the best !

**Comment by hammy2899** [comment]
@dutrieux Its already published, its tagged as 2.7.4
