### ISSUE TITLE
Default theme overrides not included when using a packaged theme

### ISSUE THREAD

**Issue by pbernery** [fomantic/Fomantic-UI#619]
# Bug report

This is more a question than a bug report I guess, but I didn't find any explanation on this behaviour.

When using a packaged theme, the default theme variables are used but not the overrides. What is the reason of this behaviour?

This is notably confusing for the "reset" global component, which includes Normalize, which is kind of mandatory to have Semantic/Fomantic UI working correctly.

**Comment by lubber-de** [comment]
Which packaged theme are you talking about, so we can try it out ourselves?
Any packaged theme should contain all desired `.overrides` and `.variables` If any of them is missing, only the default one will be used. (The default files are **always** imported first!)
The reset.overrides slightly adjusts settings which should (by theme design) differ to the default normalize.css setting

**Comment by pbernery** [comment]
Actually, it seems that the default theme overrides are not imported if you change the theme in theme.config. 

If I am not mistaken, the function loadOverrides In the file [theme.less](https://github.com/fomantic/Fomantic-UI/blob/master/src/theme.less) is missing an import of the default theme overrides. If it was, the default theme would be completely applied, then overridable by the packaged theme. 

Currently, overrides of the default theme are not imported. This leads to checkbox not checked, accordion with weird aspects, or normalize not included, because a part of the definition of these “components” is those files. 

I’m using a custom packaged theme, but I guess it should have the same behavior with the GitHub theme. I’ll try it, but in the meantime, if you try to display a checkbox with this theme, I guess it won’t display the check.

**Comment by lubber-de** [comment]
😱 It seems, you are totally right, interesting it was never  mentioned before for SUI (we haven't touched the loadoverrides since FUI was forked from SUI)

**Comment by lubber-de** [comment]
I think this should be fixed by #626

**Comment by pbernery** [comment]
Indeed. I thought it was “by design” but couldn’t find any clue of that. 

FYI, we also added the import of .overrides files as you did in the PR.
