### ISSUE TITLE
Conflicting CSS styles for certain dropdown menu item icons

### ISSUE THREAD

**Issue by maksis** [fomantic/Fomantic-UI#620]
# Bug Report

## Expected result

`image` and `remove` icons should be aligned just like other icons

## Actual result

Those icons are misplaced

## Testcase

http://jsfiddle.net/se7hm0wf/

## Screenshot (when possible)

![image](https://user-images.githubusercontent.com/5640804/55575856-8e50c380-5718-11e9-9a79-47924e88f151.png)

## Version
2.7.4

**Comment by lubber-de** [comment]
Fixed by #622
