### ISSUE TITLE
[Form Segment] Form group of segments lost rounded corner when loading

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#628]
# Bug Report
If the group of segments is form and it has CSS class name `loading`, it lost the rounded corner.

## Steps to reproduce
1. Create the form with class name `ui form segments`.
2. Add the form fields within each `ui segment` container.
3. Manipulate the form to put loading state. Or add class name `loading` to `ui form segments`.

## Expected result
The segments should keep rounded corners.

## Actual result
The rounded corners become square until the class name `loading` is removed.

## Testcase
Open https://jsfiddle.net/mgfLs0e1/, and click the submit button to reproduce.

## Screenshot
![FomanticUI-Segments](https://user-images.githubusercontent.com/930315/55627589-93734880-57d4-11e9-871b-50bc4ebf7204.png)

## Version
2.7.4

**Comment by lubber-de** [comment]
Fixed by #629
