### ISSUE TITLE
[Modal] Fade out inner dimmer on the first modal when the second modal is closed

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#633]
# Feature Request

## Description
Could you please add animation fade out on the dimmer on the first modal when the second modal is close, to have the same effect (fading) as when we close the first modal.

**Comment by lubber-de** [comment]
Could you please create a jsfiddle to reproduce your issue? My guess is: You have different dimmer settings  for multiple modals?
Or is your request related to #605?

**Comment by dutrieux** [comment]
https://jsfiddle.net/0Lwnhdpc/

I haven't different dimmer settings : I use the defaut dimmer

My request are not related to #605

**Comment by lubber-de** [comment]
Ah, you mean the inner dimmer which only covers the first modal itself to prevent clicking on it. I tag this as enhancement

**Comment by dutrieux** [comment]
Yes that's inner dimmer : sorry for my bad english :s

**Comment by lubber-de** [comment]
Implemented by #2725 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/zr8xescm/1/
