### ISSUE TITLE
[Modal] Add scrollbar margin also to fixed menu and toast to also prevent sliding effect

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#634]
# Feature Request

## Description
At this time, when the main page have a scrollbar and a modal is open a margin-right:17px is had to the body to remove a sliding effect and the margin-right is remove when all modal are closed.
Could you please had too on "fixed menu" and toast components

Note : margin-right doesn't work on position: fixed; but padding work.

**Comment by lubber-de** [comment]
Fixed by #644
