### ISSUE TITLE
[Dropdown] Can't clear dropdown cache

### ISSUE THREAD

**Issue by wolfsblu** [fomantic/Fomantic-UI#635]
# Bug Report

## Steps to reproduce
1. Create a search selection dropdown with remote content:
 `$('..').dropdown({ apiSettings: { .. } })`
2. Search for a specific item in the dropdown list
3. Remove the item from the remote data source
4. Search for the item in the dropdown dialogue again

## Expected result
There should be a way to clear the cache similar to `$('..').search('clear cache')` so that the item is no longer included in the dropdown list.

## Actual result
The item is visible indefinitely thanks to being cached.

## Version
2.7.4

**Comment by lubber-de** [comment]
Does
```javascript
apiSettings:{
  cache:false
} 
```
help?

**Comment by helmi77** [comment]
Yes, it's a workaround, but I'd like to keep using the cache. I simply need to clear it upon certain events.

**Comment by lubber-de** [comment]
@helmi77 I'll tag this as a enhancement then

**Comment by prudho** [comment]
`$('..').search('clear cache', value)` allow to delete from cache a single item.

**Comment by lubber-de** [comment]
@prudho It's about `dropdown`, not `search` 😉

**Comment by lubber-de** [comment]
Implemented by #2716
