### ISSUE TITLE
[Menu] Mouse cursor should be pointer on div.item

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#637]
# Feature request

## Steps to reproduce
1. Go to https://fomantic-ui.com/modules/tab.html#centered-item
2. Click tabs

## Expected result

Mouse cursor should be `pointer` on `tab` so that it looks clickable.
This seems possible if tab item is marked up as `a.item`.

## Actual result

Cursor do not change (keep `default`) if `div.item`.

## Screenshot (when possible)
![cursor-tab](https://user-images.githubusercontent.com/127635/55698616-b3d41a80-5a01-11e9-97a1-95bbcb6ca169.gif)

## Version
2.7.4

**Comment by lubber-de** [comment]
Closing for known reasons. See
https://github.com/fomantic/Fomantic-UI/pull/638#discussion_r273023348
