### ISSUE TITLE
[Form] Attached textarea

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#639]
# Feature Request

## Description

It would be helpful if textarea have `attached` variation so we can attach other contents (e.g. message as guidance of textarea).
Example: https://jsfiddle.net/2tbgmx7y/2/

Textarea does not support `attached` variation currently.
![image](https://user-images.githubusercontent.com/127635/55701501-5397a580-5a0e-11e9-8406-b6c458d9a6ef.png)

**Comment by exoego** [comment]
Closing this since suche use-case can be realized using transparent textarea with attached segment.
https://fomantic-ui.com/collections/form.html#transparent-textarea

**Comment by exoego** [comment]
Reopend since transparent textare with attached segment has caveat: too much margins.
https://jsfiddle.net/0enhq3zv/1/

![image](https://user-images.githubusercontent.com/127635/55713146-037b0c00-5a2b-11e9-875a-2965ff64f435.png)
![image](https://user-images.githubusercontent.com/127635/55713209-21e10780-5a2b-11e9-8f3e-21aa268d0a78.png)

**Comment by lubber-de** [comment]
Use a `fitted segment` and remove the whitespace infront of the texareas example text and you get what you need :)

https://jsfiddle.net/lubber/hws1tcm0/1/

![image](https://github.com/fomantic/Fomantic-UI/assets/18379884/7ad95de0-964d-4d58-8c25-f3fd18a56a02)
