### ISSUE TITLE
how to make grid vertically center?

### ISSUE THREAD

**Issue by fuyunliu** [fomantic/Fomantic-UI#645]
middle aligned not working

**Comment by lubber-de** [comment]
Use `center aligned column` 
See https://jsfiddle.net/j5Ld1e3q/

**Comment by fuyunliu** [comment]
> Use `center aligned column`
> See https://jsfiddle.net/j5Ld1e3q/

https://github.com/Semantic-Org/Semantic-UI/issues/6077

**Comment by fuyunliu** [comment]
must add `height: 100%;`
https://jsfiddle.net/fuyunliu/10xkzf48/

**Comment by lubber-de** [comment]
Oh, I misread 'vertically'. Then this is your solution. A fix in FUI is not necessary
