### ISSUE TITLE
Dropdown Clearable not working on mobile

### ISSUE THREAD

**Issue by jakkepedder** [fomantic/Fomantic-UI#647]
# Bug Report

## Steps to reproduce
On Android Chrome or iPhone Safari. Try to clear dropdown. It does not work.
But when the dropdown is search dropdown it works fine.

## Testcase
https://fomantic-ui.com/modules/dropdown.html#clearable-selection

## Version
2.7.4

**Comment by lubber-de** [comment]
Confirmed, but "only" affects the single selection dropdown. Clearable works on multiselection and on the selected labels

**Comment by wyysoft** [comment]
Is there any update on this issue?

**Comment by lubber-de** [comment]
Fixed by #1220 
See https://jsfiddle.net/tnk79L1q/1/show
