### ISSUE TITLE
stackable compact grid columns lose compact padding on mobile

### ISSUE THREAD

**Issue by webbp** [fomantic/Fomantic-UI#652]
## Steps to reproduce
1. https://jsfiddle.net/2tnp7vrb/2/
2. change the preview window width. wide and medium are ok, but narrow reverts to non-compact padding

## Version
2.7.4
https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.4/semantic.min.css
https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.7.4/semantic.min.js

**Comment by lubber-de** [comment]
Fixed by #1048 
See your adjusted fiddle here https://jsfiddle.net/8ftyua2g/1/
