### ISSUE TITLE
[Dropdown] Recreating while opening transition leaks intent event handlers

### ISSUE THREAD

**Issue by unarist** [fomantic/Fomantic-UI#653]
# Bug Report

## Steps to reproduce
1. Recreate dropdown by `.dropdown()` immediately after `.dropdown('show')`
2. Click any option (closes dropdown)
3. Click any `<a href="...">` links in the page

## Expected result

The browser navigates to URL in the `href` attribute.

## Actual result

Nothing happens.

Looks like `test.hide` event handler has been added with the namespace used before recreating the instance, so new instance can't remove it. Then `<a>` stops working because the handler calls `preventDefault()`.

## Testcase

https://jsfiddle.net/6suLrem1/1/

## Version
2.7.4

**Comment by lubber-de** [comment]
It's not related to the test.hide method. The reason the dropdown is still shown is, that it is still animating the "show" event while you immediatly want to re-instantiate the module.
Also fixed by #657 
See adjusted fiddle here https://jsfiddle.net/gad2791y/
