### ISSUE TITLE
[Dropdown] Recreating opened dropdown doesn't restore intent event handlers

### ISSUE THREAD

**Issue by unarist** [fomantic/Fomantic-UI#654]
# Bug Report

## Steps to reproduce
1. Open the dropdown by clicking
2. Recreate the dropdown by `.dropdown()` (The dropdown is still opened)
3. Click anywhere except inside of the dropdown

## Expected result

It closes the dropdown.

## Actual result

It does not.

Recreating seems to remove existing intent event handlers, but handlers won't be restored after recreation.

## Testcase
https://jsfiddle.net/5mvr93dL/

## Version
2.7.4

**Comment by lubber-de** [comment]
Fixed by #657 
The handlers were restored just fine, but the open menu let the "new" dropdown think its menu is hidden, although the "old" dom was still visible
See your adjusted fiddle here https://jsfiddle.net/c62bagsn/
