### ISSUE TITLE
Clearable dropdown doesn't affect multiple

### ISSUE THREAD

**Issue by nicholasgriffinVF** [fomantic/Fomantic-UI#66]
is it possible to make the Clearable dropdown that was added affect multiple dropdowns?

I think it would be cool to have the option to have a singular clear button, rather than multiple.

**Comment by prudho** [comment]
Finally foud out how to implement this without break all the things.

Thanks for your patience, and keep an eye on other great 2.5 changes 😉

**Comment by smtlab** [comment]
Just an addition - Clear icon should not be shown for empty value. Please check the demo - https://fomantic-ui.com/introduction/new.html
