### ISSUE TITLE
[Flag] Missing Isle of Man flag icon

### ISSUE THREAD

**Issue by citricacid-pl** [fomantic/Fomantic-UI#660]
# Bug Report

## Steps to reproduce
1. Insert tag `<i class="im flag"></i>`

## Expected result
There should be Isle of Man flag visible.

## Actual result
No flag is visible

## Testcase
https://jsfiddle.net/1qh4bxcv/2/

## Version
2.7.4

**Comment by lubber-de** [comment]
Flags will probably get refactored in general in a later version

**Comment by hammy2899** [comment]
We should update all flags to the following list https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes with the flags provided.

**Comment by lubber-de** [comment]
I thought of adopting the SVG flags from https://github.com/lipis/flag-icon-css/tree/master/flags/4x3
and enhance `flag` component with sizes then.

**Comment by hammy2899** [comment]
@lubber-de They would need to be in a sprite to keep file size and network requests to a low but the sprite could be an svg and then you could just scale the whole thing then change the flag position which would change the size.

**Comment by lubber-de** [comment]
Available by #1190
