### ISSUE TITLE
Set selected toggles rather than adds on dropdown that has useLabels: false setting

### ISSUE THREAD

**Issue by guushoekman** [fomantic/Fomantic-UI#670]
# Bug Report

`Set selected` toggles rather than adds values on multiple value dropdown that has `useLabels: false` setting.

## Steps to reproduce
1. Create a dropdown

```
  <div class="ui multiple selection dropdown">
    <input type="hidden" name="example">
    <i class="dropdown icon"></i>
    <div class="default text">Example</div>
    <div class="menu">
      <div class="item" data-value="foo">Foo</div>
      <div class="item" data-value="bar">Bar</div>
    </div>
  </div>
```

2. Initialise it with `$(".ui.dropdown").dropdown({useLabels: false});`

3. Use set selected on the same values multiple times: `$(".dropdown").dropdown("set selected", ["foo", "bar"])`

## Expected result

The values will be added and remain regardless of how many times `$(".dropdown").dropdown("set selected", ["foo", "bar"])` is run.

## Actual result

The values toggle. If you remove `useLabels: false` it works as expected.

## Testcase
https://jsfiddle.net/a5j7u231/

## Version
2.7.4

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/899
See your adjusted jsfiddle here https://jsfiddle.net/k8oqpjgx/

**Comment by guushoekman** [comment]
That's great! Thank you for working on this.

One thing though: it's no longer possible to deselect an option. Removing `{useLabels: false}` makes deselecting work again, so (to my layman eyes) it seems to be caused by your changes.

**Comment by lubber-de** [comment]
@guushoekman 😱 I'll work that out

**Comment by lubber-de** [comment]
@guushoekman Fixed that also, thanks for the quick response!
See new testcase here https://jsfiddle.net/k8oqpjgx/1/
