### ISSUE TITLE
menu.less extra .menu.menu

### ISSUE THREAD

**Issue by beamsky** [fomantic/Fomantic-UI#672]
First time posting so please point me in the right direction if my format is wrong for reporting a potential issue.

In Semantic-ui for menu.less line 892 it is:
`/* Inverted */
.ui.secondary.inverted.menu {
  background-color: transparent;
}`

In fomantic-ui for menu.less on line 914 it is:
`/* Inverted */
.ui.secondary.inverted.menu.menu {
  background-color: transparent;
}`

The extra .menu from what I can tell should not be there. I found this because my color override from Semantic stopped working when switching over to Fomantic.

Let me know if I can provide any more details.

**Comment by lubber-de** [comment]
@beamsky 
Basically you could override it as you wish by also increasing specificity like
`.ui.ui.ui.inverted.secondary.menu`
That additional specificity you mentioned was necessary (at that time), but not anymore, you are right.
Fixed by and more details in #673

**Comment by beamsky** [comment]
Thank you @lubber-de .. The work you all are putting in is really appreciated.
