### ISSUE TITLE
[Table] starting at 2.7.4 on iPad tables look like iPhone

### ISSUE THREAD

**Issue by keshmir** [fomantic/Fomantic-UI#681]
# Bug Report
I believe this could be a break point issue with media types.  Tables on iPad look like phone meaning table cells stack up as rows.  This is behaviour desired for phones not iPad.  You can use Chrome developer view set to iPad to reproduce this.

[Update] This is actually not only for tables.  All stackable grids start stacking in iPad which they shouldn't.

## Steps to reproduce
1. In Chrome go to docs, go to Tables: https://fomantic-ui.com/collections/table.html
2. Use inspector and set device to iPad (not iPad Pro)

## Expected result
Table cells should remain as cells

## Actual result
Table cells stack up into rows as they would on iPhone

## Version
2.7.4

**Comment by lubber-de** [comment]
Related to #567 it seems, the 768px also cover 767.99 pixels (which is set as breakpoint.)
Changing the breakpoint to 767.98px instead makes it work again...i'll prepare a PR making sure the #567 will still work

**Comment by lubber-de** [comment]
Thanks for finding out and i apology for the behavior.
Should be fixed by #686

**Comment by keshmir** [comment]
Thanks to you guys for quick responses.  looking forward to 2.7.5
