### ISSUE TITLE
[Modal] New overlay fullscreen modal sets height of any content child incorrectly

### ISSUE THREAD

**Issue by keshmir** [fomantic/Fomantic-UI#682]
# Bug Report
The problem I believe is the following css selector:
.ui.overlay.fullscreen.modal .content

The above selector is too generic and if you have any other widget within your modal that has content, it will get stretched.  Perhaps the following is a better choice:
.ui.overlay.fullscreen.modal > .content

## Steps to reproduce
1. Run this Fiddle that has accordion in modal: https://jsfiddle.net/g5hnumqz/3/

## Expected result
The accordion is right out of the docs and should behave similarly within a modal

## Actual result
The accordion content is stretched to be as tall as the entire screen

## Testcase
https://jsfiddle.net/g5hnumqz/3/

## Version
2.7.4

**Comment by lubber-de** [comment]
Fixed by #683 
See your adjusted jsfiddle here https://jsfiddle.net/9648kvab/

**Comment by keshmir** [comment]
confirmed that this fixes the issue.
