### ISSUE TITLE
Force position popup calendar in modal

### ISSUE THREAD

**Issue by joaquinglezsantos** [fomantic/Fomantic-UI#684]
## Expected result
Popup with position on botton left

## Actual result
Popup with position calculations

## Testcase
https://codepen.io/Jgonzalez92/pen/zXJKEv

**Comment by exoego** [comment]
Could you add more detail why forcing popup position is required?
I think automatic positioning is good for end-users since it can adapt screen sizes.

![image](https://user-images.githubusercontent.com/127635/57010081-b9ee9d00-6c35-11e9-9c67-c7e396fc0d0e.png)

**Comment by joaquinglezsantos** [comment]
Because when you have "scrolling content" in modal, all content  inside with popups aligned on left or right is hidden, but when is popup bottom is shown.

**Comment by lubber-de** [comment]
Implemented a new setting `forcePosition` by https://github.com/fomantic/Fomantic-UI/pull/880 which should do the job.
See https://jsfiddle.net/0cxn2gy3/

**Comment by exoego** [comment]
FUI team do not close the addressed issues until released.
