### ISSUE TITLE
[Calendar] startCalendar and endCalendar as selectors

### ISSUE THREAD

**Issue by Thanty** [fomantic/Fomantic-UI#685]
# Bug Report

Docs said we can use selectors when using startCalendar and endCalendar settings.
 
`jQuery object or selector for another calendar that represents the start date of a date range`

But this works as expected only when using jQuery objects.

## Expected result

Same when using jQuery objects.

## Testcase
https://jsfiddle.net/ue9hy7vL/

## Version
2.7.4

**Comment by lubber-de** [comment]
Fixed by #687
See your adjusted jsfiddle here: https://jsfiddle.net/c83kypx1/

**Comment by Thanty** [comment]
> 
> 
> Fixed by #687
> See your adjusted jsfiddle here: https://jsfiddle.net/c83kypx1/

**lubber-de**, thanks for the hotfix! I wonder was there a reason in searching only child elements?

**Comment by lubber-de** [comment]
@Thanty I looked into the commit log of the [repo](https://github.com/mdehoog/Semantic-UI-Calendar/commits/master) where we merged the module from , but there is nothing i can explain from where. Maybe the testcases at that time did not cover form field embeddings.
