### ISSUE TITLE
[Reveal] Type Move Right inconsistent

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#689]
# Bug Report

## Steps to reproduce
1. Using iPad or Android (not tried desktop), go to https://fomantic-ui.com/elements/reveal.html
2. Tap on the 2nd item under move (right)

## Expected result
To be consistent with left, up and down

## Actual result
Not consistent

## Screenshot (when possible)
![IMG_1303](https://user-images.githubusercontent.com/1376843/56613585-d9227480-660e-11e9-9067-9add388a066b.jpeg)

## Version
2.7.3

**Comment by lubber-de** [comment]
This is a docs issue, the example should be limited in width by adding `small image` class to the reveal div itself, which it isnt, so the right reveal still shows the image while moving to the right.
The framework code is correct so far.
See comparison here: https://jsfiddle.net/moLtk1nx/

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI-Docs/pull/117
