### ISSUE TITLE
[Search] Search ignoring Diacritics docs issue

### ISSUE THREAD

**Issue by jamessampford** [fomantic/Fomantic-UI#690]
# Docs Issue

## Steps to reproduce
1. Go to https://fomantic-ui.com/modules/search.html
2. Scroll down to “Search ignoring Diacritics”

## Expected result
JS should be in a code block

## Actual result
Not in a code block

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI-Docs/pull/115
