### ISSUE TITLE
[Calendar] add onPrev/onNext or onDisplayChange callback

### ISSUE THREAD

**Issue by PhilippGrashoff** [fomantic/Fomantic-UI#693]
Hi,
first of all: The calendar is great!

I am using the calendar for a booking tool. Depending on the availble appointments on a date, I want to color the number (or its background) from green over orange to red.

I am using the calendar inline, and coloring works easily for the first month displayed. However, coloring the newly displayed dates when prev/next icon is clicked turns to be really difficult, as a 'mouseup' event listener already attached does stop propagation.

I can think of two good ways to deal with this:
1) add some callback to these actions like onNext, onPrev (or for both directions one onDisplayChange).

2) add the ability to add extra css classes for specific dates on calendar settings.

In general, I think altering the display of single dates is something that would really improve the calendar.

Best regards
Philipp

**Comment by furqanawan** [comment]
See #677 and #674 for solution

**Comment by PhilippGrashoff** [comment]
Hi, blind me. #677 does a perfect job, I will close this.

**Comment by furqanawan** [comment]
Nice
