### ISSUE TITLE
Calendar widget breaks inline form style

### ISSUE THREAD

**Issue by prmdhost** [fomantic/Fomantic-UI#699]
# Bug Report

When the calendar widget is applied to an inline form field, the margin between label and input is lost because the widget is inserted before the label und the rule for :first-child does not work anymore.

## Testcase
https://jsfiddle.net/2e59gpw7/

## Version
2.7.4

**Comment by lubber-de** [comment]
Prepared a solution proposal at #752
See your adjusted jsfiddle here https://jsfiddle.net/vmethgkq/
