### ISSUE TITLE
Sidebar and pusher

### ISSUE THREAD

**Issue by ferrumiii** [fomantic/Fomantic-UI#700]
# Help Wanted

## Problem
Trying to do visible sidebar with content (pusher) page. There are no problems with sidebar's visibility, but the content page (which is with class "pusher") goes out of the screen on the right side. 

Is there any grid or additional class which would allow me to use sidebar (permanently visible) with content page.

**Comment by lubber-de** [comment]
Try wrapping your whole viewport into a div with `display: flex;`
```html
<div class="myapp">
  <div class="ui inverted vertical menu">
    <div class="item">
     Entry 1
    </div>
    <div class="item">
     Entry 2
    </div>
  </div>
  <div class="pusher">
  your content goes here
  </div>
</div>
```
```css
.myapp {
  display: flex;
}
```
See https://jsfiddle.net/g7ha28wk/2/

**Comment by ferrumiii** [comment]
![image](https://user-images.githubusercontent.com/3142532/56805519-fb480c80-6831-11e9-9f1d-418824d9f1cd.png)

It does not work as it should. With big amount of content, the content still goes out of the screen.

**Comment by hammy2899** [comment]
@ferrumiii Take a look at this [fiddle](https://jsfiddle.net/a7L8kpzd/) it uses some custom css to push the content from under the sidebar

**Comment by ferrumiii** [comment]
Thx for help. It works like I need.
