### ISSUE TITLE
[label] ribbon basic label had wrong calculated position 

### ISSUE THREAD

**Issue by dutrieux** [fomantic/Fomantic-UI#708]
# Description

When a **basic** ribbon label was used there were slightly mispositioned making it overlap the border

# Screenshoot
## Actual result
![ribbon_broken](https://user-images.githubusercontent.com/1622751/56945430-7b6abc80-6b27-11e9-96ad-327c7978d69f.png)

## Expected result
![ribbon_fix](https://user-images.githubusercontent.com/1622751/56945433-7dcd1680-6b27-11e9-8cf2-ddc1359c4ba3.png)

## Testcase
https://jsfiddle.net/dutrieux/h5oapxfk/9/

## Fix 
I propose to remove the border of the **basic** label and use instead a box-shadow: inset, like that all the label will have the same height and fix the wrong calculated position :
https://jsfiddle.net/dutrieux/h5oapxfk/7/
I can do a PR if you want !

## Version
2.7.4

**Comment by dutrieux** [comment]
Wouah my first "good first issue" !!!! 👍

**Comment by lubber-de** [comment]
@dutrieux While your suggestion seems to work in the specific case, the reason for keep using border is `pointing basic label`. Using your suggested change will break them (not only by color, but most important for pointer positioning)
See https://jsfiddle.net/j4h6u5fq/
![image](https://user-images.githubusercontent.com/18379884/56947195-a7d50780-6b2c-11e9-95b5-7b12667497ad.png)

I think the correct fix is to handle `basic ribbon label` by inventing additional variables to increase the margin by 0.1rem like:
```less
@basicRibbonMargin: 1.1rem;
@basicRibbonOffset: e(%("calc(%d - %d)", -@basicRibbonMargin, @ribbonTriangleSize));
@basicRibbonDistance: e(%("calc(%d + %d)", @basicRibbonMargin, @ribbonTriangleSize));
@basicRightRibbonOffset: e(%("calc(100%% + %d + %d)", @basicRibbonMargin, @ribbonTriangleSize));
```
See the result here https://jsfiddle.net/j4h6u5fq/1/

**Comment by dutrieux** [comment]
Ok my solve is not correct, I let's you do the PR but with your fix the position of the delta is not correct :

![image](https://user-images.githubusercontent.com/1622751/56948573-cf2dd380-6b30-11e9-9817-2f6d56089e32.png)

**Comment by lubber-de** [comment]
Oh, yes, good (eagle eye) catch 👍🏻
Anyway: I really would like **you** to do a proper PR. This way you will come across other parts of the framework which probably have to be considered / tested as well (like all the colors or pointer positioning when changing to box shadow)
You will learn a lot about the framework structure and dependencies then. And by doing so, you hopefully get motivated to help us out in even more cases 😊

**Comment by dutrieux** [comment]
Okay, no problem, I'll do it tonight.

**Comment by dutrieux** [comment]
Not to easy to have a perfect alignment on Chrome, Firefox and Egde at same time ... I'm trying to find the best solution...

**Comment by globophobe** [comment]
I don't know about the delta, but how about reducing border-width from 1.2em to 1.1em?

```
.ui.ribbon.label:after {
  border-width: 0 1.1em 1.1em 0;
}

.ui[class*="right ribbon"].label:after {
  border-width: 1.1em 1.1em 0 0;
}
```

https://jsfiddle.net/dqwhftap/

Before:
![image](https://user-images.githubusercontent.com/891192/57003833-6a43ad80-6c04-11e9-8e63-7107bdd10361.png)

After:
![image](https://user-images.githubusercontent.com/891192/57003837-70d22500-6c04-11e9-9e1a-40018ace808b.png)

If it fixes the issue, I'd be happy :smile: to make a pull request.

**Comment by dutrieux** [comment]
I bow down 👍

**Comment by globophobe** [comment]
Because of the border, it seems all "basic label" variants are larger by basicBorderWidth.

![normal](https://user-images.githubusercontent.com/891192/57169021-6ea7da80-6e3f-11e9-929b-cc444f11679e.png)

![basic](https://user-images.githubusercontent.com/891192/57169027-723b6180-6e3f-11e9-8ab5-ce06aad7e91b.png)

1. ui basic label
2. ui basic pointing label
3. ui basic tag label
4. ui basic labels
5. ui basic ribbon label (Fixed by https://github.com/fomantic/Fomantic-UI/pull/715)

If this is a problem, maybe their padding could be adjusted as was done for "basic ribbon label".

I'm a little busy the next week or so, @dutrieux can you?

**Comment by dutrieux** [comment]
Ok I try to make a PR to solve that !
