### ISSUE TITLE
slider does not work sometimes

### ISSUE THREAD

**Issue by digi604** [fomantic/Fomantic-UI#716]
# Bug Report

If the min value of slider is not 0 but 1 the scale is incorrect shows 01 - 101 even though the max is 10.

## Steps to reproduce
1. create a slider with: min: 1, max: 10, step: 2

## Expected result

scale starts at 1 and ends at 10

## Screenshot (when possible)
<img width="259" alt="Screenshot 2019-05-02 at 15 24 05" src="https://user-images.githubusercontent.com/25490/57078327-58d6d000-6cee-11e9-8c4f-48ad41b33ff3.png">

## Version
2.7.2

**Comment by digi604** [comment]
Also 10 should never be reachable as it starts at 1 and step is 2

**Comment by hammy2899** [comment]
Can you create a [JSFiddle ](https://jsfiddle.net/31d6y7mn) to help replicate the issue?

**Comment by lubber-de** [comment]
Fixed by #751 
See https://jsfiddle.net/1mqo5gju/1/
