### ISSUE TITLE
[Calendar] JSON formatted initialDate results in invalid year

### ISSUE THREAD

**Issue by Napryc** [fomantic/Fomantic-UI#741]
# Bug Report

## Steps to reproduce
1. Initialize a calendar with initialDate using a JSON formatted date

## Expected result
Date should be displayed properly

## Actual result
Year is always set to **2000**

## Testcase
https://jsfiddle.net/d0261oj7/2/

## Screenshot
![Capture](https://user-images.githubusercontent.com/18005617/57689563-04154c80-7640-11e9-8577-c9808f71567f.JPG)

## Version
2.7.4 + calendar fix from [issue #614](https://github.com/fomantic/Fomantic-UI/issues/614)
2.7.4 alone also tested

**Comment by lubber-de** [comment]
Fixed by #743 
See your adjusted fiddle here: https://jsfiddle.net/zmdg4cnk/

**Comment by Napryc** [comment]
Great, it works perfectly, thanks!
