### ISSUE TITLE
Ember native support like Semantic-UI-Ember

### ISSUE THREAD

**Issue by Polve** [fomantic/Fomantic-UI#745]
# Feature Request
An addon for ember would simplify the usage of this library .

## Description
Semantic-UI users can use this ember addon: https://github.com/Semantic-Org/Semantic-UI-Ember that simplify ember integration.

It would really be useful to fork that repository in order to cope with fomantic-ui instead, or just give instructions on how to change the old ember addon by hand, if possible.

**Comment by hammy2899** [comment]
I am happy to create a repository for this. If anyone wants to create to port and maintain it just leave a comment and I will invite you to the repo.

**Comment by w96k** [comment]
@hammy2899 Would love to have a link (:

**Comment by hammy2899** [comment]
I have invited you both (@w96k, @Polve) to the repo as admins.

**Comment by Polve** [comment]
@hammy2899 Thanks, I certainly don't have time now to contribute but I'll be glad to help testing

**Comment by kalenjio** [comment]
I'd love to help too

**Comment by hammy2899** [comment]
@kalenjio I have invited you to the repo.

**Comment by moses** [comment]
Also happy to help @hammy2899

**Comment by iamareebjamal** [comment]
Hi, I'm not able to find the repo

**Comment by lenrsmith** [comment]
How is this project going? I am interested to see how the development has progressed. Are you following the the same direction as Semantic-UI-Ember?
