### ISSUE TITLE
Transition does not function like it used to.

### ISSUE THREAD

**Issue by ericndar** [fomantic/Fomantic-UI#755]
# Bug Report

## Steps to reproduce
1. Run jsfiddle
2. Note that dimmer never 'hides'.
3. Change semantic version on line 4 of HTML from 2.7.5 to 2.7.2 and try again. Dimmer will 'hide' when json is returned.

## Expected result
Dimmer should hide
## Actual result
Dimmer does not hide.
## Testcase

https://jsfiddle.net/n0oe4km6/
## Screenshot (when possible)
![]()

## Version
2.7.5

**Comment by lubber-de** [comment]
Duplicate of #747 
Fixed by #748 
See your adjusted fiddle here https://jsfiddle.net/0g64n8pf/

**Comment by ericndar** [comment]
> Duplicate of #747
> Fixed by #748
> See your adjusted fiddle here https://jsfiddle.net/0g64n8pf/

Thanks!
