### ISSUE TITLE
Javascript error in semantic.js in dimmer code when calling dimmer( 'hide' )

### ISSUE THREAD

**Issue by keshmir** [fomantic/Fomantic-UI#756]
I just updated to 2.7.5 and started getting the following Javascript error on my page during the call to dimmer( 'hide' ).

Unfortunately I do not have a way to reproduce this but after debugging (and comparing code 2.7.4 vs. 2.7.5 in the area that error occurs) I found the following newly added code:

semantic.js (line 23150)
```
        complete: function (event) {
          if(event.target === element) {
              event.stopPropagation();
          }
```
The error in console is per below:

```
Uncaught TypeError: Cannot read property 'target' of undefined
    at Object.complete (semantic.js:23151)

```
So it appears that there are times that event object could be undefined which is not accounted for in the above code.  I changed the code to the following:

```
        complete: function (event) {
          if(event && event.target === element) {
              event.stopPropagation();
          }
```
after the above change my pages work fine without any issues.  I am not sure if the above change is sufficient or there maybe a deeper issue.  The author of that code would know best!  :)

## Version
2.7.5

**Comment by exoego** [comment]
I think this is fixed in https://github.com/fomantic/Fomantic-UI/pull/748 
Stay tuned for 2.7.6 (or 2.8.0)

**Comment by keshmir** [comment]
Just realized this is a duplicate of #747!  Sorry for the duplication.  Please mark this as so.
