### ISSUE TITLE
[Progress] Multiple progress bar is broken although valid total/value have been set.

### ISSUE THREAD

**Issue by ryamaguchi0220** [fomantic/Fomantic-UI#757]
# Bug Report

## Steps to reproduce
1. Set `total: 1122` and `value: [325, 111, 74, 612]` in multiple progress.

## Expected result
The multiple progress bar is not broken with no console error.

## Actual result

The multiple progress bar is broken like this
<img width="806" alt="スクリーンショット 2019-05-21 12 13 13" src="https://user-images.githubusercontent.com/14275842/58065804-e0af4c00-7bc1-11e9-99ea-685e5f5b2b30.png">
with a console error.

<img width="822" alt="スクリーンショット 2019-05-21 12 26 46" src="https://user-images.githubusercontent.com/14275842/58066313-bfe7f600-7bc3-11e9-9723-9710157191e7.png">

## Testcase
https://jsfiddle.net/d8t69y2s/

## Version
2.7.5

**Comment by exoego** [comment]
This is due to rounding error.

Workaround: You can solve this by using `precision` which is sufficiently small.
https://jsfiddle.net/7pns450z/
