### ISSUE TITLE
Bug with tooltip

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#768]
I was using the version 2.7.2 flawlessly. Today I updated to the latest version and everything works fine, except that on the browser CONSOLE it shows a message saying the "e" is undefined. It's related to the tooltip cause when I remove the tooltip it works fine.

The error only happens when I move my mouse very fast over the tooltip element (that displays the tooltip), if I move the mouse slow no error is shown in the console. 

The error happens on the most stable version of chrome and firefox. I still have no time to create a proof case cause I am traveling on a train, but if other people report this bug you can be sure it happens cause it's happening to me. So far I downgraded to 2.7.2 and the error went away.

**Comment by lubber-de** [comment]
Duplicate of #747
Fixed by #748 
As a workaround try adding https://cdn.jsdelivr.net/gh/lubber-de/fomantic-ui@930f48447ab8998729e919697112517297b04fef/src/definitions/modules/transition.js after fui 2.7.5

In case this does not fix your issue, please provide a reproducable jsfiddle

**Comment by batata004** [comment]
Yeap mine is duplicated. Thanks!
