### ISSUE TITLE
Reduce fomantic huge size, mainly on `transition` component

### ISSUE THREAD

**Issue by batata004** [fomantic/Fomantic-UI#769]
Hi,

I am already using `gulp` to reduce the size of fomantic to the bare minimmum that I really need. It works great, I can select components which I need to use and the generated code is significantly reduced when compared to the original.

But one thing still bothers me a lot: `transitions`. I cant simply remove `transitions` from the component list cause it is used on everything: from modals, to tooltips, dropdown, menus and lots of other things.

The really sad part is that transitions uses almost 35% of my `min.css` file and almost 18% of my `min.js`. THAT'S A LOT!

So I ask you this: is it possible to assign a default transition to ALL the components (for example, `fade`) and having ONLY that transition present on my `min.css` and `min.js` file? It would be a huge improvement.

Stay with me a little bit more: if you use PageSpeed or Google Insights, you will be heavily penalized on the score of your website if you use fomantic. Even after using `gulp` with a few components, the score gets very low. The main reason is transitions that consumes a LOT of time not only downloading but also PARSING it in the browser!

I use `animate.css` library for a long time and what I like most of it is that I can select specific transitions and only load them on my project. The problem with fomantic is that I cant to that. Even if I go in the minified css file and removed the "unused" transitions, sooner or later I discover something is broken on the website beucase some specific transition is missing.

Nowadays, when LOTS of people is optimizing their websites to not only look good BUT ALSO to be very well accepted by Google (and well ranked!), I think fomantic devs should take some time to fix this transition stuff. It already prevented me to use fomantic on some projects where the customer demanded a bigger than 90 score on Google PageSpeed. It's not rare nowadays and it's only getting worse.

**Comment by hammy2899** [comment]
Already commented on the issue https://github.com/fomantic/Fomantic-UI/issues/459#issuecomment-460626767

**Comment by batata004** [comment]
@hammy2899 yeap you had commented on that BUT I didnt have the chance to say that you could use a default transition name to all transitions on the library. I didnt have that idea before, that's why I opened this thread.
