### ISSUE TITLE
[form][input] - Unable to setup custom click handler in Input field in form.

### ISSUE THREAD

**Issue by ibelar** [fomantic/Fomantic-UI#770]
# Bug Report

We use to be able to setup our own handler on input field in Form. For example, using a custom File upload input. With latest release 2.7.5, input handler is not execute.
I try both click and change handler and none of them is executing.

## Steps to reproduce
1. Create form and add input
2. Setup click event listener to input.

## Expected result
Event function should be execute.

## Actual result
Event function is not execute.

## Testcase
https://jsfiddle.net/ibelar/4q02z7u1/

## Version
2.7.5

**Comment by lubber-de** [comment]
Duplicate of #746 
Fixed by #767 
See your adjusted fiddle here: https://jsfiddle.net/pua2e7bv/
