### ISSUE TITLE
Modal input not updated

### ISSUE THREAD

**Issue by zgy520** [fomantic/Fomantic-UI#775]
# modal input not updated correctly
when i show a modal, and the modal is a add form, i can get the input value correctlly, but when i hide the modal ,and show it again, i can not get the correct value ,what i get is the last value. i want to get the correct value

**Comment by lubber-de** [comment]
Please provide a reproducable jsfiddle by forking https://jsfiddle.net/31d6y7mn, so we can investigate. Thank you 🙂

**Comment by lubber-de** [comment]
Closing because of no response.
Happy to reopen it, when a reproducable testcase is provided
