### ISSUE TITLE
a:hover is rgba(0, 0, 0, 0.95) where it shouldn't be

### ISSUE THREAD

**Issue by vedranmiletic** [fomantic/Fomantic-UI#777]
# Bug Report

## Steps to reproduce
1. See https://semantic-ui.com/examples/homepage.html
2. See https://fomantic-ui.com/examples/homepage.html
3. Hover the menu links in both

## Expected result
Fomantic UI should look similar to Semantic UI.

## Actual result
Hovered links appear in `rgba(0, 0, 0, 0.95)` color.

## Testcase
Not necessary, it's an example layout.

## Version
2.7.5

**Comment by lubber-de** [comment]
Fixed by #803 
Example similiar to mentioned homepage: https://jsfiddle.net/1nx4kg52/

**Comment by vedranmiletic** [comment]
@lubber-de Updated to 2.7.6 and it's all good now. Thank you very much!
