### ISSUE TITLE
[Popup] 'target' of undefined - jQuery 3.3.1

### ISSUE THREAD

**Issue by samydoesit** [fomantic/Fomantic-UI#780]
# Bug Report

Popup with latest JQuery and VueJs seems to behave weird not sure whats the source of this Problem
back with Jquery 3.2.1 it looks like its working correctly.

## Steps to reproduce
1. Activate the Popup (by hovering Test Button)
2. And try to move the mouse quickly around, sometimes it does happen.

## Expected result
no errors

## Actual result
Uncaught TypeError: Cannot read property 'target' of undefined
    at Object.complete (semantic.js:23151)
    at Object.animate (semantic.js:23120)
    at Object.initialize (semantic.js:23025)
    at HTMLDivElement.<anonymous> (semantic.js:23949)
    at Function.each (jquery.js:354)
    at jQuery.fn.init.each (jquery.js:189)
    at jQuery.fn.init.$.fn.transition (semantic.js:22975)
    at Object.hide (semantic.js:13171)
    at hide (semantic.js:13078)

## Testcase
https://jsfiddle.net/samydoesit/4bp6n9fm/

## Screenshot of Error
![PopupError](https://user-images.githubusercontent.com/15785987/58488139-22fbfe80-8169-11e9-939b-3a856602dec3.JPG)

## Version
latest FUI
Jquery (Jsfiddle) 3.3.1
latest VueJS

**Comment by lubber-de** [comment]
Duplicate of #747
Fixed by #748
As a workaround try adding https://cdn.jsdelivr.net/gh/lubber-de/fomantic-ui@930f48447ab8998729e919697112517297b04fef/src/definitions/modules/transition.js after fui 2.7.5

See your adjusted fiddle here: https://jsfiddle.net/dpg9v5mz/

**Comment by samydoesit** [comment]
Thanks @lubber-de sorry for duplicating, already tried your workaround and somehow i think i did something wrong.

The adjusted fiddle works, thank you.

**Comment by exoego** [comment]
Why reopend??

**Comment by samydoesit** [comment]
Hey it just looks like the error appears again is it possible you forgot it?

**Comment by samydoesit** [comment]
Sorry for that, got it, someone committed an outdated version.
