### ISSUE TITLE
Bug in $.fn.transition.animate when cancelling animation

### ISSUE THREAD

**Issue by bartocc** [fomantic/Fomantic-UI#783]
# Bug Report

In the process of transitionning our app from Semantic to Fomantic, our test suite broke.

I tracked it down to a possibly wrong call to `instance.complete()` with no `event` passed as the argument here:

https://github.com/fomantic/Fomantic-UI/blob/master/src/definitions/modules/transition.js#L187

The complete method, at least on the $.fn.modal and $.fn.dimmer modules, take an `event` argument that does not seem to be passed.

## Steps to reproduce

I believe this bug happens because our test suite is running fast and the modal show animation is not over when the test suite tries to close the modal, hence triggering the first animation cancellation.

So it is a bit hard to reproduce this bug with a step by step procedure…

## Expected result

First animation cancelation should not trigger a JS error

## Actual result

First animation cancelation triggers a JS error

## Screenshot (when possible)
![]()

## Version
2.7.5

**Comment by ColinFrick** [comment]
> Duplicate of #747
> Fixed by #748
> As a workaround try adding https://cdn.jsdelivr.net/gh/lubber-de/fomantic-ui@930f48447ab8998729e919697112517297b04fef/src/definitions/modules/transition.js after fui 2.7.5
