### ISSUE TITLE
[Dropdown] Cannot read property 'observe' of undefined

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#784]
# Bug Report

## Steps to reproduce
1. Create search dropdown
2. Call `dropdown` on element with values and `allowAdditions: true`
3. Be sad when it doesn't work

## Expected result
Should work all happy

## Actual result
Throws error and dropdown is broken

## Testcase
https://jsfiddle.net/6t70ce54/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/7832163/58586172-b5f37200-8217-11e9-9939-d0ff81281872.png)

## Version
2.7.5

## Notes
Was initially reported at Semantic-Org/Semantic-UI/issues/5018, but the stale bot closed it. @nosheenzazafd had a solution as well:

> Looking at the source code, I noticed that every time selectObserver is dereferenced, it is guarded with if(selectObserver), except for the statement at line [165](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/dropdown.js#L165). I believe this statement also needs to be guarded with the same check. I did this and it fixed my problem. If needed I can provide more details to reproduce this error, however it seems to be a logic bug in the code.

**Comment by lubber-de** [comment]
Fixed by #785 accordingly
See your adjusted jsfiddle here https://jsfiddle.net/7rsge546/
