### ISSUE TITLE
[Question/Support]Dropdown with submenu

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#788]
# Help Wanted

## Problem
The white background does not go the all the way down. What am I doing wrong? 

https://jsfiddle.net/pd37qxwg/

**Comment by hakeem86** [comment]
I figured out I could something like this, is there are better way to do it? 

`.ui.selection.dropdown .menu {
  overflow: visible !important;
  max-height: 800px;
}`

**Comment by lubber-de** [comment]
@hakeem86  The fjsfiddle you provided uses a very old SUI Version (1.1)
I adjusted your fiddle using the latest Fomantic UI 2.7.5  (which supports `very long selection dropdown`)
See  https://jsfiddle.net/sbmLay9v

Another Option is to set the max-height value to the desired value, see https://jsfiddle.net/sbmLay9v/1/

**Comment by hakeem86** [comment]
I forked another users jsfiddle and did not check the S/FUI version.
On my own site I was testning with 2.7

Item16 do not work on both your jsfiddles, any ways I fixed it with custom heigth

**Comment by lubber-de** [comment]
Ah, forgot about submenu. Yes submenu is not supported when using scrolling because of its Dom tree structure which makes submenus childs of the overflow parent, so they won't be seen
