### ISSUE TITLE
Toast above Modal Dimmer

### ISSUE THREAD

**Issue by WixoGTF** [fomantic/Fomantic-UI#790]
# Bug Report

I dont know if this a bug report or just my bad implementation of Fomantic, i just want the toast compoment show above the modal dimmer i try with CSS (change the z-index) but still show behind.

## Steps to reproduce
1. Open the modal `$('#mdl_id').modal('setting', 'transition', 'horizontal flip').modal('show');`
2. Save Function 
3. Show the Toast when save function return true. `$('body').toast({ class: 'success', showIcon: 'smile', displayTime: 2000, message: 'Save it!', showProgress: 'bottom' });`

## Expected result
Using Bootstrap 3 and AlertifyJS (Alert) as example.

![imagen](https://user-images.githubusercontent.com/11972225/58740372-58088b00-83cd-11e9-9280-aa30e1638936.png)

## Actual result
![imagen](https://user-images.githubusercontent.com/11972225/58739861-f09d0c00-83c9-11e9-9c33-b613253e5a59.png)

## Version
2.7.5

**Comment by lubber-de** [comment]
I cannot reproduce. See my used example here
https://jsfiddle.net/on95rqc1/
If i click on tjhe save button within the modal the toast is shown on top of the modals dimmer as expected.
Please provide a jsfiddle with your code to reproduce the issue. thank you
![image](https://user-images.githubusercontent.com/18379884/58780104-35968d80-85d8-11e9-91ac-c6c2a51503b1.png)

**Comment by lubber-de** [comment]
Closing because of no response.
Happy to reopen it, when a reproducable testcase is provided
