### ISSUE TITLE
[Grid] Column width doesn't behave predictably when using a base width combined with responsive widths

### ISSUE THREAD

**Issue by noinkling** [fomantic/Fomantic-UI#791]
# Bug Report

Essentially the same report as made here: Semantic-Org/Semantic-UI-React#2869

Read [my comment](https://github.com/Semantic-Org/Semantic-UI-React/issues/2869#issuecomment-498008380) in that issue for why I think it should be considered a bug.

## Version
2.7.5

**Comment by noinkling** [comment]
As for suggestions how you might fix it I'm not too sure. [Link to the relevant stylesheet](https://github.com/fomantic/Fomantic-UI/blob/b1327153b6f227cd0abd3cec7f0168db150ab537/src/definitions/collections/grid.less#L339).

You could require the base width to come directly before `column` and then changing the attribute selectors to read `[class*="one wide column"]`, etc. But that introduces order-dependent behaviour which I believe kinda goes against the SUI philosophy.

Otherwise maybe you could put the base width declarations *below* the media query ones and remove `!important` - but it's probably there for a reason, right?

**Comment by lubber-de** [comment]
I dont see the need for a change, at least in the current codebase. It is working as expected
An "eight wide two wide mobile six wide tablet column" will display
- "eight" wide by default
- "two wide" on mobile
- "six wide" on tablet 
See https://jsfiddle.net/lubber/1co9w5su/4/
