### ISSUE TITLE
Tab loading can't be cancelled

### ISSUE THREAD

**Issue by kocsismate** [fomantic/Fomantic-UI#796]
# Feature Request

## Description
I have forms in tabs and I'd like to implement a functionality similar to `beforeunload` in order to prevent loading other tabs (thus losing data) when a form has already been modified.

The contents of tabs are loaded via AJAX so I tried to manipulate the `onRequest` event in the `apiSettings` as well as the `beforeLoad` event of the tab but I had no success.

I think it would be useful to make tab changing cancellable with a callback returning `false`. I hope that you also like this idea.

Thanks for keeping the legacy of Semantic uI alive! Have a nice day:

Máté

**Comment by lubber-de** [comment]
A new callback `onBeforeChange` is prepared by #2164 
Returning false will cancel the tab change and any possible ajax request)
