### ISSUE TITLE
[Dropdown] Multiple search dropdown placeholder text and arrow overlap

### ISSUE THREAD

**Issue by GammaGames** [fomantic/Fomantic-UI#817]
# Bug Report

## Steps to reproduce
1. Create multiple search dropdown
2. Call dropdown method with placeholder text

## Expected result
Arrow should be to the right of the text

## Actual result
Arrow overlaps text

## Testcase
https://jsfiddle.net/jvp1fyuw/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/7832163/59639974-f1e46d80-9119-11e9-8e6f-3a518b7d8a6a.png)

## Version
2.7.6

**Comment by lubber-de** [comment]
Fixed by #2717
