### ISSUE TITLE
Form: field with inline doesn't respect error styles

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#818]
# Bug Report

## Steps to reproduce
1. Create a form field with `inline`

## Expected result

![image](https://user-images.githubusercontent.com/14183168/59718194-e7a99880-9219-11e9-9fe4-4016b6a93ce6.png)

## Actual result

![image](https://user-images.githubusercontent.com/14183168/59718071-a0230c80-9219-11e9-9b8c-dcc5881d08d0.png)

## Testcase
https://jsfiddle.net/z5m7f13u/

## Reason

![image](https://user-images.githubusercontent.com/14183168/59718152-ce085100-9219-11e9-9eb1-346dcc25531f.png)

Styles for `inline` override `error` styles 💣 

## Version
2.7.6

**Comment by lubber-de** [comment]
Fixed by #818
See your adjusted jsfiddle here https://jsfiddle.net/q2bowsne
