### ISSUE TITLE
Rating doesn't display when using with semantic-ui-react

### ISSUE THREAD

**Issue by mkuklik** [fomantic/Fomantic-UI#821]
# Bug Report
I apologize in advance if it is a wrong forum for my issue. I am using Fomantic-ui with React. To this end, I'm using semantic-ui-react module. Everything seems to work nicely but Rating component. It doesn't show at all. It is surprising especially since it looks to be identical to Semantic-UI.

Is it an issue with Fomantic-UI or incompatibility between Semantic-ui-react and Fomantic-UI? 

Thanks,

## Steps to reproduce
1. Install semantic-ui-react and Fomantic-UI
2. <Rating icon='star' defaultRating={3} maxRating={4} /> wouldn't display

## Expected result
Rating is displayed.
## Actual result
Rating is not displayed.

## Screenshot (when possible)
![]()

## Version
semantic-ui-react 3.1.0
Fomantic-UI 2.7.6

**Comment by lubber-de** [comment]
The rating module was changed in v2.7.0 by #303 to make it possible to support any icon or color.
This would probably need adjustments in the SUI react code. 
What you could try is to import rating.css from sui 2.4.1 right after fomantic 2.7.6 css

**Comment by lubber-de** [comment]
Closing, because it needs either changes in the SUI React Code or the above mentioned workaround is used.

**Comment by Puspendert** [comment]
@lubber-de I did it using workaround and it works, but no new features provided by `fomantic-ui-css` comes with it. That's fine, expected.
But I need to import the complete `semantic-ui-css` into the package using `yarn add semantic-ui-css`.
Then on import I am doing like this on index.js file:
```
import "fomantic-ui-css/semantic.css"
import "semantic-ui-css/components/rating.css";
```
Question: Does including the complete `semantic-ui-css` package increase the bundle size? If yes, how to download only the `rating.css`?

**Comment by lubber-de** [comment]
I believe / hope the bundler is intelligent enough to only add the specified rating.css in addition to the semantic.css from FUI because of the explicit `import` declaration
