### ISSUE TITLE
Check box is not center aligned in form

### ISSUE THREAD

**Issue by hajanajubudeen88** [fomantic/Fomantic-UI#823]
# Bug Report
In the fiddle i created four fields form and in that 3 text field and one check box, in that checkbox is not aligned properly, below the details to reproduce the issue

## Steps to reproduce
1. I created four fields form with 3 text field with one checkbox 
2. All the four fields have the <b>header label </b> like First Name, Last Name etc.,
3. Whenever i created the checkbox with header label ( '<label>Check Box</label>' ) the alignment is collapsed

![checkbox](https://user-images.githubusercontent.com/32840808/59766508-f9447c00-92bd-11e9-894d-6a0d88e6b8a3.PNG)

4. if i remove the header label( <label>Check Box</label> ), its working properly with center alignment

![properCenterAlign](https://user-images.githubusercontent.com/32840808/59767356-c4d1bf80-92bf-11e9-9fea-9e5bc7b91aaa.PNG)

## Expected result

![expectedResult](https://user-images.githubusercontent.com/32840808/59768329-cb613680-92c1-11e9-8a14-c4195c477a65.png)

( OR )

![expectedResult1](https://user-images.githubusercontent.com/32840808/59768353-d6b46200-92c1-11e9-8140-ec92b12d77dc.png)

## Actual result
![checkbox](https://user-images.githubusercontent.com/32840808/59767395-db781680-92bf-11e9-93f6-cadff842fcc8.PNG)

Please help me to fix the issue with label and center aligned check box, Thanks

## Testcase
https://jsfiddle.net/hajanajubudeen88/n092dprh/11/

**Comment by maidzen** [comment]
```
.ui.form .fields:not(.grouped):not(.inline) .field:not(:only-child) .ui.checkbox  {
  margin-top: 0.8em;
}
```

**Comment by GammaGames** [comment]
When I added it I thought people would be using the label inside the `.ui.checkbox` div because it's required to make the checkbox show up. Maybe we'd want to add an exception for a fitted checkbox? For example:

```css
.ui.form .fields:not(.grouped):not(.inline) .field:not(:only-child) .ui.fitted.checkbox {
  margin-top: 0.7rem;
}
```
I'm not sure, because this seems like a somewhat small use exception.

Here's an updated fiddle https://jsfiddle.net/Luhzqgn9/

**Comment by lubber-de** [comment]
With slight adjustments of @GammaGames ' fiddle it doesn't even need the `fitted` variant of checkbox, so an additional label beside the checkbox is still working

```css
.ui.form .fields:not(.grouped):not(.inline) .field:not(:only-child) label + .ui.checkbox {
  margin-top: 0.7rem;
}
```
See https://jsfiddle.net/4poqja0t/

Who volunteers for a PR ? 😉

**Comment by hajanajubudeen88** [comment]
@lubber-de , @GammaGames , @maidzen  Its working Thanks
