### ISSUE TITLE
vertical fluid tabular menu is not working

### ISSUE THREAD

**Issue by hajanajubudeen88** [fomantic/Fomantic-UI#833]
# Help Wanted

## Problem
i'm trying to use vertical fluid tabular menu 
- in that i have four menu like ( bio, pics, companies, links )
- the active menu ( companies ) is activated by default
- when i try to change the menu like ( bio [or] pics [or] links  ) its not changed
- and its having only one content div
- i need separate content div for separate menu 

https://jsfiddle.net/hajanajubudeen88/dcksgzxv/
Please help me to fix this  thanks

**Comment by jamessampford** [comment]
Fixed fiddle - https://jsfiddle.net/xjbmdkwf/

Examples within docs shows how it should be done correctly:
https://semantic-ui.com/modules/tab.html#/examples

**Comment by hajanajubudeen88** [comment]
Thanks @jamessampford  its working, and once again thanks for the reference link

**Comment by lexycole** [comment]
> Fixed fiddle - https://jsfiddle.net/xjbmdkwf/
> 
> Examples within docs shows how it should be done correctly:
> https://semantic-ui.com/modules/tab.html#/examples

Thanks for the question @hajanajubudeen88  and thanks for the solution @jamessampford :)
