### ISSUE TITLE
[Documentation] Typo error in calendar settings

### ISSUE THREAD

**Issue by ko2in** [fomantic/Fomantic-UI#835]
# Bug Report
There is typo error in calendar settings table, in the row of `disableMinute` setting. The description should be **Disable minute selection mode**, not **Fisable minute selection mode**.

URL: https://fomantic-ui.com/modules/calendar.html#/settings

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI-Docs/pull/138
