### ISSUE TITLE
Large dropdown alignment

### ISSUE THREAD

**Issue by princeandrew01** [fomantic/Fomantic-UI#837]
# Bug Report
I noticed this issue when i was using the login template. The template, had the form set to large and I noticed alignment for the dropdown icon and clearable icon is not vertically aligned.

## Steps to reproduce
1. Create any clearable dropdown and put it in a large form

## Expected result
1. Both icons should be aligned

## Actual result
1. Icons are not aligned correctly.

## Testcase
https://jsfiddle.net/dr4omLq7/9/

## Screenshot (when possible)
![image](https://user-images.githubusercontent.com/13138963/60192262-95f9a300-9803-11e9-9a32-3f79dceec300.png)

## Version
2.7.6

**Comment by prudho** [comment]
Yes, it seems to happen on every size form's dropdowns but medium.

**Comment by prudho** [comment]
Fixed by #838.
