### ISSUE TITLE
[Table] tfoot not supported

### ISSUE THREAD

**Issue by ziaratban** [fomantic/Fomantic-UI#840]
# Bug Report
hi
`tfoot` tag not supported in table.

http://jsfiddle.net/nt3460jL/

## Version
2.7.6

**Comment by hammy2899** [comment]
`tfoot` tag currently only supports `th` tags within rows, `td` needs to be added.

https://github.com/fomantic/Fomantic-UI/blob/1fd94d2479f297c906bed557f0567d1d3f0a4d2c/src/definitions/collections/table.less#L98

**Comment by lubber-de** [comment]
Implemented by #1083
