### ISSUE TITLE
[Dropdown] Description misaligned in IE11 on large texts

### ISSUE THREAD

**Issue by mathijsco** [fomantic/Fomantic-UI#843]
# Bug Report

The text of the dropdown will overlapse the description when the text is too long.

## Steps to reproduce
1. Create a dropdown with the classes `ui floating dropdown`.
2. Ensure the text of the item is around 90 characters.
3. Notice that the text and description overlapse in IE11

## Expected result

Text and description are aligned next to eachother in Internet Explorer 11.

## Actual result

Text and description overlapse.

## Testcase
https://jsfiddle.net/2e4cpqmf/

## Screenshot (when possible)
![2019-07-04_16h31_15](https://user-images.githubusercontent.com/12410664/60673903-2cb80680-9e79-11e9-99e4-f39eafe01898.png)

## Version
2.7.6

**Comment by tranlehaiquan** [comment]
I didn't got overlapse but i got this instead:
![image](https://user-images.githubusercontent.com/17347993/67631715-4c61b780-f8cc-11e9-80f1-0ba68919969a.png)

**Comment by tranlehaiquan** [comment]
Sorry I got it : D

**Comment by lubber-de** [comment]
The floating model in IE11 and old Edge is broken.
The only possibility to fix this in those ancient browsers is to set a fixed width to the dropdown menu according to your needs, which we won't implement into the FUI core. Therefore i am closing this issue.

For example:
```css
#mylargedropdown > .menu {
	width: 600px;
}
```
![ie11menuitemwidth](https://user-images.githubusercontent.com/18379884/128608874-c773d4ec-ac23-46b5-a2cd-a557b4c6acd4.gif)
