### ISSUE TITLE
[forms inside an accordion] submit button doesn't show spinner loader

### ISSUE THREAD

**Issue by bakeiro** [fomantic/Fomantic-UI#865]
### Incompatibilty of accordeons with form spinner loader
i.e. [Submit button on formular inside a accordion] Click Should Fire spinner loader

when I delete the class transition it show the animation correctly, but if not, the form disappear and appear again
 
### Steps
Create a form inside a accordion, and minimize and maximize the accordion

### Expected Result
See spinner loader animation

### Actual Result
No animation

### Version
2.4

### Testcase
https://jsfiddle.net/dfgrwyqs/

**Comment by jamessampford** [comment]
You may want to try with the Fomantic UI release, as opposed to Semantic UI, which may have already addressed the issue

**Comment by lubber-de** [comment]
Two workarounds (which also work with SUI 2.4)
- Use `animateChildren:false`
https://jsfiddle.net/c2fxdhe9
- Wrap your form in another `div` (so ithe form is not the direct childnode  of the accordion content anymore)
https://jsfiddle.net/c2fxdhe9/1/

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/894
See your adjusted jsfiddle here https://jsfiddle.net/mL6po4dh/
