### ISSUE TITLE
[Input] type="color" is not supported

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#881]
# Bug Report

`type="color"` is not supported properly.

## Steps to reproduce
1. Create an `Input` with `type="color"`:

```html
  <div class="ui input">
    <input type="color" value="#cccccc">
  </div>
```

## Expected result
![image](https://user-images.githubusercontent.com/14183168/61304344-4c401f00-a7e9-11e9-9b37-3106a1548112.png)

## Actual result
![image](https://user-images.githubusercontent.com/14183168/61304315-434f4d80-a7e9-11e9-83c3-6fa2654c2898.png)

## Testcase
https://jsfiddle.net/vub0kwLs/

## Version
2.7.6

**Comment by lubber-de** [comment]
Trying to work out a simple CSS solution which fits into FUI style (and existing elements like `form`) (HTML5 offers many more additional input types which are not really crossbrowser stylefriendly)
A general colorpicker is already in the works by #137, so in the meantime this should quickly fix it

```css
input[type="color"] {
  padding:initial !important;
}
```
https://jsfiddle.net/dgvq60ys/

**Comment by lubber-de** [comment]
color input type supported by #2052
