### ISSUE TITLE
[Table] definition and color can't be combined

### ISSUE THREAD

**Issue by layershifter** [fomantic/Fomantic-UI#883]
# Bug Report

## Steps to reproduce
1. Create a `definition` `<table />`
2. Add `color` like `red`

## Expected result
No red border

## Actual result
Weird red border on top of the first row.

![image](https://user-images.githubusercontent.com/14183168/61388131-b58e6380-a8b7-11e9-801d-8d8b695ff121.png)

## Testcase
https://jsfiddle.net/3c4x7a2u/

## Version
2.7.6

**Comment by lubber-de** [comment]
Fixed by https://github.com/fomantic/Fomantic-UI/pull/884
See your adjusted jsfiddle here https://jsfiddle.net/9dx7mf2j/

**Comment by xReaven** [comment]
Awesome.

Thanks you guys.

**Comment by lubber-de** [comment]
Here is the jsfiddle including the firefox fix, i was missing:
https://jsfiddle.net/wz8er4tj/
