### ISSUE TITLE
Upgrade Font Awesome to 5.9.0 

### ISSUE THREAD

**Issue by mrcasablr** [fomantic/Fomantic-UI#887]
Font Awesome 5.9.0 - https://fontawesome.com/changelog/latest has new icons

**Comment by lubber-de** [comment]
@hammy2899 When you do this, please consider, if the order of the icon css can be adjusted, to fix the following bug https://github.com/fomantic/Fomantic-UI/issues/739#issuecomment-492155926

**Comment by Bradley-H** [comment]
Perhaps I'm just a bit of a purist, but lets just make our own icons with .svg's. I'm sure it'll be a bunch of work, but I would (like anyways) to seperate us from the bunch and not have to rely on 3rd parties.
