### ISSUE TITLE
[Dropdown] Unable to customize the addition item

### ISSUE THREAD

**Issue by vincenccee** [fomantic/Fomantic-UI#888]
# Help Wanted
I need some help to customize the `addition` item on the selection dropdown with the settings: 
```
allowAdditions: true
hideAdditions: false
```
## Problem
The problem here is where and when the option will be displayed. I want to always display the `addition` option (even when the user didn't type anything in the search) and want the `addition` option to always be the last option on the list.

By now I was able to customize the text and the style of the `addition` but not when it is displayed and where it is displayed. 

I tried to create a new option (with the `item` and without the `addition` classes) and bind a select event to it to create a new option, but when I tried to type something the new add option is filtered as well.

If I just create a new element at the end of the options list (without the `item` class) I lose the ability to navigate through the option with the keyboard keys, that's the reason that I need to use the `addition` item.

**Comment by ivangomes** [comment]
@vincenccee are you still working to get this done? Please let me know!

**Comment by vincenccee** [comment]
@ivangomes nope. I am not working with this anymore
