### ISSUE TITLE
[container] right margin not visible

### ISSUE THREAD

**Issue by FFDevelopment** [fomantic/Fomantic-UI#900]
# Bug Report
In case you use a fluid container and you want to have some margin, you will not have a right margin.

It's helpful to check the element with the development tools in your browser to see the missing right margin.
## Expected result
right margin

## Testcase
https://jsfiddle.net/4xob9vg7/

## Version
2.7.6

**Comment by hammy2899** [comment]
This isn't a bug, in fact the container does actually have a margin on the right but its being rendered off screen because the left margin is pushing the element to the right. You can see this more clearly here https://jsfiddle.net/oumq491r/

A simple way to solve this issue is by using padding instead of margin on your container e.g. https://jsfiddle.net/vs4xgmqh/

**Comment by FFDevelopment** [comment]
I know but the question is, is it possible to change anything for the future? I think it's strange when you use "padding" for one part and "margin" for the other ones. ;)

**Comment by hammy2899** [comment]
If you want to use margin you could just calculate the width like this https://jsfiddle.net/saw4Lx51/ however a fluid container shouldn't really use margin since that's its purpose.

**Comment by FFDevelopment** [comment]
If you say a fluid container shouldn't really use margin. Why won't be changed this filen then?
https://github.com/fomantic/Fomantic-UI/blob/7be57fcaaccf7b88f7e85e70ede8c3d5259eed61/src/definitions/elements/container.less

**Comment by lubber-de** [comment]
🤔 Both of you are right, i think:
- A fluid container is supposed to have a 100% width with no margin and this is also true for the docs site (https://fomantic-ui.com/elements/container.html#/definition scroll down to the very last example)...
- ... unless it's shown on mobile (<767px), then i think it can be considered a bug that there is a fixed margin set without the respect of a possible `fluid` container
https://github.com/fomantic/Fomantic-UI/blob/1fd94d2479f297c906bed557f0567d1d3f0a4d2c/src/definitions/elements/container.less#L32
should be changed to 
```css
.ui.container:not(.fluid) {
```
See
![fluid_container](https://user-images.githubusercontent.com/18379884/61882892-a469d600-aef9-11e9-9add-049125b6a440.gif)
