### ISSUE TITLE
"Today" in calendar popup shares className with range cells

### ISSUE THREAD

**Issue by DepaMarco** [fomantic/Fomantic-UI#901]
# Bug Report
Apparently "Today" button in calendar popup shares _className_ with range cells.

## Steps to reproduce
1. Select a date as "startDate" of the range, from the first input
2. Open calendar popup for the second input
3. Try to mouseover cells _BEFORE_ and _AFTER_ **today** cell, as you would select the "endDate" for the range

## Expected result
"Today" button should not change color, not depending on the date you select as "endDate" of the range

## Actual result
"Today" button has different backgroud and text color based on the date you select: if after **today** it takes the same colors.

## Testcase
https://jsfiddle.net/a0re4nyd/1/

## Version
2.7.6

**Comment by iwgx** [comment]
Hey, I would like to take this :smiley:

**Comment by lubber-de** [comment]
Fixed by #1066
