### ISSUE TITLE
[Search] Cached results do not trigger callbacks

### ISSUE THREAD

**Issue by mikecsh** [fomantic/Fomantic-UI#909]
# Bug Report

If search is set to cache results, when a result is returned from the search cache onSearchQuery and onResults callbacks are not called.

## Steps to reproduce
1. Set up Search component and enable caching
2. Add logging statements in onSearchQuery and onResults callbacks
3. Enter search term, e.g. "Cancer"
4. Delete a character e.g. "Cance" - result is returned by cache
5. Add a character e.g. "Cancer" - result is returned by cache

## Expected result

I would expect the callbacks to be called whether results are retrieved from an API or from the local cache. In my use case, I use onSearchQuery to add the loading class to the search field, and onResults to remove the class. This works as expected with remote searches but due to the above does not work with cached results. I therefore disable caching and lose the benefit of this feature.

## Actual result

Callbacks are not called when results are returned from cache.

## Screenshot (when possible)
N/A

## Version
2.7.6

**Comment by maidzen** [comment]
reproduced in jsfiddle
https://jsfiddle.net/sm2cgfkd/1/

**Comment by maidzen** [comment]
i have to add, this is the correct behaviour based on documentation

Docs onResult: Callback on **server** response

maybe a onCachedResult callback is needed here or onResult needs to handle both with a parameter holding the source information (server, cache)

**Comment by prudho** [comment]
IMHO the onResult should be triggered no matter where come from the information. And yes, return where it come from is a good idea !

**Comment by mikecsh** [comment]
@maidzen thanks for your reply - I don't know what I had done to prevent the automatic handling of the loading class but it's working now. I still feel that onResult should be called regardless of source and my personal opinion is to use the same callback with a spruce parameter as you suggest.

**Comment by lubber-de** [comment]
> IMHO the onResult should be triggered no matter where come from the information. And yes, return where it come from is a good idea !

Implemented by #2737 
Adjusted jsfiddle: https://jsfiddle.net/lubber/Lphw05ek/7/
