### ISSUE TITLE
Content in segment is covered by label

### ISSUE THREAD

**Issue by alexnicolaisen** [fomantic/Fomantic-UI#910]
Hi,

I merged from Semantic to Fomantic today, and found a little issue:

When using top attached label on Segment, the first part of the content gets covered by the label. 

Test case:
https://jsfiddle.net/fnmrx2tk/1/

I avoid this by bumping the content down, but that label should give room for it?

BTW: I'm really greatful for the work you are doing after Semantic stopped breathing! I just hate that Google think I want to search for Romantic or Semantic all the time :p 

Best regards
Alexander

**Comment by hammy2899** [comment]
If you wrap your content in a `<p>` tag its fine, the issue you mention is the same with SUI see https://jsfiddle.net/hjL4x1o0/

**Comment by alexnicolaisen** [comment]
I didn't have the latest version of Semantic, but it was fine there :)

But anyhow, I'll use the <p> now!

Thanks 🥇
