### ISSUE TITLE
[Dropdown] Action buttons inside the menu

### ISSUE THREAD

**Issue by Shriken** [fomantic/Fomantic-UI#911]
# Feature Request

## Description
Semantic UI offers the functionality to clear or select multiple options with few jQuery lines. Here in Fomantic you ( Amazing! ) people added the close icon inside the input field, to clear single/multiple selection. 
In my opinion, and I hope in yours as well, the actions should be visible inside the menu, while the user sees his options and is able to play with them. UX-wise, this makes the whole multi selection process faster for rich data dropdowns. 

I already created my own version of it, displayed in the following fiddle, and you will notice that I had to create a container for the options, so that the actions will be relatively positioned after them. This opens the menu to whole new possibilities. It will be easier to add new actions, to replace them, to add other custom elements before or after the items. 

Will be more than happy to hear your thoughts!
## Testcase (when possible)
https://jsfiddle.net/4o8gyrs3/

** The fiddle has one or two 'hacks' like where I increased max height for the menu to allow the actions to fit in, but this can be generalised easily.

**Comment by maidzen** [comment]
Hi Shriken, this is already possible without css hacks by using stacked menu divs

example:
https://jsfiddle.net/427pkn3o/

**Comment by Shriken** [comment]
This is great!
What about the JS? do you think it is a good idea to include the actions as settings? so it can be cleaner and easier to initialize + will work with 'select' tag?

**Comment by maidzen** [comment]
i think the way you did it is the right way to handle selections and dropdown actions by using the behavior of Dropdown(). 

Of course a "set selected all" behavior could be usefull in this case but i personaly don't think this is worth the additional code in the component. At the end of the day FUI gets used by developers and all tools for this functionality are already given.

**Comment by Shriken** [comment]
Makes perfect sense, thanks for your thoughts. it also helped me remove all my unneccasary css anyway :]
