### ISSUE TITLE
Make the step of 'labeled slider' configurable

### ISSUE THREAD

**Issue by NyxCode** [fomantic/Fomantic-UI#913]
# Feature Request

## Description
Currently, a 'labeled' slider is labeled at every possible value. With large sliders, especially on mobile devices, the labeling is confusing. 
It even get's worse with floating-point steps - then, the labeling is unreadable, even on large screens.
This could be solved by allowing the step of the labeling to be configurable so that not every value is labeled, but maybe only every 4th.

Also, i think it would be great to be able to control the labeling-step independently from the ticks-step (of a `labeled *ticked* slider`)!

## Example/Screenshots
`ui large labeled slider` from 1 to 16 with step=1 on a mobile device
![image](https://i.imgur.com/r1q33Ul.png)  

`ui large labeled slider` from 1 to 16 with step=0.5 on desktop
![image](https://i.imgur.com/azx6tzO.png)

**Comment by prudho** [comment]
That was a bit tricky, but now i think that [this PR](https://github.com/fomantic/Fomantic-UI/pull/978) might interest you 😃 !
