### ISSUE TITLE
tabular menu not updated

### ISSUE THREAD

**Issue by hakeem86** [fomantic/Fomantic-UI#915]
## Steps to reproduce
1. click change to second

## Expected result

tabular menu and segment is changed to second tab

## Actual result

Only the segment is changed to second tab, the tabular menu is not updated (First is still active)

## Testcase
https://jsfiddle.net/t6we9gv8/2/

## Screenshot (when possible)
![]()

## Version
2.7.7

**Comment by maidzen** [comment]
This is explicit for menuless tabs see Documentation

![image](https://user-images.githubusercontent.com/17901424/62449945-9b83ca80-b76b-11e9-94f6-92f4988c8f77.png)

**Comment by prudho** [comment]
Like @maidzen said, using the $.tab('change tab', path);
