### ISSUE TITLE
Guide for using Fomantic-UI-LESS

### ISSUE THREAD

**Issue by LukBukkit** [fomantic/Fomantic-UI#922]
# Help Wanted

## Problem
Hey, it would be really nice, if there was a link to a guide for using the [less version](https://github.com/fomantic/Fomantic-UI-LESS) of this awesome fork in combination with a build tool like webpack. 

You could link in the README for exmaple to this project: [Codenaut/webpack4-semantic-ui-theming](https://github.com/Codenaut/webpack4-semantic-ui-theming) or this Medium post: [Webpack 2 & Semantic UI Theming](https://medium.com/webmonkeys/webpack-2-semantic-ui-theming-a216ddf60daf).

Thanks a lot!

**Comment by hammy2899** [comment]
Take a look at this medium article too which is dedicated to Fomantic-UI https://medium.com/@marekurbanowicz/how-to-customize-fomantic-ui-with-less-and-webpack-applicable-to-semantic-ui-too-fbf98a74506c

There is a section on the Getting Started page of the website with a link to that tutorial, we tend to not link to such things on the README.
![image](https://user-images.githubusercontent.com/11588822/62548973-9738d980-b85f-11e9-9239-4eabea022ee2.png)

**Comment by LukBukkit** [comment]
Okay thanks for your explanation 👍
