### ISSUE TITLE
Attached label in a segment does not pad content

### ISSUE THREAD

**Issue by ricohumme** [fomantic/Fomantic-UI#925]
Hi,

I just updated from 2.7.5 to 2.7.7 and found that a segment containing a top attached label no longer pads the content in the next div within the segment.
To illustrate, see the attachment. Content is blurred for privacy reasons

This is the CSS part which is missing:
`.ui.top.attached.label+[class*="right floated"]+*, .ui.top.attached.label:first-child+:not(.attached){margin-top: 2rem!important}`

## Screenshot (when possible)
![Example Segment](https://user-images.githubusercontent.com/11029998/62703715-15c18280-b9ea-11e9-93cf-42f1fdbb8a54.jpg)

## Version
2.7.7

**Comment by lubber-de** [comment]
Fixed by #926 
See https://jsfiddle.net/hrL5706d/1/

Sorry for this ...

**Comment by ricohumme** [comment]
Thnx for the quick response !
