### ISSUE TITLE
[Dropdown] 'values' and 'get value'

### ISSUE THREAD

**Issue by ziaratban** [fomantic/Fomantic-UI#927]
hi
when i use `dropdown` with `values` option, `get values` method of `form` return `null` for `dropdown`!

see : http://jsfiddle.net/2m6b53dk/

fomantic-ui : 2.7.7

**Comment by ziaratban** [comment]
seems problem exists in `values` options in `dropdown`.

see : http://jsfiddle.net/bh162r9p/

**Comment by lubber-de** [comment]
Confirmed. Only affected when using `select` tag dropdowns

**Comment by rhayveAmbait** [comment]
Hi the bug still persist in 2.8.1

Here's my code, please check line 78 and 97
[bug.zip](https://github.com/fomantic/Fomantic-UI/files/9690052/bug.zip)
