### ISSUE TITLE
[Form Validation] onDirty event unpredictable behavior

### ISSUE THREAD

**Issue by mightyvoodoo** [fomantic/Fomantic-UI#930]
When we have a multiple select field inside form (with dropdown module or not) onDirty event behavior would be unpredictable.

https://jsfiddle.net/vtbyr8o1
Try to focus textarea first, then re-run and try to select/unselect options.

Thanks!

**Comment by prudho** [comment]
This is something i can see in the JSFiddle, but cannot reproduce on my computer...

Do you have another sample of code that will trigger this behavior ?

**Comment by hammy2899** [comment]
@mightyvoodoo Is this still an issue?

**Comment by mightyvoodoo** [comment]
Hello there! Sorry for very long answer.
Currently I'm on the same version. As soon as possible I'll be able to update and check.
Thanks for replies :+1:

**Comment by lubber-de** [comment]
@mightyvoodoo Do you still have an issue?

**Comment by mightyvoodoo** [comment]
@lubber-de Hello, issue is still here, reproduced with latest Fomantic version. Only occurs on forms with multiple select instantiated via `<select multiple>`. With multiple select instantiated via `<div>` form has proper behavior.

**Comment by lubber-de** [comment]
Fixed by #1612 
See your fixed jsfiddle here https://jsfiddle.net/lubber/sjnv3wkp/

**Comment by mightyvoodoo** [comment]
@lubber-de Yep, fixed. Thanks!
