### ISSUE TITLE
[Dropdown] ignoreCase breaks multiselect with search

### ISSUE THREAD

**Issue by tiaagosr** [fomantic/Fomantic-UI#931]
# Bug Report

## Steps to reproduce
1. Select one or more options from dropdown
2. With Dropdown focused press backspace OR click X on any selected option

## Expected result
Backspace with dropdown focused or clicking X on any option should remove it from current selection

## Actual result
No option gets removed from current selection

## Testcase
https://jsfiddle.net/r8enoqyg/

## Version
2.7.7

**Comment by prudho** [comment]
Fixed by #1029.

Please see your adjusted Fiddle [here](https://jsfiddle.net/ace4hd0m/).
