### ISSUE TITLE
[Dropdown] ignoreCase does not change text search behavior

### ISSUE THREAD

**Issue by tiaagosr** [fomantic/Fomantic-UI#932]
# Bug Report

## Steps to reproduce
1. Focus Dropdown
2. Type alabama on search box

## Expected result
No option is to be suggested, since search is case-insensitive only with `ignoreCase: on` .

## Actual result
Search is case-insensitive even with `ignoreCase` defaulting to off, Alabama option is suggested.

## Testcase
https://jsfiddle.net/9nymb3g1/2/

## Version
2.7.7

**Comment by lubber-de** [comment]
The `ignoreCase` setting is currently not meant to support the search functionality and only affects the label creation. Thats why it is ignored.
I therefore tag this as enhancement, because it makes sense though 😉 

Btw: The correct options for `ignoreCase` are boolean `true/false`, not `on/off`

**Comment by aexvir** [comment]
👋 I made a PR for this one

**Comment by exoego** [comment]
@aexvir 
Thanks for jumping into this issue.
Your PR #1101 LGTM, but I wonder when ignoreCase in search is useful.
Do you have use cases?

**Comment by aexvir** [comment]
I think this question would be better answered by @tiaagosr , as the issue author. To be honest, I think I rushed a bit jumping into this, but it was a small fix and the only comment agreed with it, even if it's an old issue.

Personally, I can't really think of many use cases where this would be useful, maybe some case-sensitive ID, where case sensitivity could bring the result a bit faster? Not sure...

**Comment by aexvir** [comment]
Shouldn't this issue have been closed @hammy2899 ?

**Comment by lubber-de** [comment]
@aexvir We close alle related issues when the new release is published
