### ISSUE TITLE
[Modal] When using coupled modal the first one is jumping up before the second is shown

### ISSUE THREAD

**Issue by filozof595** [fomantic/Fomantic-UI#934]
# When using coupled modal the first one is jumping up before the second is shown

## Steps to reproduce
1. You need two coupled modals
2. The second modal needs to be larger than the screen height
3. When you call the second modal the first one will jump up before hiding

## Expected result
The first modal should just disappear in middle of the screen and show the second modal.

## Actual result
The first modal jumps up before hiding. I'm seeing this only when the second modal is larger than the screen height. When the second modal is smaller then the screen height everything is normal.

## Testcase
JSFiddle when the second modal is larger than the screen size:
[Modal Jump](https://jsfiddle.net/filozof/4yf0dquL/1/)

JFFiddle when the second modal is smaller then the screen size:
[Normal modal behavior](https://jsfiddle.net/filozof/oquyfc6x/6/)

**Comment by lubber-de** [comment]
Fixed by #2722 
See your adjusted jsfiddle here https://jsfiddle.net/lubber/wenjov56/1/
