### ISSUE TITLE
[Dropdown] Opening nested calendar steals focus from input field

### ISSUE THREAD

**Issue by mark-dykstra** [fomantic/Fomantic-UI#937]
# Bug Report

Opening calendar inside a dropdown menu steals focus from input field

## Steps to reproduce
1. Open attached fiddle(s)
2. Click dropdown
3. Click either input field

## Expected result
Calendar opens, but input field still has focus so the user can type a date instead

## Actual result
Calendar opens still, but input field is blurred.  Difficult / impossible to type dates in

## Testcase
https://jsfiddle.net/Ly26mtb4/ (unexpected behavior @ 2.7.7)
https://jsfiddle.net/wrcyh210/ (expected behavior @ 2.6.3)
(Same content, only changing fomantic-ui versions)

## Version
2.7.7

Appears to have been introduced in 2.6.4 by #243 and the related changes it replaced around IE11 event bubbling, as it worked as expected in 2.6.3 and earlier, as well as with semantic-ui + semantic-ui-calendar

As a result, my current workaround is essentially to patch out that commit during my theme build process, replacing the lines below in dropdown.js

```
if (!module.has.search() || !document.activeElement.isEqualNode($search[0])) {
    $(document.activeElement).blur();
}
```

with the previous behavior from 2.6.3

```
if(module.has.menuSearch()) {
    $(document.activeElement).blur();
}
```

but that's not an especially comfortable workaround

**Comment by lubber-de** [comment]
Fixed by #955 
See your adjusted jsfiddle here: https://jsfiddle.net/g19fdp7s/1/
