### ISSUE TITLE
how to get started with vue cli?

### ISSUE THREAD

**Issue by Mccreew** [fomantic/Fomantic-UI#938]
# Help Wanted

## Problem
Describe your problem in great detail
I usually use vue cli to build my project, and i want to use fomantic-ui with my project,but how to get started?

**Comment by exoego** [comment]
Currently Fomantic UI does not officially support/integrate Vue nor vue-cli.
You may ask and get help in our Discord chat https://discord.gg/YChxjJ3 or StackOverflow.
