### ISSUE TITLE
CI wrongly pass even if LESS compilation failure

### ISSUE THREAD

**Issue by exoego** [fomantic/Fomantic-UI#944]
# Bug Report

https://travis-ci.org/fomantic/Fomantic-UI/builds/574770400#L497

## Expected result

CI should abort

## Actual result

CI pass so broken PR may get be merged.

**Comment by prudho** [comment]
Build process is complicated, do the error seem to be drowned between other gulp streams. Maybe we can try some stream combining [like this](https://github.com/gulpjs/gulp/blob/master/docs/recipes/combining-streams-to-handle-errors.md).

@ColinFrick @hammy2899 what do you think about it ?
