### ISSUE TITLE
[Component] Slider

### ISSUE THREAD

**Issue by Extarys** [fomantic/Fomantic-UI#96]
✔ Enhancements
I'm currently using Semantic UI with VueJS for a webapp and I would need a slider.
Example: https://seiyria.com/bootstrap-slider/
EDIT: I found this Semantic UI inspired slider: https://codepen.io/tyleryasaka/pen/KVqPbo

A slider would allow a user to select a value between X and Y with ease.

- Min vlaue
- Max value
- Step
- Option to show a tooltip with current value

By the way, I'm glad someone forked SemanticUI, I love it as it's appealing and aesthetically pleasing but the development was stopped/slowed. Thanks!

**Comment by ColinFrick** [comment]
@Extarys FUI 2.5 will include the Range Slider by @tyleryasaka
https://github.com/fomantic/Fomantic-UI/pull/78
https://github.com/tyleryasaka/semantic-ui-range

**Comment by hammy2899** [comment]
I'm closing this since the PR was merged.

**Comment by Extarys** [comment]
I'm sorry I searched before posting but I didn't see it HMMMM

thanks!
