### ISSUE TITLE
[Form] make set values function support calendar component

### ISSUE THREAD

**Issue by callmeshilin** [fomantic/Fomantic-UI#980]
# Feature Request
make form component `set values` function support with `ui calendar` component.
## Description
if there is a calendar component in a form, current the form `set values` function does not support `ui calendar` component, help to fix. thanks.

## Screenshot (when possible)
![]()

**Comment by hammy2899** [comment]
The logic used in this PR https://github.com/fomantic/Fomantic-UI/pull/918 can be reused for this

**Comment by lubber-de** [comment]
Fixed by #981 
See https://jsfiddle.net/dbLr687e/1/
