### ISSUE TITLE
[Feature Request][Dropdown] Clean Selection ...

### ISSUE THREAD

**Issue by ziaratban** [fomantic/Fomantic-UI#992]
# Feature Request

## Description
how i can implements this feature by set a setting ?

## Example
```html
<div class="ui search selection dropdown">
  <i class="dropdown icon"></i>
  <input name="language" type="hidden" class="" value="fa_IR">
  <input class="search" autocomplete="off" tabindex="0">
  <div class="default text"></div>
  <div class="menu " tabindex="-1">
    <div class="item" data-value="fa_IR">فارسی (ایران)</div>
  </div>
</div>
```
```js
$('.ui.dropdown').dropdown({
  forceSelection : false,
  fullTextSearch : true,
  onHide : function(){ //feature is here
    $(this).dropdown('set selected',$(this).dropdown('get value')).find('>input.search').val('');
  },
});
```

## Testcase
http://jsfiddle.net/jr6tnge1/

**Comment by lubber-de** [comment]
There is no setting, but an existing behavior to shorten your code:
```
$(this).dropdown('remove searchTerm');
```
See http://jsfiddle.net/c4pyLvus/

**Comment by ziaratban** [comment]
yes. but i think this feature must be added to setting for prevent complexity.

**Comment by lubber-de** [comment]
What is your use case yo `forceSelection:true` does not work for you? It will remove the searchTerm when it does not match any dropdown entry as expected
See http://jsfiddle.net/5uckpnga/

The intention of `forceSelection:false` basically is to _not_ remove the searchterm but let the user select something which is not in the list

**Comment by ziaratban** [comment]
because when i set `forceSelection` to `true` and when be typed part of text , one of item in list , selected!
is not good.

**Comment by lubber-de** [comment]
I am still not understanding your use case.`'forceSelection:true` of course selects anything matching while typing, that's the intention of it.
The code you are providing always removes the search term when hiding the menu. That is not the intention of `forceSelection:false `. It's meant to be able to select something which is not in the list.
I am not sure if we really should add an option to always remove the searchterm on hide if nothing is found... Let's see what others say

**Comment by lubber-de** [comment]
@ziaratban After thinking about it for a while now, i think we can make use of the already existing `allowAdditions`  setting. This is `false` by default and should remove the searchterm when it does not match anything.
I prepared a PR to support that here  https://github.com/fomantic/Fomantic-UI/pull/1002
