### ISSUE TITLE
[modal] popup and allowMultiple

### ISSUE THREAD

**Issue by ziaratban** [fomantic/Fomantic-UI#993]
popup module not woking in modal when i set `allowMultiple` setting.

http://jsfiddle.net/f7tLpc9s/1/

**Comment by lubber-de** [comment]
That's because the module is being detached at runtime _after_ your popup is declared.

Two possible solutions:
- create the popup after the modal is shown
http://jsfiddle.net/kpmn4w3d
or
- define `detachable: false` to your modal
http://jsfiddle.net/kpmn4w3d/1/
