### ISSUE TITLE
[Dropdown] Escaped element gets duplicated

### ISSUE THREAD

**Issue by johannes85** [fomantic/Fomantic-UI#997]
# Bug Report

When I add a new element with characters which will be html escaped, it wil get duplicated under certain conditions.

I think this is intruduced with: https://github.com/fomantic/Fomantic-UI/commit/f7c24ace480ef0f98350d8192caff44f42adf0a9

## Steps to reproduce
1. Open https://jsfiddle.net/yzvmobrw/1/
2. Add the following value: <div>
3. Press enter
4. Click in the white area under the element

## Expected result
The new element should be added.

## Actual result
The new element will be added twice.

## Testcase
https://jsfiddle.net/yzvmobrw/1/

## Screenshot (when possible)
![dropdown](https://user-images.githubusercontent.com/470531/64243326-78357200-cf07-11e9-9d56-00b73d40f9ba.gif)

## Version
2.7.8

**Comment by lubber-de** [comment]
Interesting, it does _not_ occur when using "tab" instead of "enter" 🤔

**Comment by johannes85** [comment]
And it also isn't occuring if you don't press enter and simply just klick outside of the box.

**Comment by aexvir** [comment]
👋 Hi there! I'd like to take this one
